import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const agadir: DestinationProfile = {
  id: "agadir",
  name: "Agadir",
  country: "Maroc",
  countryCode: "MA",
  iata: "AGA",
  tagline: "Soleil toute l'année, surf à Taghazout et poisson grillé au port.",
  description:
    "La station balnéaire la plus ensoleillée du Maroc : grande plage de sable, spots de surf réputés à 20 minutes, piscines naturelles de Paradise Valley et Essaouira en excursion.",
  fallbackGradient: "from-amber-300 via-orange-500 to-cyan-600",
  type: "balneaire",
  costLevel: 1,
  costs: {
    accommodationPerNight: { eco: 18, standard: 40, confort: 95 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "3 h 30",
        durationHours: 3.5,
        roundTripPerPerson: 200,
        details: "Vol direct, taxi jusqu'au front de mer en 30 min",
      },
    ],
  },
  localMobility: [
    { mode: "taxi", description: "Petits taxis orange (demande le compteur) et grands taxis vers Taghazout" },
    { mode: "bus", description: "Bus urbains et navettes vers les spots de surf" },
    { mode: "marche", description: "La corniche se longe à pied sur plusieurs kilomètres" },
  ],
  idealDays: { min: 4, max: 9 },
  bestMonths: [3, 4, 5, 6, 9, 10, 11],
  styles: { plage: 3, detente: 3, aventure: 3, nature: 2, gastronomie: 2, fete: 1 },
  ambiances: { calme: 3, economique: 3, aventureuse: 2, sociale: 2 },
  strengths: { plages: 3, prix: 3, activites: 3, rapidite: 2, nature: 2 },
  neighborhoods: [
    {
      name: "Front de mer",
      vibe: "la corniche, pratique et animée",
      tiers: ["standard", "confort"],
      tags: ["plage"],
    },
    {
      name: "Talborjt",
      vibe: "quartier marocain, petits prix",
      tiers: ["eco", "standard"],
      tags: ["gastronomie"],
    },
    {
      name: "Taghazout",
      vibe: "village de surfeurs à 20 min",
      tiers: ["eco", "standard"],
      tags: ["aventure", "plage"],
    },
  ],
  activities: [
    {
      id: "souk-el-had",
      name: "Souk El Had",
      description: "Le grand marché aux épices, fruits secs et huile d'argan.",
      category: "shopping",
      emoji: "🧺",
      cost: 0,
      hours: 2,
      area: "Talborjt",
      moments: ["morning"],
      tags: ["shopping", "gastronomie"],
    },
    {
      id: "surf-taghazout",
      name: "Cours de surf à Taghazout",
      description: "Vagues pour tous niveaux dans le village le plus cool de la côte.",
      category: "aventure",
      emoji: "🏄",
      cost: 30,
      hours: 3,
      area: "Taghazout",
      moments: ["morning"],
      tags: ["aventure", "plage"],
      highlight: "Surf à Taghazout",
    },
    {
      id: "musee-amazigh",
      name: "Musée du patrimoine amazigh",
      description: "Bijoux, tapis et objets berbères du Souss.",
      category: "musee",
      emoji: "💍",
      cost: 2,
      hours: 1,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "port-agadir",
      name: "Poisson grillé au port",
      description: "Choisis ton poisson sur l'étal, il est grillé devant toi.",
      category: "food",
      emoji: "🐟",
      cost: 12,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "plage-agadir",
      name: "Grande plage d'Agadir",
      description: "6 km de sable doré, baignade et beach-volley.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 4,
      area: "Front de mer",
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      highlight: "Journée plage à Agadir",
      repeatable: true,
    },
    {
      id: "hammam-agadir",
      name: "Hammam et massage à l'argan",
      description: "Gommage au savon noir puis massage à l'huile d'argan.",
      category: "detente",
      emoji: "🧖",
      cost: 25,
      hours: 2,
      moments: ["afternoon"],
      tags: ["detente"],
    },
    {
      id: "quad",
      name: "Quad dans les dunes",
      description: "Balade en quad entre dunes et plages sauvages au sud de la ville.",
      category: "aventure",
      emoji: "🏍️",
      cost: 40,
      hours: 3,
      moments: ["afternoon"],
      tags: ["aventure"],
    },
    {
      id: "kasbah",
      name: "Kasbah d'Agadir Oufella au coucher du soleil",
      description: "Les remparts de l'ancienne kasbah, vue sur la baie et le port.",
      category: "panorama",
      emoji: "🌅",
      cost: 5,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique"],
      highlight: "Coucher de soleil sur la baie",
      repeatable: true,
    },
    {
      id: "dromadaire",
      name: "Balade à dromadaire au coucher du soleil",
      description: "Le long de l'estuaire et des dunes, lumière dorée garantie.",
      category: "evenement",
      emoji: "🐪",
      cost: 20,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "aventure"],
    },
    {
      id: "marina-agadir",
      name: "Soirée à la marina",
      description: "Terrasses, glaciers et bars au bord des bateaux.",
      category: "nightlife",
      emoji: "🍹",
      cost: 20,
      hours: 3,
      area: "Front de mer",
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "paradise-valley",
      name: "Paradise Valley",
      description: "Gorges, palmiers et piscines naturelles turquoise dans l'Atlas.",
      category: "nature",
      emoji: "🏞️",
      cost: 20,
      hours: 6,
      moments: ["morning"],
      tags: ["nature", "aventure"],
      highlight: "Les piscines de Paradise Valley",
      fullDay: true,
    },
    {
      id: "essaouira",
      name: "Excursion à Essaouira",
      description: "Médina blanche et bleue, remparts et port de pêche.",
      category: "excursion",
      emoji: "🏰",
      cost: 35,
      hours: 10,
      moments: ["morning"],
      tags: ["culture", "romantique"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "ovo-snack-agadir",
      name: "Snack OVO",
      description: "Msemen, harira et thé à la menthe pour quelques dirhams.",
      cuisine: "Street food marocaine",
      emoji: "🥙",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 5,
      area: "Talborjt",
      meals: ["lunch", "dinner"],
      tags: [],
    },
    {
      id: "ovo-tajine-agadir",
      name: "Dar OVO",
      description: "Tajines et couscous du vendredi dans une maison familiale.",
      cuisine: "Cuisine marocaine",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Talborjt",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
    },
    {
      id: "ovo-surf-cafe",
      name: "OVO Surf Café",
      description: "Bowls, smoothies et vue sur les vagues de Taghazout.",
      cuisine: "Café healthy",
      emoji: "🥑",
      kind: "bistrot",
      isLocal: false,
      priceLevel: 1,
      cost: 12,
      area: "Taghazout",
      meals: ["lunch"],
      tags: [],
    },
    {
      id: "ovo-poisson-agadir",
      name: "OVO Poissons",
      description: "Poissons et fruits de mer grillés en terrasse sur la corniche.",
      cuisine: "Poissons",
      emoji: "🐟",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Front de mer",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
    },
  ],
  geo: {
    center: p(30.4278, -9.5981),
    zoom: 12,
    neighborhoods: {
      "Front de mer": p(30.418, -9.604),
      Talborjt: p(30.4225, -9.593),
      Taghazout: p(30.544, -9.709),
    },
    places: {
      "souk-el-had": p(30.413, -9.577),
      "surf-taghazout": p(30.544, -9.709),
      "musee-amazigh": p(30.42, -9.598),
      "port-agadir": p(30.425, -9.635),
      "plage-agadir": p(30.418, -9.604),
      "hammam-agadir": p(30.42, -9.595),
      quad: p(30.35, -9.56),
      kasbah: p(30.433, -9.617),
      dromadaire: p(30.37, -9.6),
      "marina-agadir": p(30.427, -9.615),
      "paradise-valley": p(30.63, -9.45),
      essaouira: p(31.5125, -9.77),
    },
  },
  source: "demo",
};
