import { destinationImages } from "@/config/images";
import type { DestinationProfile } from "../../types";

export const amsterdam: DestinationProfile = {
  id: "amsterdam",
  name: "Amsterdam",
  country: "Pays-Bas",
  countryCode: "NL",
  tagline: "Canaux à vélo, musées et cafés cosy.",
  description:
    "Une ville à vivre à vélo, entre canaux bordés de maisons penchées, musées de classe mondiale et nuits électro.",
  image: { src: destinationImages.amsterdam, alt: "Maisons au bord d'un canal à Amsterdam" },
  fallbackGradient: "from-sky-400 via-blue-600 to-indigo-800",
  type: "ville",
  costLevel: 4,
  costs: {
    accommodationPerNight: { eco: 45, standard: 85, confort: 160 },
    foodPerDay: { eco: 35, standard: 55, confort: 90 },
    localTransportPerDay: 9,
  },
  access: {
    mode: "train",
    from: "Paris",
    durationLabel: "3 h 20 en train",
    durationHours: 3.3,
    roundTripPerPerson: 140,
  },
  localTransport: "Vélo de location, tram et marche",
  idealDays: { min: 2, max: 5 },
  bestMonths: [4, 5, 6, 7, 8, 9],
  styles: {
    ville: 3,
    culture: 3,
    fete: 3,
    shopping: 2,
    romantique: 2,
    gastronomie: 1,
    festivals: 2,
    nature: 1,
  },
  ambiances: { festive: 3, sociale: 3, romantique: 2, authentique: 2, calme: 1 },
  strengths: { culture: 3, "vie-nocturne": 3, securite: 3, rapidite: 3, activites: 2, confort: 2 },
  neighborhoods: [
    {
      name: "Jordaan",
      vibe: "canaux pittoresques et cafés bruns",
      tiers: ["standard", "confort"],
      tags: ["romantique", "ville"],
    },
    {
      name: "De Pijp",
      vibe: "jeune, marchés et bars",
      tiers: ["eco", "standard"],
      tags: ["fete", "gastronomie"],
    },
    { name: "Oost", vibe: "calme et verdoyant", tiers: ["eco", "standard"], tags: ["detente"] },
  ],
  activities: [
    {
      id: "rijks",
      name: "Rijksmuseum",
      description: "Rembrandt, Vermeer et la Ronde de nuit.",
      category: "musee",
      emoji: "🖼️",
      cost: 25,
      hours: 3,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "La Ronde de nuit au Rijksmuseum",
    },
    {
      id: "van-gogh",
      name: "Musée Van Gogh",
      description: "La plus grande collection du peintre au monde.",
      category: "musee",
      emoji: "🌻",
      cost: 22,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "anne-frank",
      name: "Maison d'Anne Frank",
      description: "Une visite forte, à réserver à l'avance.",
      category: "monument",
      emoji: "📖",
      cost: 16,
      hours: 1.5,
      area: "Jordaan",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "velo",
      name: "Tour des canaux à vélo",
      description: "Comme un local, de pont en pont.",
      category: "quartier",
      emoji: "🚲",
      cost: 15,
      hours: 3,
      moments: ["morning", "afternoon"],
      tags: ["ville", "aventure"],
      highlight: "Les canaux à vélo",
    },
    {
      id: "croisiere",
      name: "Croisière sur les canaux au coucher du soleil",
      description: "Amsterdam vue de l'eau, lumière dorée.",
      category: "panorama",
      emoji: "🛥️",
      cost: 20,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "detente"],
      highlight: "Croisière au coucher du soleil",
    },
    {
      id: "jordaan",
      name: "Flânerie dans le Jordaan & les Negen Straatjes",
      description: "Petites rues, boutiques vintage et cafés.",
      category: "shopping",
      emoji: "🛍️",
      cost: 5,
      hours: 2.5,
      area: "Jordaan",
      moments: ["afternoon"],
      tags: ["shopping", "ville", "romantique"],
    },
    {
      id: "albert-cuyp",
      name: "Marché Albert Cuyp",
      description: "Stroopwafels chauds et harengs pour les braves.",
      category: "food",
      emoji: "🧇",
      cost: 10,
      hours: 1.5,
      area: "De Pijp",
      moments: ["morning", "afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "vondelpark",
      name: "Pique-nique au Vondelpark",
      description: "Le poumon vert de la ville.",
      category: "detente",
      emoji: "🌳",
      cost: 0,
      hours: 2,
      moments: ["afternoon"],
      tags: ["detente", "nature"],
      repeatable: true,
    },
    {
      id: "adam",
      name: "A'DAM Lookout et sa balançoire",
      description: "Vue à 360° et frissons au-dessus du vide.",
      category: "panorama",
      emoji: "🎢",
      cost: 17,
      hours: 1.5,
      moments: ["afternoon", "evening"],
      tags: ["aventure", "ville"],
    },
    {
      id: "brown-cafe",
      name: "Soirée dans les cafés bruns",
      description: "Bières locales dans des bars centenaires.",
      category: "nightlife",
      emoji: "🍺",
      cost: 20,
      hours: 2.5,
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "club-ams",
      name: "Nuit électro dans un club mythique",
      description: "La capitale européenne de la musique électronique.",
      category: "nightlife",
      emoji: "🎧",
      cost: 30,
      hours: 4,
      moments: ["evening"],
      tags: ["fete", "festivals"],
      highlight: "Nuit électro",
    },
    {
      id: "zaanse",
      name: "Excursion aux moulins de Zaanse Schans",
      description: "Moulins à vent et polders, à 20 min du centre.",
      category: "excursion",
      emoji: "🌾",
      cost: 15,
      hours: 5,
      moments: ["morning"],
      tags: ["nature", "culture"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "broodje",
      name: "Snack à broodjes",
      description: "Sandwichs et soupe maison pour un déjeuner rapide.",
      priceLevel: 1,
      cost: 10,
      meals: ["lunch"],
      tags: [],
    },
    {
      id: "foodhallen",
      name: "Foodhallen",
      description: "Halle gourmande aux mille stands.",
      priceLevel: 1,
      cost: 18,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "fete"],
    },
    {
      id: "rijsttafel",
      name: "Rijsttafel indonésienne",
      description: "Une vingtaine de petits plats à partager.",
      priceLevel: 2,
      cost: 35,
      meals: ["dinner"],
      tags: ["gastronomie"],
    },
    {
      id: "canal-bistro",
      name: "Bistrot au bord d'un canal",
      description: "Cuisine de saison en terrasse sur l'eau.",
      priceLevel: 2,
      cost: 38,
      meals: ["dinner"],
      tags: ["romantique"],
    },
    {
      id: "gastro-ams",
      name: "Restaurant de chef à De Pijp",
      description: "Menu créatif et produits locaux.",
      priceLevel: 3,
      cost: 80,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
    },
  ],
  source: "demo",
};
