import { destinationImages } from "@/config/images";
import type { DestinationProfile } from "../../types";

export const athenes: DestinationProfile = {
  id: "athenes",
  name: "Athènes",
  country: "Grèce",
  countryCode: "GR",
  tagline: "L'Acropole, les rooftops et la mer à 30 minutes.",
  description:
    "Berceau de la démocratie devenu capitale bouillonnante : ruines antiques, street art, tavernes et plages de la Riviera athénienne.",
  image: { src: destinationImages.athenes, alt: "L'Acropole d'Athènes" },
  fallbackGradient: "from-sky-300 via-cyan-600 to-blue-900",
  type: "mixte",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 25, standard: 55, confort: 110 },
    foodPerDay: { eco: 22, standard: 35, confort: 65 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "3 h 20",
        durationHours: 3.3,
        roundTripPerPerson: 180,
        details: "Vol direct, métro direct vers le centre",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Moderne, relie aussi l'aéroport" },
    { mode: "tram", description: "Jusqu'aux plages de la Riviera" },
    { mode: "marche", description: "Plaka et le centre historique à pied" },
  ],
  idealDays: { min: 3, max: 7 },
  bestMonths: [4, 5, 6, 7, 8, 9, 10],
  styles: { culture: 3, plage: 2, gastronomie: 2, fete: 2, ville: 2, romantique: 2, detente: 2, nature: 1 },
  ambiances: { authentique: 3, sociale: 2, festive: 2, romantique: 2, economique: 2 },
  strengths: { culture: 3, plages: 2, gastronomie: 2, prix: 2, "vie-nocturne": 2 },
  neighborhoods: [
    {
      name: "Plaka",
      vibe: "au pied de l'Acropole",
      tiers: ["standard", "confort"],
      tags: ["culture", "romantique"],
    },
    { name: "Psiri", vibe: "street art et bars", tiers: ["eco", "standard"], tags: ["fete"] },
    { name: "Koukaki", vibe: "résidentiel et branché", tiers: ["eco", "standard"], tags: ["ville"] },
  ],
  activities: [
    {
      id: "acropole",
      name: "Acropole & Parthénon",
      description: "Le monument le plus célèbre de Grèce, à l'ouverture.",
      category: "monument",
      emoji: "🏛️",
      cost: 20,
      hours: 3,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Le Parthénon",
    },
    {
      id: "musee-acropole",
      name: "Musée de l'Acropole",
      description: "Les frises originales et un sol de verre sur les fouilles.",
      category: "musee",
      emoji: "🗿",
      cost: 15,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "plaka",
      name: "Plaka & Anafiotika",
      description: "Un village des Cyclades caché en pleine ville.",
      category: "quartier",
      emoji: "🏘️",
      cost: 0,
      hours: 2,
      area: "Plaka",
      moments: ["morning", "afternoon"],
      tags: ["romantique", "ville", "culture"],
    },
    {
      id: "monastiraki",
      name: "Marché aux puces de Monastiraki",
      description: "Brocante, sandales en cuir et souvlaki.",
      category: "shopping",
      emoji: "🛍️",
      cost: 10,
      hours: 2,
      moments: ["afternoon"],
      tags: ["shopping"],
    },
    {
      id: "lycabette",
      name: "Coucher de soleil sur le mont Lycabette",
      description: "La vue la plus haute sur Athènes et la mer.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "nature"],
      highlight: "Coucher de soleil au Lycabette",
    },
    {
      id: "riviera",
      name: "Plages de la Riviera athénienne",
      description: "Eau turquoise à 30 minutes de tram.",
      category: "plage",
      emoji: "🏖️",
      cost: 8,
      hours: 4,
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      highlight: "Baignade sur la Riviera",
      repeatable: true,
    },
    {
      id: "street-food-gr",
      name: "Tour street food grec",
      description: "Koulouri, spanakopita et loukoumades.",
      category: "food",
      emoji: "🥙",
      cost: 18,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "cinema",
      name: "Cinéma en plein air",
      description: "Film sous les étoiles avec vue sur l'Acropole.",
      category: "evenement",
      emoji: "🎬",
      cost: 10,
      hours: 2,
      moments: ["evening"],
      tags: ["romantique", "festivals"],
    },
    {
      id: "psiri-bars",
      name: "Rooftops et bars de Psiri",
      description: "Cocktails face au Parthénon illuminé.",
      category: "nightlife",
      emoji: "🍸",
      cost: 20,
      hours: 3,
      area: "Psiri",
      moments: ["evening"],
      tags: ["fete", "romantique"],
      highlight: "Rooftop face au Parthénon",
      repeatable: true,
    },
    {
      id: "gazi",
      name: "Clubs de Gazi",
      description: "L'ancienne usine à gaz devenue quartier de la nuit.",
      category: "nightlife",
      emoji: "🎉",
      cost: 25,
      hours: 4,
      moments: ["evening"],
      tags: ["fete"],
    },
    {
      id: "sounion",
      name: "Cap Sounion & temple de Poséidon",
      description: "Route côtière et coucher de soleil mythique.",
      category: "excursion",
      emoji: "🌊",
      cost: 25,
      hours: 6,
      moments: ["morning"],
      tags: ["culture", "plage", "romantique"],
      highlight: "Le temple de Poséidon",
      fullDay: true,
    },
    {
      id: "egine",
      name: "Journée sur l'île d'Égine",
      description: "Ferry, pistaches et criques sauvages.",
      category: "excursion",
      emoji: "⛴️",
      cost: 30,
      hours: 8,
      moments: ["morning"],
      tags: ["plage", "nature", "detente"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "souvlaki",
      name: "Souvlaki de quartier",
      description: "Pita, tzatziki et frites dedans, évidemment.",
      priceLevel: 1,
      cost: 7,
      meals: ["lunch", "dinner"],
      tags: [],
    },
    {
      id: "taverne",
      name: "Taverne traditionnelle",
      description: "Moussaka, feta rôtie et vin maison.",
      priceLevel: 1,
      cost: 18,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
    },
    {
      id: "meze",
      name: "Mezedopoleio",
      description: "Petits plats à partager et ouzo.",
      priceLevel: 2,
      cost: 25,
      meals: ["dinner"],
      tags: ["gastronomie", "fete"],
    },
    {
      id: "gastro-gr",
      name: "Restaurant de chef avec vue sur l'Acropole",
      description: "Cuisine grecque contemporaine.",
      priceLevel: 3,
      cost: 70,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
    },
  ],
  source: "demo",
};
