import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const bali: DestinationProfile = {
  id: "bali",
  name: "Bali",
  country: "Indonésie",
  countryCode: "ID",
  iata: "DPS",
  tagline: "Rizières, temples, surf et couchers de soleil.",
  description:
    "L'île des dieux : rizières en terrasses d'Ubud, temples au bord des falaises, spots de surf de Canggu, lever de soleil sur un volcan et beach clubs, le tout à petit prix sur place.",
  fallbackGradient: "from-emerald-300 via-teal-500 to-orange-400",
  type: "balneaire",
  costLevel: 1,
  costs: {
    accommodationPerNight: { eco: 15, standard: 40, confort: 100 },
    localTransportPerDay: 8,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "17 h",
        durationHours: 17,
        roundTripPerPerson: 850,
        details: "Vol avec une escale (Singapour, Doha, Dubaï…), taxi ou VTC depuis l'aéroport",
      },
    ],
  },
  localMobility: [
    { mode: "taxi", description: "Chauffeur à la journée ou VTC (Grab, Gojek), le plus simple" },
    { mode: "velo", description: "Scooter si tu as le permis et de l'expérience, la circulation est dense" },
    { mode: "ferry", description: "Bateaux rapides vers Nusa Penida et les îles Gili" },
  ],
  idealDays: { min: 8, max: 16 },
  bestMonths: [4, 5, 6, 7, 8, 9, 10],
  styles: { plage: 3, nature: 3, detente: 3, aventure: 3, culture: 2, fete: 2, romantique: 3 },
  ambiances: { calme: 3, romantique: 3, aventureuse: 3, economique: 3, festive: 2 },
  strengths: { nature: 3, plages: 3, prix: 3, activites: 3, "vie-nocturne": 2 },
  neighborhoods: [
    {
      name: "Ubud",
      vibe: "rizières, yoga et artisans",
      tiers: ["eco", "standard", "confort"],
      tags: ["nature", "culture", "detente"],
    },
    {
      name: "Canggu",
      vibe: "surf, cafés et ambiance jeune",
      tiers: ["eco", "standard"],
      tags: ["plage", "fete"],
    },
    {
      name: "Seminyak",
      vibe: "plages, boutiques et beach clubs",
      tiers: ["standard", "confort"],
      tags: ["plage", "fete"],
    },
    {
      name: "Uluwatu",
      vibe: "falaises, criques et couchers de soleil",
      tiers: ["standard", "confort"],
      tags: ["plage", "romantique"],
    },
  ],
  activities: [
    {
      id: "tegallalang",
      name: "Rizières de Tegallalang",
      description: "Les terrasses vertes les plus photographiées de Bali, tôt le matin.",
      category: "nature",
      emoji: "🌾",
      cost: 3,
      hours: 2,
      area: "Ubud",
      moments: ["morning"],
      tags: ["nature"],
      highlight: "Les rizières de Tegallalang",
    },
    {
      id: "monkey-forest",
      name: "Forêt des singes d'Ubud",
      description: "Temples moussus et centaines de macaques (garde tes lunettes !).",
      category: "nature",
      emoji: "🐒",
      cost: 6,
      hours: 1.5,
      area: "Ubud",
      moments: ["morning", "afternoon"],
      tags: ["nature"],
    },
    {
      id: "tirta-empul",
      name: "Temple de l'eau sacrée Tirta Empul",
      description: "Rituel de purification sous les fontaines du temple.",
      category: "monument",
      emoji: "⛲",
      cost: 3,
      hours: 2,
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "yoga-ubud",
      name: "Cours de yoga à Ubud",
      description: "Séance dans un shala ouvert sur la jungle.",
      category: "detente",
      emoji: "🧘",
      cost: 10,
      hours: 1.5,
      area: "Ubud",
      moments: ["morning"],
      tags: ["detente"],
      repeatable: true,
    },
    {
      id: "cuisine-bali",
      name: "Cours de cuisine balinaise",
      description: "Marché le matin, puis sambal, satay et curry dans une maison familiale.",
      category: "food",
      emoji: "🍛",
      cost: 30,
      hours: 4,
      moments: ["morning"],
      tags: ["gastronomie", "culture"],
    },
    {
      id: "surf-canggu",
      name: "Cours de surf à Canggu",
      description: "Vagues douces pour débutants, planche et coach inclus.",
      category: "aventure",
      emoji: "🏄",
      cost: 25,
      hours: 2.5,
      area: "Canggu",
      moments: ["morning"],
      tags: ["aventure", "plage"],
    },
    {
      id: "massage-bali",
      name: "Massage balinais",
      description: "Une heure de massage aux huiles pour quelques euros.",
      category: "detente",
      emoji: "💆",
      cost: 12,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["detente"],
      repeatable: true,
    },
    {
      id: "padang-padang",
      name: "Plage de Padang Padang",
      description: "Crique de sable blanc nichée entre les rochers d'Uluwatu.",
      category: "plage",
      emoji: "🏖️",
      cost: 1,
      hours: 3,
      area: "Uluwatu",
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      repeatable: true,
    },
    {
      id: "beach-club-bali",
      name: "Après-midi en beach club",
      description: "Piscine face à l'océan, DJ et cocktails au coucher du soleil.",
      category: "nightlife",
      emoji: "🍹",
      cost: 25,
      hours: 4,
      area: "Seminyak",
      moments: ["afternoon"],
      tags: ["fete", "plage"],
    },
    {
      id: "uluwatu-kecak",
      name: "Temple d'Uluwatu et danse Kecak",
      description: "Temple perché sur une falaise, puis danse du feu au coucher du soleil.",
      category: "evenement",
      emoji: "🔥",
      cost: 12,
      hours: 2.5,
      area: "Uluwatu",
      moments: ["evening"],
      tags: ["culture", "romantique"],
      highlight: "La danse Kecak au coucher du soleil",
    },
    {
      id: "canggu-soiree",
      name: "Soirée à Canggu",
      description: "Bars de surfeurs, concerts et fêtes en bord de plage.",
      category: "nightlife",
      emoji: "🎶",
      cost: 15,
      hours: 3,
      area: "Canggu",
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "batur",
      name: "Lever de soleil sur le volcan Batur",
      description: "Départ à 2 h du matin pour voir le jour se lever au sommet.",
      category: "excursion",
      emoji: "🌋",
      cost: 45,
      hours: 8,
      moments: ["morning"],
      tags: ["aventure", "nature"],
      highlight: "Le lever de soleil sur le Batur",
      fullDay: true,
    },
    {
      id: "munduk",
      name: "Cascades et lacs de Munduk",
      description: "Les montagnes du nord : cascades dans la jungle, lacs volcaniques et temple d'Ulun Danu.",
      category: "excursion",
      emoji: "💦",
      cost: 35,
      hours: 10,
      moments: ["morning"],
      tags: ["nature", "aventure"],
      fullDay: true,
    },
    {
      id: "nusa-penida",
      name: "Excursion à Nusa Penida",
      description: "Falaise de Kelingking en T-rex, snorkeling avec les raies manta.",
      category: "excursion",
      emoji: "🦈",
      cost: 50,
      hours: 10,
      moments: ["morning"],
      tags: ["nature", "plage", "aventure"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-mak-beng",
      name: "Warung Mak Beng",
      description: "Un seul menu depuis 1941 : poisson frit et soupe de poisson épicée, à Sanur.",
      cuisine: "Warung balinais",
      emoji: "🐟",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 5,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-ibu-oka",
      name: "Warung Babi Guling Ibu Oka",
      description: "Le cochon de lait rôti aux épices, spécialité d'Ubud.",
      cuisine: "Cuisine balinaise",
      emoji: "🐖",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 5,
      area: "Ubud",
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-naughty-nuris",
      name: "Naughty Nuri's Ubud",
      description: "Travers de porc grillés et martinis, ambiance animée.",
      cuisine: "Grillades",
      emoji: "🍖",
      kind: "bistrot",
      isLocal: false,
      priceLevel: 1,
      cost: 15,
      area: "Ubud",
      meals: ["lunch", "dinner"],
      tags: ["fete"],
      real: true,
    },
    {
      id: "r-potato-head",
      name: "Potato Head Beach Club",
      description: "Le beach club iconique de Seminyak : piscine, DJ et coucher de soleil.",
      cuisine: "Beach club",
      emoji: "🌴",
      kind: "bar",
      isLocal: false,
      priceLevel: 2,
      cost: 35,
      area: "Seminyak",
      meals: ["lunch", "dinner"],
      tags: ["fete", "plage"],
      real: true,
    },
    {
      id: "r-mozaic",
      name: "Mozaic",
      description: "Table gastronomique d'Ubud mêlant produits indonésiens et technique française.",
      cuisine: "Cuisine d'auteur",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 90,
      area: "Ubud",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(-8.5, 115.2),
    zoom: 10,
    neighborhoods: {
      Ubud: p(-8.5069, 115.2625),
      Canggu: p(-8.6478, 115.1385),
      Seminyak: p(-8.6913, 115.1683),
      Uluwatu: p(-8.8291, 115.0849),
    },
    places: {
      tegallalang: p(-8.433, 115.279),
      "monkey-forest": p(-8.5188, 115.2585),
      "tirta-empul": p(-8.415, 115.3153),
      "yoga-ubud": p(-8.5069, 115.2625),
      "cuisine-bali": p(-8.5, 115.26),
      "surf-canggu": p(-8.659, 115.13),
      "massage-bali": p(-8.51, 115.265),
      "padang-padang": p(-8.811, 115.103),
      "beach-club-bali": p(-8.691, 115.157),
      "uluwatu-kecak": p(-8.8291, 115.0849),
      "canggu-soiree": p(-8.648, 115.138),
      batur: p(-8.242, 115.375),
      munduk: p(-8.27, 115.07),
      "nusa-penida": p(-8.75, 115.475),
      "r-mak-beng": p(-8.676, 115.263),
      "r-ibu-oka": p(-8.507, 115.263),
      "r-naughty-nuris": p(-8.4995, 115.2505),
      "r-potato-head": p(-8.68, 115.154),
      "r-mozaic": p(-8.499, 115.25),
    },
  },
  source: "demo",
};
