import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const bangkok: DestinationProfile = {
  id: "bangkok",
  name: "Bangkok",
  country: "Thaïlande",
  countryCode: "TH",
  iata: "BKK",
  tagline: "Temples dorés, street food à 2 € et rooftops vertigineux.",
  description:
    "Chaotique et irrésistible : temples étincelants, canaux en bateau, marchés géants, cuisine de rue parmi les meilleures du monde et nuits sur les toits. La porte d'entrée idéale de l'Asie.",
  fallbackGradient: "from-amber-300 via-orange-500 to-fuchsia-700",
  type: "ville",
  costLevel: 1,
  costs: {
    accommodationPerNight: { eco: 15, standard: 40, confort: 95 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "11 h 30",
        durationHours: 11.5,
        roundTripPerPerson: 650,
        details: "Vol direct ou avec escale, Airport Rail Link jusqu'au centre en 30 min",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "BTS (métro aérien) et MRT pour éviter les embouteillages" },
    { mode: "ferry", description: "Bateaux-bus sur le fleuve Chao Phraya, idéal pour les temples" },
    { mode: "taxi", description: "Tuk-tuk (négocie avant) et VTC via Grab" },
  ],
  idealDays: { min: 4, max: 8 },
  bestMonths: [11, 12, 1, 2, 3],
  styles: { ville: 3, gastronomie: 3, culture: 3, fete: 3, shopping: 3, detente: 2, aventure: 1 },
  ambiances: { economique: 3, festive: 3, aventureuse: 3, sociale: 3, authentique: 2 },
  strengths: { prix: 3, gastronomie: 3, "vie-nocturne": 3, culture: 3, activites: 3 },
  neighborhoods: [
    {
      name: "Rattanakosin",
      vibe: "la vieille ville des temples",
      tiers: ["standard", "confort"],
      tags: ["culture"],
    },
    {
      name: "Banglamphu",
      vibe: "Khao San, backpackers et petits prix",
      tiers: ["eco", "standard"],
      tags: ["fete"],
    },
    {
      name: "Sukhumvit",
      vibe: "moderne, rooftops et centres commerciaux",
      tiers: ["standard", "confort"],
      tags: ["fete", "shopping"],
    },
    {
      name: "Riverside",
      vibe: "au bord du fleuve, hôtels avec vue",
      tiers: ["confort"],
      tags: ["romantique", "detente"],
    },
  ],
  activities: [
    {
      id: "grand-palais",
      name: "Grand Palais et Bouddha d'émeraude",
      description:
        "Le palais royal scintillant et le temple le plus sacré du pays. Épaules et genoux couverts.",
      category: "monument",
      emoji: "👑",
      cost: 15,
      hours: 2.5,
      area: "Rattanakosin",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Le Grand Palais",
    },
    {
      id: "wat-pho",
      name: "Wat Pho et le Bouddha couché",
      description: "Un bouddha doré de 46 m, et l'école historique du massage thaï.",
      category: "monument",
      emoji: "🛕",
      cost: 8,
      hours: 1.5,
      area: "Rattanakosin",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "chatuchak",
      name: "Marché de Chatuchak",
      description: "15 000 stands le week-end : fringues, déco, plantes et snacks.",
      category: "shopping",
      emoji: "🛍️",
      cost: 0,
      hours: 3,
      moments: ["morning"],
      tags: ["shopping"],
    },
    {
      id: "klongs",
      name: "Longtail dans les canaux de Thonburi",
      description: "Maisons sur pilotis et temples cachés, au ras de l'eau.",
      category: "panorama",
      emoji: "🚤",
      cost: 20,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["aventure", "culture"],
    },
    {
      id: "jim-thompson",
      name: "Maison de Jim Thompson",
      description: "Maisons en teck et histoire mystérieuse du roi de la soie thaïe.",
      category: "musee",
      emoji: "🏡",
      cost: 7,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "lumpini",
      name: "Parc Lumpini",
      description: "Poumon vert, tai-chi au lever du jour et varans en liberté.",
      category: "detente",
      emoji: "🦎",
      cost: 0,
      hours: 1.5,
      moments: ["morning"],
      tags: ["detente", "nature"],
    },
    {
      id: "massage-thai",
      name: "Massage thaï traditionnel",
      description: "Une heure de massage pour une dizaine d'euros.",
      category: "detente",
      emoji: "💆",
      cost: 10,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["detente"],
      repeatable: true,
    },
    {
      id: "wat-arun",
      name: "Coucher de soleil face au Wat Arun",
      description: "Le temple de l'Aube en porcelaine, depuis la rive d'en face.",
      category: "panorama",
      emoji: "🌅",
      cost: 5,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "culture"],
      highlight: "Coucher de soleil sur le Wat Arun",
    },
    {
      id: "yaowarat",
      name: "Street food à Chinatown (Yaowarat)",
      description: "La rue des néons et des woks : nouilles, fruits de mer et desserts.",
      category: "food",
      emoji: "🍜",
      cost: 10,
      hours: 2,
      moments: ["evening"],
      tags: ["gastronomie"],
      highlight: "Street food à Chinatown",
      repeatable: true,
    },
    {
      id: "muay-thai",
      name: "Combat de muay-thaï",
      description: "Ambiance électrique dans un stade historique.",
      category: "evenement",
      emoji: "🥊",
      cost: 40,
      hours: 3,
      moments: ["evening"],
      tags: ["festivals", "aventure"],
    },
    {
      id: "rooftop-bkk",
      name: "Cocktail sur un rooftop",
      description: "Bar à 60 étages au-dessus de la ville illuminée.",
      category: "nightlife",
      emoji: "🍸",
      cost: 25,
      hours: 1.5,
      area: "Riverside",
      moments: ["evening"],
      tags: ["romantique", "fete"],
    },
    {
      id: "khao-san",
      name: "Soirée Khao San Road",
      description: "La rue des backpackers : musique, seaux de cocktails et rencontres.",
      category: "nightlife",
      emoji: "🎉",
      cost: 10,
      hours: 3,
      area: "Banglamphu",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit sur Khao San Road",
      repeatable: true,
    },
    {
      id: "ayutthaya",
      name: "Excursion à Ayutthaya",
      description: "L'ancienne capitale du Siam, temples en ruine et têtes de bouddha dans les racines.",
      category: "excursion",
      emoji: "🏛️",
      cost: 30,
      hours: 9,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Les temples d'Ayutthaya",
      fullDay: true,
    },
    {
      id: "marche-flottant",
      name: "Marché flottant de Damnoen Saduak",
      description: "Barques chargées de fruits et de soupes, tôt le matin.",
      category: "excursion",
      emoji: "🛶",
      cost: 30,
      hours: 6,
      moments: ["morning"],
      tags: ["culture", "gastronomie"],
    },
  ],
  restaurants: [
    {
      id: "r-thip-samai",
      name: "Thip Samai",
      description: "Le pad thaï de référence depuis 1966, servi dans une omelette.",
      cuisine: "Pad thaï",
      emoji: "🍜",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 5,
      area: "Rattanakosin",
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-jok-prince",
      name: "Jok Prince",
      description: "Soupe de riz fumée au charbon, étoilée au guide Michelin street food.",
      cuisine: "Street food thaïe",
      emoji: "🥣",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 3,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-krua-apsorn",
      name: "Krua Apsorn",
      description: "Cuisine thaïe familiale, crabe au curry jaune réputé.",
      cuisine: "Cuisine thaïe",
      emoji: "🦀",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Banglamphu",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-supanniga",
      name: "Supanniga Eating Room",
      description: "Recettes de famille de l'Est thaï, terrasse face au Wat Arun.",
      cuisine: "Cuisine thaïe",
      emoji: "🌅",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Rattanakosin",
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      real: true,
    },
    {
      id: "r-jay-fai",
      name: "Jay Fai",
      description: "La cheffe aux lunettes de ski et son omelette au crabe étoilée. Des heures d'attente.",
      cuisine: "Street food étoilée",
      emoji: "🔥",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 45,
      area: "Banglamphu",
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
  ],
  geo: {
    center: p(13.7563, 100.5018),
    zoom: 12,
    neighborhoods: {
      Rattanakosin: p(13.7505, 100.4935),
      Banglamphu: p(13.759, 100.497),
      Sukhumvit: p(13.738, 100.5605),
      Riverside: p(13.7235, 100.5145),
    },
    places: {
      "grand-palais": p(13.75, 100.4913),
      "wat-pho": p(13.7465, 100.4927),
      chatuchak: p(13.7999, 100.55),
      klongs: p(13.743, 100.488),
      "jim-thompson": p(13.7494, 100.5282),
      lumpini: p(13.731, 100.5418),
      "massage-thai": p(13.7468, 100.4935),
      "wat-arun": p(13.7437, 100.4889),
      yaowarat: p(13.74, 100.509),
      "muay-thai": p(13.758, 100.507),
      "rooftop-bkk": p(13.7215, 100.517),
      "khao-san": p(13.759, 100.497),
      ayutthaya: p(14.3532, 100.5689),
      "marche-flottant": p(13.519, 99.959),
      "r-thip-samai": p(13.7527, 100.5047),
      "r-jok-prince": p(13.725, 100.514),
      "r-krua-apsorn": p(13.759, 100.501),
      "r-supanniga": p(13.7458, 100.4908),
      "r-jay-fai": p(13.7527, 100.5049),
    },
  },
  source: "demo",
};
