import { destinationImages } from "@/config/images";
import type { DestinationProfile } from "../../types";

export const barcelone: DestinationProfile = {
  id: "barcelone",
  name: "Barcelone",
  country: "Espagne",
  countryCode: "ES",
  tagline: "Gaudí le jour, tapas et rooftops la nuit.",
  description:
    "La ville qui a tout : plages en plein centre, architecture folle, marchés gourmands et une vie nocturne légendaire.",
  image: { src: destinationImages.barcelone, alt: "La Sagrada Família à Barcelone" },
  fallbackGradient: "from-orange-400 via-red-500 to-fuchsia-700",
  type: "mixte",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 30, standard: 65, confort: 130 },
    foodPerDay: { eco: 28, standard: 45, confort: 80 },
    localTransportPerDay: 7,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "1 h 45",
        durationHours: 1.75,
        roundTripPerPerson: 130,
        details: "Vol direct, aéroport relié au centre en train ou bus",
      },
      {
        mode: "train",
        durationLabel: "6 h 35",
        durationHours: 6.6,
        roundTripPerPerson: 160,
        details: "Train direct à grande vitesse",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Rapide et fréquent, idéal pour tout le séjour" },
    { mode: "marche", description: "Vieille ville et front de mer se font à pied" },
    { mode: "velo", description: "Pistes cyclables le long de la plage" },
  ],
  idealDays: { min: 3, max: 6 },
  bestMonths: [5, 6, 7, 8, 9, 10],
  styles: {
    fete: 3,
    plage: 3,
    ville: 3,
    culture: 2,
    gastronomie: 3,
    shopping: 2,
    festivals: 3,
    romantique: 1,
    detente: 1,
  },
  ambiances: { festive: 3, sociale: 3, authentique: 1, romantique: 1, luxueuse: 2 },
  strengths: {
    "vie-nocturne": 3,
    plages: 3,
    gastronomie: 3,
    culture: 2,
    activites: 3,
    rapidite: 3,
    securite: 2,
  },
  neighborhoods: [
    {
      name: "Gothique & Born",
      vibe: "cœur historique, bars cachés",
      tiers: ["eco", "standard"],
      tags: ["culture", "fete"],
    },
    {
      name: "Eixample",
      vibe: "élégant, au milieu des œuvres de Gaudí",
      tiers: ["standard", "confort"],
      tags: ["ville", "shopping"],
    },
    {
      name: "Barceloneta",
      vibe: "pieds dans le sable",
      tiers: ["standard", "confort"],
      tags: ["plage", "fete"],
    },
    {
      name: "Gràcia",
      vibe: "village bohème et places animées",
      tiers: ["eco", "standard"],
      tags: ["detente", "romantique"],
    },
  ],
  activities: [
    {
      id: "sagrada",
      name: "Sagrada Família",
      description: "Le chef-d'œuvre inachevé de Gaudí, vertigineux de l'intérieur.",
      category: "monument",
      emoji: "⛪",
      cost: 26,
      hours: 2,
      area: "Eixample",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
      highlight: "La Sagrada Família",
    },
    {
      id: "guell",
      name: "Park Güell",
      description: "Mosaïques colorées et vue sur toute la ville.",
      category: "monument",
      emoji: "🦎",
      cost: 18,
      hours: 2,
      area: "Gràcia",
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
    },
    {
      id: "gothique",
      name: "Quartier gothique & El Born",
      description: "Ruelles médiévales, places cachées et cathédrale.",
      category: "quartier",
      emoji: "🏛️",
      cost: 0,
      hours: 2.5,
      area: "Ciutat Vella",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "picasso",
      name: "Musée Picasso",
      description: "Les années de formation du génie, dans des palais gothiques.",
      category: "musee",
      emoji: "🎨",
      cost: 15,
      hours: 2,
      area: "El Born",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "boqueria",
      name: "Marché de la Boqueria",
      description: "Jus frais, jamón et fruits de mer au comptoir.",
      category: "food",
      emoji: "🍓",
      cost: 15,
      hours: 1.5,
      area: "La Rambla",
      moments: ["morning"],
      tags: ["gastronomie"],
    },
    {
      id: "barceloneta",
      name: "Plage de la Barceloneta",
      description: "Baignade et chiringuitos en plein centre-ville.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 3.5,
      area: "Barceloneta",
      moments: ["afternoon"],
      tags: ["plage", "detente", "fete"],
      highlight: "Après-midi à la Barceloneta",
      repeatable: true,
    },
    {
      id: "paddle",
      name: "Paddle ou kayak en mer",
      description: "Session en mer face à la skyline.",
      category: "aventure",
      emoji: "🛶",
      cost: 35,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["aventure", "plage"],
    },
    {
      id: "bunkers",
      name: "Coucher de soleil aux Bunkers del Carmel",
      description: "Le spot panoramique préféré des locaux.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "ville"],
      highlight: "Coucher de soleil aux Bunkers",
      repeatable: true,
    },
    {
      id: "montjuic",
      name: "Montjuïc et la fontaine magique",
      description: "Jardins, château et spectacle d'eau et de lumière.",
      category: "panorama",
      emoji: "⛲",
      cost: 0,
      hours: 2.5,
      moments: ["afternoon", "evening"],
      tags: ["romantique", "detente"],
    },
    {
      id: "gracia-shopping",
      name: "Boutiques de créateurs à Gràcia et au Born",
      description: "Concept stores, friperies et céramique locale.",
      category: "shopping",
      emoji: "🛍️",
      cost: 10,
      hours: 2.5,
      moments: ["afternoon"],
      tags: ["shopping"],
    },
    {
      id: "tapas-crawl",
      name: "Tournée des bars à tapas",
      description: "De comptoir en comptoir dans le Born.",
      category: "food",
      emoji: "🍢",
      cost: 25,
      hours: 2.5,
      area: "El Born",
      moments: ["evening"],
      tags: ["gastronomie", "fete"],
      highlight: "Tournée des tapas",
    },
    {
      id: "rooftop-bar",
      name: "Rooftop et cocktails sur le port",
      description: "Apéro face à la mer avant la nuit.",
      category: "nightlife",
      emoji: "🍸",
      cost: 20,
      hours: 2.5,
      moments: ["evening"],
      tags: ["fete", "romantique"],
    },
    {
      id: "club",
      name: "Clubs du Port Olímpic",
      description: "Là où la nuit barcelonaise se termine au lever du soleil.",
      category: "nightlife",
      emoji: "🎉",
      cost: 30,
      hours: 4,
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit en club face à la mer",
      repeatable: true,
    },
    {
      id: "flamenco",
      name: "Spectacle de flamenco",
      description: "Guitare, palmas et passion dans un tablao intime.",
      category: "evenement",
      emoji: "💃",
      cost: 35,
      hours: 1.5,
      moments: ["evening"],
      tags: ["culture", "festivals", "romantique"],
    },
    {
      id: "montserrat",
      name: "Excursion à Montserrat",
      description: "Monastère perché sur des pics de roche, randonnées.",
      category: "excursion",
      emoji: "⛰️",
      cost: 40,
      hours: 7,
      moments: ["morning"],
      tags: ["nature", "aventure", "culture"],
      highlight: "Les pics de Montserrat",
      fullDay: true,
    },
    {
      id: "sitges",
      name: "Journée plage à Sitges",
      description: "Village côtier festif à 40 minutes de train.",
      category: "excursion",
      emoji: "🌊",
      cost: 10,
      hours: 6,
      moments: ["morning"],
      tags: ["plage", "fete", "detente"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "bodega",
      name: "Bodega de quartier",
      description: "Vermut, anchois et patatas bravas au comptoir.",
      priceLevel: 1,
      cost: 16,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "fete"],
    },
    {
      id: "menu-del-dia",
      name: "Menu del día d'un bistrot local",
      description: "Entrée, plat, dessert à prix doux le midi.",
      priceLevel: 1,
      cost: 15,
      meals: ["lunch"],
      tags: [],
    },
    {
      id: "chiringuito",
      name: "Chiringuito sur la plage",
      description: "Paella et sangria les pieds dans le sable.",
      priceLevel: 2,
      cost: 28,
      area: "Barceloneta",
      meals: ["lunch", "dinner"],
      tags: ["plage", "fete"],
    },
    {
      id: "tapas-moderne",
      name: "Bar à tapas créatif",
      description: "Tapas revisitées par une nouvelle génération de chefs.",
      priceLevel: 2,
      cost: 35,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
    },
    {
      id: "gastro-bcn",
      name: "Restaurant gastronomique catalan",
      description: "Cuisine d'auteur autour des produits de la mer et du marché.",
      priceLevel: 3,
      cost: 80,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
    },
  ],
  source: "demo",
};
