import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const berlin: DestinationProfile = {
  id: "berlin",
  name: "Berlin",
  country: "Allemagne",
  countryCode: "DE",
  iata: "BER",
  tagline: "Histoire, street art et techno jusqu'au lundi.",
  description:
    "La capitale la plus libre d'Europe : le Mur et ses fresques, des musées géants, des friches devenues parcs, et une vie nocturne qui ne s'arrête jamais.",
  fallbackGradient: "from-slate-400 via-zinc-600 to-fuchsia-800",
  type: "ville",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 30, standard: 65, confort: 130 },
    localTransportPerDay: 9,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "1 h 50",
        durationHours: 1.8,
        roundTripPerPerson: 140,
        details: "Vol direct, train FEX jusqu'au centre en 30 min",
      },
      {
        mode: "train",
        durationLabel: "8 h",
        durationHours: 8,
        roundTripPerPerson: 170,
        details: "Train direct depuis Paris-Est, ou train de nuit selon les saisons",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "U-Bahn et S-Bahn couvrent toute la ville, même la nuit le week-end" },
    { mode: "velo", description: "Ville plate et pistes cyclables partout" },
    { mode: "tram", description: "Trams dans l'est de la ville" },
  ],
  idealDays: { min: 3, max: 6 },
  bestMonths: [5, 6, 7, 8, 9],
  styles: {
    fete: 3,
    culture: 3,
    ville: 3,
    shopping: 2,
    festivals: 3,
    gastronomie: 1,
    nature: 1,
    aventure: 1,
  },
  ambiances: { festive: 3, sociale: 3, authentique: 2, economique: 2, aventureuse: 2 },
  strengths: { "vie-nocturne": 3, culture: 3, rapidite: 2, securite: 2, prix: 2, activites: 3 },
  neighborhoods: [
    {
      name: "Mitte",
      vibe: "central, musées et monuments",
      tiers: ["standard", "confort"],
      tags: ["culture", "ville"],
    },
    {
      name: "Kreuzberg",
      vibe: "alternatif, canal et street food",
      tiers: ["eco", "standard"],
      tags: ["fete", "gastronomie"],
    },
    {
      name: "Friedrichshain",
      vibe: "clubs, bars et East Side Gallery",
      tiers: ["eco", "standard"],
      tags: ["fete"],
    },
    {
      name: "Prenzlauer Berg",
      vibe: "cafés, parcs et calme",
      tiers: ["standard", "confort"],
      tags: ["detente", "shopping"],
    },
  ],
  activities: [
    {
      id: "brandebourg",
      name: "Porte de Brandebourg et coupole du Reichstag",
      description:
        "Le symbole de la réunification, puis la coupole de verre du Parlement (gratuite, sur réservation).",
      category: "monument",
      emoji: "🏛️",
      cost: 0,
      hours: 2,
      area: "Mitte",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
      highlight: "La coupole du Reichstag",
    },
    {
      id: "memorial",
      name: "Mémorial aux Juifs assassinés d'Europe",
      description: "2 711 stèles de béton où l'on se perd, et un centre d'information bouleversant.",
      category: "monument",
      emoji: "🕯️",
      cost: 0,
      hours: 1,
      area: "Mitte",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "ile-musees",
      name: "Île aux Musées",
      description: "Cinq musées classés à l'Unesco, dont le buste de Néfertiti au Neues Museum.",
      category: "musee",
      emoji: "🏺",
      cost: 19,
      hours: 3,
      area: "Mitte",
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "bernauer",
      name: "Mémorial du Mur, Bernauer Strasse",
      description: "Le dernier tronçon avec son no man's land, pour comprendre la ville coupée en deux.",
      category: "musee",
      emoji: "🧱",
      cost: 0,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "east-side",
      name: "East Side Gallery",
      description: "1,3 km de Mur recouvert de fresques, dont le fameux baiser Brejnev-Honecker.",
      category: "quartier",
      emoji: "🎨",
      cost: 0,
      hours: 1.5,
      area: "Friedrichshain",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
      highlight: "Les fresques de l'East Side Gallery",
    },
    {
      id: "tv-tower",
      name: "Tour de télévision",
      description: "Vue à 203 m sur toute la ville, bar panoramique.",
      category: "panorama",
      emoji: "🗼",
      cost: 25,
      hours: 1,
      area: "Mitte",
      moments: ["afternoon"],
      tags: ["ville"],
    },
    {
      id: "markthalle",
      name: "Street food à la Markthalle Neun",
      description: "Halle couverte de Kreuzberg, stands du monde entier (le jeudi soir surtout).",
      category: "food",
      emoji: "🌮",
      cost: 15,
      hours: 1.5,
      area: "Kreuzberg",
      moments: ["afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "tempelhof",
      name: "Vélo sur l'ancien aéroport de Tempelhof",
      description: "Les pistes d'atterrissage transformées en immense parc : vélo, roller, pique-nique.",
      category: "nature",
      emoji: "🚲",
      cost: 0,
      hours: 2,
      moments: ["afternoon"],
      tags: ["detente", "nature", "aventure"],
      repeatable: true,
    },
    {
      id: "mauerpark",
      name: "Puces et karaoké du Mauerpark",
      description: "Le dimanche : brocante, food trucks et karaoké géant dans l'amphithéâtre.",
      category: "shopping",
      emoji: "🎤",
      cost: 0,
      hours: 3,
      area: "Prenzlauer Berg",
      moments: ["afternoon"],
      tags: ["shopping", "fete"],
    },
    {
      id: "spree",
      name: "Croisière sur la Spree",
      description: "Une heure de bateau entre la cathédrale, le Reichstag et la gare centrale.",
      category: "panorama",
      emoji: "🛥️",
      cost: 20,
      hours: 1,
      area: "Mitte",
      moments: ["afternoon"],
      tags: ["detente", "ville"],
    },
    {
      id: "klunkerkranich",
      name: "Coucher de soleil sur un rooftop de Neukölln",
      description: "Bar-jardin sur le toit d'un parking, DJ et vue sur la ville.",
      category: "panorama",
      emoji: "🌅",
      cost: 8,
      hours: 2,
      moments: ["evening"],
      tags: ["fete", "detente"],
      repeatable: true,
    },
    {
      id: "bars-kreuzberg",
      name: "Bars de Kreuzberg et Neukölln",
      description: "Bars de quartier, canal et Späti (épiceries de nuit) pour prolonger.",
      category: "nightlife",
      emoji: "🍻",
      cost: 20,
      hours: 3,
      area: "Kreuzberg",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit à Kreuzberg",
      repeatable: true,
    },
    {
      id: "club-berlin",
      name: "Nuit techno dans un club légendaire",
      description: "Les clubs berlinois ouvrent tout le week-end. Sélection à l'entrée, pas de photos.",
      category: "nightlife",
      emoji: "🎧",
      cost: 25,
      hours: 5,
      area: "Friedrichshain",
      moments: ["evening"],
      tags: ["fete", "festivals"],
      highlight: "Une nuit techno à Berlin",
    },
    {
      id: "potsdam",
      name: "Excursion à Potsdam",
      description: "Château de Sanssouci, jardins et quartier hollandais, à 30 min de train.",
      category: "excursion",
      emoji: "🏰",
      cost: 25,
      hours: 7,
      moments: ["morning"],
      tags: ["culture", "romantique"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-curry-36",
      name: "Curry 36",
      description: "La currywurst de référence, servie au comptoir depuis les années 1980.",
      cuisine: "Currywurst",
      emoji: "🌭",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 5,
      area: "Kreuzberg",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-mustafas",
      name: "Mustafa's Gemüse Kebap",
      description: "Le kebab aux légumes grillés le plus célèbre de Berlin. Prévois la queue.",
      cuisine: "Kebab",
      emoji: "🥙",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 7,
      area: "Kreuzberg",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-konnopke",
      name: "Konnopke's Imbiss",
      description: "Currywurst sous le métro aérien depuis 1930, une institution de l'Est.",
      cuisine: "Currywurst",
      emoji: "🌭",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 5,
      area: "Prenzlauer Berg",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-prater",
      name: "Prater Garten",
      description: "Le plus vieux biergarten de Berlin : bière maison sous les marronniers.",
      cuisine: "Biergarten",
      emoji: "🍺",
      kind: "bar",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      area: "Prenzlauer Berg",
      meals: ["lunch", "dinner"],
      tags: ["fete"],
      real: true,
    },
    {
      id: "r-letzte-instanz",
      name: "Zur letzten Instanz",
      description: "Le plus vieux restaurant de Berlin (1621) : jarret et cuisine berlinoise.",
      cuisine: "Cuisine allemande",
      emoji: "🍖",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      area: "Mitte",
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-katz-orange",
      name: "Katz Orange",
      description: "Viandes cuites 12 heures et produits de la région dans une ancienne brasserie.",
      cuisine: "Cuisine allemande moderne",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 50,
      area: "Mitte",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(52.52, 13.405),
    zoom: 12,
    neighborhoods: {
      Mitte: p(52.5205, 13.3985),
      Kreuzberg: p(52.4985, 13.4035),
      Friedrichshain: p(52.5125, 13.454),
      "Prenzlauer Berg": p(52.5385, 13.4245),
    },
    places: {
      brandebourg: p(52.5163, 13.3777),
      memorial: p(52.5139, 13.3787),
      "ile-musees": p(52.521, 13.3969),
      bernauer: p(52.5352, 13.3903),
      "east-side": p(52.505, 13.4396),
      "tv-tower": p(52.5208, 13.4094),
      markthalle: p(52.502, 13.4318),
      tempelhof: p(52.473, 13.4039),
      mauerpark: p(52.543, 13.402),
      spree: p(52.52, 13.4),
      klunkerkranich: p(52.4818, 13.431),
      "bars-kreuzberg": p(52.49, 13.423),
      "club-berlin": p(52.5112, 13.4432),
      potsdam: p(52.4043, 13.038),
      "r-curry-36": p(52.4935, 13.3877),
      "r-mustafas": p(52.4938, 13.3879),
      "r-konnopke": p(52.5407, 13.4122),
      "r-prater": p(52.5398, 13.4101),
      "r-letzte-instanz": p(52.5171, 13.4151),
      "r-katz-orange": p(52.5306, 13.396),
    },
  },
  source: "demo",
};
