import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const bordeaux: DestinationProfile = {
  id: "bordeaux",
  name: "Bordeaux",
  country: "France",
  countryCode: "FR",
  iata: "BOD",
  tagline: "Pierre blonde, vins d'exception et l'océan à une heure.",
  description:
    "Élégante et détendue à 2 h de Paris : façades du XVIIIᵉ, miroir d'eau, quais à vélo, apéros en guinguette, puis Saint-Émilion ou la dune du Pilat en excursion.",
  fallbackGradient: "from-rose-300 via-red-700 to-purple-900",
  type: "ville",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 30, standard: 65, confort: 130 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "train",
        durationLabel: "2 h 05",
        durationHours: 2.1,
        roundTripPerPerson: 90,
        details: "TGV direct Paris-Montparnasse – Bordeaux-Saint-Jean, tram vers le centre",
      },
      {
        mode: "voiture",
        durationLabel: "5 h 45",
        durationHours: 5.75,
        roundTripPerVehicle: 180,
        details: "Carburant + péages par l'A10",
      },
    ],
  },
  localMobility: [
    { mode: "tram", description: "Trois lignes de tram qui desservent tout le centre" },
    { mode: "velo", description: "Ville plate et quais aménagés : idéal à vélo (V³)" },
    { mode: "marche", description: "Le centre historique est en grande partie piéton" },
    { mode: "ferry", description: "Les BatCub, navettes fluviales sur la Garonne" },
  ],
  idealDays: { min: 2, max: 4 },
  bestMonths: [4, 5, 6, 7, 8, 9, 10],
  styles: {
    gastronomie: 3,
    culture: 3,
    ville: 3,
    romantique: 3,
    detente: 2,
    fete: 2,
    shopping: 2,
    nature: 1,
  },
  ambiances: { romantique: 3, authentique: 2, calme: 2, sociale: 2, luxueuse: 2 },
  strengths: { gastronomie: 3, culture: 3, rapidite: 3, securite: 3, confort: 2 },
  neighborhoods: [
    {
      name: "Saint-Pierre",
      vibe: "la vieille ville, places et terrasses",
      tiers: ["standard", "confort"],
      tags: ["culture", "fete"],
    },
    {
      name: "Chartrons",
      vibe: "antiquaires, cavistes et brunchs",
      tiers: ["standard", "confort"],
      tags: ["shopping", "romantique"],
    },
    {
      name: "Saint-Michel",
      vibe: "populaire et cosmopolite, marché et puces",
      tiers: ["eco", "standard"],
      tags: ["gastronomie", "ville"],
    },
    {
      name: "La Bastide",
      vibe: "rive droite, calme et vue sur les quais",
      tiers: ["eco", "standard"],
      tags: ["detente"],
    },
  ],
  activities: [
    {
      id: "miroir-eau",
      name: "Place de la Bourse et miroir d'eau",
      description: "Le plus grand miroir d'eau du monde, magique à la tombée du jour.",
      category: "monument",
      emoji: "🪞",
      cost: 0,
      hours: 1,
      area: "Saint-Pierre",
      moments: ["afternoon", "evening"],
      tags: ["ville", "romantique"],
      highlight: "Le miroir d'eau au crépuscule",
      repeatable: true,
    },
    {
      id: "saint-pierre",
      name: "Balade dans le quartier Saint-Pierre",
      description: "Porte Cailhau, place du Parlement et ruelles pavées.",
      category: "quartier",
      emoji: "🏘️",
      cost: 0,
      hours: 2,
      area: "Saint-Pierre",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "cite-vin",
      name: "La Cité du Vin",
      description: "Musée immersif sur le vin du monde entier, dégustation au belvédère.",
      category: "musee",
      emoji: "🍷",
      cost: 22,
      hours: 2.5,
      moments: ["morning", "afternoon"],
      tags: ["culture", "gastronomie"],
      highlight: "Dégustation au sommet de la Cité du Vin",
    },
    {
      id: "bassins-lumieres",
      name: "Bassins des Lumières",
      description: "Expositions numériques projetées dans une ancienne base sous-marine.",
      category: "musee",
      emoji: "✨",
      cost: 15,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "chartrons",
      name: "Les Chartrons et le marché des Quais",
      description: "Rue Notre-Dame, antiquaires et marché du dimanche au bord de l'eau.",
      category: "shopping",
      emoji: "🛍️",
      cost: 0,
      hours: 2,
      area: "Chartrons",
      moments: ["morning"],
      tags: ["shopping", "gastronomie"],
    },
    {
      id: "capucins",
      name: "Huîtres au marché des Capucins",
      description: "Le « ventre de Bordeaux » : huîtres et vin blanc dès le matin.",
      category: "food",
      emoji: "🦪",
      cost: 15,
      hours: 1.5,
      area: "Saint-Michel",
      moments: ["morning"],
      tags: ["gastronomie"],
    },
    {
      id: "velo-quais",
      name: "Les quais à vélo",
      description: "De la Cité du Vin au pont de pierre, puis retour par la rive droite.",
      category: "nature",
      emoji: "🚲",
      cost: 5,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["detente", "nature"],
      repeatable: true,
    },
    {
      id: "darwin",
      name: "Darwin, friche de la rive droite",
      description: "Street art, skatepark, épicerie bio et bars dans d'anciennes casernes.",
      category: "quartier",
      emoji: "🛹",
      cost: 0,
      hours: 2,
      area: "La Bastide",
      moments: ["afternoon"],
      tags: ["ville", "shopping"],
    },
    {
      id: "parlement",
      name: "Soirée place du Parlement",
      description: "Terrasses et bars de la vieille ville, l'endroit où tout le monde se retrouve.",
      category: "nightlife",
      emoji: "🍹",
      cost: 20,
      hours: 3,
      area: "Saint-Pierre",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit dans le vieux Bordeaux",
      repeatable: true,
    },
    {
      id: "guinguette",
      name: "Apéro en guinguette sur les quais",
      description: "Transats, planches et musique au bord de la Garonne l'été.",
      category: "nightlife",
      emoji: "🎶",
      cost: 15,
      hours: 2.5,
      area: "Chartrons",
      moments: ["evening"],
      tags: ["fete", "detente"],
    },
    {
      id: "saint-emilion",
      name: "Excursion à Saint-Émilion",
      description: "Village médiéval classé, église monolithe et dégustation chez un vigneron.",
      category: "excursion",
      emoji: "🍇",
      cost: 60,
      hours: 8,
      moments: ["morning"],
      tags: ["gastronomie", "culture", "romantique"],
      highlight: "Les vignes de Saint-Émilion",
      fullDay: true,
    },
    {
      id: "dune-pilat",
      name: "Dune du Pilat et bassin d'Arcachon",
      description: "La plus haute dune d'Europe, puis huîtres au Cap Ferret ou baignade.",
      category: "excursion",
      emoji: "🏜️",
      cost: 20,
      hours: 9,
      moments: ["morning"],
      tags: ["nature", "plage", "aventure"],
      highlight: "Le sommet de la dune du Pilat",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-chez-jean-mi",
      name: "Chez Jean-Mi",
      description: "Le comptoir à huîtres du marché des Capucins, avec un verre de blanc.",
      cuisine: "Huîtres & fruits de mer",
      emoji: "🦪",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "Saint-Michel",
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-entrecote",
      name: "L'Entrecôte",
      description: "Une seule formule : entrecôte, sauce secrète et frites à volonté.",
      cuisine: "Grillades",
      emoji: "🥩",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-petit-commerce",
      name: "Le Petit Commerce",
      description: "Poissons et fruits de mer ultra-frais dans une rue animée de Saint-Pierre.",
      cuisine: "Poissons",
      emoji: "🐟",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 35,
      area: "Saint-Pierre",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "fete"],
      real: true,
    },
    {
      id: "r-la-tupina",
      name: "La Tupina",
      description: "Cuisine du Sud-Ouest au coin de la cheminée : confit, frites à la graisse de canard.",
      cuisine: "Cuisine du Sud-Ouest",
      emoji: "🔥",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 55,
      area: "Saint-Michel",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(44.8412, -0.5738),
    zoom: 14,
    neighborhoods: {
      "Saint-Pierre": p(44.8398, -0.5722),
      Chartrons: p(44.8545, -0.5695),
      "Saint-Michel": p(44.8345, -0.5655),
      "La Bastide": p(44.8435, -0.5585),
    },
    places: {
      "miroir-eau": p(44.8413, -0.57),
      "saint-pierre": p(44.8395, -0.572),
      "cite-vin": p(44.8625, -0.5503),
      "bassins-lumieres": p(44.871, -0.555),
      chartrons: p(44.853, -0.569),
      capucins: p(44.831, -0.569),
      "velo-quais": p(44.848, -0.565),
      darwin: p(44.85, -0.56),
      parlement: p(44.841, -0.5725),
      guinguette: p(44.856, -0.566),
      "saint-emilion": p(44.894, -0.155),
      "dune-pilat": p(44.589, -1.213),
      "r-chez-jean-mi": p(44.8311, -0.5692),
      "r-entrecote": p(44.844, -0.5745),
      "r-petit-commerce": p(44.8395, -0.573),
      "r-la-tupina": p(44.834, -0.5635),
    },
  },
  source: "demo",
};
