import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const bruxelles: DestinationProfile = {
  id: "bruxelles",
  name: "Bruxelles",
  country: "Belgique",
  countryCode: "BE",
  iata: "BRU",
  tagline: "Grand-Place, BD, frites et bières d'abbaye, à 1 h 25 de Paris.",
  description:
    "Le week-end parfait en train : l'une des plus belles places du monde, fresques de BD, chocolatiers, bières belges par centaines et Bruges en excursion.",
  fallbackGradient: "from-yellow-300 via-amber-500 to-red-700",
  type: "ville",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 30, standard: 70, confort: 135 },
    localTransportPerDay: 7,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "train",
        durationLabel: "1 h 25",
        durationHours: 1.4,
        roundTripPerPerson: 90,
        details: "Train direct Paris-Nord – Bruxelles-Midi, jusqu'à 20 par jour",
      },
      {
        mode: "bus",
        durationLabel: "4 h",
        durationHours: 4,
        roundTripPerPerson: 40,
        details: "Bus low-cost depuis Paris, le moins cher",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Le centre historique se fait à pied" },
    { mode: "metro", description: "Métro, tram et bus STIB pour Saint-Gilles et l'Atomium" },
    { mode: "velo", description: "Vélos en libre-service (Villo!)" },
  ],
  idealDays: { min: 2, max: 4 },
  bestMonths: [4, 5, 6, 7, 8, 9, 12],
  styles: { ville: 3, gastronomie: 3, culture: 2, fete: 2, shopping: 2, festivals: 2, romantique: 1 },
  ambiances: { sociale: 3, festive: 2, authentique: 2, economique: 2 },
  strengths: { rapidite: 3, gastronomie: 3, culture: 2, "vie-nocturne": 2, securite: 2 },
  neighborhoods: [
    {
      name: "Centre",
      vibe: "autour de la Grand-Place, tout à pied",
      tiers: ["standard", "confort"],
      tags: ["culture", "ville"],
    },
    {
      name: "Saint-Gilles",
      vibe: "Art nouveau, bars et ambiance bobo",
      tiers: ["eco", "standard"],
      tags: ["fete"],
    },
    {
      name: "Sablon",
      vibe: "antiquaires, chocolatiers et musées",
      tiers: ["confort"],
      tags: ["shopping", "romantique"],
    },
    {
      name: "Ixelles",
      vibe: "étudiant et cosmopolite, place Flagey",
      tiers: ["eco", "standard"],
      tags: ["fete", "gastronomie"],
    },
  ],
  activities: [
    {
      id: "grand-place",
      name: "Grand-Place et Manneken-Pis",
      description: "Façades dorées des maisons des corporations, et le petit bonhomme à deux rues.",
      category: "monument",
      emoji: "🏛️",
      cost: 0,
      hours: 1.5,
      area: "Centre",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
      highlight: "La Grand-Place illuminée",
    },
    {
      id: "galeries",
      name: "Galeries royales Saint-Hubert",
      description: "Passage couvert du XIXᵉ, chocolatiers et librairies.",
      category: "shopping",
      emoji: "🍫",
      cost: 10,
      hours: 1.5,
      area: "Centre",
      moments: ["morning", "afternoon"],
      tags: ["shopping", "gastronomie"],
    },
    {
      id: "bd",
      name: "Parcours BD et musée de la BD",
      description: "Tintin, Spirou et les Schtroumpfs, dans un magasin Art nouveau de Horta.",
      category: "musee",
      emoji: "💬",
      cost: 13,
      hours: 2,
      area: "Centre",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "magritte",
      name: "Musée Magritte",
      description: "La plus grande collection du maître du surréalisme.",
      category: "musee",
      emoji: "🎩",
      cost: 10,
      hours: 1.5,
      area: "Sablon",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "atomium",
      name: "Atomium",
      description: "Un cristal de fer agrandi 165 milliards de fois, vue depuis la sphère du haut.",
      category: "monument",
      emoji: "⚛️",
      cost: 16,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["ville"],
    },
    {
      id: "marolles",
      name: "Puces des Marolles",
      description: "Marché aux puces tous les matins place du Jeu de Balle.",
      category: "shopping",
      emoji: "🛍️",
      cost: 0,
      hours: 1.5,
      moments: ["morning"],
      tags: ["shopping"],
    },
    {
      id: "cantillon",
      name: "Brasserie Cantillon",
      description: "La dernière brasserie de lambic de Bruxelles, fermentation spontanée.",
      category: "food",
      emoji: "🍺",
      cost: 10,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "soignes",
      name: "Vélo dans la forêt de Soignes",
      description: "Hêtraie cathédrale aux portes de la ville.",
      category: "nature",
      emoji: "🌳",
      cost: 10,
      hours: 3,
      moments: ["morning"],
      tags: ["nature", "detente"],
    },
    {
      id: "mont-des-arts",
      name: "Coucher de soleil au Mont des Arts",
      description: "Jardins en terrasses et vue sur l'hôtel de ville.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1,
      area: "Sablon",
      moments: ["evening"],
      tags: ["romantique"],
      repeatable: true,
    },
    {
      id: "bieres",
      name: "Dégustation de bières belges",
      description: "Trappistes, gueuzes et triples dans un bar aux milliers de références.",
      category: "food",
      emoji: "🍻",
      cost: 20,
      hours: 2,
      area: "Centre",
      moments: ["evening"],
      tags: ["gastronomie", "fete"],
      highlight: "Tour des bières belges",
    },
    {
      id: "saint-gilles-soiree",
      name: "Soirée au Parvis de Saint-Gilles",
      description: "Terrasses bondées et bars de quartier jusque tard.",
      category: "nightlife",
      emoji: "🍹",
      cost: 15,
      hours: 3,
      area: "Saint-Gilles",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit au Parvis de Saint-Gilles",
      repeatable: true,
    },
    {
      id: "bruges",
      name: "Excursion à Bruges",
      description: "Canaux, béguinage et beffroi, à 1 h de train.",
      category: "excursion",
      emoji: "🚤",
      cost: 30,
      hours: 8,
      moments: ["morning"],
      tags: ["romantique", "culture"],
      highlight: "Les canaux de Bruges",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-maison-antoine",
      name: "Maison Antoine",
      description: "La friterie la plus célèbre de Bruxelles, place Jourdan.",
      cuisine: "Frites belges",
      emoji: "🍟",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      area: "Ixelles",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-mer-du-nord",
      name: "Mer du Nord",
      description: "Comptoir de poissonnier : croquettes de crevettes et vin blanc debout.",
      cuisine: "Poissons & crevettes",
      emoji: "🦐",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 18,
      area: "Centre",
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-fin-de-siecle",
      name: "Fin de Siècle",
      description: "Cuisine belge (carbonnade, stoemp) sans réservation, sur des tables en bois.",
      cuisine: "Cuisine belge",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Centre",
      meals: ["dinner"],
      tags: ["gastronomie", "fete"],
      real: true,
    },
    {
      id: "r-chez-leon",
      name: "Chez Léon",
      description: "Moules-frites depuis 1893 dans la rue des Bouchers.",
      cuisine: "Moules-frites",
      emoji: "🦪",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      area: "Centre",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-quincaillerie",
      name: "La Quincaillerie",
      description: "Brasserie Art nouveau dans une ancienne quincaillerie, plateau de fruits de mer.",
      cuisine: "Brasserie",
      emoji: "🔧",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 55,
      area: "Ixelles",
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      real: true,
    },
  ],
  geo: {
    center: p(50.8467, 4.3525),
    zoom: 14,
    neighborhoods: {
      Centre: p(50.8467, 4.3525),
      "Saint-Gilles": p(50.831, 4.345),
      Sablon: p(50.8405, 4.3565),
      Ixelles: p(50.8275, 4.372),
    },
    places: {
      "grand-place": p(50.8467, 4.3525),
      galeries: p(50.848, 4.355),
      bd: p(50.8513, 4.3598),
      magritte: p(50.8425, 4.3585),
      atomium: p(50.8949, 4.3415),
      marolles: p(50.8375, 4.345),
      cantillon: p(50.8414, 4.335),
      soignes: p(50.787, 4.413),
      "mont-des-arts": p(50.8445, 4.356),
      bieres: p(50.848, 4.354),
      "saint-gilles-soiree": p(50.831, 4.345),
      bruges: p(51.2093, 3.2247),
      "r-maison-antoine": p(50.8378, 4.383),
      "r-mer-du-nord": p(50.85, 4.3475),
      "r-fin-de-siecle": p(50.8505, 4.348),
      "r-chez-leon": p(50.8475, 4.3545),
      "r-quincaillerie": p(50.826, 4.362),
    },
  },
  source: "demo",
};
