import { destinationImages } from "@/config/images";
import type { DestinationProfile } from "../../types";

export const budapest: DestinationProfile = {
  id: "budapest",
  name: "Budapest",
  country: "Hongrie",
  countryCode: "HU",
  tagline: "Bains thermaux le jour, ruin bars la nuit.",
  description:
    "La perle du Danube : thermes Art nouveau, bars installés dans des immeubles en ruine et panoramas grandioses, à petit prix.",
  image: { src: destinationImages.budapest, alt: "Le Parlement de Budapest au bord du Danube" },
  fallbackGradient: "from-emerald-400 via-teal-600 to-night-900",
  type: "ville",
  costLevel: 1,
  costs: {
    accommodationPerNight: { eco: 20, standard: 42, confort: 90 },
    foodPerDay: { eco: 18, standard: 30, confort: 55 },
    localTransportPerDay: 5,
  },
  access: {
    mode: "avion",
    from: "Paris",
    durationLabel: "2 h 10",
    durationHours: 2.2,
    roundTripPerPerson: 150,
  },
  localTransport: "Métro, trams le long du Danube et marche",
  idealDays: { min: 3, max: 5 },
  bestMonths: [4, 5, 6, 7, 8, 9, 12],
  styles: { fete: 3, detente: 3, culture: 3, ville: 2, romantique: 2, festivals: 3, gastronomie: 2 },
  ambiances: { festive: 3, economique: 3, sociale: 3, calme: 2, romantique: 2, authentique: 2 },
  strengths: { prix: 3, "vie-nocturne": 3, culture: 2, securite: 2, confort: 2, activites: 2 },
  neighborhoods: [
    { name: "Quartier juif (VIIe)", vibe: "le QG des ruin bars", tiers: ["eco", "standard"], tags: ["fete"] },
    {
      name: "Belváros",
      vibe: "central, au bord du Danube",
      tiers: ["standard", "confort"],
      tags: ["ville", "romantique"],
    },
    {
      name: "Buda",
      vibe: "calme, collines et thermes",
      tiers: ["standard", "confort"],
      tags: ["detente", "culture"],
    },
  ],
  activities: [
    {
      id: "szechenyi",
      name: "Bains thermaux Széchenyi",
      description: "Bassins extérieurs à 38 °C dans un palais jaune.",
      category: "detente",
      emoji: "♨️",
      cost: 30,
      hours: 3,
      moments: ["morning", "afternoon"],
      tags: ["detente", "fete"],
      highlight: "Les bains Széchenyi",
    },
    {
      id: "gellert",
      name: "Thermes Gellért",
      description: "Mosaïques Art nouveau et piscine à colonnes.",
      category: "detente",
      emoji: "🛁",
      cost: 32,
      hours: 2.5,
      moments: ["morning", "afternoon"],
      tags: ["detente", "romantique"],
    },
    {
      id: "parlement",
      name: "Parlement hongrois",
      description: "Le plus bel édifice du Danube, et sa couronne sacrée.",
      category: "monument",
      emoji: "🏛️",
      cost: 30,
      hours: 1.5,
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "chateau-buda",
      name: "Colline du château & bastion des Pêcheurs",
      description: "Tourelles blanches et vue sur Pest.",
      category: "monument",
      emoji: "🏰",
      cost: 5,
      hours: 2.5,
      area: "Buda",
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
      highlight: "Le bastion des Pêcheurs",
    },
    {
      id: "chaussures",
      name: "Promenade du Danube & chaussures au bord du Danube",
      description: "Un mémorial poignant le long du fleuve.",
      category: "quartier",
      emoji: "🌊",
      cost: 0,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "halles",
      name: "Grande halle centrale",
      description: "Paprika, lángos et saucissons en tous genres.",
      category: "food",
      emoji: "🌶️",
      cost: 10,
      hours: 1.5,
      moments: ["morning"],
      tags: ["gastronomie", "shopping"],
    },
    {
      id: "gellert-hill",
      name: "Coucher de soleil sur la colline Gellért",
      description: "Toute la ville illuminée à tes pieds.",
      category: "panorama",
      emoji: "🌇",
      cost: 0,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "nature"],
      highlight: "Budapest illuminée depuis Gellért",
    },
    {
      id: "croisiere-danube",
      name: "Croisière de nuit sur le Danube",
      description: "Le Parlement doré qui se reflète dans l'eau.",
      category: "panorama",
      emoji: "🛳️",
      cost: 15,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "detente"],
    },
    {
      id: "margit",
      name: "Vélo sur l'île Marguerite",
      description: "Parc, fontaine musicale et piscines en plein air.",
      category: "nature",
      emoji: "🚲",
      cost: 8,
      hours: 2.5,
      moments: ["afternoon"],
      tags: ["nature", "detente", "aventure"],
      repeatable: true,
    },
    {
      id: "ruin-bars",
      name: "Tournée des ruin bars",
      description: "Bars bric-à-brac dans des immeubles abandonnés.",
      category: "nightlife",
      emoji: "🍻",
      cost: 15,
      hours: 3,
      area: "VIIe",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit dans les ruin bars",
      repeatable: true,
    },
    {
      id: "sparty",
      name: "Bath party nocturne",
      description: "DJ, lumières et bassins chauds jusqu'au bout de la nuit.",
      category: "nightlife",
      emoji: "🪩",
      cost: 50,
      hours: 4,
      moments: ["evening"],
      tags: ["fete", "festivals"],
      highlight: "Une bath party",
    },
    {
      id: "szentendre",
      name: "Excursion à Szentendre",
      description: "Village d'artistes coloré au bord du Danube.",
      category: "excursion",
      emoji: "🎨",
      cost: 12,
      hours: 5,
      moments: ["morning"],
      tags: ["culture", "detente"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "langos",
      name: "Stand à lángos",
      description: "Pain frit à la crème et au fromage, régressif.",
      priceLevel: 1,
      cost: 6,
      meals: ["lunch"],
      tags: [],
    },
    {
      id: "etkezde",
      name: "Étkezde (cantine familiale)",
      description: "Goulash et paprikás maison à petit prix.",
      priceLevel: 1,
      cost: 10,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
    },
    {
      id: "food-court",
      name: "Street food court du VIIe",
      description: "Burgers, hongrois ou vegan, ambiance guinguette.",
      priceLevel: 1,
      cost: 12,
      meals: ["dinner"],
      tags: ["fete"],
    },
    {
      id: "bistro-hu",
      name: "Bistrot hongrois moderne",
      description: "Canard, paprika fumé et vins de Tokaj.",
      priceLevel: 2,
      cost: 28,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
    },
    {
      id: "gastro-hu",
      name: "Grand café historique & dîner de chef",
      description: "Lustres, dorures et menu gastronomique.",
      priceLevel: 3,
      cost: 65,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
    },
  ],
  source: "demo",
};
