import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const copenhague: DestinationProfile = {
  id: "copenhague",
  name: "Copenhague",
  country: "Danemark",
  countryCode: "DK",
  iata: "CPH",
  tagline: "Vélos, canaux colorés et hygge à la danoise.",
  description:
    "La ville la plus cool du Nord : on s'y déplace à vélo, on se baigne dans le port, on dîne en street food au bord de l'eau et on sort à Kødbyen. Chère, mais inoubliable.",
  fallbackGradient: "from-yellow-300 via-rose-400 to-sky-600",
  type: "ville",
  costLevel: 4,
  costs: {
    accommodationPerNight: { eco: 45, standard: 100, confort: 190 },
    localTransportPerDay: 10,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "1 h 55",
        durationHours: 1.9,
        roundTripPerPerson: 170,
        details: "Vol direct, métro jusqu'au centre en 15 min",
      },
    ],
  },
  localMobility: [
    { mode: "velo", description: "La capitale mondiale du vélo : location partout" },
    { mode: "metro", description: "Métro automatique 24 h/24" },
    { mode: "ferry", description: "Bateaux-bus du port inclus dans les tickets" },
    { mode: "marche", description: "Le centre est compact et piéton" },
  ],
  idealDays: { min: 3, max: 5 },
  bestMonths: [5, 6, 7, 8, 9],
  styles: {
    ville: 3,
    gastronomie: 3,
    detente: 2,
    culture: 2,
    fete: 2,
    shopping: 2,
    romantique: 2,
    aventure: 1,
  },
  ambiances: { calme: 2, sociale: 3, luxueuse: 2, romantique: 2, festive: 2 },
  strengths: { securite: 3, gastronomie: 3, culture: 2, rapidite: 2, confort: 3 },
  neighborhoods: [
    {
      name: "Indre By",
      vibe: "le centre historique, tout à pied",
      tiers: ["standard", "confort"],
      tags: ["culture", "ville"],
    },
    {
      name: "Nørrebro",
      vibe: "jeune et multiculturel, cafés et friperies",
      tiers: ["eco", "standard"],
      tags: ["fete", "shopping"],
    },
    {
      name: "Vesterbro",
      vibe: "ancien quartier rouge devenu branché",
      tiers: ["eco", "standard"],
      tags: ["fete", "gastronomie"],
    },
    {
      name: "Christianshavn",
      vibe: "canaux, péniches et calme",
      tiers: ["standard", "confort"],
      tags: ["romantique", "detente"],
    },
  ],
  activities: [
    {
      id: "nyhavn",
      name: "Nyhavn et ses maisons colorées",
      description: "Le port de carte postale, voiliers anciens et terrasses.",
      category: "quartier",
      emoji: "⛵",
      cost: 0,
      hours: 1,
      area: "Indre By",
      moments: ["morning", "afternoon"],
      tags: ["ville", "romantique"],
      highlight: "Les façades colorées de Nyhavn",
    },
    {
      id: "velo-cph",
      name: "Copenhague à vélo",
      description: "Balade guidée ou en solo, comme les locaux, des lacs au port.",
      category: "aventure",
      emoji: "🚲",
      cost: 15,
      hours: 3,
      moments: ["morning"],
      tags: ["ville", "aventure"],
    },
    {
      id: "rosenborg",
      name: "Château de Rosenborg",
      description: "Château Renaissance dans un jardin royal, joyaux de la couronne au sous-sol.",
      category: "monument",
      emoji: "👑",
      cost: 17,
      hours: 1.5,
      area: "Indre By",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "rundetaarn",
      name: "Tour Ronde",
      description: "Une rampe en spirale (pas d'escalier !) jusqu'à la vue sur les toits.",
      category: "panorama",
      emoji: "🗼",
      cost: 6,
      hours: 1,
      area: "Indre By",
      moments: ["morning", "afternoon"],
      tags: ["ville"],
    },
    {
      id: "canaux",
      name: "Balade en bateau sur les canaux",
      description: "Une heure entre Nyhavn, Christianshavn et l'opéra.",
      category: "panorama",
      emoji: "🛥️",
      cost: 15,
      hours: 1,
      moments: ["morning", "afternoon"],
      tags: ["detente", "romantique"],
    },
    {
      id: "christiania",
      name: "Christiania, la ville libre",
      description:
        "Communauté autogérée depuis 1971, maisons bricolées et art partout. Pas de photos rue Pusher.",
      category: "quartier",
      emoji: "🌈",
      cost: 0,
      hours: 1.5,
      area: "Christianshavn",
      moments: ["afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "tivoli",
      name: "Jardins de Tivoli",
      description: "Le parc d'attractions de 1843 qui a inspiré Disney, féerique le soir.",
      category: "evenement",
      emoji: "🎡",
      cost: 25,
      hours: 3,
      moments: ["afternoon", "evening"],
      tags: ["romantique", "festivals"],
      highlight: "Tivoli illuminé",
    },
    {
      id: "copenhill",
      name: "Randonnée sur le toit de CopenHill",
      description: "Une usine d'incinération avec piste de ski et sentier sur son toit.",
      category: "nature",
      emoji: "⛷️",
      cost: 0,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["aventure", "nature"],
    },
    {
      id: "baignade-port",
      name: "Baignade dans le port",
      description: "Les bains d'Islands Brygge : eau propre en plein centre-ville.",
      category: "plage",
      emoji: "🏊",
      cost: 0,
      hours: 2,
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      repeatable: true,
    },
    {
      id: "reffen",
      name: "Street food à Reffen",
      description: "Food trucks et containers au bord de l'eau, coucher de soleil inclus.",
      category: "food",
      emoji: "🍔",
      cost: 15,
      hours: 2,
      moments: ["evening"],
      tags: ["gastronomie", "fete"],
      highlight: "Dîner street food à Reffen",
      repeatable: true,
    },
    {
      id: "kodbyen",
      name: "Soirée à Kødbyen",
      description: "L'ancien quartier des abattoirs, devenu repaire de bars et clubs.",
      category: "nightlife",
      emoji: "🍸",
      cost: 25,
      hours: 3,
      area: "Vesterbro",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit à Kødbyen",
      repeatable: true,
    },
    {
      id: "bars-norrebro",
      name: "Bars de Nørrebro",
      description: "Bars à bières artisanales et caves à vin nature sur Jægersborggade.",
      category: "nightlife",
      emoji: "🍺",
      cost: 20,
      hours: 3,
      area: "Nørrebro",
      moments: ["evening"],
      tags: ["fete"],
    },
    {
      id: "louisiana",
      name: "Musée Louisiana",
      description: "Art moderne face à la mer, à 35 min de train : un des plus beaux musées du monde.",
      category: "excursion",
      emoji: "🖼️",
      cost: 25,
      hours: 6,
      moments: ["morning"],
      tags: ["culture", "detente"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-grod",
      name: "Grød",
      description: "Des porridges salés et sucrés revisités, parfaits pour un déjeuner pas cher.",
      cuisine: "Porridge",
      emoji: "🥣",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Nørrebro",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-paludan",
      name: "Paludan Bogcafé",
      description: "Café-librairie étudiant, assiettes généreuses entre les rayonnages.",
      cuisine: "Café",
      emoji: "📚",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "Indre By",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-torvehallerne",
      name: "Torvehallerne",
      description: "Deux halles de verre : smørrebrød, poisson, cafés et spécialités danoises.",
      cuisine: "Halles gourmandes",
      emoji: "🥪",
      kind: "street-food",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      area: "Indre By",
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-schonnemann",
      name: "Restaurant Schønnemann",
      description: "Le smørrebrød (tartine danoise) depuis 1877, avec un verre d'aquavit.",
      cuisine: "Smørrebrød",
      emoji: "🍞",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 35,
      area: "Indre By",
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-fiskebar",
      name: "Kødbyens Fiskebar",
      description: "Bar à poissons et huîtres dans l'ancien quartier des abattoirs.",
      cuisine: "Poissons nordiques",
      emoji: "🦪",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 55,
      area: "Vesterbro",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(55.6761, 12.5683),
    zoom: 13,
    neighborhoods: {
      "Indre By": p(55.6795, 12.5775),
      Nørrebro: p(55.6935, 12.5485),
      Vesterbro: p(55.6685, 12.5555),
      Christianshavn: p(55.6725, 12.5935),
    },
    places: {
      nyhavn: p(55.6798, 12.5907),
      "velo-cph": p(55.6761, 12.5683),
      rosenborg: p(55.6858, 12.5773),
      rundetaarn: p(55.6814, 12.5757),
      canaux: p(55.679, 12.587),
      christiania: p(55.6736, 12.6002),
      tivoli: p(55.6737, 12.5681),
      copenhill: p(55.6825, 12.627),
      "baignade-port": p(55.664, 12.578),
      reffen: p(55.6934, 12.6078),
      kodbyen: p(55.669, 12.562),
      "bars-norrebro": p(55.6926, 12.546),
      louisiana: p(55.969, 12.543),
      "r-grod": p(55.6937, 12.5503),
      "r-paludan": p(55.6795, 12.5718),
      "r-torvehallerne": p(55.684, 12.5695),
      "r-schonnemann": p(55.6823, 12.576),
      "r-fiskebar": p(55.6687, 12.5613),
    },
  },
  source: "demo",
};
