import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const cracovie: DestinationProfile = {
  id: "cracovie",
  name: "Cracovie",
  country: "Pologne",
  countryCode: "PL",
  iata: "KRK",
  tagline: "Une vieille ville de conte, des caves festives et des prix mini.",
  description:
    "La plus belle ville de Pologne, et l'une des moins chères d'Europe : Grand-Place médiévale, quartier juif de Kazimierz, pierogi à volonté, bars en cave et lieux de mémoire essentiels.",
  fallbackGradient: "from-red-400 via-rose-600 to-amber-600",
  type: "ville",
  costLevel: 1,
  costs: {
    accommodationPerNight: { eco: 18, standard: 40, confort: 85 },
    localTransportPerDay: 4,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h 10",
        durationHours: 2.2,
        roundTripPerPerson: 120,
        details: "Vol direct, train jusqu'à la gare centrale en 20 min",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Vieille ville et Kazimierz se font à pied" },
    { mode: "tram", description: "Trams nombreux et bon marché" },
    { mode: "taxi", description: "VTC très abordables" },
  ],
  idealDays: { min: 3, max: 5 },
  bestMonths: [5, 6, 7, 8, 9, 12],
  styles: { culture: 3, fete: 3, ville: 2, gastronomie: 2, romantique: 2, festivals: 2 },
  ambiances: { economique: 3, festive: 3, authentique: 3, sociale: 3, romantique: 2 },
  strengths: { prix: 3, culture: 3, "vie-nocturne": 3, securite: 3, rapidite: 2 },
  neighborhoods: [
    {
      name: "Stare Miasto",
      vibe: "la vieille ville, au pied de la Grand-Place",
      tiers: ["standard", "confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Kazimierz",
      vibe: "ancien quartier juif, bars et cafés bohèmes",
      tiers: ["eco", "standard"],
      tags: ["fete", "culture"],
    },
    {
      name: "Podgórze",
      vibe: "rive droite, calme et chargé d'histoire",
      tiers: ["eco", "standard"],
      tags: ["culture", "detente"],
    },
  ],
  activities: [
    {
      id: "rynek",
      name: "Grand-Place et halle aux Draps",
      description: "L'une des plus grandes places médiévales d'Europe, trompettiste à chaque heure.",
      category: "quartier",
      emoji: "🏰",
      cost: 0,
      hours: 1.5,
      area: "Stare Miasto",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
      highlight: "La Grand-Place de Cracovie",
    },
    {
      id: "wawel",
      name: "Château et cathédrale du Wawel",
      description: "La colline royale, ses appartements et la grotte du dragon.",
      category: "monument",
      emoji: "🐉",
      cost: 15,
      hours: 2.5,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Le château du Wawel",
    },
    {
      id: "rynek-underground",
      name: "Musée souterrain de la Grand-Place",
      description: "Les fondations médiévales sous la place, en mode interactif.",
      category: "musee",
      emoji: "🏺",
      cost: 8,
      hours: 1.5,
      area: "Stare Miasto",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "kazimierz",
      name: "Balade dans Kazimierz",
      description: "Synagogues, cours secrètes et street art dans le quartier le plus vivant.",
      category: "quartier",
      emoji: "🕍",
      cost: 0,
      hours: 2,
      area: "Kazimierz",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "schindler",
      name: "Usine d'Oskar Schindler",
      description: "Musée poignant sur Cracovie pendant l'occupation nazie.",
      category: "musee",
      emoji: "🏭",
      cost: 8,
      hours: 2,
      area: "Podgórze",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "zapiekanka",
      name: "Zapiekanka place Nowy",
      description: "La demi-baguette gratinée, star de la street food polonaise.",
      category: "food",
      emoji: "🥖",
      cost: 4,
      hours: 1,
      area: "Kazimierz",
      moments: ["afternoon", "evening"],
      tags: ["gastronomie"],
      repeatable: true,
    },
    {
      id: "vodka",
      name: "Dégustation de vodka polonaise",
      description: "Cerise, miel, herbe de bison : tour d'horizon avec zakuski.",
      category: "food",
      emoji: "🥃",
      cost: 20,
      hours: 1.5,
      moments: ["evening"],
      tags: ["gastronomie", "fete"],
    },
    {
      id: "vistule",
      name: "Croisière sur la Vistule",
      description: "Une heure de bateau au pied du Wawel.",
      category: "panorama",
      emoji: "🛥️",
      cost: 10,
      hours: 1,
      moments: ["afternoon"],
      tags: ["detente", "romantique"],
    },
    {
      id: "krakus",
      name: "Coucher de soleil au tertre de Krakus",
      description: "Colline préhistorique avec vue sur toute la ville.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      area: "Podgórze",
      moments: ["evening"],
      tags: ["romantique", "nature"],
      repeatable: true,
    },
    {
      id: "bars-kazimierz",
      name: "Bars de Kazimierz",
      description: "Bars bric-à-brac à l'ambiance de salon de grand-mère, bière et vodka à petit prix.",
      category: "nightlife",
      emoji: "🍻",
      cost: 12,
      hours: 3,
      area: "Kazimierz",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit à Kazimierz",
      repeatable: true,
    },
    {
      id: "clubs-caves",
      name: "Clubs en cave de la vieille ville",
      description: "Des dizaines de clubs sous les voûtes médiévales.",
      category: "nightlife",
      emoji: "🎉",
      cost: 10,
      hours: 4,
      area: "Stare Miasto",
      moments: ["evening"],
      tags: ["fete"],
    },
    {
      id: "wieliczka",
      name: "Mine de sel de Wieliczka",
      description: "Chapelles et lustres sculptés dans le sel, à 135 m sous terre.",
      category: "excursion",
      emoji: "🧂",
      cost: 30,
      hours: 5,
      moments: ["morning"],
      tags: ["culture", "aventure"],
      highlight: "La cathédrale de sel de Wieliczka",
    },
    {
      id: "auschwitz",
      name: "Mémorial d'Auschwitz-Birkenau",
      description:
        "Visite guidée du camp, lieu de mémoire essentiel et bouleversant. Réserve longtemps à l'avance.",
      category: "excursion",
      emoji: "🕯️",
      cost: 25,
      hours: 7,
      moments: ["morning"],
      tags: ["culture"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-endzior",
      name: "Endzior",
      description: "Le kiosque à zapiekanki le plus célèbre de la place Nowy.",
      cuisine: "Street food polonaise",
      emoji: "🥖",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 4,
      area: "Kazimierz",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-pod-temida",
      name: "Bar Mleczny Pod Temidą",
      description: "Un « bar à lait », cantine populaire : soupe et pierogi pour quelques złotys.",
      cuisine: "Cuisine polonaise",
      emoji: "🥟",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      area: "Stare Miasto",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-pod-wawelem",
      name: "Pod Wawelem",
      description: "Brasserie aux portions gigantesques et à l'ambiance joyeuse.",
      cuisine: "Cuisine polonaise",
      emoji: "🍖",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      area: "Stare Miasto",
      meals: ["lunch", "dinner"],
      tags: ["fete"],
      real: true,
    },
    {
      id: "r-starka",
      name: "Starka",
      description: "Cuisine polonaise et vodkas maison dans une salle chaleureuse de Kazimierz.",
      cuisine: "Cuisine polonaise",
      emoji: "🥃",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Kazimierz",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
    {
      id: "r-wierzynek",
      name: "Wierzynek",
      description: "Table historique de la Grand-Place, cuisine polonaise raffinée.",
      cuisine: "Cuisine polonaise raffinée",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 55,
      area: "Stare Miasto",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(50.0614, 19.9366),
    zoom: 14,
    neighborhoods: {
      "Stare Miasto": p(50.0617, 19.9373),
      Kazimierz: p(50.0513, 19.944),
      Podgórze: p(50.0445, 19.9535),
    },
    places: {
      rynek: p(50.0617, 19.9373),
      wawel: p(50.054, 19.9354),
      "rynek-underground": p(50.0619, 19.9369),
      kazimierz: p(50.0513, 19.944),
      schindler: p(50.0475, 19.9617),
      zapiekanka: p(50.0515, 19.9446),
      vodka: p(50.06, 19.938),
      vistule: p(50.052, 19.933),
      krakus: p(50.038, 19.958),
      "bars-kazimierz": p(50.051, 19.945),
      "clubs-caves": p(50.063, 19.937),
      wieliczka: p(49.9832, 20.055),
      auschwitz: p(50.027, 19.203),
      "r-endzior": p(50.0516, 19.9447),
      "r-pod-temida": p(50.058, 19.938),
      "r-pod-wawelem": p(50.0565, 19.9365),
      "r-starka": p(50.0495, 19.9425),
      "r-wierzynek": p(50.0613, 19.9383),
    },
  },
  source: "demo",
};
