import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const dubai: DestinationProfile = {
  id: "dubai",
  name: "Dubaï",
  country: "Émirats arabes unis",
  countryCode: "AE",
  iata: "DXB",
  tagline: "Gratte-ciel record, souks et dunes au coucher du soleil.",
  description:
    "Le soleil garanti en plein hiver : la plus haute tour du monde, souks de l'or en abra, safari dans le désert, plages de sable fin et rooftops. Luxe partout, mais le vieux Dubaï reste abordable.",
  fallbackGradient: "from-amber-200 via-orange-400 to-sky-700",
  type: "mixte",
  costLevel: 4,
  costs: {
    accommodationPerNight: { eco: 45, standard: 100, confort: 220 },
    localTransportPerDay: 10,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "6 h 45",
        durationHours: 6.75,
        roundTripPerPerson: 450,
        details: "Vol direct, métro jusqu'au centre en 30 min",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Métro automatique propre et climatisé" },
    { mode: "taxi", description: "Taxis et VTC nombreux (la ville est faite pour la voiture)" },
    { mode: "ferry", description: "Abra traditionnelle pour traverser la Creek, pour 1 dirham" },
  ],
  idealDays: { min: 4, max: 7 },
  bestMonths: [11, 12, 1, 2, 3],
  styles: { shopping: 3, plage: 3, ville: 3, aventure: 2, fete: 2, detente: 2, culture: 1 },
  ambiances: { luxueuse: 3, festive: 2, aventureuse: 2, sociale: 2 },
  strengths: { securite: 3, confort: 3, plages: 3, activites: 3, "vie-nocturne": 2 },
  neighborhoods: [
    {
      name: "Downtown",
      vibe: "au pied du Burj Khalifa",
      tiers: ["standard", "confort"],
      tags: ["shopping", "ville"],
    },
    {
      name: "Dubai Marina",
      vibe: "plage, tours et vie nocturne",
      tiers: ["standard", "confort"],
      tags: ["plage", "fete"],
    },
    {
      name: "Deira",
      vibe: "le vieux Dubaï des souks, le plus abordable",
      tiers: ["eco", "standard"],
      tags: ["culture", "shopping"],
    },
  ],
  activities: [
    {
      id: "souks-deira",
      name: "Souks de l'or et des épices, en abra",
      description: "Traversée de la Creek en barque puis dédales d'épices, d'encens et de bijoux.",
      category: "shopping",
      emoji: "⛵",
      cost: 1,
      hours: 2,
      area: "Deira",
      moments: ["morning"],
      tags: ["culture", "shopping"],
      highlight: "Les souks du vieux Dubaï",
    },
    {
      id: "al-fahidi",
      name: "Quartier historique Al Fahidi",
      description: "Maisons en corail et tours à vent, galeries et cafés.",
      category: "quartier",
      emoji: "🏘️",
      cost: 0,
      hours: 2,
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "museum-future",
      name: "Museum of the Future",
      description: "Le bâtiment ovale calligraphié et ses expositions sur 2071.",
      category: "musee",
      emoji: "🔮",
      cost: 40,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "dubai-frame",
      name: "Dubai Frame",
      description: "Un cadre photo géant de 150 m entre le vieux et le nouveau Dubaï.",
      category: "panorama",
      emoji: "🖼️",
      cost: 15,
      hours: 1,
      moments: ["morning", "afternoon"],
      tags: ["ville"],
    },
    {
      id: "dubai-mall",
      name: "Dubai Mall et son aquarium",
      description: "Le plus grand centre commercial du monde, requins inclus.",
      category: "shopping",
      emoji: "🛍️",
      cost: 0,
      hours: 3,
      area: "Downtown",
      moments: ["afternoon"],
      tags: ["shopping"],
    },
    {
      id: "ski-dubai",
      name: "Ski Dubai",
      description: "Pistes de ski et pingouins… dans un centre commercial en plein désert.",
      category: "aventure",
      emoji: "⛷️",
      cost: 70,
      hours: 2,
      moments: ["afternoon"],
      tags: ["aventure"],
    },
    {
      id: "jbr",
      name: "Plage de JBR",
      description: "Sable fin, eau chaude et promenade animée au pied des tours.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 3,
      area: "Dubai Marina",
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      repeatable: true,
    },
    {
      id: "desert-safari",
      name: "Safari dans le désert",
      description: "4x4 dans les dunes, coucher de soleil et dîner bédouin sous les étoiles.",
      category: "excursion",
      emoji: "🐪",
      cost: 60,
      hours: 6,
      moments: ["afternoon"],
      tags: ["aventure", "nature"],
      highlight: "Coucher de soleil dans les dunes",
    },
    {
      id: "burj-khalifa",
      name: "Burj Khalifa au coucher du soleil",
      description: "Observatoire au 124ᵉ étage de la plus haute tour du monde.",
      category: "panorama",
      emoji: "🏙️",
      cost: 45,
      hours: 1.5,
      area: "Downtown",
      moments: ["evening"],
      tags: ["ville", "romantique"],
      highlight: "Au sommet du Burj Khalifa",
    },
    {
      id: "fontaine-dubai",
      name: "Spectacle de la fontaine",
      description: "Jets d'eau géants en musique au pied du Burj Khalifa, gratuit chaque soir.",
      category: "evenement",
      emoji: "⛲",
      cost: 0,
      hours: 1,
      area: "Downtown",
      moments: ["evening"],
      tags: ["romantique"],
    },
    {
      id: "marina-soiree",
      name: "Soirée rooftop à la Marina",
      description: "Bars en hauteur, lounges et clubs (alcool servi dans les hôtels, cher).",
      category: "nightlife",
      emoji: "🍸",
      cost: 40,
      hours: 3,
      area: "Dubai Marina",
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "abu-dhabi",
      name: "Excursion à Abu Dhabi",
      description: "La grande mosquée Sheikh Zayed, blanche et immense, et le Louvre Abu Dhabi.",
      category: "excursion",
      emoji: "🕌",
      cost: 40,
      hours: 9,
      moments: ["morning"],
      tags: ["culture"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-al-mallah",
      name: "Al Mallah",
      description: "Shawarmas et jus frais sur une terrasse de Satwa, ouvert tard.",
      cuisine: "Street food libanaise",
      emoji: "🌯",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-ravi",
      name: "Ravi Restaurant",
      description: "Curry et naan pakistanais depuis 1978, l'adresse culte à petit prix.",
      cuisine: "Cuisine pakistanaise",
      emoji: "🍛",
      kind: "local",
      isLocal: false,
      priceLevel: 1,
      cost: 8,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-al-ustad",
      name: "Al Ustad Special Kabab",
      description: "Kebabs iraniens depuis 1978, murs couverts de photos de clients.",
      cuisine: "Cuisine iranienne",
      emoji: "🍢",
      kind: "local",
      isLocal: false,
      priceLevel: 1,
      cost: 12,
      area: "Deira",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-arabian-tea-house",
      name: "Arabian Tea House",
      description: "Petit-déjeuner émirati dans une cour ombragée d'Al Fahidi.",
      cuisine: "Cuisine émiratie",
      emoji: "🫖",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      meals: ["lunch"],
      tags: ["romantique"],
      real: true,
    },
    {
      id: "r-pierchic",
      name: "Pierchic",
      description: "Restaurant de poissons au bout d'une jetée, face au Burj Al Arab.",
      cuisine: "Poissons & fruits de mer",
      emoji: "🦞",
      kind: "gastronomique",
      isLocal: false,
      priceLevel: 3,
      cost: 100,
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      real: true,
    },
  ],
  geo: {
    center: p(25.2048, 55.2708),
    zoom: 11,
    neighborhoods: {
      Downtown: p(25.1972, 55.2744),
      "Dubai Marina": p(25.08, 55.14),
      Deira: p(25.269, 55.304),
    },
    places: {
      "souks-deira": p(25.269, 55.297),
      "al-fahidi": p(25.2637, 55.2995),
      "museum-future": p(25.2192, 55.2819),
      "dubai-frame": p(25.2353, 55.3004),
      "dubai-mall": p(25.1985, 55.2796),
      "ski-dubai": p(25.117, 55.2),
      jbr: p(25.078, 55.134),
      "desert-safari": p(24.99, 55.6),
      "burj-khalifa": p(25.1972, 55.2744),
      "fontaine-dubai": p(25.1956, 55.275),
      "marina-soiree": p(25.08, 55.14),
      "abu-dhabi": p(24.4128, 54.4749),
      "r-al-mallah": p(25.233, 55.279),
      "r-ravi": p(25.234, 55.278),
      "r-al-ustad": p(25.26, 55.296),
      "r-arabian-tea-house": p(25.2637, 55.3),
      "r-pierchic": p(25.134, 55.184),
    },
  },
  source: "demo",
};
