import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const dublin: DestinationProfile = {
  id: "dublin",
  name: "Dublin",
  country: "Irlande",
  countryCode: "IE",
  iata: "DUB",
  tagline: "Pubs, musique live et falaises à portée de train.",
  description:
    "Une capitale à taille humaine où tout finit au pub : Guinness au Gravity Bar, sessions de musique irlandaise, balades sur les falaises de Howth et lacs du Wicklow.",
  fallbackGradient: "from-emerald-400 via-green-600 to-teal-900",
  type: "ville",
  costLevel: 4,
  costs: {
    accommodationPerNight: { eco: 45, standard: 100, confort: 180 },
    localTransportPerDay: 8,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "1 h 40",
        durationHours: 1.7,
        roundTripPerPerson: 130,
        details: "Vol direct, bus express jusqu'au centre en 30 min",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Le centre se fait facilement à pied" },
    { mode: "tram", description: "Deux lignes de tram (Luas) dans la ville" },
    { mode: "bus", description: "Train DART le long de la côte, de Howth à Dún Laoghaire" },
  ],
  idealDays: { min: 3, max: 5 },
  bestMonths: [5, 6, 7, 8, 9],
  styles: { fete: 3, culture: 2, ville: 2, nature: 2, festivals: 3, gastronomie: 1, aventure: 1 },
  ambiances: { sociale: 3, festive: 3, authentique: 3, aventureuse: 1 },
  strengths: { "vie-nocturne": 3, securite: 3, culture: 2, nature: 2, rapidite: 3 },
  neighborhoods: [
    {
      name: "Temple Bar",
      vibe: "pubs et musique à chaque coin de rue",
      tiers: ["standard", "confort"],
      tags: ["fete"],
    },
    {
      name: "Georgian Dublin",
      vibe: "élégant, parcs et portes colorées",
      tiers: ["confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Smithfield",
      vibe: "local, distilleries et pubs à sessions",
      tiers: ["eco", "standard"],
      tags: ["culture", "fete"],
    },
    {
      name: "Portobello",
      vibe: "village calme au bord du canal",
      tiers: ["eco", "standard"],
      tags: ["detente"],
    },
  ],
  activities: [
    {
      id: "trinity",
      name: "Trinity College et le Livre de Kells",
      description: "Manuscrit enluminé du IXᵉ siècle et la vertigineuse Long Room.",
      category: "musee",
      emoji: "📜",
      cost: 25,
      hours: 1.5,
      area: "Georgian Dublin",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "La Long Room de Trinity College",
    },
    {
      id: "guinness",
      name: "Guinness Storehouse",
      description: "Sept étages sur la stout la plus célèbre, pinte offerte au Gravity Bar panoramique.",
      category: "musee",
      emoji: "🍺",
      cost: 30,
      hours: 2,
      moments: ["afternoon"],
      tags: ["fete", "culture"],
      highlight: "Une pinte au Gravity Bar",
    },
    {
      id: "jameson",
      name: "Distillerie Jameson",
      description: "Visite et dégustation de whiskey irlandais dans l'ancienne distillerie.",
      category: "musee",
      emoji: "🥃",
      cost: 26,
      hours: 1.5,
      area: "Smithfield",
      moments: ["morning", "afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "grafton",
      name: "St Stephen's Green et Grafton Street",
      description: "Parc victorien et rue piétonne des musiciens de rue.",
      category: "quartier",
      emoji: "🌳",
      cost: 0,
      hours: 1.5,
      area: "Georgian Dublin",
      moments: ["morning", "afternoon"],
      tags: ["ville", "detente"],
    },
    {
      id: "kilmainham",
      name: "Prison de Kilmainham",
      description: "Là où furent exécutés les leaders de l'insurrection de 1916. Réserve tôt.",
      category: "musee",
      emoji: "🔒",
      cost: 8,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "epic",
      name: "EPIC, le musée de l'émigration irlandaise",
      description: "Musée interactif sur les 10 millions d'Irlandais partis dans le monde.",
      category: "musee",
      emoji: "🧳",
      cost: 25,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "phoenix-park",
      name: "Phoenix Park à vélo",
      description: "Un des plus grands parcs urbains d'Europe, avec des daims en liberté.",
      category: "nature",
      emoji: "🦌",
      cost: 10,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["nature", "detente"],
    },
    {
      id: "howth",
      name: "Randonnée sur les falaises de Howth",
      description: "Sentier côtier au-dessus de la mer, phoques au port et fish & chips.",
      category: "nature",
      emoji: "🥾",
      cost: 5,
      hours: 4,
      moments: ["morning"],
      tags: ["nature", "aventure"],
      highlight: "Les falaises de Howth",
    },
    {
      id: "forty-foot",
      name: "Baignade au Forty Foot",
      description: "Plongeon dans l'eau fraîche comme les Dublinois, toute l'année.",
      category: "plage",
      emoji: "🏊",
      cost: 0,
      hours: 1.5,
      moments: ["morning"],
      tags: ["aventure", "plage"],
    },
    {
      id: "dun-laoghaire",
      name: "Coucher de soleil sur la jetée de Dún Laoghaire",
      description: "Longue promenade sur la jetée, glace à la main.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "detente"],
      repeatable: true,
    },
    {
      id: "session-trad",
      name: "Session de musique irlandaise",
      description: "Violons et bodhrán dans un vrai pub de Smithfield, entrée libre.",
      category: "evenement",
      emoji: "🎻",
      cost: 10,
      hours: 2,
      area: "Smithfield",
      moments: ["evening"],
      tags: ["culture", "festivals", "fete"],
      highlight: "Une session trad au pub",
    },
    {
      id: "temple-bar",
      name: "Tournée des pubs de Temple Bar",
      description: "Musique live tous les soirs, ambiance garantie (pintes plus chères qu'ailleurs).",
      category: "nightlife",
      emoji: "🍻",
      cost: 25,
      hours: 3,
      area: "Temple Bar",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit à Temple Bar",
      repeatable: true,
    },
    {
      id: "glendalough",
      name: "Excursion à Glendalough et au Wicklow",
      description: "Lacs, forêts et monastère médiéval dans les « montagnes jardin de l'Irlande ».",
      category: "excursion",
      emoji: "🏞️",
      cost: 35,
      hours: 8,
      moments: ["morning"],
      tags: ["nature", "culture"],
      highlight: "Les lacs de Glendalough",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-leo-burdock",
      name: "Leo Burdock",
      description: "Le plus vieux fish & chips de la ville (1913), à emporter.",
      cuisine: "Fish & chips",
      emoji: "🐟",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-queen-of-tarts",
      name: "Queen of Tarts",
      description: "Salon de thé douillet : scones, tartes et petit-déjeuner irlandais.",
      cuisine: "Café & pâtisserie",
      emoji: "🥧",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "Temple Bar",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-brother-hubbard",
      name: "Brother Hubbard",
      description: "Brunch et cuisine d'inspiration moyen-orientale sur Capel Street.",
      cuisine: "Brunch",
      emoji: "🍳",
      kind: "bistrot",
      isLocal: false,
      priceLevel: 2,
      cost: 20,
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-brazen-head",
      name: "The Brazen Head",
      description: "Le plus vieux pub d'Irlande (1198) : ragoût irlandais et musique le soir.",
      cuisine: "Pub irlandais",
      emoji: "🍀",
      kind: "bar",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      meals: ["dinner"],
      tags: ["fete", "gastronomie"],
      real: true,
    },
    {
      id: "r-winding-stair",
      name: "The Winding Stair",
      description: "Au-dessus d'une librairie, vue sur le Ha'penny Bridge et cuisine irlandaise.",
      cuisine: "Cuisine irlandaise",
      emoji: "📖",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 55,
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      real: true,
    },
  ],
  geo: {
    center: p(53.3438, -6.2672),
    zoom: 13,
    neighborhoods: {
      "Temple Bar": p(53.3454, -6.2644),
      "Georgian Dublin": p(53.3385, -6.2505),
      Smithfield: p(53.3488, -6.2785),
      Portobello: p(53.3315, -6.2665),
    },
    places: {
      trinity: p(53.3438, -6.2546),
      guinness: p(53.3419, -6.2867),
      jameson: p(53.3486, -6.2773),
      grafton: p(53.3382, -6.2591),
      kilmainham: p(53.3419, -6.3095),
      epic: p(53.3481, -6.2476),
      "phoenix-park": p(53.3559, -6.3298),
      howth: p(53.379, -6.059),
      "forty-foot": p(53.289, -6.114),
      "dun-laoghaire": p(53.296, -6.13),
      "session-trad": p(53.3488, -6.2785),
      "temple-bar": p(53.3454, -6.2644),
      glendalough: p(53.0104, -6.3278),
      "r-leo-burdock": p(53.3425, -6.271),
      "r-queen-of-tarts": p(53.3441, -6.267),
      "r-brother-hubbard": p(53.3471, -6.2694),
      "r-brazen-head": p(53.3446, -6.2764),
      "r-winding-stair": p(53.3465, -6.263),
    },
  },
  source: "demo",
};
