import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const edimbourg: DestinationProfile = {
  id: "edimbourg",
  name: "Édimbourg",
  country: "Royaume-Uni",
  countryCode: "GB",
  iata: "EDI",
  tagline: "Château sur un volcan, ruelles gothiques et whisky.",
  description:
    "Une ville de conte, entre vieille ville médiévale et nouvelle ville géorgienne : ascension d'Arthur's Seat, pubs à musique live, fantômes des souterrains et Highlands à portée de bus.",
  fallbackGradient: "from-slate-400 via-indigo-700 to-purple-900",
  type: "ville",
  costLevel: 4,
  costs: {
    accommodationPerNight: { eco: 40, standard: 95, confort: 180 },
    localTransportPerDay: 7,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "1 h 50",
        durationHours: 1.85,
        roundTripPerPerson: 150,
        details: "Vol direct, tram jusqu'au centre en 35 min",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Tout se fait à pied (ça monte et ça descend !)" },
    { mode: "bus", description: "Bus Lothian fréquents, jusqu'à la plage de Portobello" },
    { mode: "tram", description: "Tram de l'aéroport jusqu'au port de Leith" },
  ],
  idealDays: { min: 3, max: 5 },
  bestMonths: [5, 6, 7, 8, 9],
  styles: { culture: 3, nature: 3, ville: 2, romantique: 2, fete: 2, festivals: 3, aventure: 2 },
  ambiances: { authentique: 3, romantique: 2, sociale: 2, aventureuse: 2, calme: 2 },
  strengths: { culture: 3, nature: 3, securite: 3, "vie-nocturne": 2, rapidite: 2 },
  neighborhoods: [
    {
      name: "Old Town",
      vibe: "médiéval, sur le Royal Mile",
      tiers: ["standard", "confort"],
      tags: ["culture", "fete"],
    },
    {
      name: "New Town",
      vibe: "géorgien, élégant et commerçant",
      tiers: ["standard", "confort"],
      tags: ["shopping", "romantique"],
    },
    {
      name: "Leith",
      vibe: "l'ancien port, bars et restos",
      tiers: ["eco", "standard"],
      tags: ["fete", "gastronomie"],
    },
    { name: "Stockbridge", vibe: "village chic et paisible", tiers: ["confort"], tags: ["detente"] },
  ],
  activities: [
    {
      id: "chateau-edi",
      name: "Château d'Édimbourg",
      description: "Forteresse perchée sur un volcan éteint, joyaux de la couronne d'Écosse.",
      category: "monument",
      emoji: "🏰",
      cost: 25,
      hours: 2.5,
      area: "Old Town",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Le château d'Édimbourg",
    },
    {
      id: "royal-mile",
      name: "Royal Mile et ses closes",
      description: "La grande rue de la vieille ville et ses passages étroits vers les jardins.",
      category: "quartier",
      emoji: "🏘️",
      cost: 0,
      hours: 2,
      area: "Old Town",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "arthurs-seat",
      name: "Ascension d'Arthur's Seat",
      description: "Un ancien volcan en pleine ville : 45 min de montée pour une vue jusqu'à la mer.",
      category: "nature",
      emoji: "⛰️",
      cost: 0,
      hours: 2.5,
      moments: ["morning", "afternoon"],
      tags: ["nature", "aventure"],
      highlight: "La vue depuis Arthur's Seat",
    },
    {
      id: "musee-ecosse",
      name: "Musée national d'Écosse",
      description: "Gratuit et passionnant : de la brebis Dolly aux reliques vikings. Rooftop en bonus.",
      category: "musee",
      emoji: "🏛️",
      cost: 0,
      hours: 2,
      area: "Old Town",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "victoria-street",
      name: "Victoria Street et Grassmarket",
      description: "La rue courbe aux façades colorées qui aurait inspiré le Chemin de Traverse.",
      category: "shopping",
      emoji: "🪄",
      cost: 0,
      hours: 1.5,
      area: "Old Town",
      moments: ["morning", "afternoon"],
      tags: ["shopping", "ville"],
    },
    {
      id: "dean-village",
      name: "Dean Village et Water of Leith",
      description: "Ancien village de meuniers au fond d'une vallée, en plein centre.",
      category: "quartier",
      emoji: "🌉",
      cost: 0,
      hours: 1.5,
      area: "Stockbridge",
      moments: ["morning", "afternoon"],
      tags: ["romantique", "nature"],
    },
    {
      id: "whisky",
      name: "Dégustation de whisky",
      description: "Initiation aux régions du scotch et dégustation guidée.",
      category: "food",
      emoji: "🥃",
      cost: 25,
      hours: 1.5,
      area: "Old Town",
      moments: ["afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "portobello",
      name: "Plage de Portobello",
      description: "Promenade balnéaire victorienne à 20 min de bus, baignade pour les courageux.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 2.5,
      moments: ["afternoon"],
      tags: ["plage", "detente"],
    },
    {
      id: "calton-hill",
      name: "Coucher de soleil sur Calton Hill",
      description: "Monuments néoclassiques et vue sur le château, la vieille ville et la mer.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1,
      moments: ["evening"],
      tags: ["romantique", "ville"],
      highlight: "Coucher de soleil sur Calton Hill",
      repeatable: true,
    },
    {
      id: "souterrains",
      name: "Visite des souterrains hantés",
      description: "Les voûtes sous le South Bridge, histoires de fantômes à la lampe.",
      category: "evenement",
      emoji: "👻",
      cost: 20,
      hours: 1.5,
      area: "Old Town",
      moments: ["evening"],
      tags: ["culture", "aventure"],
    },
    {
      id: "pubs-grassmarket",
      name: "Pubs et musique live au Grassmarket",
      description: "Folk écossais, pintes de real ale et ambiance de fin de semaine.",
      category: "nightlife",
      emoji: "🍻",
      cost: 20,
      hours: 3,
      area: "Old Town",
      moments: ["evening"],
      tags: ["fete", "festivals"],
      highlight: "Nuit dans les pubs d'Édimbourg",
      repeatable: true,
    },
    {
      id: "leith-shore",
      name: "Soirée sur le port de Leith",
      description: "Bars et restos le long de l'eau, plus local que le centre.",
      category: "nightlife",
      emoji: "⚓",
      cost: 20,
      hours: 3,
      area: "Leith",
      moments: ["evening"],
      tags: ["fete", "gastronomie"],
    },
    {
      id: "highlands",
      name: "Excursion dans les Highlands",
      description: "Lochs, vallées de Glencoe et châteaux en ruine en une journée de bus.",
      category: "excursion",
      emoji: "🏞️",
      cost: 60,
      hours: 11,
      moments: ["morning"],
      tags: ["nature", "aventure"],
      highlight: "Les paysages des Highlands",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-oink",
      name: "Oink",
      description: "Sandwichs au cochon rôti entier, farce et sauce pomme, sur Victoria Street.",
      cuisine: "Street food écossaise",
      emoji: "🐖",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      area: "Old Town",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-mums",
      name: "Mums Great Comfort Food",
      description: "Saucisses, purée et tourtes façon cantine britannique, portions énormes.",
      cuisine: "Comfort food britannique",
      emoji: "🥧",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "Old Town",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-deacon-brodie",
      name: "Deacon Brodie's Tavern",
      description: "Pub historique du Royal Mile, fish & chips et haggis.",
      cuisine: "Pub écossais",
      emoji: "🍺",
      kind: "bar",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Old Town",
      meals: ["lunch", "dinner"],
      tags: ["fete"],
      real: true,
    },
    {
      id: "r-scran-scallie",
      name: "The Scran & Scallie",
      description: "Gastropub du chef Tom Kitchin à Stockbridge, produits écossais.",
      cuisine: "Gastropub écossais",
      emoji: "🍽️",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 40,
      area: "Stockbridge",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-witchery",
      name: "The Witchery by the Castle",
      description: "Salles gothiques éclairées aux bougies au pied du château.",
      cuisine: "Cuisine écossaise",
      emoji: "🕯️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 75,
      area: "Old Town",
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      real: true,
    },
  ],
  geo: {
    center: p(55.9533, -3.1883),
    zoom: 14,
    neighborhoods: {
      "Old Town": p(55.9495, -3.1905),
      "New Town": p(55.9545, -3.1985),
      Leith: p(55.9755, -3.17),
      Stockbridge: p(55.9583, -3.2085),
    },
    places: {
      "chateau-edi": p(55.9486, -3.1999),
      "royal-mile": p(55.95, -3.188),
      "arthurs-seat": p(55.9441, -3.1618),
      "musee-ecosse": p(55.9469, -3.1899),
      "victoria-street": p(55.948, -3.1935),
      "dean-village": p(55.9523, -3.2177),
      whisky: p(55.9488, -3.196),
      portobello: p(55.954, -3.11),
      "calton-hill": p(55.9553, -3.1827),
      souterrains: p(55.9495, -3.187),
      "pubs-grassmarket": p(55.9474, -3.196),
      "leith-shore": p(55.9755, -3.17),
      highlands: p(56.68, -5.1),
      "r-oink": p(55.9484, -3.1937),
      "r-mums": p(55.9458, -3.188),
      "r-deacon-brodie": p(55.9495, -3.1928),
      "r-scran-scallie": p(55.9583, -3.2102),
      "r-witchery": p(55.9488, -3.1975),
    },
  },
  source: "demo",
};
