import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const florence: DestinationProfile = {
  id: "florence",
  name: "Florence",
  country: "Italie",
  countryCode: "IT",
  iata: "FLR",
  tagline: "La Renaissance à chaque coin de rue, et la Toscane en bonus.",
  description:
    "Un musée à ciel ouvert : le Duomo, le David, les Offices, puis aperitivo à Santo Spirito, coucher de soleil sur l'Arno et escapade dans les vignes du Chianti.",
  fallbackGradient: "from-amber-300 via-orange-500 to-rose-700",
  type: "ville",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 35, standard: 75, confort: 150 },
    localTransportPerDay: 4,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "1 h 45",
        durationHours: 1.75,
        roundTripPerPerson: 170,
        details: "Vol vers Florence ou Pise (souvent moins cher), puis tram ou train jusqu'au centre",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Tout le centre historique se fait à pied" },
    { mode: "bus", description: "Bus et tram pour les collines et la gare" },
    { mode: "velo", description: "Vélos en libre-service pour longer l'Arno" },
  ],
  idealDays: { min: 3, max: 5 },
  bestMonths: [4, 5, 6, 9, 10],
  styles: {
    culture: 3,
    romantique: 3,
    gastronomie: 3,
    ville: 2,
    shopping: 2,
    nature: 1,
    detente: 1,
    fete: 1,
  },
  ambiances: { romantique: 3, authentique: 2, luxueuse: 2, calme: 2, sociale: 2 },
  strengths: { culture: 3, gastronomie: 3, securite: 3, rapidite: 2, prix: 1 },
  neighborhoods: [
    {
      name: "Centro storico",
      vibe: "entre le Duomo et la Signoria",
      tiers: ["standard", "confort"],
      tags: ["culture", "ville"],
    },
    {
      name: "Oltrarno",
      vibe: "artisans, places vivantes et ambiance locale",
      tiers: ["eco", "standard"],
      tags: ["romantique", "gastronomie", "fete"],
    },
    {
      name: "Santa Croce",
      vibe: "animé, bars et petits restos",
      tiers: ["eco", "standard"],
      tags: ["fete", "ville"],
    },
    {
      name: "San Niccolò",
      vibe: "calme, au pied du Piazzale Michelangelo",
      tiers: ["confort"],
      tags: ["romantique", "detente"],
    },
  ],
  activities: [
    {
      id: "duomo",
      name: "Duomo et coupole de Brunelleschi",
      description:
        "463 marches jusqu'au sommet de la coupole, fresques du Jugement dernier au passage. Créneau à réserver.",
      category: "monument",
      emoji: "⛪",
      cost: 30,
      hours: 2.5,
      area: "Centro storico",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "La montée sur la coupole du Duomo",
    },
    {
      id: "uffizi",
      name: "Galerie des Offices",
      description: "Botticelli, Léonard, Raphaël : la Naissance de Vénus en vrai.",
      category: "musee",
      emoji: "🖼️",
      cost: 25,
      hours: 3,
      area: "Centro storico",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "La Naissance de Vénus aux Offices",
    },
    {
      id: "accademia",
      name: "Le David à la Galleria dell'Accademia",
      description: "Cinq mètres de marbre sculptés par Michel-Ange.",
      category: "musee",
      emoji: "🗿",
      cost: 16,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "ponte-vecchio",
      name: "Ponte Vecchio et place de la Seigneurie",
      description: "Le pont des orfèvres et la place aux statues en plein air.",
      category: "quartier",
      emoji: "🌉",
      cost: 0,
      hours: 1.5,
      area: "Centro storico",
      moments: ["morning", "afternoon"],
      tags: ["ville", "romantique"],
    },
    {
      id: "boboli",
      name: "Jardins de Boboli",
      description: "Jardins à l'italienne derrière le palais Pitti, grottes et vue sur la ville.",
      category: "detente",
      emoji: "🌳",
      cost: 10,
      hours: 2.5,
      area: "Oltrarno",
      moments: ["morning", "afternoon"],
      tags: ["detente", "nature", "romantique"],
    },
    {
      id: "oltrarno",
      name: "Ateliers d'artisans de l'Oltrarno",
      description: "Maroquiniers, doreurs et relieurs dans les ruelles de l'autre rive.",
      category: "shopping",
      emoji: "🧵",
      cost: 0,
      hours: 2,
      area: "Oltrarno",
      moments: ["morning", "afternoon"],
      tags: ["shopping", "culture"],
    },
    {
      id: "mercato-centrale",
      name: "Mercato Centrale",
      description: "Marché au rez-de-chaussée, stands de dégustation à l'étage.",
      category: "food",
      emoji: "🧀",
      cost: 15,
      hours: 1.5,
      moments: ["morning"],
      tags: ["gastronomie"],
    },
    {
      id: "cours-pates",
      name: "Cours de pâtes fraîches",
      description: "Pétrir, étaler, découper… puis manger ce qu'on a cuisiné, avec un verre de chianti.",
      category: "food",
      emoji: "🍝",
      cost: 60,
      hours: 3,
      moments: ["afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "fiesole",
      name: "Vélo électrique jusqu'à Fiesole",
      description: "Montée tranquille vers le village étrusque qui domine Florence.",
      category: "aventure",
      emoji: "🚴",
      cost: 45,
      hours: 3,
      moments: ["morning"],
      tags: ["aventure", "nature"],
    },
    {
      id: "piazzale",
      name: "Coucher de soleil au Piazzale Michelangelo",
      description: "Toute la ville en rose et or, le Duomo au centre du tableau.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      area: "San Niccolò",
      moments: ["evening"],
      tags: ["romantique", "ville"],
      highlight: "Coucher de soleil sur Florence",
      repeatable: true,
    },
    {
      id: "santo-spirito",
      name: "Aperitivo place Santo Spirito",
      description: "Spritz sur les marches de l'église, la place s'anime jusque tard.",
      category: "nightlife",
      emoji: "🍹",
      cost: 15,
      hours: 2.5,
      area: "Oltrarno",
      moments: ["evening"],
      tags: ["fete", "romantique"],
      highlight: "Aperitivo à Santo Spirito",
      repeatable: true,
    },
    {
      id: "santa-croce-bars",
      name: "Soirée dans les bars de Santa Croce",
      description: "Bars étudiants et caves à vin autour de la basilique.",
      category: "nightlife",
      emoji: "🍷",
      cost: 20,
      hours: 3,
      area: "Santa Croce",
      moments: ["evening"],
      tags: ["fete"],
    },
    {
      id: "chianti",
      name: "Excursion dans le Chianti",
      description: "Collines de cyprès, villages et dégustation dans un domaine viticole.",
      category: "excursion",
      emoji: "🍇",
      cost: 90,
      hours: 8,
      moments: ["morning"],
      tags: ["nature", "gastronomie", "romantique"],
      highlight: "Les vignobles du Chianti",
      fullDay: true,
    },
    {
      id: "pise",
      name: "Excursion à Pise",
      description: "La tour penchée et la place des Miracles, à une heure de train.",
      category: "excursion",
      emoji: "🗼",
      cost: 30,
      hours: 6,
      moments: ["morning"],
      tags: ["culture"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-antico-vinaio",
      name: "All'Antico Vinaio",
      description: "Schiacciata (focaccia toscane) garnie à la demande, la file vaut le coup.",
      cuisine: "Sandwichs toscans",
      emoji: "🥪",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 10,
      area: "Santa Croce",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-nerbone",
      name: "Da Nerbone",
      description: "Comptoir de 1872 dans le Mercato Centrale : panino au lampredotto (tripes).",
      cuisine: "Street food florentine",
      emoji: "🥙",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 10,
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-trattoria-mario",
      name: "Trattoria Mario",
      description: "Tables partagées, cuisine familiale, le midi uniquement.",
      cuisine: "Cuisine toscane",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 20,
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-osteria-santo-spirito",
      name: "Osteria Santo Spirito",
      description: "Sur la place la plus sympa de l'Oltrarno, gnocchis gratinés à la truffe.",
      cuisine: "Cuisine toscane",
      emoji: "🍝",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 32,
      area: "Oltrarno",
      meals: ["lunch", "dinner"],
      tags: ["romantique", "gastronomie"],
      real: true,
    },
    {
      id: "r-sostanza",
      name: "Trattoria Sostanza",
      description: "Institution de 1869 : poulet au beurre et bistecca à la florentine.",
      cuisine: "Cuisine toscane",
      emoji: "🥩",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 45,
      area: "Centro storico",
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-buca-mario",
      name: "Buca Mario",
      description: "Cave voûtée depuis 1886, bistecca alla fiorentina dans les règles de l'art.",
      cuisine: "Cuisine florentine",
      emoji: "🍷",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 60,
      area: "Centro storico",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(43.7696, 11.2558),
    zoom: 14,
    neighborhoods: {
      "Centro storico": p(43.7713, 11.2545),
      Oltrarno: p(43.7659, 11.2478),
      "Santa Croce": p(43.7686, 11.262),
      "San Niccolò": p(43.7645, 11.2625),
    },
    places: {
      duomo: p(43.7731, 11.256),
      uffizi: p(43.7678, 11.2553),
      accademia: p(43.7768, 11.2586),
      "ponte-vecchio": p(43.768, 11.2531),
      boboli: p(43.7625, 11.2482),
      oltrarno: p(43.7665, 11.247),
      "mercato-centrale": p(43.7765, 11.2533),
      "cours-pates": p(43.77, 11.256),
      fiesole: p(43.8067, 11.294),
      piazzale: p(43.7629, 11.265),
      "santo-spirito": p(43.7663, 11.2479),
      "santa-croce-bars": p(43.7686, 11.262),
      chianti: p(43.546, 11.308),
      pise: p(43.723, 10.3966),
      "r-antico-vinaio": p(43.7685, 11.2573),
      "r-nerbone": p(43.7763, 11.2537),
      "r-trattoria-mario": p(43.776, 11.2536),
      "r-osteria-santo-spirito": p(43.7659, 11.2474),
      "r-sostanza": p(43.7729, 11.2474),
      "r-buca-mario": p(43.7715, 11.2493),
    },
  },
  source: "demo",
};
