import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const hanoi: DestinationProfile = {
  id: "hanoi",
  name: "Hanoï",
  country: "Viêt Nam",
  countryCode: "VN",
  iata: "HAN",
  tagline: "Scooters, phở fumant et baie d'Halong à l'horizon.",
  description:
    "Une capitale pleine d'énergie : vieux quartier aux 36 rues, café à l'œuf, bière fraîche sur des tabourets en plastique, puis les paysages irréels de Ninh Binh et de la baie d'Halong.",
  fallbackGradient: "from-lime-300 via-emerald-600 to-red-700",
  type: "ville",
  costLevel: 1,
  costs: {
    accommodationPerNight: { eco: 12, standard: 35, confort: 85 },
    localTransportPerDay: 4,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "12 h",
        durationHours: 12,
        roundTripPerPerson: 700,
        details: "Vol direct ou avec escale, taxi ou bus jusqu'au vieux quartier en 45 min",
      },
    ],
  },
  localMobility: [
    {
      mode: "marche",
      description: "Le vieux quartier se vit à pied (traverse lentement, les scooters t'évitent)",
    },
    { mode: "taxi", description: "VTC et moto-taxis via Grab, très bon marché" },
    { mode: "bus", description: "Bus et minibus pour Ninh Binh et Halong" },
  ],
  idealDays: { min: 4, max: 10 },
  bestMonths: [3, 4, 10, 11, 12],
  styles: { gastronomie: 3, culture: 3, ville: 2, nature: 3, aventure: 2, fete: 2 },
  ambiances: { authentique: 3, economique: 3, aventureuse: 3, sociale: 2 },
  strengths: { prix: 3, gastronomie: 3, culture: 3, nature: 3, securite: 2 },
  neighborhoods: [
    {
      name: "Vieux quartier",
      vibe: "le cœur battant, rues des métiers",
      tiers: ["eco", "standard"],
      tags: ["culture", "fete"],
    },
    {
      name: "Hoan Kiem",
      vibe: "autour du lac, central et agréable",
      tiers: ["standard", "confort"],
      tags: ["romantique", "ville"],
    },
    {
      name: "Tay Ho",
      vibe: "lac de l'Ouest, calme et verdoyant",
      tiers: ["standard", "confort"],
      tags: ["detente"],
    },
  ],
  activities: [
    {
      id: "vieux-quartier-hanoi",
      name: "Le vieux quartier des 36 rues",
      description: "Chaque rue son métier : soie, bambou, papier votif, étain…",
      category: "quartier",
      emoji: "🛵",
      cost: 0,
      hours: 2,
      area: "Vieux quartier",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
      highlight: "Se perdre dans le vieux quartier",
    },
    {
      id: "hoan-kiem",
      name: "Lac Hoan Kiem et temple Ngoc Son",
      description: "Tai-chi au lever du jour et pont rouge vers le temple.",
      category: "detente",
      emoji: "🌉",
      cost: 1,
      hours: 1.5,
      area: "Hoan Kiem",
      moments: ["morning"],
      tags: ["romantique", "culture"],
    },
    {
      id: "temple-litterature",
      name: "Temple de la Littérature",
      description: "La première université du pays, cours et jardins paisibles.",
      category: "monument",
      emoji: "🏯",
      cost: 2,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "mausolee",
      name: "Mausolée de Hô Chi Minh",
      description: "Le lieu le plus solennel du pays, le matin uniquement. Tenue correcte.",
      category: "monument",
      emoji: "🏛️",
      cost: 0,
      hours: 1.5,
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "musee-femme",
      name: "Musée de la Femme vietnamienne",
      description: "L'un des meilleurs musées de la ville, passionnant et bien expliqué.",
      category: "musee",
      emoji: "👒",
      cost: 2,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "cours-cuisine-hanoi",
      name: "Cours de cuisine vietnamienne",
      description: "Marché, puis nems, phở et salade de papaye.",
      category: "food",
      emoji: "🥢",
      cost: 30,
      hours: 3,
      moments: ["morning"],
      tags: ["gastronomie"],
    },
    {
      id: "tay-ho",
      name: "Vélo autour du lac de l'Ouest",
      description: "17 km de berges, pagodes et cafés au bord de l'eau.",
      category: "nature",
      emoji: "🚲",
      cost: 5,
      hours: 2,
      area: "Tay Ho",
      moments: ["afternoon"],
      tags: ["detente", "nature"],
    },
    {
      id: "street-food-hanoi",
      name: "Tour street food du soir",
      description: "Bún chả, bánh mì, nems frits et café à l'œuf en tabourets bas.",
      category: "food",
      emoji: "🍜",
      cost: 20,
      hours: 3,
      area: "Vieux quartier",
      moments: ["evening"],
      tags: ["gastronomie"],
      highlight: "Street food à Hanoï",
      repeatable: true,
    },
    {
      id: "marionnettes",
      name: "Marionnettes sur l'eau",
      description: "Art traditionnel né dans les rizières, musique live.",
      category: "evenement",
      emoji: "🎎",
      cost: 5,
      hours: 1,
      area: "Hoan Kiem",
      moments: ["evening"],
      tags: ["culture"],
    },
    {
      id: "ta-hien",
      name: "Bia hơi rue Ta Hien",
      description: "La bière fraîche du jour à quelques centimes, sur le trottoir.",
      category: "nightlife",
      emoji: "🍺",
      cost: 5,
      hours: 3,
      area: "Vieux quartier",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Soirée bia hơi",
      repeatable: true,
    },
    {
      id: "ninh-binh",
      name: "Excursion à Ninh Binh",
      description: "La « baie d'Halong terrestre » : barque entre les pitons calcaires de Trang An.",
      category: "excursion",
      emoji: "🛶",
      cost: 45,
      hours: 10,
      moments: ["morning"],
      tags: ["nature"],
      highlight: "Les paysages de Ninh Binh",
      fullDay: true,
    },
    {
      id: "halong",
      name: "Croisière dans la baie d'Halong",
      description: "Kayak entre les îlots karstiques et grottes (idéal avec une nuit à bord).",
      category: "excursion",
      emoji: "⛵",
      cost: 90,
      hours: 12,
      moments: ["morning"],
      tags: ["nature", "romantique", "aventure"],
      highlight: "La baie d'Halong",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-pho-bat-dan",
      name: "Phở Gia Truyền Bát Đàn",
      description: "Le phở au bœuf de référence, on fait la queue et on mange vite.",
      cuisine: "Phở",
      emoji: "🍜",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 3,
      area: "Vieux quartier",
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-bun-cha-huong-lien",
      name: "Bún Chả Hương Liên",
      description: "Le bún chả (porc grillé et vermicelles) partagé par Obama et Bourdain.",
      cuisine: "Bún chả",
      emoji: "🥢",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 4,
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-cafe-giang",
      name: "Café Giảng",
      description: "L'inventeur du café à l'œuf en 1946, crémeux comme un tiramisu.",
      cuisine: "Café vietnamien",
      emoji: "☕",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 2,
      area: "Vieux quartier",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-cha-ca-thang-long",
      name: "Chả Cá Thăng Long",
      description: "Poisson au curcuma et à l'aneth cuit à table, spécialité de Hanoï.",
      cuisine: "Cuisine du Nord",
      emoji: "🐟",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
  ],
  geo: {
    center: p(21.0285, 105.8542),
    zoom: 13,
    neighborhoods: {
      "Vieux quartier": p(21.034, 105.85),
      "Hoan Kiem": p(21.0288, 105.8525),
      "Tay Ho": p(21.058, 105.82),
    },
    places: {
      "vieux-quartier-hanoi": p(21.034, 105.85),
      "hoan-kiem": p(21.0288, 105.8525),
      "temple-litterature": p(21.0277, 105.8355),
      mausolee: p(21.0368, 105.8346),
      "musee-femme": p(21.025, 105.855),
      "cours-cuisine-hanoi": p(21.03, 105.85),
      "tay-ho": p(21.058, 105.82),
      "street-food-hanoi": p(21.0335, 105.85),
      marionnettes: p(21.0318, 105.853),
      "ta-hien": p(21.036, 105.852),
      "ninh-binh": p(20.251, 105.975),
      halong: p(20.9101, 107.1839),
      "r-pho-bat-dan": p(21.0335, 105.8466),
      "r-bun-cha-huong-lien": p(21.018, 105.854),
      "r-cafe-giang": p(21.0333, 105.854),
      "r-cha-ca-thang-long": p(21.031, 105.846),
    },
  },
  source: "demo",
};
