import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const ibiza: DestinationProfile = {
  id: "ibiza",
  name: "Ibiza",
  country: "Espagne",
  countryCode: "ES",
  iata: "IBZ",
  tagline: "Criques turquoise, couchers de soleil mythiques et clubs légendaires.",
  description:
    "L'île de la fête, mais pas que : vieille ville fortifiée, criques sauvages, marchés hippies et escapade à Formentera. Chère en été, magique au printemps.",
  fallbackGradient: "from-fuchsia-400 via-pink-500 to-sky-500",
  type: "balneaire",
  costLevel: 4,
  costs: {
    accommodationPerNight: { eco: 45, standard: 95, confort: 190 },
    localTransportPerDay: 12,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h",
        durationHours: 2,
        roundTripPerPerson: 180,
        details: "Vols directs surtout d'avril à octobre, bus ou taxi vers les plages",
      },
    ],
  },
  localMobility: [
    { mode: "bus", description: "Bus entre la ville, Sant Antoni et les plages (réduits hors saison)" },
    { mode: "taxi", description: "Taxis chers et rares en août : réserve à l'avance" },
    { mode: "ferry", description: "Ferries rapides vers Formentera en 30 min" },
    { mode: "velo", description: "Scooter ou vélo électrique pour explorer les criques" },
  ],
  idealDays: { min: 4, max: 8 },
  bestMonths: [5, 6, 7, 8, 9],
  styles: { fete: 3, plage: 3, detente: 2, romantique: 2, nature: 2, aventure: 2, festivals: 3 },
  ambiances: { festive: 3, sociale: 3, luxueuse: 3, romantique: 2, calme: 1 },
  strengths: { "vie-nocturne": 3, plages: 3, nature: 2, securite: 3, activites: 2 },
  neighborhoods: [
    {
      name: "Dalt Vila et port",
      vibe: "la vieille ville et les bars du port",
      tiers: ["standard", "confort"],
      tags: ["culture", "fete"],
    },
    {
      name: "Playa d'en Bossa",
      vibe: "plage et clubs à portée de pied",
      tiers: ["standard", "confort"],
      tags: ["fete", "plage"],
    },
    {
      name: "Sant Antoni",
      vibe: "couchers de soleil et ambiance jeune",
      tiers: ["eco", "standard"],
      tags: ["fete", "plage"],
    },
    {
      name: "Santa Eulària",
      vibe: "calme, familial et bord de mer",
      tiers: ["standard", "confort"],
      tags: ["detente", "romantique"],
    },
  ],
  activities: [
    {
      id: "dalt-vila",
      name: "Dalt Vila, la ville haute fortifiée",
      description: "Remparts Renaissance classés à l'Unesco, ruelles blanches et vue sur le port.",
      category: "monument",
      emoji: "🏰",
      cost: 0,
      hours: 2,
      area: "Dalt Vila et port",
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
    },
    {
      id: "ses-salines",
      name: "Plage de Ses Salines",
      description: "Longue plage de sable blanc dans un parc naturel, eau turquoise.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 4,
      moments: ["morning", "afternoon"],
      tags: ["plage", "detente"],
      highlight: "Journée à Ses Salines",
      repeatable: true,
    },
    {
      id: "cala-comte",
      name: "Coucher de soleil à Cala Comte",
      description: "Rochers, eau cristalline et l'un des plus beaux couchers de soleil de l'île.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 2,
      moments: ["evening"],
      tags: ["romantique", "plage", "detente"],
      highlight: "Coucher de soleil à Cala Comte",
      repeatable: true,
    },
    {
      id: "cafe-del-mar",
      name: "Sunset au Café del Mar",
      description: "Le rituel de Sant Antoni : un verre, de la musique chill et le soleil qui plonge.",
      category: "panorama",
      emoji: "🍹",
      cost: 15,
      hours: 1.5,
      area: "Sant Antoni",
      moments: ["evening"],
      tags: ["fete", "romantique"],
    },
    {
      id: "es-vedra",
      name: "Point de vue sur Es Vedrà",
      description: "Le rocher mystérieux qui surgit de la mer, depuis la falaise.",
      category: "panorama",
      emoji: "🪨",
      cost: 0,
      hours: 1.5,
      moments: ["afternoon", "evening"],
      tags: ["nature", "romantique"],
    },
    {
      id: "kayak-ibiza",
      name: "Kayak et snorkeling dans les criques",
      description: "Grottes marines et criques accessibles seulement par la mer.",
      category: "aventure",
      emoji: "🛶",
      cost: 45,
      hours: 3,
      moments: ["morning"],
      tags: ["aventure", "nature", "plage"],
    },
    {
      id: "yoga-ibiza",
      name: "Yoga face à la mer",
      description: "Séance au lever du jour sur une terrasse ou une plage calme.",
      category: "detente",
      emoji: "🧘",
      cost: 20,
      hours: 1.5,
      moments: ["morning"],
      tags: ["detente"],
    },
    {
      id: "hippy-market",
      name: "Marché hippie de Punta Arabí",
      description: "Le mercredi, bijoux, fringues et artisans depuis les années 1970.",
      category: "shopping",
      emoji: "🛍️",
      cost: 0,
      hours: 2.5,
      area: "Santa Eulària",
      moments: ["morning"],
      tags: ["shopping"],
    },
    {
      id: "day-club",
      name: "Pool party en day club",
      description: "Piscine, DJ stars et fête en plein jour à Playa d'en Bossa.",
      category: "nightlife",
      emoji: "🎧",
      cost: 60,
      hours: 4,
      area: "Playa d'en Bossa",
      moments: ["afternoon"],
      tags: ["fete", "festivals"],
    },
    {
      id: "boat-party-ibiza",
      name: "Boat party",
      description: "Bateau, DJ, baignade en pleine mer et coucher de soleil.",
      category: "nightlife",
      emoji: "🛥️",
      cost: 60,
      hours: 4,
      moments: ["afternoon"],
      tags: ["fete", "plage"],
      highlight: "Boat party au large d'Ibiza",
    },
    {
      id: "port-ibiza",
      name: "Soirée dans les bars du port",
      description: "Terrasses, parades et apéros avant les clubs.",
      category: "nightlife",
      emoji: "🍸",
      cost: 25,
      hours: 3,
      area: "Dalt Vila et port",
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "club-ibiza",
      name: "Nuit dans un club mythique",
      description: "Les plus grands DJ du monde, jusqu'au lever du soleil. Billets souvent chers.",
      category: "nightlife",
      emoji: "🎉",
      cost: 70,
      hours: 5,
      moments: ["evening"],
      tags: ["fete", "festivals"],
      highlight: "Nuit en club à Ibiza",
    },
    {
      id: "formentera",
      name: "Excursion à Formentera",
      description: "L'île voisine aux eaux caribéennes, en ferry puis en scooter.",
      category: "excursion",
      emoji: "⛴️",
      cost: 60,
      hours: 9,
      moments: ["morning"],
      tags: ["plage", "nature", "detente"],
      highlight: "Les eaux turquoise de Formentera",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-bar-san-juan",
      name: "Comidas Bar San Juan",
      description: "Cantine familiale de la ville, tables partagées et prix d'avant.",
      cuisine: "Cuisine ibicenca",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "Dalt Vila et port",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-bar-costa",
      name: "Bar Costa",
      description: "Bar de village à Santa Gertrudis : jambons suspendus et bocadillos.",
      cuisine: "Tapas & bocadillos",
      emoji: "🥖",
      kind: "bar",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-la-bodega-ibiza",
      name: "La Bodega",
      description: "Bar à tapas au pied de Dalt Vila, animé dès l'apéro.",
      cuisine: "Tapas",
      emoji: "🍷",
      kind: "bar",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Dalt Vila et port",
      meals: ["dinner"],
      tags: ["fete"],
      real: true,
    },
    {
      id: "r-es-boldado",
      name: "Es Boldado",
      description: "Poissons et riz face au rocher d'Es Vedrà, au bout d'une piste.",
      cuisine: "Poissons & paella",
      emoji: "🐟",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 45,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
    {
      id: "r-sa-capella",
      name: "Sa Capella",
      description: "Dîner dans une chapelle du XVIᵉ siècle éclairée aux bougies.",
      cuisine: "Cuisine méditerranéenne",
      emoji: "🕯️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 60,
      area: "Sant Antoni",
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      real: true,
    },
  ],
  geo: {
    center: p(38.9395, 1.36),
    zoom: 11,
    neighborhoods: {
      "Dalt Vila et port": p(38.9095, 1.4365),
      "Playa d'en Bossa": p(38.8835, 1.4085),
      "Sant Antoni": p(38.9805, 1.3035),
      "Santa Eulària": p(38.9845, 1.5335),
    },
    places: {
      "dalt-vila": p(38.9067, 1.4357),
      "ses-salines": p(38.84, 1.396),
      "cala-comte": p(38.964, 1.22),
      "cafe-del-mar": p(38.9819, 1.2958),
      "es-vedra": p(38.869, 1.209),
      "kayak-ibiza": p(39.01, 1.295),
      "yoga-ibiza": p(38.885, 1.41),
      "hippy-market": p(38.976, 1.562),
      "day-club": p(38.881, 1.404),
      "boat-party-ibiza": p(38.98, 1.3),
      "port-ibiza": p(38.911, 1.438),
      "club-ibiza": p(38.916, 1.44),
      formentera: p(38.705, 1.45),
      "r-bar-san-juan": p(38.9086, 1.4353),
      "r-bar-costa": p(38.987, 1.429),
      "r-la-bodega-ibiza": p(38.908, 1.436),
      "r-es-boldado": p(38.874, 1.221),
      "r-sa-capella": p(38.995, 1.31),
    },
  },
  source: "demo",
};
