import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const istanbul: DestinationProfile = {
  id: "istanbul",
  name: "Istanbul",
  country: "Turquie",
  countryCode: "TR",
  iata: "IST",
  tagline: "Entre deux continents : mosquées, bazars et ferries sur le Bosphore.",
  description:
    "Une mégapole fascinante et abordable : Sainte-Sophie, Grand Bazar, hammam, traversée en ferry vers l'Asie pour quelques centimes et rooftops au coucher du soleil.",
  fallbackGradient: "from-amber-300 via-rose-500 to-indigo-800",
  type: "ville",
  costLevel: 1,
  costs: {
    accommodationPerNight: { eco: 22, standard: 50, confort: 110 },
    localTransportPerDay: 4,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "3 h 30",
        durationHours: 3.5,
        roundTripPerPerson: 220,
        details: "Vol direct vers IST ou SAW, puis métro ou navette (45 à 60 min)",
      },
    ],
  },
  localMobility: [
    { mode: "tram", description: "Le tram T1 relie Sultanahmet, Eminönü et Karaköy" },
    { mode: "ferry", description: "Les vapur traversent le Bosphore pour le prix d'un ticket de métro" },
    { mode: "metro", description: "Métro et funiculaire avec la carte Istanbulkart" },
    { mode: "taxi", description: "Taxis bon marché (demande le compteur)" },
  ],
  idealDays: { min: 4, max: 7 },
  bestMonths: [4, 5, 6, 9, 10],
  styles: { culture: 3, gastronomie: 3, ville: 3, shopping: 3, fete: 2, romantique: 2, detente: 2 },
  ambiances: { authentique: 3, economique: 3, sociale: 2, aventureuse: 2, festive: 2 },
  strengths: { culture: 3, gastronomie: 3, prix: 3, "vie-nocturne": 2, activites: 3 },
  neighborhoods: [
    {
      name: "Sultanahmet",
      vibe: "au pied des grands monuments",
      tiers: ["eco", "standard"],
      tags: ["culture"],
    },
    {
      name: "Beyoğlu",
      vibe: "Istiklal, Taksim et vie nocturne",
      tiers: ["eco", "standard", "confort"],
      tags: ["fete", "shopping"],
    },
    {
      name: "Karaköy",
      vibe: "branché, cafés et galeries au bord de l'eau",
      tiers: ["standard", "confort"],
      tags: ["gastronomie", "romantique"],
    },
    {
      name: "Kadıköy",
      vibe: "rive asiatique, local et étudiant",
      tiers: ["eco", "standard"],
      tags: ["fete", "gastronomie"],
    },
  ],
  activities: [
    {
      id: "sainte-sophie",
      name: "Sainte-Sophie",
      description: "Basilique puis mosquée depuis 1 500 ans, coupole vertigineuse. Tenue couvrante demandée.",
      category: "monument",
      emoji: "🕌",
      cost: 25,
      hours: 1.5,
      area: "Sultanahmet",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "La coupole de Sainte-Sophie",
    },
    {
      id: "mosquee-bleue",
      name: "Mosquée bleue",
      description: "Six minarets et 20 000 carreaux d'Iznik (hors heures de prière).",
      category: "monument",
      emoji: "🕌",
      cost: 0,
      hours: 1,
      area: "Sultanahmet",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "topkapi",
      name: "Palais de Topkapı",
      description: "Le palais des sultans, son harem et sa vue sur le Bosphore.",
      category: "musee",
      emoji: "👑",
      cost: 40,
      hours: 3,
      area: "Sultanahmet",
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "citerne",
      name: "Citerne Basilique",
      description: "Forêt de colonnes éclairées dans une citerne byzantine souterraine.",
      category: "monument",
      emoji: "🏛️",
      cost: 25,
      hours: 1,
      area: "Sultanahmet",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "grand-bazar",
      name: "Grand Bazar",
      description: "4 000 boutiques sous des voûtes peintes : négocie avec le sourire.",
      category: "shopping",
      emoji: "🛍️",
      cost: 0,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["shopping"],
      highlight: "Se perdre dans le Grand Bazar",
    },
    {
      id: "bazar-epices",
      name: "Bazar aux épices",
      description: "Loukoums, épices et thés, puis sandwich au poisson sur le quai.",
      category: "food",
      emoji: "🌶️",
      cost: 10,
      hours: 1,
      moments: ["morning", "afternoon"],
      tags: ["gastronomie", "shopping"],
    },
    {
      id: "balat",
      name: "Balat et Fener",
      description: "Maisons colorées en pente, églises et cafés vintage.",
      category: "quartier",
      emoji: "🏘️",
      cost: 0,
      hours: 2,
      moments: ["morning"],
      tags: ["ville", "culture"],
    },
    {
      id: "hammam",
      name: "Hammam traditionnel",
      description: "Vapeur, gommage et mousse dans un hammam historique.",
      category: "detente",
      emoji: "🧖",
      cost: 50,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["detente"],
    },
    {
      id: "bosphore",
      name: "Croisière sur le Bosphore",
      description: "Palais, forteresses et villas en bois entre l'Europe et l'Asie.",
      category: "panorama",
      emoji: "⛴️",
      cost: 10,
      hours: 2,
      moments: ["afternoon"],
      tags: ["detente", "romantique"],
      highlight: "Le Bosphore en bateau",
    },
    {
      id: "kadikoy",
      name: "Ferry vers Kadıköy, rive asiatique",
      description: "20 min de traversée avec les mouettes, puis marché et ruelles animées.",
      category: "quartier",
      emoji: "🌉",
      cost: 3,
      hours: 3,
      area: "Kadıköy",
      moments: ["afternoon"],
      tags: ["ville", "gastronomie"],
    },
    {
      id: "galata",
      name: "Coucher de soleil depuis la tour de Galata",
      description: "Vue à 360° sur la Corne d'Or et les minarets.",
      category: "panorama",
      emoji: "🌅",
      cost: 30,
      hours: 1,
      moments: ["evening"],
      tags: ["romantique", "ville"],
      repeatable: true,
    },
    {
      id: "rooftop-karakoy",
      name: "Rooftop à Karaköy",
      description: "Cocktail face à la vieille ville quand les mosquées s'illuminent.",
      category: "nightlife",
      emoji: "🍸",
      cost: 15,
      hours: 2,
      area: "Karaköy",
      moments: ["evening"],
      tags: ["romantique", "fete"],
    },
    {
      id: "beyoglu",
      name: "Soirée à Beyoğlu",
      description: "Meyhane (tavernes à meze), bars de Nevizade et clubs d'Istiklal.",
      category: "nightlife",
      emoji: "🎶",
      cost: 20,
      hours: 3,
      area: "Beyoğlu",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit à Beyoğlu",
      repeatable: true,
    },
    {
      id: "iles-princes",
      name: "Îles des Princes",
      description: "Îles sans voitures, maisons en bois et baignade, à 1 h 30 de ferry.",
      category: "excursion",
      emoji: "🏝️",
      cost: 10,
      hours: 8,
      moments: ["morning"],
      tags: ["detente", "nature"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-balik-ekmek",
      name: "Tarihi Eminönü Balık Ekmek",
      description: "Sandwichs au maquereau grillé sur les bateaux du quai d'Eminönü.",
      cuisine: "Street food turque",
      emoji: "🐟",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 4,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-durumzade",
      name: "Dürümzade",
      description: "Dürüm au bœuf grillé au charbon, ouvert jusque tard à Beyoğlu.",
      cuisine: "Kebab",
      emoji: "🌯",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      area: "Beyoğlu",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-gulluoglu",
      name: "Karaköy Güllüoğlu",
      description: "La maison du baklava depuis 1949, avec un thé.",
      cuisine: "Pâtisseries turques",
      emoji: "🍯",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      area: "Karaköy",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-ciya",
      name: "Çiya Sofrası",
      description: "Recettes oubliées d'Anatolie à Kadıköy, buffet de meze au poids.",
      cuisine: "Cuisine anatolienne",
      emoji: "🥘",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "Kadıköy",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-karakoy-lokantasi",
      name: "Karaköy Lokantası",
      description: "Lokanta turquoise : plats du jour le midi, meze et rakı le soir.",
      cuisine: "Cuisine turque",
      emoji: "🍽️",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Karaköy",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
    {
      id: "r-mikla",
      name: "Mikla",
      description: "Cuisine néo-anatolienne sur un toit avec vue sur toute la ville.",
      cuisine: "Cuisine turque d'auteur",
      emoji: "🌃",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 90,
      area: "Beyoğlu",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(41.0122, 28.976),
    zoom: 13,
    neighborhoods: {
      Sultanahmet: p(41.0055, 28.9769),
      Beyoğlu: p(41.0345, 28.9775),
      Karaköy: p(41.0235, 28.9765),
      Kadıköy: p(40.9905, 29.027),
    },
    places: {
      "sainte-sophie": p(41.0086, 28.9802),
      "mosquee-bleue": p(41.0054, 28.9768),
      topkapi: p(41.0115, 28.9834),
      citerne: p(41.0084, 28.9779),
      "grand-bazar": p(41.0107, 28.9681),
      "bazar-epices": p(41.0165, 28.9707),
      balat: p(41.029, 28.949),
      hammam: p(41.0085, 28.971),
      bosphore: p(41.017, 28.976),
      kadikoy: p(40.99, 29.025),
      galata: p(41.0256, 28.9742),
      "rooftop-karakoy": p(41.024, 28.977),
      beyoglu: p(41.034, 28.978),
      "iles-princes": p(40.874, 29.129),
      "r-balik-ekmek": p(41.017, 28.973),
      "r-durumzade": p(41.0355, 28.981),
      "r-gulluoglu": p(41.022, 28.977),
      "r-ciya": p(40.9905, 29.0275),
      "r-karakoy-lokantasi": p(41.023, 28.978),
      "r-mikla": p(41.031, 28.976),
    },
  },
  source: "demo",
};
