import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const kotor: DestinationProfile = {
  id: "kotor",
  name: "Kotor",
  country: "Monténégro",
  countryCode: "ME",
  iata: "TIV",
  tagline: "Un fjord du sud, des remparts et des eaux turquoise.",
  description:
    "La pépite de l'Adriatique : une vieille ville vénitienne au fond d'une baie encadrée de montagnes, des remparts à gravir au lever du jour, des criques et des villages de pêcheurs, à prix doux.",
  fallbackGradient: "from-teal-300 via-cyan-600 to-slate-800",
  type: "balneaire",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 25, standard: 55, confort: 120 },
    localTransportPerDay: 6,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h 30",
        durationHours: 2.5,
        roundTripPerPerson: 220,
        details: "Vol vers Tivat (à 15 min) ou Dubrovnik (2 h de route), surtout en saison",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "La vieille ville est piétonne" },
    { mode: "bus", description: "Bus le long de la baie, vers Perast et Budva" },
    { mode: "ferry", description: "Bateaux-taxis et excursions en bateau dans la baie" },
  ],
  idealDays: { min: 3, max: 7 },
  bestMonths: [5, 6, 7, 8, 9, 10],
  styles: { nature: 3, plage: 2, romantique: 3, aventure: 3, culture: 2, detente: 2, fete: 2 },
  ambiances: { romantique: 3, calme: 3, aventureuse: 3, economique: 2, authentique: 2 },
  strengths: { nature: 3, prix: 2, activites: 3, securite: 3, plages: 2 },
  neighborhoods: [
    {
      name: "Vieille ville",
      vibe: "dans les remparts, ruelles et chats",
      tiers: ["standard", "confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Dobrota",
      vibe: "au bord de l'eau, calme, pour se baigner",
      tiers: ["eco", "standard"],
      tags: ["detente", "plage"],
    },
    { name: "Perast", vibe: "village baroque face aux îlots", tiers: ["confort"], tags: ["romantique"] },
  ],
  activities: [
    {
      id: "vieille-ville-kotor",
      name: "Vieille ville de Kotor",
      description: "Places vénitiennes, églises romanes et chats partout.",
      category: "quartier",
      emoji: "🐈",
      cost: 0,
      hours: 2,
      area: "Vieille ville",
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
      highlight: "La vieille ville de Kotor",
    },
    {
      id: "forteresse-kotor",
      name: "Montée à la forteresse Saint-Jean",
      description: "1 350 marches pour la vue sur tout le fjord (tôt le matin ou au crépuscule).",
      category: "panorama",
      emoji: "🏰",
      cost: 15,
      hours: 2.5,
      moments: ["morning", "evening"],
      tags: ["aventure", "romantique"],
      highlight: "La baie de Kotor depuis la forteresse",
    },
    {
      id: "musee-chats",
      name: "Musée des chats",
      description: "Petit musée insolite dédié aux chats, mascottes de la ville.",
      category: "musee",
      emoji: "😺",
      cost: 1,
      hours: 1,
      area: "Vieille ville",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "kayak-kotor",
      name: "Kayak dans la baie",
      description: "Pagayer entre les montagnes, eau calme et transparente.",
      category: "aventure",
      emoji: "🛶",
      cost: 35,
      hours: 3,
      moments: ["morning"],
      tags: ["aventure", "nature"],
    },
    {
      id: "lovcen",
      name: "Parc national du Lovćen",
      description: "La route aux 25 lacets puis le mausolée au sommet, vue sur la mer.",
      category: "nature",
      emoji: "⛰️",
      cost: 20,
      hours: 5,
      moments: ["morning"],
      tags: ["nature", "aventure"],
    },
    {
      id: "perast",
      name: "Perast et Notre-Dame-du-Rocher",
      description: "Village baroque et barque vers l'îlot à l'église bleue.",
      category: "quartier",
      emoji: "⛪",
      cost: 5,
      hours: 3,
      area: "Perast",
      moments: ["afternoon"],
      tags: ["culture", "romantique"],
    },
    {
      id: "baignade-kotor",
      name: "Baignade dans la baie",
      description: "Pontons et petites plages de galets le long de Dobrota.",
      category: "plage",
      emoji: "🏊",
      cost: 0,
      hours: 3,
      area: "Dobrota",
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      repeatable: true,
    },
    {
      id: "sveti-stefan",
      name: "Point de vue sur Sveti Stefan",
      description: "L'îlot-hôtel le plus photographié de l'Adriatique.",
      category: "panorama",
      emoji: "🏝️",
      cost: 0,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["romantique"],
    },
    {
      id: "vin-vranac",
      name: "Dégustation de vin Vranac",
      description: "Le rouge corsé du Monténégro, avec fromages et jambon de Njeguši.",
      category: "food",
      emoji: "🍷",
      cost: 20,
      hours: 1.5,
      moments: ["evening"],
      tags: ["gastronomie"],
    },
    {
      id: "bars-kotor",
      name: "Bars de la vieille ville",
      description: "Terrasses sur les places éclairées, ambiance détendue.",
      category: "nightlife",
      emoji: "🍹",
      cost: 15,
      hours: 3,
      area: "Vieille ville",
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "budva",
      name: "Soirée à Budva",
      description: "La station festive de la côte : plages le jour, clubs la nuit.",
      category: "nightlife",
      emoji: "🎉",
      cost: 20,
      hours: 4,
      moments: ["evening"],
      tags: ["fete", "plage"],
      highlight: "Nuit à Budva",
    },
    {
      id: "grotte-bleue-me",
      name: "Bateau vers la grotte bleue",
      description: "Tour de la baie en bateau, baignade dans une grotte lumineuse.",
      category: "excursion",
      emoji: "🚤",
      cost: 40,
      hours: 5,
      moments: ["morning"],
      tags: ["plage", "nature"],
    },
    {
      id: "dubrovnik",
      name: "Excursion à Dubrovnik",
      description: "La perle de la Croatie et ses remparts, de l'autre côté de la frontière.",
      category: "excursion",
      emoji: "🏯",
      cost: 50,
      hours: 11,
      moments: ["morning"],
      tags: ["culture", "romantique"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "ovo-burek-kotor",
      name: "Pekara OVO",
      description: "Burek (feuilleté au fromage ou à la viande) et yaourt pour le petit-déjeuner.",
      cuisine: "Boulangerie des Balkans",
      emoji: "🥐",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 4,
      area: "Vieille ville",
      meals: ["lunch"],
      tags: [],
    },
    {
      id: "ovo-konoba-kotor",
      name: "Konoba OVO",
      description: "Taverne familiale : poisson grillé, risotto noir et vin maison.",
      cuisine: "Cuisine monténégrine",
      emoji: "🐟",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 22,
      area: "Vieille ville",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
    },
    {
      id: "ovo-grill-kotor",
      name: "OVO Grill",
      description: "Ćevapi, pljeskavica et salade shopska à petit prix.",
      cuisine: "Grillades des Balkans",
      emoji: "🍖",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 10,
      area: "Dobrota",
      meals: ["lunch", "dinner"],
      tags: [],
    },
    {
      id: "ovo-table-kotor",
      name: "Table OVO Perast",
      description: "Dîner les pieds dans l'eau face aux îlots, poissons et fruits de mer.",
      cuisine: "Poissons de l'Adriatique",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 50,
      area: "Perast",
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
    },
  ],
  geo: {
    center: p(42.4247, 18.7712),
    zoom: 13,
    neighborhoods: {
      "Vieille ville": p(42.4247, 18.7712),
      Dobrota: p(42.44, 18.765),
      Perast: p(42.4865, 18.699),
    },
    places: {
      "vieille-ville-kotor": p(42.4247, 18.7712),
      "forteresse-kotor": p(42.4219, 18.7747),
      "musee-chats": p(42.425, 18.771),
      "kayak-kotor": p(42.43, 18.76),
      lovcen: p(42.399, 18.837),
      perast: p(42.4865, 18.699),
      "baignade-kotor": p(42.44, 18.765),
      "sveti-stefan": p(42.256, 18.891),
      "vin-vranac": p(42.4245, 18.7715),
      "bars-kotor": p(42.4245, 18.7705),
      budva: p(42.278, 18.837),
      "grotte-bleue-me": p(42.396, 18.558),
      dubrovnik: p(42.6507, 18.0944),
    },
  },
  source: "demo",
};
