import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const le_caire: DestinationProfile = {
  id: "le-caire",
  name: "Le Caire",
  country: "Égypte",
  countryCode: "EG",
  iata: "CAI",
  tagline: "Les pyramides au bout de la rue et felouques sur le Nil.",
  description:
    "Une mégapole bouillonnante au pied des dernières merveilles du monde antique : pyramides de Gizeh, trésors de Toutânkhamon, bazars médiévaux et couchers de soleil en felouque.",
  fallbackGradient: "from-yellow-200 via-amber-500 to-orange-800",
  type: "ville",
  costLevel: 1,
  costs: {
    accommodationPerNight: { eco: 15, standard: 40, confort: 100 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "4 h 45",
        durationHours: 4.75,
        roundTripPerPerson: 350,
        details: "Vol direct, VTC jusqu'au centre en 45 min. Visa à l'arrivée ou en ligne",
      },
    ],
  },
  localMobility: [
    { mode: "taxi", description: "VTC (Uber, Careem) : le plus simple et bon marché" },
    { mode: "metro", description: "Métro pour le centre (voitures réservées aux femmes)" },
    { mode: "ferry", description: "Felouques et bateaux-taxis sur le Nil" },
  ],
  idealDays: { min: 4, max: 7 },
  bestMonths: [10, 11, 12, 1, 2, 3, 4],
  styles: { culture: 3, aventure: 2, gastronomie: 2, ville: 2, shopping: 2, romantique: 1 },
  ambiances: { authentique: 3, aventureuse: 3, economique: 3, sociale: 2 },
  strengths: { culture: 3, prix: 3, activites: 3, gastronomie: 2 },
  neighborhoods: [
    {
      name: "Downtown",
      vibe: "le centre-ville Belle Époque, animé",
      tiers: ["eco", "standard"],
      tags: ["ville", "culture"],
    },
    {
      name: "Zamalek",
      vibe: "île verte et chic sur le Nil",
      tiers: ["standard", "confort"],
      tags: ["fete", "romantique"],
    },
    {
      name: "Gizeh",
      vibe: "vue sur les pyramides depuis l'hôtel",
      tiers: ["standard", "confort"],
      tags: ["culture"],
    },
    {
      name: "Le Caire islamique",
      vibe: "minarets, souks et ruelles médiévales",
      tiers: ["eco"],
      tags: ["culture", "shopping"],
    },
  ],
  activities: [
    {
      id: "pyramides",
      name: "Pyramides de Gizeh et Sphinx",
      description: "Les seules merveilles antiques encore debout. Arrive à l'ouverture.",
      category: "monument",
      emoji: "🔺",
      cost: 30,
      hours: 4,
      area: "Gizeh",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Les pyramides de Gizeh",
    },
    {
      id: "gem",
      name: "Grand Musée égyptien",
      description: "Le nouveau musée géant face aux pyramides, trésors de Toutânkhamon.",
      category: "musee",
      emoji: "🏺",
      cost: 30,
      hours: 3,
      area: "Gizeh",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
      highlight: "Les trésors de Toutânkhamon",
    },
    {
      id: "musee-tahrir",
      name: "Musée égyptien de la place Tahrir",
      description: "Le musée historique rose, rempli de statues et de momies.",
      category: "musee",
      emoji: "🗿",
      cost: 25,
      hours: 2.5,
      area: "Downtown",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "citadelle",
      name: "Citadelle de Saladin",
      description: "Forteresse médiévale et mosquée d'albâtre dominant la ville.",
      category: "monument",
      emoji: "🕌",
      cost: 15,
      hours: 2,
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "caire-copte",
      name: "Le Caire copte",
      description: "Église suspendue et vieilles synagogues au cœur des remparts romains.",
      category: "quartier",
      emoji: "⛪",
      cost: 0,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "khan-khalili",
      name: "Khan el-Khalili et rue Al-Muizz",
      description: "Le grand bazar et la plus belle rue médiévale du monde islamique.",
      category: "shopping",
      emoji: "🪔",
      cost: 0,
      hours: 2.5,
      area: "Le Caire islamique",
      moments: ["afternoon"],
      tags: ["shopping", "culture"],
      highlight: "Le bazar de Khan el-Khalili",
    },
    {
      id: "al-azhar-park",
      name: "Parc Al-Azhar au coucher du soleil",
      description: "Jardins suspendus avec vue sur les minarets de la vieille ville.",
      category: "detente",
      emoji: "🌇",
      cost: 2,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "detente"],
    },
    {
      id: "felouque",
      name: "Felouque sur le Nil",
      description: "Voile traditionnelle au coucher du soleil, loin du bruit de la ville.",
      category: "panorama",
      emoji: "⛵",
      cost: 15,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "detente"],
      highlight: "Coucher de soleil en felouque",
      repeatable: true,
    },
    {
      id: "tanoura",
      name: "Spectacle de danse soufie",
      description: "Les derviches tourneurs et leurs jupes colorées, dans un palais mamelouk.",
      category: "evenement",
      emoji: "🌀",
      cost: 5,
      hours: 1.5,
      area: "Le Caire islamique",
      moments: ["evening"],
      tags: ["culture"],
    },
    {
      id: "cairo-tower",
      name: "Tour du Caire",
      description: "Vue à 360° : le Nil, la ville et, par temps clair, les pyramides.",
      category: "panorama",
      emoji: "🗼",
      cost: 10,
      hours: 1,
      area: "Zamalek",
      moments: ["evening"],
      tags: ["ville"],
    },
    {
      id: "zamalek-soiree",
      name: "Soirée à Zamalek",
      description: "Bars, rooftops et cafés au bord du Nil.",
      category: "nightlife",
      emoji: "🍹",
      cost: 20,
      hours: 3,
      area: "Zamalek",
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "saqqarah",
      name: "Saqqarah et Memphis",
      description: "La pyramide à degrés, la plus ancienne d'Égypte, et des tombes peintes.",
      category: "excursion",
      emoji: "🏜️",
      cost: 25,
      hours: 7,
      moments: ["morning"],
      tags: ["culture", "aventure"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-abou-tarek",
      name: "Abou Tarek",
      description: "Le temple du koshari (riz, lentilles, pâtes, sauce tomate épicée) sur quatre étages.",
      cuisine: "Koshari",
      emoji: "🍲",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 3,
      area: "Downtown",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-zooba",
      name: "Zooba",
      description: "Street food égyptienne revisitée, falafels et ta'ameya colorés.",
      cuisine: "Street food égyptienne",
      emoji: "🧆",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      area: "Zamalek",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-felfela",
      name: "Felfela",
      description: "Institution de 1959 : foul, falafels et mezze dans un décor de jardin.",
      cuisine: "Cuisine égyptienne",
      emoji: "🫘",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      area: "Downtown",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-naguib-mahfouz",
      name: "Café Naguib Mahfouz",
      description: "Café-restaurant ottoman au cœur du bazar, thé à la menthe et tajines.",
      cuisine: "Cuisine égyptienne",
      emoji: "🫖",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 15,
      area: "Le Caire islamique",
      meals: ["lunch", "dinner"],
      tags: ["romantique"],
      real: true,
    },
    {
      id: "r-abou-el-sid",
      name: "Abou El Sid",
      description: "Cuisine égyptienne traditionnelle dans une salle aux lanternes, à Zamalek.",
      cuisine: "Cuisine égyptienne",
      emoji: "🏮",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      area: "Zamalek",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(30.0444, 31.2357),
    zoom: 11,
    neighborhoods: {
      Downtown: p(30.048, 31.239),
      Zamalek: p(30.061, 31.221),
      Gizeh: p(29.99, 31.14),
      "Le Caire islamique": p(30.047, 31.262),
    },
    places: {
      pyramides: p(29.9792, 31.1342),
      gem: p(29.994, 31.119),
      "musee-tahrir": p(30.0478, 31.2336),
      citadelle: p(30.0287, 31.2599),
      "caire-copte": p(30.0053, 31.2302),
      "khan-khalili": p(30.0477, 31.2622),
      "al-azhar-park": p(30.04, 31.264),
      felouque: p(30.044, 31.225),
      tanoura: p(30.0455, 31.262),
      "cairo-tower": p(30.0459, 31.2243),
      "zamalek-soiree": p(30.06, 31.22),
      saqqarah: p(29.8713, 31.2165),
      "r-abou-tarek": p(30.05, 31.241),
      "r-zooba": p(30.061, 31.219),
      "r-felfela": p(30.048, 31.238),
      "r-naguib-mahfouz": p(30.0475, 31.262),
      "r-abou-el-sid": p(30.062, 31.222),
    },
  },
  source: "demo",
};
