import { destinationImages } from "@/config/images";
import type { DestinationProfile } from "../../types";

export const lisbonne: DestinationProfile = {
  id: "lisbonne",
  name: "Lisbonne",
  country: "Portugal",
  countryCode: "PT",
  tagline: "Tramways jaunes, miradouros et couchers de soleil sur le Tage.",
  description:
    "Une capitale solaire à taille humaine, entre ruelles pavées, vues panoramiques, fado et plages à 30 minutes.",
  image: { src: destinationImages.lisbonne, alt: "Tramway jaune dans une rue de Lisbonne" },
  fallbackGradient: "from-amber-400 via-orange-500 to-rose-600",
  type: "mixte",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 25, standard: 55, confort: 110 },
    foodPerDay: { eco: 25, standard: 40, confort: 70 },
    localTransportPerDay: 6,
  },
  access: {
    mode: "avion",
    from: "Paris",
    durationLabel: "2 h 35",
    durationHours: 2.6,
    roundTripPerPerson: 150,
  },
  localTransport: "Métro, tramways et beaucoup de marche (ça grimpe !)",
  idealDays: { min: 3, max: 6 },
  bestMonths: [4, 5, 6, 7, 8, 9, 10],
  styles: {
    ville: 3,
    culture: 2,
    gastronomie: 3,
    plage: 2,
    fete: 2,
    romantique: 3,
    detente: 2,
    festivals: 1,
    aventure: 1,
  },
  ambiances: { authentique: 3, romantique: 3, festive: 2, sociale: 2, economique: 2, calme: 1 },
  strengths: { prix: 2, securite: 3, culture: 2, gastronomie: 3, plages: 2, "vie-nocturne": 2, rapidite: 2 },
  neighborhoods: [
    {
      name: "Baixa-Chiado",
      vibe: "central, pratique et vivant",
      tiers: ["standard", "confort"],
      tags: ["ville", "shopping", "culture"],
    },
    {
      name: "Alfama",
      vibe: "ruelles historiques et vues sur le Tage",
      tiers: ["eco", "standard"],
      tags: ["romantique", "culture"],
    },
    {
      name: "Cais do Sodré",
      vibe: "animé le soir, proche des bars",
      tiers: ["eco", "standard"],
      tags: ["fete"],
    },
    { name: "Príncipe Real", vibe: "élégant et calme", tiers: ["confort"], tags: ["detente", "romantique"] },
  ],
  activities: [
    {
      id: "belem",
      name: "Tour de Belém & monastère des Hiéronymites",
      description: "Le Lisbonne des grandes découvertes, en bord de Tage.",
      category: "monument",
      emoji: "🏰",
      cost: 18,
      hours: 3,
      area: "Belém",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
      highlight: "Le monastère des Hiéronymites",
    },
    {
      id: "pasteis",
      name: "Pastéis de nata à Belém",
      description: "La pâtisserie iconique, encore tiède.",
      category: "food",
      emoji: "🥐",
      cost: 5,
      hours: 1,
      area: "Belém",
      moments: ["morning", "afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "alfama",
      name: "Balade dans l'Alfama",
      description: "Escaliers, azulejos et linge aux fenêtres dans le plus vieux quartier.",
      category: "quartier",
      emoji: "🏘️",
      cost: 0,
      hours: 2.5,
      area: "Alfama",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville", "romantique"],
    },
    {
      id: "tram28",
      name: "Tram 28 à travers les collines",
      description: "Le trajet mythique entre Graça et Estrela.",
      category: "quartier",
      emoji: "🚋",
      cost: 3,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["ville"],
    },
    {
      id: "miradouro",
      name: "Coucher de soleil au miradouro da Senhora do Monte",
      description: "La plus belle vue sur la ville quand le ciel devient orange.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      area: "Graça",
      moments: ["evening"],
      tags: ["romantique", "ville", "detente"],
      highlight: "Coucher de soleil sur les toits",
      repeatable: true,
    },
    {
      id: "gulbenkian",
      name: "Musée Calouste Gulbenkian",
      description: "Une collection d'art magnifique et un jardin paisible.",
      category: "musee",
      emoji: "🖼️",
      cost: 15,
      hours: 2.5,
      moments: ["morning", "afternoon"],
      tags: ["culture", "detente"],
    },
    {
      id: "lx-factory",
      name: "LX Factory : créateurs et street art",
      description: "Ancienne usine devenue repaire de boutiques et cafés.",
      category: "shopping",
      emoji: "🛍️",
      cost: 10,
      hours: 2.5,
      area: "Alcântara",
      moments: ["afternoon"],
      tags: ["shopping", "ville"],
    },
    {
      id: "time-out",
      name: "Dégustation au Time Out Market",
      description: "Le meilleur de la cuisine lisboète sous un même toit.",
      category: "food",
      emoji: "🍤",
      cost: 20,
      hours: 1.5,
      area: "Cais do Sodré",
      moments: ["afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "caparica",
      name: "Plage de Costa da Caparica",
      description: "Des kilomètres de sable à 30 minutes du centre.",
      category: "plage",
      emoji: "🏖️",
      cost: 5,
      hours: 4,
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      highlight: "Après-midi à Costa da Caparica",
      repeatable: true,
    },
    {
      id: "surf",
      name: "Initiation au surf",
      description: "Cours collectif pour débutants sur la côte.",
      category: "aventure",
      emoji: "🏄",
      cost: 45,
      hours: 3,
      moments: ["morning"],
      tags: ["aventure", "plage"],
    },
    {
      id: "fado",
      name: "Concert de fado dans une taverne",
      description: "La musique de l'âme portugaise, à la bougie.",
      category: "evenement",
      emoji: "🎶",
      cost: 30,
      hours: 2,
      area: "Alfama",
      moments: ["evening"],
      tags: ["culture", "romantique", "festivals"],
      highlight: "Une soirée fado",
    },
    {
      id: "bairro-alto",
      name: "Soirée dans les ruelles du Bairro Alto",
      description: "Des bars minuscules et toute la ville dans la rue.",
      category: "nightlife",
      emoji: "🍹",
      cost: 20,
      hours: 3,
      area: "Bairro Alto",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit au Bairro Alto",
      repeatable: true,
    },
    {
      id: "pink-street",
      name: "Bars de Cais do Sodré & Pink Street",
      description: "Clubs et bars jusqu'au bout de la nuit.",
      category: "nightlife",
      emoji: "🎉",
      cost: 25,
      hours: 3,
      area: "Cais do Sodré",
      moments: ["evening"],
      tags: ["fete"],
    },
    {
      id: "sintra",
      name: "Excursion à Sintra et ses palais",
      description: "Palais colorés et forêts enchantées à 40 min de train.",
      category: "excursion",
      emoji: "🏰",
      cost: 35,
      hours: 7,
      moments: ["morning"],
      tags: ["culture", "nature", "romantique"],
      highlight: "Les palais de Sintra",
      fullDay: true,
    },
    {
      id: "cascais",
      name: "Journée à Cascais en bord de mer",
      description: "Station balnéaire chic, criques et balade côtière.",
      category: "excursion",
      emoji: "🌊",
      cost: 10,
      hours: 6,
      moments: ["morning"],
      tags: ["plage", "detente"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "tasca",
      name: "Tasca de quartier",
      description: "Sardines grillées et vinho verde, ambiance familiale.",
      priceLevel: 1,
      cost: 15,
      area: "Alfama",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
    },
    {
      id: "bifana",
      name: "Comptoir à bifanas",
      description: "Le sandwich au porc mariné, institution locale.",
      priceLevel: 1,
      cost: 8,
      meals: ["lunch"],
      tags: [],
    },
    {
      id: "pastelaria",
      name: "Café-pastelaria du coin",
      description: "Salades, tostas et pastéis pour une pause rapide.",
      priceLevel: 1,
      cost: 9,
      meals: ["lunch"],
      tags: [],
    },
    {
      id: "marisqueira",
      name: "Marisqueira populaire",
      description: "Fruits de mer à partager, bruyant et délicieux.",
      priceLevel: 2,
      cost: 35,
      meals: ["dinner"],
      tags: ["gastronomie", "fete"],
    },
    {
      id: "rooftop",
      name: "Rooftop avec vue sur le Tage",
      description: "Cocktails et petites assiettes au soleil couchant.",
      priceLevel: 2,
      cost: 30,
      meals: ["dinner"],
      tags: ["romantique", "fete"],
    },
    {
      id: "chef",
      name: "Table d'un jeune chef portugais",
      description: "Menu dégustation autour des produits de l'Atlantique.",
      priceLevel: 3,
      cost: 70,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
    },
  ],
  source: "demo",
};
