import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const ljubljana: DestinationProfile = {
  id: "ljubljana",
  name: "Ljubljana",
  country: "Slovénie",
  countryCode: "SI",
  iata: "LJU",
  tagline: "Une petite capitale verte, et le lac de Bled à 45 minutes.",
  description:
    "Une capitale de poche, piétonne et détendue : terrasses le long de la rivière, château sur la colline, quartier alternatif de Metelkova, puis lacs alpins et grottes géantes en excursion.",
  fallbackGradient: "from-emerald-300 via-teal-500 to-sky-700",
  type: "mixte",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 28, standard: 60, confort: 120 },
    localTransportPerDay: 4,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h",
        durationHours: 2,
        roundTripPerPerson: 200,
        details: "Vol direct selon la saison (ou via Venise / Zagreb), navette jusqu'au centre en 30 min",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Le centre est entièrement piéton" },
    { mode: "velo", description: "Vélos BicikeLJ en libre-service, presque gratuits" },
    { mode: "bus", description: "Bus pour Bled, Bohinj et Postojna" },
  ],
  idealDays: { min: 3, max: 6 },
  bestMonths: [5, 6, 7, 8, 9],
  styles: { nature: 3, romantique: 3, culture: 2, detente: 3, aventure: 2, gastronomie: 2, fete: 2 },
  ambiances: { calme: 3, romantique: 3, authentique: 2, aventureuse: 2 },
  strengths: { nature: 3, securite: 3, rapidite: 2, activites: 2, prix: 2 },
  neighborhoods: [
    {
      name: "Vieille ville",
      vibe: "ruelles baroques au pied du château",
      tiers: ["standard", "confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Metelkova",
      vibe: "quartier alternatif, street art et concerts",
      tiers: ["eco"],
      tags: ["fete"],
    },
    {
      name: "Trnovo",
      vibe: "calme et résidentiel, au bord de l'eau",
      tiers: ["eco", "standard"],
      tags: ["detente"],
    },
  ],
  activities: [
    {
      id: "vieille-ville-lj",
      name: "Vieille ville et triple pont",
      description: "Le pont des Trois, le pont des Dragons et le marché de Plečnik.",
      category: "quartier",
      emoji: "🐉",
      cost: 0,
      hours: 2,
      area: "Vieille ville",
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
      highlight: "Le triple pont de Ljubljana",
    },
    {
      id: "chateau-lj",
      name: "Château de Ljubljana",
      description: "Funiculaire jusqu'au château, vue sur les Alpes par temps clair.",
      category: "monument",
      emoji: "🏰",
      cost: 15,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "marche-lj",
      name: "Marché central et Open Kitchen",
      description: "Produits locaux le matin, et le vendredi l'Open Kitchen des chefs.",
      category: "food",
      emoji: "🧀",
      cost: 12,
      hours: 1.5,
      area: "Vieille ville",
      moments: ["morning"],
      tags: ["gastronomie"],
    },
    {
      id: "galerie-nationale",
      name: "Galerie nationale",
      description: "Peinture slovène et européenne dans un palais du XIXᵉ.",
      category: "musee",
      emoji: "🖼️",
      cost: 8,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "tivoli-lj",
      name: "Parc Tivoli",
      description: "Grand parc arboré et galerie photo en plein air.",
      category: "detente",
      emoji: "🌳",
      cost: 0,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["detente", "nature"],
    },
    {
      id: "velo-lj",
      name: "Vélo sur le Chemin du souvenir",
      description: "33 km de sentier vert qui fait le tour de la ville.",
      category: "nature",
      emoji: "🚲",
      cost: 5,
      hours: 3,
      moments: ["morning"],
      tags: ["nature", "aventure"],
    },
    {
      id: "bateau-lj",
      name: "Balade en bateau sur la Ljubljanica",
      description: "La vieille ville depuis l'eau, au crépuscule.",
      category: "panorama",
      emoji: "🛶",
      cost: 12,
      hours: 1,
      moments: ["evening"],
      tags: ["romantique"],
    },
    {
      id: "quais-lj",
      name: "Terrasses des quais",
      description: "Verres de vin slovène le long de la rivière, ambiance douce.",
      category: "nightlife",
      emoji: "🍷",
      cost: 15,
      hours: 2.5,
      area: "Vieille ville",
      moments: ["evening"],
      tags: ["fete", "romantique"],
      repeatable: true,
    },
    {
      id: "metelkova",
      name: "Soirée à Metelkova",
      description: "Anciennes casernes couvertes de graffitis, bars et concerts underground.",
      category: "nightlife",
      emoji: "🎸",
      cost: 10,
      hours: 3,
      area: "Metelkova",
      moments: ["evening"],
      tags: ["fete", "festivals"],
      highlight: "Nuit à Metelkova",
      repeatable: true,
    },
    {
      id: "bled",
      name: "Excursion au lac de Bled",
      description: "Barque jusqu'à l'île et son église, château sur la falaise et gâteau à la crème.",
      category: "excursion",
      emoji: "🏝️",
      cost: 20,
      hours: 8,
      moments: ["morning"],
      tags: ["nature", "romantique"],
      highlight: "Le lac de Bled",
      fullDay: true,
    },
    {
      id: "bohinj",
      name: "Lac de Bohinj et cascade Savica",
      description: "Le lac alpin sauvage du parc du Triglav, baignade l'été.",
      category: "excursion",
      emoji: "🏞️",
      cost: 25,
      hours: 9,
      moments: ["morning"],
      tags: ["nature", "aventure"],
      fullDay: true,
    },
    {
      id: "postojna",
      name: "Grotte de Postojna et château de Predjama",
      description: "Petit train dans une grotte géante, puis château encastré dans la falaise.",
      category: "excursion",
      emoji: "🦇",
      cost: 45,
      hours: 7,
      moments: ["morning"],
      tags: ["nature", "culture"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-hot-horse",
      name: "Hot Horse",
      description: "Le burger de cheval, spécialité insolite de Ljubljana, dans le parc Tivoli.",
      cuisine: "Burgers",
      emoji: "🍔",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 7,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-druga-violina",
      name: "Druga Violina",
      description: "Café-restaurant solidaire de la vieille ville, plats slovènes simples.",
      cuisine: "Cuisine slovène",
      emoji: "🎻",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Vieille ville",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-gostilna-sokol",
      name: "Gostilna Sokol",
      description: "Auberge traditionnelle : saucisses de Carniole, goulasch et bière.",
      cuisine: "Cuisine slovène",
      emoji: "🍺",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Vieille ville",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-jb",
      name: "JB Restavracija",
      description: "La table du chef Janez Bratovž, cuisine slovène raffinée.",
      cuisine: "Cuisine slovène d'auteur",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 80,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(46.0511, 14.5061),
    zoom: 14,
    neighborhoods: {
      "Vieille ville": p(46.0495, 14.506),
      Metelkova: p(46.0567, 14.516),
      Trnovo: p(46.043, 14.5),
    },
    places: {
      "vieille-ville-lj": p(46.0511, 14.5061),
      "chateau-lj": p(46.049, 14.5086),
      "marche-lj": p(46.0515, 14.51),
      "galerie-nationale": p(46.054, 14.501),
      "tivoli-lj": p(46.054, 14.498),
      "velo-lj": p(46.06, 14.52),
      "bateau-lj": p(46.049, 14.505),
      "quais-lj": p(46.0485, 14.504),
      metelkova: p(46.0567, 14.516),
      bled: p(46.3625, 14.0938),
      bohinj: p(46.283, 13.885),
      postojna: p(45.7825, 14.204),
      "r-hot-horse": p(46.058, 14.495),
      "r-druga-violina": p(46.047, 14.507),
      "r-gostilna-sokol": p(46.0495, 14.5075),
      "r-jb": p(46.054, 14.506),
    },
  },
  source: "demo",
};
