import { destinationImages } from "@/config/images";
import type { DestinationProfile } from "../../types";

export const londres: DestinationProfile = {
  id: "londres",
  name: "Londres",
  country: "Royaume-Uni",
  countryCode: "GB",
  tagline: "Musées gratuits, marchés street food et nuits sans fin.",
  description:
    "Une métropole qui ne s'arrête jamais : grands musées gratuits, quartiers aux mille ambiances et scène musicale mythique.",
  image: { src: destinationImages.londres, alt: "Tower Bridge à Londres" },
  fallbackGradient: "from-slate-400 via-indigo-600 to-night-950",
  type: "ville",
  costLevel: 4,
  costs: {
    accommodationPerNight: { eco: 50, standard: 95, confort: 180 },
    foodPerDay: { eco: 35, standard: 55, confort: 95 },
    localTransportPerDay: 12,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "train",
        durationLabel: "2 h 20",
        durationHours: 2.3,
        roundTripPerPerson: 160,
        details: "Sous la Manche, de centre-ville à centre-ville",
      },
      {
        mode: "avion",
        durationLabel: "1 h 15",
        durationHours: 1.25,
        roundTripPerPerson: 140,
        details: "Vol court, mais aéroports éloignés du centre",
      },
      {
        mode: "bus",
        durationLabel: "8 h",
        durationHours: 8,
        roundTripPerPerson: 60,
        details: "Autocar de nuit ou de jour, le plus économique",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Le Tube dessert toute la ville" },
    { mode: "bus", description: "Les bus à impériale, parfaits pour visiter" },
    { mode: "marche", description: "Les quartiers centraux se relient à pied" },
  ],
  idealDays: { min: 3, max: 6 },
  bestMonths: [4, 5, 6, 7, 8, 9, 12],
  styles: { ville: 3, culture: 3, shopping: 3, fete: 3, festivals: 3, gastronomie: 2, romantique: 1 },
  ambiances: { festive: 3, sociale: 3, luxueuse: 2, authentique: 1 },
  strengths: { culture: 3, "vie-nocturne": 3, activites: 3, rapidite: 3, securite: 2, confort: 2 },
  neighborhoods: [
    {
      name: "Shoreditch",
      vibe: "street art, bars et créateurs",
      tiers: ["eco", "standard"],
      tags: ["fete", "shopping"],
    },
    {
      name: "Covent Garden",
      vibe: "central, théâtres et boutiques",
      tiers: ["standard", "confort"],
      tags: ["ville", "culture"],
    },
    { name: "Camden", vibe: "alternatif et musical", tiers: ["eco"], tags: ["fete", "festivals"] },
  ],
  activities: [
    {
      id: "british-museum",
      name: "British Museum",
      description: "La pierre de Rosette et 2 millions d'années d'histoire (gratuit).",
      category: "musee",
      emoji: "🏺",
      cost: 0,
      hours: 3,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
      highlight: "Le British Museum",
    },
    {
      id: "westminster",
      name: "Westminster, Big Ben & Buckingham",
      description: "La carte postale royale, de la Tamise au palais.",
      category: "monument",
      emoji: "👑",
      cost: 0,
      hours: 2.5,
      moments: ["morning"],
      tags: ["culture", "ville"],
    },
    {
      id: "tower",
      name: "Tour de Londres & Tower Bridge",
      description: "Joyaux de la Couronne et vue sur la Tamise.",
      category: "monument",
      emoji: "🏰",
      cost: 35,
      hours: 3,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "tate",
      name: "Tate Modern & balade South Bank",
      description: "Art contemporain dans une ancienne centrale électrique.",
      category: "musee",
      emoji: "🎨",
      cost: 0,
      hours: 2.5,
      moments: ["afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "borough",
      name: "Borough Market",
      description: "Le temple du street food londonien.",
      category: "food",
      emoji: "🥧",
      cost: 18,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["gastronomie"],
      highlight: "Street food à Borough Market",
    },
    {
      id: "camden",
      name: "Camden Market",
      description: "Friperies, vinyles et cuisine du monde.",
      category: "shopping",
      emoji: "🎸",
      cost: 15,
      hours: 2.5,
      area: "Camden",
      moments: ["afternoon"],
      tags: ["shopping", "fete"],
    },
    {
      id: "shoreditch",
      name: "Street art à Shoreditch & Brick Lane",
      description: "Fresques, vintage et bagels à toute heure.",
      category: "quartier",
      emoji: "🖌️",
      cost: 0,
      hours: 2.5,
      area: "Shoreditch",
      moments: ["afternoon"],
      tags: ["ville", "shopping"],
    },
    {
      id: "oxford",
      name: "Shopping à Oxford Street & Carnaby",
      description: "Les grandes enseignes et les pépites de Soho.",
      category: "shopping",
      emoji: "🛍️",
      cost: 10,
      hours: 3,
      moments: ["afternoon"],
      tags: ["shopping"],
    },
    {
      id: "primrose",
      name: "Coucher de soleil à Primrose Hill",
      description: "La skyline de Londres depuis la colline.",
      category: "panorama",
      emoji: "🌇",
      cost: 0,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "detente"],
    },
    {
      id: "hyde",
      name: "Pause à Hyde Park",
      description: "Barque sur le lac et écureuils peu farouches.",
      category: "detente",
      emoji: "🌳",
      cost: 0,
      hours: 2,
      moments: ["afternoon"],
      tags: ["detente", "nature"],
      repeatable: true,
    },
    {
      id: "musical",
      name: "Comédie musicale dans le West End",
      description: "Les meilleurs spectacles du monde, en VO.",
      category: "evenement",
      emoji: "🎭",
      cost: 60,
      hours: 2.5,
      moments: ["evening"],
      tags: ["culture", "festivals", "romantique"],
      highlight: "Une comédie musicale dans le West End",
    },
    {
      id: "pub",
      name: "Tournée des pubs",
      description: "Pintes et ambiance chaleureuse dans des pubs historiques.",
      category: "nightlife",
      emoji: "🍺",
      cost: 25,
      hours: 3,
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "live",
      name: "Concert live à Camden",
      description: "La scène qui a vu naître des légendes.",
      category: "nightlife",
      emoji: "🎤",
      cost: 25,
      hours: 3,
      area: "Camden",
      moments: ["evening"],
      tags: ["fete", "festivals"],
      highlight: "Concert live à Camden",
    },
    {
      id: "brighton",
      name: "Excursion à Brighton",
      description: "Jetée, plage de galets et ambiance décontractée.",
      category: "excursion",
      emoji: "🎡",
      cost: 25,
      hours: 7,
      moments: ["morning"],
      tags: ["plage", "fete", "detente"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "bagel",
      name: "Bagel shop de Brick Lane",
      description: "Bagels au bœuf salé, ouvert jour et nuit.",
      priceLevel: 1,
      cost: 8,
      meals: ["lunch"],
      tags: [],
    },
    {
      id: "curry",
      name: "Curry house",
      description: "Le vrai plat national britannique.",
      priceLevel: 1,
      cost: 18,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
    },
    {
      id: "pub-food",
      name: "Pub food traditionnelle",
      description: "Fish & chips ou pie, avec une pinte.",
      priceLevel: 2,
      cost: 25,
      meals: ["lunch", "dinner"],
      tags: ["fete"],
    },
    {
      id: "rooftop-ldn",
      name: "Rooftop restaurant avec vue",
      description: "Cocktails et assiettes à partager au-dessus de la ville.",
      priceLevel: 2,
      cost: 45,
      meals: ["dinner"],
      tags: ["romantique", "fete"],
    },
    {
      id: "gastro-ldn",
      name: "Restaurant de chef à Soho",
      description: "Cuisine britannique moderne et inventive.",
      priceLevel: 3,
      cost: 90,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
    },
  ],
  source: "demo",
};
