import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const madrid: DestinationProfile = {
  id: "madrid",
  name: "Madrid",
  country: "Espagne",
  countryCode: "ES",
  iata: "MAD",
  tagline: "Musées géants, terrasses bondées et nuits sans fin.",
  description:
    "Une capitale qui vit dehors : les chefs-d'œuvre du Prado le matin, le Retiro l'après-midi, les tapas de La Latina et les bars de Malasaña jusqu'à l'aube.",
  fallbackGradient: "from-rose-400 via-red-600 to-amber-700",
  type: "ville",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 30, standard: 65, confort: 130 },
    localTransportPerDay: 6,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h",
        durationHours: 2,
        roundTripPerPerson: 140,
        details: "Vol direct, métro jusqu'au centre en 30 à 40 min",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Un des métros les plus pratiques d'Europe" },
    { mode: "marche", description: "Le centre (Sol, Latina, Malasaña) se parcourt à pied" },
    { mode: "velo", description: "Vélos électriques en libre-service (BiciMAD)" },
    { mode: "taxi", description: "Taxis et VTC nombreux la nuit" },
  ],
  idealDays: { min: 3, max: 5 },
  bestMonths: [4, 5, 6, 9, 10],
  styles: { ville: 3, culture: 3, fete: 3, gastronomie: 3, shopping: 2, romantique: 2, festivals: 2 },
  ambiances: { festive: 3, sociale: 3, authentique: 2, luxueuse: 2, romantique: 2 },
  strengths: { culture: 3, "vie-nocturne": 3, gastronomie: 3, securite: 3, rapidite: 3, prix: 2 },
  neighborhoods: [
    {
      name: "Sol et Centro",
      vibe: "au cœur de tout, pratique pour visiter",
      tiers: ["eco", "standard", "confort"],
      tags: ["ville", "culture"],
    },
    {
      name: "Malasaña",
      vibe: "vintage, bars indés et friperies",
      tiers: ["eco", "standard"],
      tags: ["fete", "shopping"],
    },
    {
      name: "La Latina",
      vibe: "le quartier des tapas et du Rastro",
      tiers: ["standard"],
      tags: ["gastronomie", "fete"],
    },
    {
      name: "Salamanca",
      vibe: "chic et calme, grandes boutiques",
      tiers: ["confort"],
      tags: ["shopping", "romantique"],
    },
  ],
  activities: [
    {
      id: "prado",
      name: "Musée du Prado",
      description: "Velázquez, Goya, Bosch : l'une des plus grandes collections de peinture au monde.",
      category: "musee",
      emoji: "🖼️",
      cost: 15,
      hours: 3,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Les Ménines au Prado",
    },
    {
      id: "reina-sofia",
      name: "Musée Reina Sofía",
      description: "Art moderne et le Guernica de Picasso, face à face.",
      category: "musee",
      emoji: "🎨",
      cost: 12,
      hours: 2.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "retiro",
      name: "Parc du Retiro et barque sur l'étang",
      description: "Le grand poumon vert, son palais de cristal et ses barques.",
      category: "detente",
      emoji: "🚣",
      cost: 6,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["detente", "romantique", "nature"],
      repeatable: true,
    },
    {
      id: "palais-royal",
      name: "Palais royal",
      description: "3 400 pièces, salles du trône et armurerie royale.",
      category: "monument",
      emoji: "👑",
      cost: 14,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "plaza-mayor",
      name: "Plaza Mayor et Puerta del Sol",
      description: "Le Madrid des Habsbourg, arcades et place du kilomètre zéro.",
      category: "quartier",
      emoji: "🏛️",
      cost: 0,
      hours: 2,
      area: "Sol et Centro",
      moments: ["morning", "afternoon"],
      tags: ["ville", "culture"],
    },
    {
      id: "san-miguel",
      name: "Dégustation au Mercado de San Miguel",
      description: "Halle en fer forgé : huîtres, jamón, croquetas et vermouth.",
      category: "food",
      emoji: "🥂",
      cost: 20,
      hours: 1.5,
      area: "Sol et Centro",
      moments: ["afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "debod",
      name: "Coucher de soleil au temple de Debod",
      description: "Un vrai temple égyptien offert à l'Espagne, face au soleil couchant.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1,
      moments: ["evening"],
      tags: ["romantique", "detente"],
      highlight: "Coucher de soleil au temple de Debod",
      repeatable: true,
    },
    {
      id: "rastro",
      name: "Marché aux puces du Rastro",
      description: "Le dimanche matin, des centaines d'étals de vintage et de bric-à-brac.",
      category: "shopping",
      emoji: "🛍️",
      cost: 0,
      hours: 2.5,
      area: "La Latina",
      moments: ["morning"],
      tags: ["shopping", "ville"],
    },
    {
      id: "bernabeu",
      name: "Visite du stade Santiago-Bernabéu",
      description: "Vestiaires, pelouse et musée du Real Madrid.",
      category: "monument",
      emoji: "⚽",
      cost: 30,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["ville"],
    },
    {
      id: "latina-tapas",
      name: "Tapas dans les bars de La Latina",
      description: "La Cava Baja, rue de tavernes où l'on grignote debout.",
      category: "food",
      emoji: "🍤",
      cost: 25,
      hours: 2.5,
      area: "La Latina",
      moments: ["evening"],
      tags: ["gastronomie", "fete"],
      repeatable: true,
    },
    {
      id: "flamenco-madrid",
      name: "Flamenco au tablao",
      description: "Spectacle dans un tablao historique du vieux Madrid.",
      category: "evenement",
      emoji: "💃",
      cost: 40,
      hours: 1.5,
      moments: ["evening"],
      tags: ["culture", "festivals"],
    },
    {
      id: "malasana",
      name: "Soirée à Malasaña",
      description: "Bars rock, terrasses de la place du Dos de Mayo et DJ jusqu'au bout de la nuit.",
      category: "nightlife",
      emoji: "🍹",
      cost: 20,
      hours: 3,
      area: "Malasaña",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit à Malasaña",
      repeatable: true,
    },
    {
      id: "club-madrid",
      name: "Nuit en club",
      description: "Madrid sort tard : les clubs ne se remplissent qu'après 1 h du matin.",
      category: "nightlife",
      emoji: "🎉",
      cost: 20,
      hours: 3.5,
      moments: ["evening"],
      tags: ["fete"],
    },
    {
      id: "tolede",
      name: "Excursion à Tolède",
      description: "La ville aux trois cultures, perchée sur un rocher, à 30 min de train.",
      category: "excursion",
      emoji: "🏰",
      cost: 30,
      hours: 8,
      moments: ["morning"],
      tags: ["culture", "romantique"],
      highlight: "Les ruelles de Tolède",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-la-campana",
      name: "Bar La Campana",
      description: "Le fameux bocadillo de calamares, à deux pas de la Plaza Mayor.",
      cuisine: "Street food madrilène",
      emoji: "🥖",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      area: "Sol et Centro",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-san-gines",
      name: "Chocolatería San Ginés",
      description: "Churros et chocolat épais depuis 1894, ouvert jusque tard.",
      cuisine: "Churros & chocolat",
      emoji: "🍫",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 7,
      area: "Sol et Centro",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-casa-labra",
      name: "Casa Labra",
      description: "Taverne de 1860 près de Sol, célèbre pour ses beignets de morue.",
      cuisine: "Tapas",
      emoji: "🐟",
      kind: "bar",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Sol et Centro",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-san-ildefonso",
      name: "Mercado de San Ildefonso",
      description: "Street food market sur trois étages et terrasses, en plein Malasaña.",
      cuisine: "Food hall",
      emoji: "🌮",
      kind: "street-food",
      isLocal: false,
      priceLevel: 1,
      cost: 15,
      area: "Malasaña",
      meals: ["lunch", "dinner"],
      tags: ["fete"],
      real: true,
    },
    {
      id: "r-casa-lucio",
      name: "Casa Lucio",
      description: "La taverne des huevos rotos (œufs cassés sur frites) dans la Cava Baja.",
      cuisine: "Cuisine madrilène",
      emoji: "🍳",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 45,
      area: "La Latina",
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-botin",
      name: "Sobrino de Botín",
      description: "Le plus vieux restaurant du monde (1725) : cochon de lait rôti au four à bois.",
      cuisine: "Cuisine castillane",
      emoji: "🍖",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 55,
      area: "Sol et Centro",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(40.4168, -3.7038),
    zoom: 13,
    neighborhoods: {
      "Sol et Centro": p(40.4169, -3.7035),
      Malasaña: p(40.4262, -3.7045),
      "La Latina": p(40.4115, -3.7105),
      Salamanca: p(40.4292, -3.6795),
    },
    places: {
      prado: p(40.4138, -3.6921),
      "reina-sofia": p(40.4086, -3.6944),
      retiro: p(40.4153, -3.6845),
      "palais-royal": p(40.418, -3.7143),
      "plaza-mayor": p(40.4155, -3.7074),
      "san-miguel": p(40.4154, -3.7089),
      debod: p(40.424, -3.7178),
      rastro: p(40.4087, -3.7075),
      bernabeu: p(40.4531, -3.6883),
      "latina-tapas": p(40.4124, -3.7089),
      "flamenco-madrid": p(40.413, -3.7147),
      malasana: p(40.4262, -3.7045),
      "club-madrid": p(40.4101, -3.6934),
      tolede: p(39.8628, -4.0273),
      "r-la-campana": p(40.4146, -3.7076),
      "r-san-gines": p(40.4169, -3.7068),
      "r-casa-labra": p(40.418, -3.7052),
      "r-san-ildefonso": p(40.4225, -3.7019),
      "r-casa-lucio": p(40.4121, -3.7087),
      "r-botin": p(40.4141, -3.708),
    },
  },
  source: "demo",
};
