import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const malte: DestinationProfile = {
  id: "malte",
  name: "Malte",
  country: "Malte",
  countryCode: "MT",
  iata: "MLA",
  tagline: "Eaux turquoise, cités fortifiées et fêtes à Paceville.",
  description:
    "Un petit archipel au soleil toute l'année : La Valette et ses remparts dorés, plongée et Blue Lagoon, cité silencieuse de Mdina et nuits animées à St Julian's. On y parle anglais.",
  fallbackGradient: "from-cyan-300 via-sky-500 to-amber-400",
  type: "balneaire",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 28, standard: 60, confort: 120 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h 35",
        durationHours: 2.6,
        roundTripPerPerson: 170,
        details: "Vol direct, bus ou taxi vers La Valette en 20 min",
      },
    ],
  },
  localMobility: [
    { mode: "bus", description: "Bus sur toute l'île, avec la carte Tallinja" },
    { mode: "ferry", description: "Ferries vers Gozo, Comino et entre La Valette et Sliema" },
    { mode: "taxi", description: "VTC (Bolt) bon marché pour les trajets de nuit" },
  ],
  idealDays: { min: 4, max: 8 },
  bestMonths: [4, 5, 6, 7, 8, 9, 10],
  styles: { plage: 3, culture: 3, fete: 3, aventure: 2, detente: 2, romantique: 2, nature: 2 },
  ambiances: { festive: 3, sociale: 3, calme: 2, romantique: 2, aventureuse: 2 },
  strengths: { plages: 3, culture: 3, "vie-nocturne": 3, securite: 3, activites: 3, prix: 2 },
  neighborhoods: [
    {
      name: "La Valette",
      vibe: "la capitale fortifiée, élégante et historique",
      tiers: ["standard", "confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Sliema",
      vibe: "front de mer moderne, ferries et commerces",
      tiers: ["eco", "standard"],
      tags: ["plage", "shopping"],
    },
    {
      name: "St Julian's",
      vibe: "Paceville et ses clubs, pour faire la fête",
      tiers: ["eco", "standard", "confort"],
      tags: ["fete"],
    },
    {
      name: "Mellieħa",
      vibe: "au nord, près des plus belles plages",
      tiers: ["standard", "confort"],
      tags: ["plage", "detente"],
    },
  ],
  activities: [
    {
      id: "valette",
      name: "Balade dans La Valette",
      description: "Capitale Renaissance en pierre dorée, balcons colorés et rues en pente vers la mer.",
      category: "quartier",
      emoji: "🏰",
      cost: 0,
      hours: 2,
      area: "La Valette",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
      highlight: "Les remparts de La Valette",
    },
    {
      id: "st-john",
      name: "Co-cathédrale Saint-Jean",
      description: "Intérieur baroque tout en or et deux Caravage.",
      category: "monument",
      emoji: "⛪",
      cost: 15,
      hours: 1.5,
      area: "La Valette",
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "barrakka",
      name: "Jardins Upper Barrakka",
      description: "La plus belle vue sur le Grand Port, et le coup de canon de midi.",
      category: "panorama",
      emoji: "💥",
      cost: 0,
      hours: 1,
      area: "La Valette",
      moments: ["morning"],
      tags: ["culture", "romantique"],
    },
    {
      id: "trois-cites",
      name: "Les Trois Cités en barque",
      description: "Traversée en dgħajsa jusqu'à Birgu, ruelles et marinas.",
      category: "quartier",
      emoji: "🚣",
      cost: 3,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
    },
    {
      id: "mdina",
      name: "Mdina, la cité silencieuse",
      description: "Ancienne capitale fortifiée sur une colline, ruelles désertes et vue sur l'île.",
      category: "quartier",
      emoji: "🌙",
      cost: 0,
      hours: 2.5,
      moments: ["afternoon"],
      tags: ["culture", "romantique"],
      highlight: "Les ruelles de Mdina",
    },
    {
      id: "blue-grotto",
      name: "Grotte bleue en bateau",
      description: "Arches marines et eau phosphorescente le matin.",
      category: "panorama",
      emoji: "🌊",
      cost: 10,
      hours: 1.5,
      moments: ["morning"],
      tags: ["nature"],
    },
    {
      id: "marsaxlokk",
      name: "Marché de Marsaxlokk",
      description: "Village de pêcheurs aux barques luzzu colorées, marché le dimanche.",
      category: "food",
      emoji: "🐟",
      cost: 10,
      hours: 2,
      moments: ["morning"],
      tags: ["gastronomie", "culture"],
    },
    {
      id: "plongee",
      name: "Baptême de plongée",
      description: "Eaux parmi les plus claires de Méditerranée, épaves et grottes.",
      category: "aventure",
      emoji: "🤿",
      cost: 60,
      hours: 3,
      moments: ["morning"],
      tags: ["aventure", "nature"],
    },
    {
      id: "golden-bay",
      name: "Plage de Golden Bay",
      description: "Grande plage de sable doré entre les falaises.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 3.5,
      area: "Mellieħa",
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      repeatable: true,
    },
    {
      id: "dingli",
      name: "Coucher de soleil sur les falaises de Dingli",
      description: "Falaises de 250 m au-dessus de la mer, face au soleil couchant.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "nature"],
      highlight: "Coucher de soleil à Dingli",
      repeatable: true,
    },
    {
      id: "sliema-apero",
      name: "Apéro sur le front de mer de Sliema",
      description: "Terrasses face à La Valette illuminée.",
      category: "nightlife",
      emoji: "🍹",
      cost: 15,
      hours: 2,
      area: "Sliema",
      moments: ["evening"],
      tags: ["fete", "romantique"],
    },
    {
      id: "paceville",
      name: "Soirée à Paceville",
      description: "Le quartier des clubs : entrée souvent gratuite, fête jusqu'à l'aube.",
      category: "nightlife",
      emoji: "🎉",
      cost: 20,
      hours: 4,
      area: "St Julian's",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit à Paceville",
      repeatable: true,
    },
    {
      id: "comino",
      name: "Blue Lagoon à Comino",
      description: "Le lagon turquoise le plus célèbre de Malte, en bateau depuis le nord.",
      category: "excursion",
      emoji: "🏝️",
      cost: 30,
      hours: 7,
      moments: ["morning"],
      tags: ["plage", "nature"],
      highlight: "Le Blue Lagoon",
      fullDay: true,
    },
    {
      id: "gozo",
      name: "Excursion à Gozo",
      description: "L'île sœur, plus verte et sauvage : citadelle, salines et criques.",
      category: "excursion",
      emoji: "⛴️",
      cost: 25,
      hours: 9,
      moments: ["morning"],
      tags: ["nature", "culture", "aventure"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-crystal-palace",
      name: "Crystal Palace",
      description: "Les pastizzi (feuilletés à la ricotta ou aux petits pois) les plus célèbres, à Rabat.",
      cuisine: "Pastizzi",
      emoji: "🥐",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 3,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-is-suq",
      name: "Is-Suq tal-Belt",
      description: "Le marché couvert rénové de La Valette, food court et produits maltais.",
      cuisine: "Food hall",
      emoji: "🧺",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "La Valette",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-nenu",
      name: "Nenu the Artisan Baker",
      description: "Ftira (pain maltais) cuite au four à bois et plats traditionnels.",
      cuisine: "Cuisine maltaise",
      emoji: "🍞",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 20,
      area: "La Valette",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-tartarun",
      name: "Tartarun",
      description: "Poissons du jour face au port de pêche de Marsaxlokk.",
      cuisine: "Poissons",
      emoji: "🐟",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 45,
      meals: ["lunch"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
    {
      id: "r-rubino",
      name: "Rubino",
      description: "Ancienne pâtisserie de 1906 devenue table maltaise de référence.",
      cuisine: "Cuisine maltaise",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 45,
      area: "La Valette",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(35.9, 14.45),
    zoom: 11,
    neighborhoods: {
      "La Valette": p(35.8989, 14.5146),
      Sliema: p(35.912, 14.504),
      "St Julian's": p(35.9205, 14.4895),
      Mellieħa: p(35.957, 14.362),
    },
    places: {
      valette: p(35.8989, 14.5146),
      "st-john": p(35.8977, 14.5125),
      barrakka: p(35.8946, 14.5125),
      "trois-cites": p(35.888, 14.522),
      mdina: p(35.886, 14.403),
      "blue-grotto": p(35.82, 14.457),
      marsaxlokk: p(35.841, 14.544),
      plongee: p(35.987, 14.329),
      "golden-bay": p(35.934, 14.344),
      dingli: p(35.858, 14.382),
      "sliema-apero": p(35.912, 14.504),
      paceville: p(35.921, 14.489),
      comino: p(36.0145, 14.322),
      gozo: p(36.044, 14.251),
      "r-crystal-palace": p(35.8826, 14.401),
      "r-is-suq": p(35.8976, 14.5132),
      "r-nenu": p(35.8993, 14.513),
      "r-tartarun": p(35.8415, 14.5445),
      "r-rubino": p(35.8985, 14.514),
    },
  },
  source: "demo",
};
