import { destinationImages } from "@/config/images";
import type { DestinationProfile } from "../../types";

export const marrakech: DestinationProfile = {
  id: "marrakech",
  name: "Marrakech",
  country: "Maroc",
  countryCode: "MA",
  tagline: "Souks, riads et désert aux portes de la ville.",
  description:
    "Dépaysement total à 3 h de vol : médina bouillonnante, riads apaisants, cuisine épicée et Atlas à l'horizon.",
  image: { src: destinationImages.marrakech, alt: "Place animée de la médina de Marrakech" },
  fallbackGradient: "from-orange-500 via-rose-600 to-purple-800",
  type: "ville",
  costLevel: 1,
  costs: {
    accommodationPerNight: { eco: 18, standard: 40, confort: 100 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "3 h 15",
        durationHours: 3.25,
        roundTripPerPerson: 170,
        details: "Vol direct, 15 min de l'aéroport à la médina",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "La médina se parcourt uniquement à pied" },
    { mode: "taxi", description: "Petits taxis : fixe le prix avant de monter" },
  ],
  idealDays: { min: 3, max: 7 },
  bestMonths: [3, 4, 5, 10, 11, 12],
  styles: {
    culture: 3,
    aventure: 3,
    detente: 3,
    shopping: 3,
    gastronomie: 2,
    nature: 2,
    romantique: 2,
    fete: 1,
  },
  ambiances: { authentique: 3, aventureuse: 3, calme: 2, luxueuse: 3, economique: 3, romantique: 2 },
  strengths: { prix: 3, culture: 3, confort: 2, activites: 2, gastronomie: 2, nature: 2 },
  neighborhoods: [
    {
      name: "Médina",
      vibe: "riad traditionnel au cœur des souks",
      tiers: ["eco", "standard", "confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Guéliz",
      vibe: "moderne, cafés et rooftops",
      tiers: ["eco", "standard"],
      tags: ["ville", "fete"],
    },
    { name: "Palmeraie", vibe: "hôtels avec piscine au calme", tiers: ["confort"], tags: ["detente"] },
  ],
  activities: [
    {
      id: "jemaa",
      name: "Place Jemaa el-Fna à la tombée du jour",
      description: "Conteurs, musiciens et stands fumants : le grand spectacle.",
      category: "quartier",
      emoji: "🎪",
      cost: 0,
      hours: 2,
      area: "Médina",
      moments: ["evening"],
      tags: ["culture", "ville"],
      highlight: "La place Jemaa el-Fna le soir",
    },
    {
      id: "souks",
      name: "Se perdre dans les souks",
      description: "Épices, lanternes, cuir : négocie avec le sourire.",
      category: "shopping",
      emoji: "🧿",
      cost: 20,
      hours: 3,
      area: "Médina",
      moments: ["morning", "afternoon"],
      tags: ["shopping", "culture"],
    },
    {
      id: "majorelle",
      name: "Jardin Majorelle & musée YSL",
      description: "Le bleu Majorelle et les cactus géants.",
      category: "monument",
      emoji: "💙",
      cost: 25,
      hours: 2,
      area: "Guéliz",
      moments: ["morning"],
      tags: ["culture", "romantique", "nature"],
      highlight: "Le jardin Majorelle",
    },
    {
      id: "bahia",
      name: "Palais de la Bahia & médersa Ben Youssef",
      description: "Zelliges, stucs et cèdre sculpté.",
      category: "monument",
      emoji: "🕌",
      cost: 12,
      hours: 2.5,
      area: "Médina",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "hammam",
      name: "Hammam traditionnel & massage",
      description: "Gommage au savon noir puis détente totale.",
      category: "detente",
      emoji: "🧖",
      cost: 35,
      hours: 2,
      moments: ["afternoon"],
      tags: ["detente", "romantique"],
      highlight: "Hammam & massage",
    },
    {
      id: "cooking-ma",
      name: "Cours de cuisine marocaine",
      description: "Tajine et pastilla, du marché à l'assiette.",
      category: "food",
      emoji: "🍲",
      cost: 40,
      hours: 3.5,
      moments: ["morning"],
      tags: ["gastronomie"],
    },
    {
      id: "rooftop-ma",
      name: "Thé à la menthe sur un rooftop",
      description: "Coucher de soleil sur les minarets.",
      category: "panorama",
      emoji: "🌅",
      cost: 6,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "detente"],
      highlight: "Coucher de soleil sur la médina",
      repeatable: true,
    },
    {
      id: "piscine",
      name: "Après-midi piscine dans un beach club",
      description: "Transats et piscine à l'ombre des palmiers.",
      category: "detente",
      emoji: "🏊",
      cost: 30,
      hours: 4,
      area: "Palmeraie",
      moments: ["afternoon"],
      tags: ["detente", "plage"],
      repeatable: true,
    },
    {
      id: "quad",
      name: "Quad ou dromadaire dans la Palmeraie",
      description: "Pistes de terre rouge à l'orée de la ville.",
      category: "aventure",
      emoji: "🐪",
      cost: 45,
      hours: 3,
      area: "Palmeraie",
      moments: ["morning", "afternoon"],
      tags: ["aventure", "nature"],
    },
    {
      id: "guéliz-bar",
      name: "Soirée rooftop & DJ à Guéliz",
      description: "Les adresses branchées de la ville nouvelle.",
      category: "nightlife",
      emoji: "🎶",
      cost: 25,
      hours: 3,
      area: "Guéliz",
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "atlas",
      name: "Excursion dans l'Atlas & vallée de l'Ourika",
      description: "Villages berbères, cascades et thé chez l'habitant.",
      category: "excursion",
      emoji: "🏔️",
      cost: 35,
      hours: 8,
      moments: ["morning"],
      tags: ["nature", "aventure", "culture"],
      highlight: "Journée dans l'Atlas",
      fullDay: true,
    },
    {
      id: "agafay",
      name: "Nuit sous les étoiles dans le désert d'Agafay",
      description: "Dîner berbère et bivouac à 45 min de la ville.",
      category: "excursion",
      emoji: "🏜️",
      cost: 60,
      hours: 8,
      moments: ["morning"],
      tags: ["aventure", "romantique", "nature"],
      highlight: "Le désert d'Agafay",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "stand",
      name: "OVO Grill de la Place",
      description: "Brochettes, harira et escargots pour les curieux.",
      cuisine: "Grillades marocaines",
      emoji: "🍢",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      area: "Médina",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
    },
    {
      id: "tanjia",
      name: "OVO Tanjia",
      description: "Le plat des souks, cuit toute la nuit.",
      cuisine: "Cuisine marocaine",
      emoji: "🍲",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 7,
      meals: ["lunch"],
      tags: ["gastronomie"],
    },
    {
      id: "cafe-ma",
      name: "Café OVO Médina",
      description: "Salades marocaines et jus d'orange pressé.",
      cuisine: "Salades & jus frais",
      emoji: "🥗",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 10,
      meals: ["lunch"],
      tags: [],
    },
    {
      id: "riad-diner",
      name: "Riad OVO Table",
      description: "Tajines et pastilla autour d'un patio illuminé.",
      cuisine: "Cuisine marocaine",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
    },
    {
      id: "gastro-ma",
      name: "Palais OVO",
      description: "Cuisine marocaine raffinée et musique andalouse.",
      cuisine: "Gastronomie marocaine",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 60,
      meals: ["dinner"],
      tags: ["romantique", "festivals"],
    },
  ],
  source: "demo",
};
