import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const marseille: DestinationProfile = {
  id: "marseille",
  name: "Marseille",
  country: "France",
  countryCode: "FR",
  iata: "MRS",
  tagline: "Calanques, pastis au Vieux-Port et nuits au Cours Julien.",
  description:
    "La ville la plus solaire de France : randonnées et criques des calanques, quartiers vivants, cuisine du monde entier et coucher de soleil sur la Corniche.",
  fallbackGradient: "from-sky-400 via-blue-600 to-yellow-400",
  type: "mixte",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 30, standard: 65, confort: 130 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "train",
        durationLabel: "3 h 15",
        durationHours: 3.25,
        roundTripPerPerson: 100,
        details: "TGV direct jusqu'à Marseille-Saint-Charles, en plein centre",
      },
      {
        mode: "avion",
        durationLabel: "1 h 20",
        durationHours: 1.35,
        roundTripPerPerson: 120,
        details: "Vol direct, navette jusqu'à la gare Saint-Charles en 25 min",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Deux lignes de métro et le tram pour le centre" },
    { mode: "bus", description: "Bus vers les plages, la Corniche et l'entrée des calanques" },
    { mode: "ferry", description: "Navettes maritimes vers le Frioul et l'Estaque" },
    { mode: "marche", description: "Vieux-Port, Panier et Cours Julien à pied" },
  ],
  idealDays: { min: 3, max: 6 },
  bestMonths: [4, 5, 6, 7, 8, 9, 10],
  styles: { nature: 3, plage: 3, aventure: 3, ville: 2, fete: 2, gastronomie: 2, culture: 2, festivals: 2 },
  ambiances: { authentique: 3, aventureuse: 3, sociale: 3, festive: 2, economique: 2 },
  strengths: { nature: 3, plages: 3, activites: 3, rapidite: 3, "vie-nocturne": 2, gastronomie: 2 },
  neighborhoods: [
    {
      name: "Vieux-Port",
      vibe: "au cœur de la ville, terrasses et bateaux",
      tiers: ["standard", "confort"],
      tags: ["ville", "romantique"],
    },
    {
      name: "Le Panier",
      vibe: "le plus vieux quartier, ruelles et street art",
      tiers: ["eco", "standard"],
      tags: ["culture", "ville"],
    },
    {
      name: "Cours Julien",
      vibe: "alternatif, graffitis, bars et concerts",
      tiers: ["eco", "standard"],
      tags: ["fete", "shopping"],
    },
    {
      name: "Endoume",
      vibe: "entre Corniche et petites calanques urbaines",
      tiers: ["standard", "confort"],
      tags: ["plage", "detente"],
    },
  ],
  activities: [
    {
      id: "vieux-port",
      name: "Vieux-Port et son ombrière miroir",
      description: "Le marché aux poissons du matin et le miroir géant de Norman Foster.",
      category: "quartier",
      emoji: "⚓",
      cost: 0,
      hours: 1.5,
      area: "Vieux-Port",
      moments: ["morning"],
      tags: ["ville"],
    },
    {
      id: "bonne-mere",
      name: "Notre-Dame-de-la-Garde",
      description: "La « Bonne Mère » veille sur la ville : vue à 360° sur la mer et les îles.",
      category: "panorama",
      emoji: "⛪",
      cost: 0,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
      highlight: "Marseille vue de la Bonne Mère",
    },
    {
      id: "panier",
      name: "Le Panier et la Vieille Charité",
      description: "Escaliers, façades colorées, savonneries et street art.",
      category: "quartier",
      emoji: "🎨",
      cost: 0,
      hours: 2,
      area: "Le Panier",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "mucem",
      name: "MuCEM et fort Saint-Jean",
      description: "Musée des civilisations de la Méditerranée, résille de béton et passerelle vers le fort.",
      category: "musee",
      emoji: "🏛️",
      cost: 12,
      hours: 2.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "noailles",
      name: "Marché de Noailles",
      description: "Le « ventre de Marseille » : épices, pâtisseries orientales et produits du monde.",
      category: "food",
      emoji: "🌶️",
      cost: 10,
      hours: 1,
      moments: ["morning"],
      tags: ["gastronomie"],
    },
    {
      id: "calanques",
      name: "Randonnée dans les calanques",
      description:
        "Sugiton ou En-Vau : falaises blanches et eau turquoise. Parfois fermées en été (risque d'incendie).",
      category: "nature",
      emoji: "🥾",
      cost: 0,
      hours: 5,
      moments: ["morning"],
      tags: ["nature", "aventure", "plage"],
      highlight: "Baignade dans une calanque",
    },
    {
      id: "kayak-calanques",
      name: "Kayak dans les calanques",
      description: "Les criques inaccessibles à pied, en kayak depuis la Pointe-Rouge.",
      category: "aventure",
      emoji: "🛶",
      cost: 45,
      hours: 4,
      moments: ["morning"],
      tags: ["aventure", "nature"],
    },
    {
      id: "frioul",
      name: "Îles du Frioul et château d'If",
      description: "Navette depuis le Vieux-Port, prison du comte de Monte-Cristo et criques.",
      category: "excursion",
      emoji: "🏝️",
      cost: 20,
      hours: 5,
      moments: ["afternoon"],
      tags: ["nature", "plage", "culture"],
    },
    {
      id: "catalans",
      name: "Plage des Catalans",
      description: "La plage de sable du centre-ville, volley et baignade.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 3,
      area: "Endoume",
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      repeatable: true,
    },
    {
      id: "vallon-auffes",
      name: "Coucher de soleil au Vallon des Auffes",
      description: "Petit port de pêcheurs sous la Corniche, puis coucher de soleil sur les îles.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      area: "Endoume",
      moments: ["evening"],
      tags: ["romantique", "detente"],
      highlight: "Coucher de soleil sur la Corniche",
      repeatable: true,
    },
    {
      id: "cours-julien",
      name: "Soirée au Cours Julien",
      description: "Bars, concerts et terrasses dans le quartier le plus arty.",
      category: "nightlife",
      emoji: "🎸",
      cost: 20,
      hours: 3,
      area: "Cours Julien",
      moments: ["evening"],
      tags: ["fete", "festivals"],
      highlight: "Nuit au Cours Julien",
      repeatable: true,
    },
    {
      id: "velodrome",
      name: "Match de l'OM au Vélodrome",
      description: "L'ambiance la plus folle de France les soirs de match (selon le calendrier).",
      category: "evenement",
      emoji: "⚽",
      cost: 40,
      hours: 3,
      moments: ["evening"],
      tags: ["festivals", "fete"],
    },
    {
      id: "cassis",
      name: "Journée à Cassis",
      description: "Port pastel, vin blanc et balade en bateau dans les calanques.",
      category: "excursion",
      emoji: "⛵",
      cost: 30,
      hours: 8,
      moments: ["morning"],
      tags: ["plage", "romantique", "nature"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-chez-yassine",
      name: "Chez Yassine",
      description: "Cantine tunisienne de Noailles : lablabi, couscous et brik à petit prix.",
      cuisine: "Cuisine tunisienne",
      emoji: "🥘",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-chez-sauveur",
      name: "Chez Sauveur",
      description: "Pizzeria au feu de bois de 1943, à l'ancienne, près de Noailles.",
      cuisine: "Pizza marseillaise",
      emoji: "🍕",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-chez-etienne",
      name: "Chez Étienne",
      description: "Institution du Panier : pizza, supions et ambiance de famille. Pas de CB.",
      cuisine: "Cuisine marseillaise",
      emoji: "🍕",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Le Panier",
      meals: ["dinner"],
      tags: ["gastronomie", "fete"],
      real: true,
    },
    {
      id: "r-chez-jeannot",
      name: "Chez Jeannot",
      description: "Pizzas et poissons en terrasse dans le Vallon des Auffes.",
      cuisine: "Pizza & poissons",
      emoji: "🐟",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 28,
      area: "Endoume",
      meals: ["lunch", "dinner"],
      tags: ["romantique"],
      real: true,
    },
    {
      id: "r-boite-sardine",
      name: "La Boîte à Sardine",
      description: "Poissonnerie-restaurant déjantée, poisson du jour selon la pêche.",
      cuisine: "Poissons & fruits de mer",
      emoji: "🐟",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-chez-fonfon",
      name: "Chez Fonfon",
      description: "La bouillabaisse dans les règles depuis 1952, au Vallon des Auffes.",
      cuisine: "Bouillabaisse",
      emoji: "🍲",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 70,
      area: "Endoume",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(43.2965, 5.3698),
    zoom: 13,
    neighborhoods: {
      "Vieux-Port": p(43.2951, 5.374),
      "Le Panier": p(43.2985, 5.3685),
      "Cours Julien": p(43.293, 5.383),
      Endoume: p(43.2835, 5.3545),
    },
    places: {
      "vieux-port": p(43.2951, 5.374),
      "bonne-mere": p(43.284, 5.3712),
      panier: p(43.299, 5.367),
      mucem: p(43.2966, 5.361),
      noailles: p(43.296, 5.38),
      calanques: p(43.215, 5.443),
      "kayak-calanques": p(43.2455, 5.3745),
      frioul: p(43.28, 5.31),
      catalans: p(43.2905, 5.353),
      "vallon-auffes": p(43.2855, 5.35),
      "cours-julien": p(43.293, 5.383),
      velodrome: p(43.2698, 5.3959),
      cassis: p(43.214, 5.538),
      "r-chez-yassine": p(43.2963, 5.3805),
      "r-chez-sauveur": p(43.2945, 5.381),
      "r-chez-etienne": p(43.2983, 5.3693),
      "r-chez-jeannot": p(43.286, 5.3497),
      "r-boite-sardine": p(43.2983, 5.3848),
      "r-chez-fonfon": p(43.2856, 5.3503),
    },
  },
  source: "demo",
};
