import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const mexico: DestinationProfile = {
  id: "mexico",
  name: "Mexico",
  country: "Mexique",
  countryCode: "MX",
  iata: "MEX",
  tagline: "Pyramides, tacos al pastor et mezcal sous les jacarandas.",
  description:
    "Une mégapole vibrante et colorée : pyramides de Teotihuacan, maison de Frida Kahlo, barques fleuries de Xochimilco, lucha libre et les meilleurs tacos du monde pour quelques pesos.",
  fallbackGradient: "from-pink-400 via-orange-500 to-emerald-600",
  type: "ville",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 20, standard: 50, confort: 110 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "12 h",
        durationHours: 12,
        roundTripPerPerson: 650,
        details: "Vol direct, taxi officiel ou VTC jusqu'au centre en 30 à 45 min",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Métro très bon marché (évite les heures de pointe)" },
    { mode: "taxi", description: "VTC (Uber, DiDi) sûrs et abordables, surtout le soir" },
    { mode: "marche", description: "Roma, Condesa et le centre historique à pied" },
  ],
  idealDays: { min: 5, max: 10 },
  bestMonths: [3, 4, 5, 10, 11],
  styles: { culture: 3, gastronomie: 3, ville: 3, fete: 3, festivals: 2, shopping: 2, aventure: 1 },
  ambiances: { authentique: 3, festive: 3, sociale: 3, economique: 3, aventureuse: 2 },
  strengths: { gastronomie: 3, culture: 3, prix: 3, "vie-nocturne": 3, activites: 3 },
  neighborhoods: [
    {
      name: "Centro Histórico",
      vibe: "le cœur colonial autour du Zócalo",
      tiers: ["eco", "standard"],
      tags: ["culture"],
    },
    {
      name: "Roma",
      vibe: "Art déco, cafés et bars à mezcal",
      tiers: ["standard", "confort"],
      tags: ["fete", "gastronomie"],
    },
    {
      name: "Condesa",
      vibe: "parcs, avenues arborées et terrasses",
      tiers: ["standard", "confort"],
      tags: ["detente", "romantique"],
    },
    {
      name: "Coyoacán",
      vibe: "village bohème, la maison de Frida",
      tiers: ["standard"],
      tags: ["culture", "romantique"],
    },
  ],
  activities: [
    {
      id: "zocalo",
      name: "Zócalo et cathédrale",
      description: "L'une des plus grandes places du monde, bordée de palais.",
      category: "monument",
      emoji: "🇲🇽",
      cost: 0,
      hours: 2,
      area: "Centro Histórico",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Le Zócalo",
    },
    {
      id: "templo-mayor",
      name: "Templo Mayor",
      description: "Les ruines du grand temple aztèque, en plein centre-ville.",
      category: "musee",
      emoji: "🏺",
      cost: 5,
      hours: 1.5,
      area: "Centro Histórico",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "bellas-artes",
      name: "Palais des Beaux-Arts",
      description: "Façade de marbre et fresques de Diego Rivera.",
      category: "monument",
      emoji: "🎭",
      cost: 5,
      hours: 1.5,
      area: "Centro Histórico",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "anthropologie",
      name: "Musée national d'anthropologie",
      description: "La pierre du Soleil aztèque et 3 000 ans de civilisations.",
      category: "musee",
      emoji: "🗿",
      cost: 5,
      hours: 3,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Le musée d'anthropologie",
    },
    {
      id: "chapultepec",
      name: "Château de Chapultepec",
      description: "Château sur la colline du grand parc, vue sur la ville.",
      category: "monument",
      emoji: "🏰",
      cost: 5,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture", "nature"],
    },
    {
      id: "frida",
      name: "Maison bleue de Frida Kahlo",
      description: "La maison-atelier de Frida à Coyoacán. Billets à réserver.",
      category: "musee",
      emoji: "💙",
      cost: 13,
      hours: 1.5,
      area: "Coyoacán",
      moments: ["morning"],
      tags: ["culture", "romantique"],
    },
    {
      id: "roma-condesa",
      name: "Parcs et cafés de Roma-Condesa",
      description: "Avenues arborées, parc México et cafés de spécialité.",
      category: "quartier",
      emoji: "🌳",
      cost: 0,
      hours: 2.5,
      area: "Condesa",
      moments: ["afternoon"],
      tags: ["detente", "ville"],
    },
    {
      id: "xochimilco",
      name: "Trajinera à Xochimilco",
      description: "Barques colorées sur les canaux, mariachis et vendeurs flottants.",
      category: "evenement",
      emoji: "🛶",
      cost: 25,
      hours: 3,
      moments: ["afternoon"],
      tags: ["fete", "culture"],
      highlight: "Les canaux de Xochimilco",
    },
    {
      id: "tacos-tour",
      name: "Tournée des taquerias",
      description: "Al pastor, suadero et campechano, debout au comptoir.",
      category: "food",
      emoji: "🌮",
      cost: 15,
      hours: 2,
      moments: ["evening"],
      tags: ["gastronomie"],
      repeatable: true,
    },
    {
      id: "lucha",
      name: "Lucha libre à l'Arena México",
      description: "Masques, acrobaties et public déchaîné, le spectacle le plus fun de la ville.",
      category: "evenement",
      emoji: "🤼",
      cost: 15,
      hours: 2.5,
      moments: ["evening"],
      tags: ["festivals", "fete"],
    },
    {
      id: "mezcal",
      name: "Bars à mezcal de la Roma",
      description: "Dégustation de mezcals artisanaux, puis bars et clubs.",
      category: "nightlife",
      emoji: "🥃",
      cost: 20,
      hours: 3,
      area: "Roma",
      moments: ["evening"],
      tags: ["fete", "gastronomie"],
      highlight: "Nuit dans les bars à mezcal",
      repeatable: true,
    },
    {
      id: "teotihuacan",
      name: "Pyramides de Teotihuacan",
      description: "Les pyramides du Soleil et de la Lune, en montgolfière pour les chanceux.",
      category: "excursion",
      emoji: "🔺",
      cost: 25,
      hours: 8,
      moments: ["morning"],
      tags: ["culture", "aventure"],
      highlight: "Les pyramides de Teotihuacan",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-los-cocuyos",
      name: "Taquería Los Cocuyos",
      description: "Minuscule taqueria du centre ouverte tard, tacos de suadero légendaires.",
      cuisine: "Tacos",
      emoji: "🌮",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 4,
      area: "Centro Histórico",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-el-huequito",
      name: "El Huequito",
      description: "Tacos al pastor depuis 1959, découpés sur la broche.",
      cuisine: "Tacos al pastor",
      emoji: "🔥",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      area: "Centro Histórico",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-cafe-tacuba",
      name: "Café de Tacuba",
      description: "Institution de 1912 aux azulejos, enchiladas et chocolat chaud.",
      cuisine: "Cuisine mexicaine",
      emoji: "🌶️",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      area: "Centro Histórico",
      meals: ["lunch", "dinner"],
      tags: ["romantique"],
      real: true,
    },
    {
      id: "r-contramar",
      name: "Contramar",
      description: "Poissons et tostadas de thon, le déjeuner préféré des Mexicains branchés.",
      cuisine: "Poissons & fruits de mer",
      emoji: "🐟",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 40,
      area: "Roma",
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-rosetta",
      name: "Rosetta",
      description: "Cuisine mexicaine d'auteur dans une maison de la Roma, pâtisseries célèbres.",
      cuisine: "Cuisine mexicaine d'auteur",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 60,
      area: "Roma",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(19.4326, -99.1332),
    zoom: 12,
    neighborhoods: {
      "Centro Histórico": p(19.4336, -99.1352),
      Roma: p(19.4178, -99.1622),
      Condesa: p(19.412, -99.1737),
      Coyoacán: p(19.3496, -99.1617),
    },
    places: {
      zocalo: p(19.4326, -99.1332),
      "templo-mayor": p(19.4351, -99.1314),
      "bellas-artes": p(19.4352, -99.1412),
      anthropologie: p(19.426, -99.186),
      chapultepec: p(19.4204, -99.1819),
      frida: p(19.3551, -99.1624),
      "roma-condesa": p(19.412, -99.17),
      xochimilco: p(19.2573, -99.1036),
      "tacos-tour": p(19.415, -99.165),
      lucha: p(19.4247, -99.152),
      mezcal: p(19.417, -99.16),
      teotihuacan: p(19.6925, -98.8438),
      "r-los-cocuyos": p(19.4318, -99.1377),
      "r-el-huequito": p(19.4325, -99.141),
      "r-cafe-tacuba": p(19.436, -99.1405),
      "r-contramar": p(19.419, -99.164),
      "r-rosetta": p(19.4185, -99.16),
    },
  },
  source: "demo",
};
