import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const milan: DestinationProfile = {
  id: "milan",
  name: "Milan",
  country: "Italie",
  countryCode: "IT",
  iata: "MIL",
  tagline: "Mode, design et aperitivo au bord des canaux.",
  description:
    "La capitale du style italien : Duomo et ses toits, la Cène de Léonard, quartiers de Brera et des Navigli, aperitivo à volonté et le lac de Côme à une heure de train.",
  fallbackGradient: "from-stone-300 via-amber-600 to-neutral-800",
  type: "ville",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 35, standard: 80, confort: 160 },
    localTransportPerDay: 6,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "1 h 30",
        durationHours: 1.5,
        roundTripPerPerson: 130,
        details: "Vol vers Linate ou Malpensa, métro ou train jusqu'au centre",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Métro rapide avec paiement sans contact" },
    { mode: "tram", description: "Trams historiques orange dans le centre" },
    { mode: "marche", description: "Duomo, Brera et Navigli à pied" },
  ],
  idealDays: { min: 2, max: 4 },
  bestMonths: [4, 5, 6, 9, 10],
  styles: { shopping: 3, culture: 3, gastronomie: 3, ville: 3, fete: 2, romantique: 2 },
  ambiances: { luxueuse: 3, sociale: 2, festive: 2, romantique: 2 },
  strengths: { culture: 3, gastronomie: 3, rapidite: 3, "vie-nocturne": 2, confort: 2 },
  neighborhoods: [
    {
      name: "Centro",
      vibe: "autour du Duomo, tout à pied",
      tiers: ["standard", "confort"],
      tags: ["culture", "shopping"],
    },
    {
      name: "Brera",
      vibe: "bohème chic, galeries et ruelles",
      tiers: ["confort"],
      tags: ["romantique", "culture"],
    },
    { name: "Navigli", vibe: "canaux, bars et aperitivo", tiers: ["eco", "standard"], tags: ["fete"] },
    { name: "Isola", vibe: "moderne, jeune et Bosco Verticale", tiers: ["eco", "standard"], tags: ["ville"] },
  ],
  activities: [
    {
      id: "duomo-milan",
      name: "Duomo et ses toits en terrasse",
      description: "Promenade parmi les flèches de marbre, vue sur toute la ville.",
      category: "monument",
      emoji: "⛪",
      cost: 15,
      hours: 2,
      area: "Centro",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Les toits du Duomo",
    },
    {
      id: "cene",
      name: "La Cène de Léonard de Vinci",
      description: "15 minutes face au chef-d'œuvre. Réserve plusieurs semaines à l'avance.",
      category: "musee",
      emoji: "🖼️",
      cost: 15,
      hours: 1,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
      highlight: "La Cène de Léonard",
    },
    {
      id: "galleria",
      name: "Galerie Victor-Emmanuel II",
      description: "Le plus beau passage couvert d'Italie, verrière et mosaïques.",
      category: "shopping",
      emoji: "🛍️",
      cost: 0,
      hours: 1,
      area: "Centro",
      moments: ["morning", "afternoon"],
      tags: ["shopping"],
    },
    {
      id: "brera-pinacotheque",
      name: "Brera et sa pinacothèque",
      description: "Raphaël et Caravage, puis les ruelles d'artistes.",
      category: "musee",
      emoji: "🎨",
      cost: 15,
      hours: 2.5,
      area: "Brera",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "sforza",
      name: "Château des Sforza et parc Sempione",
      description: "Forteresse Renaissance, musées et grand parc.",
      category: "monument",
      emoji: "🏰",
      cost: 5,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture", "detente"],
    },
    {
      id: "isola",
      name: "Bosco Verticale et quartier Isola",
      description: "Les tours-forêts et le quartier le plus design.",
      category: "quartier",
      emoji: "🌳",
      cost: 0,
      hours: 1.5,
      area: "Isola",
      moments: ["afternoon"],
      tags: ["ville"],
    },
    {
      id: "prada",
      name: "Fondazione Prada",
      description: "Art contemporain dans une distillerie, tour dorée et café Wes Anderson.",
      category: "musee",
      emoji: "✨",
      cost: 15,
      hours: 2,
      moments: ["afternoon"],
      tags: ["culture"],
    },
    {
      id: "san-siro",
      name: "Visite du stade de San Siro",
      description: "Le temple de l'Inter et du Milan AC.",
      category: "evenement",
      emoji: "⚽",
      cost: 30,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["festivals"],
    },
    {
      id: "navigli",
      name: "Aperitivo sur les Navigli",
      description: "Spritz et buffet le long des canaux au coucher du soleil.",
      category: "nightlife",
      emoji: "🍹",
      cost: 15,
      hours: 2.5,
      area: "Navigli",
      moments: ["evening"],
      tags: ["fete", "romantique"],
      highlight: "Aperitivo sur les Navigli",
      repeatable: true,
    },
    {
      id: "corso-como",
      name: "Soirée à Corso Como",
      description: "Clubs et bars chics du quartier Garibaldi.",
      category: "nightlife",
      emoji: "🎉",
      cost: 25,
      hours: 3,
      moments: ["evening"],
      tags: ["fete"],
    },
    {
      id: "come",
      name: "Excursion au lac de Côme",
      description: "Bellagio, villas et bateaux sur le lac, à 1 h de train.",
      category: "excursion",
      emoji: "⛵",
      cost: 25,
      hours: 9,
      moments: ["morning"],
      tags: ["romantique", "nature"],
      highlight: "Le lac de Côme",
      fullDay: true,
    },
    {
      id: "bergame",
      name: "Excursion à Bergame",
      description: "La ville haute médiévale et ses remparts vénitiens.",
      category: "excursion",
      emoji: "🏘️",
      cost: 15,
      hours: 7,
      moments: ["morning"],
      tags: ["culture"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-luini",
      name: "Luini",
      description: "Panzerotti frits ou au four derrière le Duomo, depuis 1949.",
      cuisine: "Street food lombarde",
      emoji: "🥟",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 5,
      area: "Centro",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-spontini",
      name: "Spontini",
      description: "Parts de pizza épaisse et moelleuse, une institution milanaise.",
      cuisine: "Pizza",
      emoji: "🍕",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-pave",
      name: "Pavè",
      description: "Pâtisserie-café adorée pour ses viennoiseries et son brunch.",
      cuisine: "Café & pâtisserie",
      emoji: "🥐",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 10,
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-trattoria-milanese",
      name: "Trattoria Milanese",
      description: "Risotto au safran et escalope milanaise depuis 1933.",
      cuisine: "Cuisine milanaise",
      emoji: "🍛",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 45,
      area: "Centro",
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-ratana",
      name: "Ratanà",
      description: "Cuisine milanaise moderne dans une ancienne gare de l'Isola.",
      cuisine: "Cuisine milanaise moderne",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 55,
      area: "Isola",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(45.4642, 9.19),
    zoom: 13,
    neighborhoods: {
      Centro: p(45.4642, 9.19),
      Brera: p(45.4719, 9.188),
      Navigli: p(45.452, 9.176),
      Isola: p(45.4855, 9.1905),
    },
    places: {
      "duomo-milan": p(45.4642, 9.1916),
      cene: p(45.4659, 9.1709),
      galleria: p(45.4659, 9.19),
      "brera-pinacotheque": p(45.4719, 9.188),
      sforza: p(45.4705, 9.1793),
      isola: p(45.4855, 9.1905),
      prada: p(45.4445, 9.2045),
      "san-siro": p(45.4781, 9.124),
      navigli: p(45.452, 9.176),
      "corso-como": p(45.482, 9.188),
      come: p(45.987, 9.258),
      bergame: p(45.7038, 9.6627),
      "r-luini": p(45.4652, 9.1918),
      "r-spontini": p(45.478, 9.209),
      "r-pave": p(45.476, 9.202),
      "r-trattoria-milanese": p(45.461, 9.184),
      "r-ratana": p(45.484, 9.19),
    },
  },
  source: "demo",
};
