import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const montreal: DestinationProfile = {
  id: "montreal",
  name: "Montréal",
  country: "Canada",
  countryCode: "CA",
  iata: "YMQ",
  tagline: "L'Amérique en français : festivals, poutine et escaliers en colimaçon.",
  description:
    "Une ville nord-américaine qui parle ta langue : Vieux-Montréal pavé, quartiers vivants du Plateau et du Mile End, festivals tout l'été et bagels chauds à 3 h du matin.",
  fallbackGradient: "from-red-400 via-rose-600 to-slate-700",
  type: "ville",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 35, standard: 80, confort: 150 },
    localTransportPerDay: 7,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "7 h 30",
        durationHours: 7.5,
        roundTripPerPerson: 550,
        details: "Vol direct, bus 747 jusqu'au centre-ville. Autorisation eTA obligatoire",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Métro simple et rapide (souterrain, parfait l'hiver)" },
    { mode: "velo", description: "Vélos BIXI en libre-service, pistes cyclables partout" },
    { mode: "marche", description: "Vieux-Montréal, Plateau et Mile End à pied" },
  ],
  idealDays: { min: 4, max: 8 },
  bestMonths: [5, 6, 7, 8, 9, 12],
  styles: { ville: 3, festivals: 3, gastronomie: 3, culture: 2, fete: 3, nature: 2, shopping: 2 },
  ambiances: { sociale: 3, festive: 3, authentique: 2, calme: 1 },
  strengths: { securite: 3, "vie-nocturne": 3, gastronomie: 3, culture: 2, activites: 2 },
  neighborhoods: [
    {
      name: "Vieux-Montréal",
      vibe: "rues pavées et architecture européenne",
      tiers: ["standard", "confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Plateau Mont-Royal",
      vibe: "maisons colorées, cafés et bars",
      tiers: ["eco", "standard"],
      tags: ["fete", "ville"],
    },
    {
      name: "Mile End",
      vibe: "artistes, bagels et friperies",
      tiers: ["eco", "standard"],
      tags: ["shopping", "gastronomie"],
    },
    {
      name: "Centre-ville",
      vibe: "festivals et musées",
      tiers: ["standard", "confort"],
      tags: ["festivals", "culture"],
    },
  ],
  activities: [
    {
      id: "vieux-montreal",
      name: "Vieux-Montréal et basilique Notre-Dame",
      description: "Rues pavées, et une basilique bleue et or à couper le souffle.",
      category: "monument",
      emoji: "⛪",
      cost: 16,
      hours: 2,
      area: "Vieux-Montréal",
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
      highlight: "La basilique Notre-Dame",
    },
    {
      id: "mont-royal",
      name: "Belvédère du Mont-Royal",
      description: "Montée par les sentiers du parc, vue sur les gratte-ciel et le Saint-Laurent.",
      category: "nature",
      emoji: "⛰️",
      cost: 0,
      hours: 2,
      moments: ["morning"],
      tags: ["nature", "ville"],
      highlight: "La vue du Mont-Royal",
    },
    {
      id: "jean-talon",
      name: "Marché Jean-Talon",
      description: "Produits du Québec, sirop d'érable, fromages et stands de dégustation.",
      category: "food",
      emoji: "🍁",
      cost: 15,
      hours: 1.5,
      moments: ["morning"],
      tags: ["gastronomie"],
    },
    {
      id: "plateau",
      name: "Plateau et ses escaliers extérieurs",
      description: "Balade dans les ruelles vertes et les maisons aux escaliers en colimaçon.",
      category: "quartier",
      emoji: "🏘️",
      cost: 0,
      hours: 2,
      area: "Plateau Mont-Royal",
      moments: ["afternoon"],
      tags: ["ville"],
    },
    {
      id: "mile-end",
      name: "Friperies et cafés du Mile End",
      description: "Le quartier des artistes, disquaires et cafés italiens.",
      category: "shopping",
      emoji: "🛍️",
      cost: 0,
      hours: 2,
      area: "Mile End",
      moments: ["afternoon"],
      tags: ["shopping"],
    },
    {
      id: "mbam",
      name: "Musée des beaux-arts",
      description: "Grande collection d'art québécois et expositions internationales.",
      category: "musee",
      emoji: "🖼️",
      cost: 24,
      hours: 2.5,
      area: "Centre-ville",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "tam-tams",
      name: "Tam-tams du Mont-Royal",
      description: "Chaque dimanche d'été, percussions et danse au pied du monument.",
      category: "evenement",
      emoji: "🥁",
      cost: 0,
      hours: 2,
      moments: ["afternoon"],
      tags: ["festivals", "fete"],
    },
    {
      id: "bota-bota",
      name: "Bota Bota, spa flottant",
      description: "Bains nordiques sur un bateau amarré dans le Vieux-Port.",
      category: "detente",
      emoji: "♨️",
      cost: 60,
      hours: 3,
      area: "Vieux-Montréal",
      moments: ["afternoon"],
      tags: ["detente", "romantique"],
    },
    {
      id: "grande-roue",
      name: "Grande roue du Vieux-Port",
      description: "Vue sur le fleuve et la ville illuminée.",
      category: "panorama",
      emoji: "🎡",
      cost: 25,
      hours: 1,
      area: "Vieux-Montréal",
      moments: ["evening"],
      tags: ["romantique"],
    },
    {
      id: "festivals-mtl",
      name: "Soirée de festival",
      description:
        "Jazz, Juste pour rire, Francos : des concerts gratuits tout l'été au Quartier des spectacles.",
      category: "evenement",
      emoji: "🎶",
      cost: 0,
      hours: 3,
      area: "Centre-ville",
      moments: ["evening"],
      tags: ["festivals", "fete"],
      highlight: "Un festival en plein air",
    },
    {
      id: "saint-laurent",
      name: "Soirée boulevard Saint-Laurent",
      description: "Bars, microbrasseries et clubs de la « Main ».",
      category: "nightlife",
      emoji: "🍻",
      cost: 25,
      hours: 3,
      area: "Plateau Mont-Royal",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit sur le boulevard Saint-Laurent",
      repeatable: true,
    },
    {
      id: "tremblant",
      name: "Excursion au Mont-Tremblant",
      description: "Village de montagne, randonnée ou luge l'été, ski l'hiver.",
      category: "excursion",
      emoji: "🏔️",
      cost: 60,
      hours: 10,
      moments: ["morning"],
      tags: ["nature", "aventure"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-st-viateur",
      name: "St-Viateur Bagel",
      description: "Bagels roulés à la main et cuits au feu de bois, 24 h/24.",
      cuisine: "Bagels",
      emoji: "🥯",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 5,
      area: "Mile End",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-la-banquise",
      name: "La Banquise",
      description: "Des dizaines de poutines différentes, ouvert jour et nuit.",
      cuisine: "Poutine",
      emoji: "🍟",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "Plateau Mont-Royal",
      meals: ["lunch", "dinner"],
      tags: ["fete"],
      real: true,
    },
    {
      id: "r-schwartzs",
      name: "Schwartz's",
      description: "Le smoked meat de Montréal depuis 1928, au comptoir.",
      cuisine: "Smoked meat",
      emoji: "🥪",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 18,
      area: "Plateau Mont-Royal",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-olive-gourmando",
      name: "Olive et Gourmando",
      description: "Café-boulangerie du Vieux-Montréal, sandwichs chauds et brunch.",
      cuisine: "Café & brunch",
      emoji: "🥐",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      area: "Vieux-Montréal",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-pied-de-cochon",
      name: "Au Pied de Cochon",
      description: "Cuisine québécoise généreuse et décadente, foie gras sur poutine.",
      cuisine: "Cuisine québécoise",
      emoji: "🐷",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 70,
      area: "Plateau Mont-Royal",
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
  ],
  geo: {
    center: p(45.5088, -73.5698),
    zoom: 13,
    neighborhoods: {
      "Vieux-Montréal": p(45.5045, -73.5563),
      "Plateau Mont-Royal": p(45.522, -73.58),
      "Mile End": p(45.523, -73.6),
      "Centre-ville": p(45.5085, -73.568),
    },
    places: {
      "vieux-montreal": p(45.5045, -73.5563),
      "mont-royal": p(45.5039, -73.5875),
      "jean-talon": p(45.5362, -73.6149),
      plateau: p(45.522, -73.58),
      "mile-end": p(45.523, -73.6),
      mbam: p(45.4985, -73.5795),
      "tam-tams": p(45.516, -73.588),
      "bota-bota": p(45.5013, -73.552),
      "grande-roue": p(45.508, -73.548),
      "festivals-mtl": p(45.5085, -73.568),
      "saint-laurent": p(45.514, -73.572),
      tremblant: p(46.21, -74.585),
      "r-st-viateur": p(45.5227, -73.601),
      "r-la-banquise": p(45.525, -73.575),
      "r-schwartzs": p(45.5163, -73.5776),
      "r-olive-gourmando": p(45.501, -73.5575),
      "r-pied-de-cochon": p(45.522, -73.573),
    },
  },
  source: "demo",
};
