import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const naples: DestinationProfile = {
  id: "naples",
  name: "Naples",
  country: "Italie",
  countryCode: "IT",
  iata: "NAP",
  tagline: "La vraie pizza, le Vésuve et la dolce vita sans filtre.",
  description:
    "Bouillonnante, généreuse et pas chère : ruelles du centre historique, pizzas à 5 €, Pompéi au pied du volcan et escapades à Capri ou sur la côte amalfitaine.",
  fallbackGradient: "from-sky-300 via-blue-500 to-amber-500",
  type: "mixte",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 28, standard: 60, confort: 120 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h 10",
        durationHours: 2.2,
        roundTripPerPerson: 150,
        details: "Vol direct, navette Alibus jusqu'au port et à la gare en 20 min",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Le centre historique se vit à pied (attention aux scooters !)" },
    { mode: "metro", description: "Métro, dont des stations-musées, et funiculaires vers le Vomero" },
    { mode: "ferry", description: "Ferries vers Capri, Ischia et la côte amalfitaine" },
    { mode: "bus", description: "Train Circumvesuviana vers Pompéi et Sorrente" },
  ],
  idealDays: { min: 3, max: 7 },
  bestMonths: [4, 5, 6, 9, 10],
  styles: { gastronomie: 3, culture: 3, ville: 3, plage: 2, nature: 2, aventure: 2, fete: 2, romantique: 2 },
  ambiances: { authentique: 3, economique: 3, sociale: 3, festive: 2, aventureuse: 2 },
  strengths: { gastronomie: 3, prix: 3, culture: 3, nature: 2, plages: 2, "vie-nocturne": 2 },
  neighborhoods: [
    {
      name: "Centro Storico",
      vibe: "ruelles, églises et pizzerias historiques",
      tiers: ["eco", "standard"],
      tags: ["culture", "gastronomie"],
    },
    {
      name: "Quartieri Spagnoli",
      vibe: "populaire, linge aux fenêtres et street art",
      tiers: ["eco", "standard"],
      tags: ["ville", "fete"],
    },
    {
      name: "Chiaia",
      vibe: "chic, près du front de mer",
      tiers: ["standard", "confort"],
      tags: ["romantique", "shopping"],
    },
    {
      name: "Vomero",
      vibe: "sur la colline, calme avec vue",
      tiers: ["standard", "confort"],
      tags: ["detente"],
    },
  ],
  activities: [
    {
      id: "spaccanapoli",
      name: "Spaccanapoli et la rue des crèches",
      description: "La rue qui coupe la vieille ville en deux, et les santons de San Gregorio Armeno.",
      category: "quartier",
      emoji: "🏘️",
      cost: 0,
      hours: 2,
      area: "Centro Storico",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "sansevero",
      name: "Chapelle Sansevero et le Christ voilé",
      description: "Une sculpture de marbre si fine qu'on croit voir le voile respirer.",
      category: "musee",
      emoji: "🗿",
      cost: 10,
      hours: 1,
      area: "Centro Storico",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
      highlight: "Le Christ voilé",
    },
    {
      id: "sottosuolo",
      name: "Naples souterraine",
      description: "Citernes grecques et abris de guerre à 40 mètres sous la ville.",
      category: "monument",
      emoji: "🕯️",
      cost: 15,
      hours: 1.5,
      area: "Centro Storico",
      moments: ["morning", "afternoon"],
      tags: ["culture", "aventure"],
    },
    {
      id: "mann",
      name: "Musée archéologique national",
      description: "Les trésors de Pompéi et d'Herculanum : mosaïques, fresques et statues.",
      category: "musee",
      emoji: "🏺",
      cost: 22,
      hours: 2.5,
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "quartieri",
      name: "Quartieri Spagnoli et la fresque de Maradona",
      description: "Le quartier le plus vivant, autel géant dédié au dieu du foot.",
      category: "quartier",
      emoji: "⚽",
      cost: 0,
      hours: 1.5,
      area: "Quartieri Spagnoli",
      moments: ["afternoon"],
      tags: ["ville"],
    },
    {
      id: "street-food-napoli",
      name: "Street food napolitaine",
      description: "Pizza fritta, cuoppo de fritures et sfogliatella encore chaude.",
      category: "food",
      emoji: "🍕",
      cost: 12,
      hours: 1.5,
      area: "Centro Storico",
      moments: ["morning", "afternoon"],
      tags: ["gastronomie"],
      repeatable: true,
    },
    {
      id: "sant-elmo",
      name: "Castel Sant'Elmo et vue sur la baie",
      description: "Funiculaire jusqu'au Vomero pour la vue sur la ville et le Vésuve.",
      category: "panorama",
      emoji: "🏰",
      cost: 5,
      hours: 1.5,
      area: "Vomero",
      moments: ["morning", "afternoon"],
      tags: ["ville", "romantique"],
    },
    {
      id: "lungomare",
      name: "Coucher de soleil sur le front de mer",
      description: "Du Castel dell'Ovo à Mergellina, le Vésuve rosit en face.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      area: "Chiaia",
      moments: ["evening"],
      tags: ["romantique", "detente"],
      highlight: "Coucher de soleil sur la baie de Naples",
      repeatable: true,
    },
    {
      id: "marechiaro",
      name: "Baignade à Marechiaro",
      description: "Criques et rochers de Posillipo où les Napolitains se baignent l'été.",
      category: "plage",
      emoji: "🏊",
      cost: 0,
      hours: 3,
      moments: ["afternoon"],
      tags: ["plage", "detente"],
    },
    {
      id: "bellini",
      name: "Soirée piazza Bellini",
      description: "Place étudiante au-dessus de ruines grecques, bars et spritz à petit prix.",
      category: "nightlife",
      emoji: "🍹",
      cost: 15,
      hours: 3,
      area: "Centro Storico",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit sur la piazza Bellini",
      repeatable: true,
    },
    {
      id: "vesuve",
      name: "Randonnée au sommet du Vésuve",
      description: "Montée au bord du cratère du volcan le plus célèbre d'Europe.",
      category: "aventure",
      emoji: "🌋",
      cost: 30,
      hours: 5,
      moments: ["morning"],
      tags: ["aventure", "nature"],
      highlight: "Le cratère du Vésuve",
    },
    {
      id: "pompei",
      name: "Excursion à Pompéi",
      description: "La ville romaine figée par l'éruption de 79, rues et maisons intactes.",
      category: "excursion",
      emoji: "🏛️",
      cost: 25,
      hours: 7,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Les ruines de Pompéi",
      fullDay: true,
    },
    {
      id: "capri",
      name: "Excursion à Capri",
      description: "Ferry, Faraglioni, jardins d'Auguste et eau turquoise.",
      category: "excursion",
      emoji: "⛵",
      cost: 70,
      hours: 9,
      moments: ["morning"],
      tags: ["plage", "romantique", "nature"],
      fullDay: true,
    },
    {
      id: "amalfi",
      name: "Journée sur la côte amalfitaine",
      description: "Positano et Amalfi, villages en cascade au-dessus de la mer.",
      category: "excursion",
      emoji: "🍋",
      cost: 45,
      hours: 10,
      moments: ["morning"],
      tags: ["romantique", "nature", "plage"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-da-michele",
      name: "L'Antica Pizzeria da Michele",
      description: "Deux pizzas seulement (margherita, marinara) depuis 1870. Prends un ticket.",
      cuisine: "Pizza napolitaine",
      emoji: "🍕",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 10,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-sorbillo",
      name: "Gino e Toto Sorbillo",
      description: "La pizzeria star de la via dei Tribunali, pâte ultra-légère.",
      cuisine: "Pizza napolitaine",
      emoji: "🍕",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Centro Storico",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-starita",
      name: "Pizzeria Starita",
      description: "Pizzeria de quartier à Materdei, réputée pour sa pizza frite.",
      cuisine: "Pizza napolitaine",
      emoji: "🍕",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      meals: ["dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-nennella",
      name: "Trattoria Da Nennella",
      description: "Ambiance survoltée, serveurs qui chantent et plats du jour pas chers.",
      cuisine: "Cuisine napolitaine",
      emoji: "🎶",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 20,
      area: "Quartieri Spagnoli",
      meals: ["lunch", "dinner"],
      tags: ["fete"],
      real: true,
    },
    {
      id: "r-tandem",
      name: "Tandem",
      description: "Petite adresse du centre dédiée au ragù napolitain, mijoté des heures.",
      cuisine: "Cuisine napolitaine",
      emoji: "🍝",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 22,
      area: "Centro Storico",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-palazzo-petrucci",
      name: "Palazzo Petrucci",
      description: "Table étoilée les pieds dans l'eau à Posillipo, vue sur le Vésuve.",
      cuisine: "Cuisine napolitaine d'auteur",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 90,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(40.8467, 14.2522),
    zoom: 13,
    neighborhoods: {
      "Centro Storico": p(40.8497, 14.2555),
      "Quartieri Spagnoli": p(40.8418, 14.2459),
      Chiaia: p(40.835, 14.2395),
      Vomero: p(40.8455, 14.2295),
    },
    places: {
      spaccanapoli: p(40.8483, 14.2553),
      sansevero: p(40.8493, 14.255),
      sottosuolo: p(40.8506, 14.257),
      mann: p(40.8535, 14.2505),
      quartieri: p(40.8418, 14.2459),
      "street-food-napoli": p(40.8485, 14.256),
      "sant-elmo": p(40.8438, 14.2394),
      lungomare: p(40.8282, 14.2475),
      marechiaro: p(40.795, 14.191),
      bellini: p(40.849, 14.2515),
      vesuve: p(40.821, 14.426),
      pompei: p(40.749, 14.4989),
      capri: p(40.55, 14.24),
      amalfi: p(40.628, 14.484),
      "r-da-michele": p(40.8497, 14.2632),
      "r-sorbillo": p(40.8505, 14.2555),
      "r-starita": p(40.8566, 14.2466),
      "r-nennella": p(40.841, 14.247),
      "r-tandem": p(40.8472, 14.2555),
      "r-palazzo-petrucci": p(40.8135, 14.217),
    },
  },
  source: "demo",
};
