import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const new_york: DestinationProfile = {
  id: "new-york",
  name: "New York",
  country: "États-Unis",
  countryCode: "US",
  iata: "NYC",
  tagline: "La ville qui ne dort jamais, en vrai.",
  description:
    "Gratte-ciel, Central Park, musées géants, pizza à la part, jazz à Greenwich Village et bars de Brooklyn : un film grandeur nature. Chère, mais on peut s'en sortir malin.",
  fallbackGradient: "from-slate-300 via-sky-600 to-indigo-900",
  type: "ville",
  costLevel: 4,
  costs: {
    accommodationPerNight: { eco: 55, standard: 120, confort: 230 },
    localTransportPerDay: 8,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "8 h 30",
        durationHours: 8.5,
        roundTripPerPerson: 550,
        details:
          "Vol direct vers JFK ou Newark, AirTrain + métro jusqu'à Manhattan. Formulaire ESTA obligatoire",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Métro 24 h/24, paiement sans contact au portique" },
    { mode: "marche", description: "Manhattan se découvre à pied, bloc par bloc" },
    { mode: "velo", description: "Vélos Citi Bike pour Central Park et les quais" },
    { mode: "ferry", description: "Ferries NYC et Staten Island (gratuit) pour la vue" },
  ],
  idealDays: { min: 5, max: 9 },
  bestMonths: [4, 5, 6, 9, 10, 12],
  styles: { ville: 3, culture: 3, shopping: 3, fete: 3, gastronomie: 3, festivals: 2, romantique: 2 },
  ambiances: { festive: 3, sociale: 3, luxueuse: 2, aventureuse: 2 },
  strengths: { culture: 3, "vie-nocturne": 3, gastronomie: 3, activites: 3, securite: 2 },
  neighborhoods: [
    {
      name: "Midtown",
      vibe: "au pied des gratte-ciel, pratique pour tout",
      tiers: ["standard", "confort"],
      tags: ["ville", "shopping"],
    },
    {
      name: "Lower East Side",
      vibe: "bars, street art et restos",
      tiers: ["standard", "confort"],
      tags: ["fete", "gastronomie"],
    },
    {
      name: "Williamsburg",
      vibe: "Brooklyn branché, friperies et rooftops",
      tiers: ["eco", "standard"],
      tags: ["fete", "shopping"],
    },
    {
      name: "Greenwich Village",
      vibe: "brownstones, jazz et petites rues",
      tiers: ["confort"],
      tags: ["romantique", "culture"],
    },
  ],
  activities: [
    {
      id: "central-park",
      name: "Central Park à vélo",
      description: "Bethesda Terrace, Strawberry Fields et le lac, loin du bruit.",
      category: "nature",
      emoji: "🌳",
      cost: 15,
      hours: 2.5,
      moments: ["morning", "afternoon"],
      tags: ["nature", "detente"],
      highlight: "Central Park à vélo",
    },
    {
      id: "met",
      name: "The Met",
      description: "Un temple égyptien, Van Gogh et 5 000 ans d'art sous un même toit.",
      category: "musee",
      emoji: "🏛️",
      cost: 30,
      hours: 3,
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "moma",
      name: "MoMA",
      description: "La Nuit étoilée, Warhol et Pollock, au cœur de Midtown.",
      category: "musee",
      emoji: "🎨",
      cost: 30,
      hours: 2.5,
      area: "Midtown",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "brooklyn-bridge",
      name: "Pont de Brooklyn et DUMBO",
      description: "Traversée à pied au petit matin, puis la vue carte postale depuis DUMBO.",
      category: "panorama",
      emoji: "🌉",
      cost: 0,
      hours: 2,
      moments: ["morning"],
      tags: ["ville", "romantique"],
      highlight: "Traversée du pont de Brooklyn",
    },
    {
      id: "memorial-911",
      name: "Mémorial du 11-Septembre",
      description: "Deux bassins là où se dressaient les tours, émouvant et sobre.",
      category: "monument",
      emoji: "🕊️",
      cost: 0,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "staten-ferry",
      name: "Ferry de Staten Island",
      description: "Gratuit, et la meilleure vue sur la statue de la Liberté et Manhattan.",
      category: "panorama",
      emoji: "🗽",
      cost: 0,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["ville"],
    },
    {
      id: "high-line",
      name: "High Line et Chelsea Market",
      description: "Promenade sur une ancienne voie ferrée, puis halle gourmande.",
      category: "quartier",
      emoji: "🚶",
      cost: 0,
      hours: 2,
      moments: ["afternoon"],
      tags: ["ville", "gastronomie"],
    },
    {
      id: "williamsburg-shop",
      name: "Friperies et cafés de Williamsburg",
      description: "Vintage, disquaires et murs peints de Brooklyn.",
      category: "shopping",
      emoji: "🛍️",
      cost: 0,
      hours: 2.5,
      area: "Williamsburg",
      moments: ["afternoon"],
      tags: ["shopping"],
    },
    {
      id: "coney-island",
      name: "Coney Island",
      description: "Plage, grande roue et hot-dogs Nathan's au bout du métro.",
      category: "plage",
      emoji: "🎢",
      cost: 3,
      hours: 3,
      moments: ["afternoon"],
      tags: ["plage", "fete"],
    },
    {
      id: "top-rock",
      name: "Top of the Rock au coucher du soleil",
      description: "L'Empire State Building en face, Central Park derrière.",
      category: "panorama",
      emoji: "🌆",
      cost: 45,
      hours: 1.5,
      area: "Midtown",
      moments: ["evening"],
      tags: ["romantique", "ville"],
      highlight: "Manhattan au coucher du soleil",
    },
    {
      id: "broadway",
      name: "Comédie musicale à Broadway",
      description: "Billets à prix réduit le jour même au guichet TKTS de Times Square.",
      category: "evenement",
      emoji: "🎭",
      cost: 90,
      hours: 3,
      area: "Midtown",
      moments: ["evening"],
      tags: ["culture", "festivals"],
    },
    {
      id: "jazz-club",
      name: "Club de jazz à Greenwich Village",
      description: "Petites salles mythiques où l'on écoute à deux mètres des musiciens.",
      category: "evenement",
      emoji: "🎷",
      cost: 30,
      hours: 2,
      area: "Greenwich Village",
      moments: ["evening"],
      tags: ["culture", "romantique"],
    },
    {
      id: "les-bars",
      name: "Bars du Lower East Side",
      description: "Speakeasies cachés, rooftops et bars à cocktails.",
      category: "nightlife",
      emoji: "🍸",
      cost: 30,
      hours: 3,
      area: "Lower East Side",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit dans le Lower East Side",
      repeatable: true,
    },
  ],
  restaurants: [
    {
      id: "r-joes-pizza",
      name: "Joe's Pizza",
      description: "La part de pizza new-yorkaise par excellence, depuis 1975.",
      cuisine: "Pizza à la part",
      emoji: "🍕",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      area: "Greenwich Village",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-los-tacos",
      name: "Los Tacos No. 1",
      description: "Tacos al pastor dans le Chelsea Market, parmi les meilleurs de la ville.",
      cuisine: "Tacos",
      emoji: "🌮",
      kind: "street-food",
      isLocal: false,
      priceLevel: 1,
      cost: 12,
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-xian",
      name: "Xi'an Famous Foods",
      description: "Nouilles tirées à la main et agneau au cumin, épicé à souhait.",
      cuisine: "Cuisine chinoise",
      emoji: "🍜",
      kind: "local",
      isLocal: false,
      priceLevel: 1,
      cost: 13,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-katz",
      name: "Katz's Delicatessen",
      description: "Le sandwich au pastrami géant depuis 1888 (et la scène de Quand Harry rencontre Sally).",
      cuisine: "Deli new-yorkais",
      emoji: "🥪",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      area: "Lower East Side",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-peter-luger",
      name: "Peter Luger Steak House",
      description: "Steakhouse légendaire de Brooklyn depuis 1887.",
      cuisine: "Steakhouse",
      emoji: "🥩",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 100,
      area: "Williamsburg",
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
  ],
  geo: {
    center: p(40.7359, -73.9911),
    zoom: 12,
    neighborhoods: {
      Midtown: p(40.7549, -73.984),
      "Lower East Side": p(40.715, -73.9843),
      Williamsburg: p(40.7081, -73.9571),
      "Greenwich Village": p(40.7336, -74.0027),
    },
    places: {
      "central-park": p(40.7829, -73.9654),
      met: p(40.7794, -73.9632),
      moma: p(40.7614, -73.9776),
      "brooklyn-bridge": p(40.7061, -73.9969),
      "memorial-911": p(40.7115, -74.0134),
      "staten-ferry": p(40.701, -74.013),
      "high-line": p(40.748, -74.0048),
      "williamsburg-shop": p(40.714, -73.961),
      "coney-island": p(40.5749, -73.9859),
      "top-rock": p(40.7593, -73.9794),
      broadway: p(40.758, -73.9855),
      "jazz-club": p(40.731, -74.001),
      "les-bars": p(40.72, -73.988),
      "r-joes-pizza": p(40.7306, -74.0026),
      "r-los-tacos": p(40.7424, -74.006),
      "r-xian": p(40.7153, -73.997),
      "r-katz": p(40.7223, -73.9874),
      "r-peter-luger": p(40.7099, -73.9623),
    },
  },
  source: "demo",
};
