import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const nice: DestinationProfile = {
  id: "nice",
  name: "Nice",
  country: "France",
  countryCode: "FR",
  iata: "NCE",
  tagline: "La Baie des Anges, la socca et la Riviera à portée de train.",
  description:
    "Soleil 300 jours par an : Promenade des Anglais, ruelles colorées du Vieux-Nice, baignade dans une eau turquoise et escapades vers Èze, Monaco ou Villefranche.",
  fallbackGradient: "from-sky-300 via-cyan-500 to-amber-400",
  type: "balneaire",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 35, standard: 75, confort: 150 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "train",
        durationLabel: "5 h 45",
        durationHours: 5.75,
        roundTripPerPerson: 110,
        details: "TGV direct Paris-Gare de Lyon – Nice-Ville, au centre-ville",
      },
      {
        mode: "avion",
        durationLabel: "1 h 25",
        durationHours: 1.4,
        roundTripPerPerson: 130,
        details: "Vol direct, tram jusqu'au centre en 25 min",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Vieux-Nice, port et Promenade se font à pied" },
    { mode: "tram", description: "Tram depuis l'aéroport et à travers la ville" },
    { mode: "bus", description: "Bus à petit prix vers Villefranche, Èze et Monaco" },
    { mode: "velo", description: "Vélos en libre-service le long de la mer" },
  ],
  idealDays: { min: 3, max: 6 },
  bestMonths: [5, 6, 7, 8, 9, 10],
  styles: { plage: 3, detente: 3, romantique: 3, ville: 2, gastronomie: 2, culture: 2, nature: 2, fete: 2 },
  ambiances: { romantique: 3, calme: 2, sociale: 2, luxueuse: 2, festive: 2 },
  strengths: { plages: 3, securite: 3, rapidite: 3, gastronomie: 2, nature: 2, "vie-nocturne": 2 },
  neighborhoods: [
    {
      name: "Vieux-Nice",
      vibe: "ruelles ocre, marchés et bars",
      tiers: ["eco", "standard"],
      tags: ["culture", "fete"],
    },
    {
      name: "Port Lympia",
      vibe: "façades colorées et terrasses",
      tiers: ["standard", "confort"],
      tags: ["romantique", "gastronomie"],
    },
    {
      name: "Carré d'Or",
      vibe: "chic, à deux pas de la Promenade",
      tiers: ["confort"],
      tags: ["plage", "shopping"],
    },
    {
      name: "Libération",
      vibe: "vie locale et marché, moins cher",
      tiers: ["eco", "standard"],
      tags: ["gastronomie"],
    },
  ],
  activities: [
    {
      id: "vieux-nice",
      name: "Vieux-Nice et marché du cours Saleya",
      description: "Fleurs, fruits et épices le matin, ruelles baroques ensuite.",
      category: "quartier",
      emoji: "🌸",
      cost: 0,
      hours: 2,
      area: "Vieux-Nice",
      moments: ["morning"],
      tags: ["culture", "gastronomie"],
    },
    {
      id: "colline-chateau",
      name: "Colline du Château",
      description: "La vue carte postale sur la Baie des Anges et le port, cascade en bonus.",
      category: "panorama",
      emoji: "🏞️",
      cost: 0,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["nature", "romantique"],
      highlight: "La Baie des Anges depuis la colline du Château",
    },
    {
      id: "promenade",
      name: "Promenade des Anglais à vélo",
      description: "7 km de front de mer, chaises bleues et palmiers.",
      category: "quartier",
      emoji: "🚲",
      cost: 5,
      hours: 2,
      area: "Carré d'Or",
      moments: ["morning", "afternoon"],
      tags: ["ville", "detente"],
    },
    {
      id: "street-food-nice",
      name: "Street food niçoise",
      description: "Socca, pan bagnat, pissaladière et petits farcis : le goût de Nice.",
      category: "food",
      emoji: "🫓",
      cost: 15,
      hours: 1.5,
      area: "Vieux-Nice",
      moments: ["morning", "afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "matisse",
      name: "Musée Matisse",
      description: "Dans une villa rouge de Cimiez, au milieu des oliviers.",
      category: "musee",
      emoji: "🎨",
      cost: 12,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "chagall",
      name: "Musée Marc Chagall",
      description: "Les grandes toiles bleues du Message biblique et un joli jardin.",
      category: "musee",
      emoji: "🖼️",
      cost: 10,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "plage-nice",
      name: "Baignade à la plage",
      description: "Galets, eau cristalline et transat face à la Baie des Anges.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 3,
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      highlight: "Baignade dans la Baie des Anges",
      repeatable: true,
    },
    {
      id: "coco-beach",
      name: "Rochers de Coco Beach",
      description: "Plongeons depuis les rochers, à l'est du port, loin de la foule.",
      category: "plage",
      emoji: "🤿",
      cost: 0,
      hours: 2.5,
      moments: ["afternoon"],
      tags: ["plage", "aventure"],
    },
    {
      id: "kayak-villefranche",
      name: "Kayak dans la rade de Villefranche",
      description: "Une des plus belles baies de la Riviera, eau calme et turquoise.",
      category: "aventure",
      emoji: "🛶",
      cost: 30,
      hours: 2,
      moments: ["morning"],
      tags: ["aventure", "plage"],
    },
    {
      id: "cap-ferrat",
      name: "Tour du cap Ferrat à pied",
      description: "Sentier du littoral entre pins, villas et criques.",
      category: "nature",
      emoji: "🥾",
      cost: 0,
      hours: 3,
      moments: ["morning"],
      tags: ["nature", "detente"],
    },
    {
      id: "rauba-capeu",
      name: "Coucher de soleil au Rauba-Capeù",
      description: "Le monument aux morts illuminé, la mer qui rougit et toute la Promenade.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique"],
      highlight: "Coucher de soleil sur la Promenade",
      repeatable: true,
    },
    {
      id: "bars-vieux-nice",
      name: "Soirée dans les bars du Vieux-Nice",
      description: "Pubs, bars à vin et places animées jusque tard.",
      category: "nightlife",
      emoji: "🍹",
      cost: 20,
      hours: 3,
      area: "Vieux-Nice",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit dans le Vieux-Nice",
      repeatable: true,
    },
    {
      id: "port-apero",
      name: "Apéro sur le port Lympia",
      description: "Rosé en terrasse face aux pointus colorés.",
      category: "nightlife",
      emoji: "🍷",
      cost: 15,
      hours: 2,
      area: "Port Lympia",
      moments: ["evening"],
      tags: ["fete", "romantique"],
    },
    {
      id: "eze-monaco",
      name: "Èze village et Monaco",
      description: "Village perché au-dessus de la mer, puis le rocher de Monaco.",
      category: "excursion",
      emoji: "🏰",
      cost: 20,
      hours: 8,
      moments: ["morning"],
      tags: ["culture", "romantique"],
      highlight: "Le village perché d'Èze",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-chez-pipo",
      name: "Chez Pipo",
      description: "La socca (galette de pois chiches) cuite au feu de bois depuis 1923.",
      cuisine: "Socca",
      emoji: "🫓",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      area: "Port Lympia",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-lou-pilha-leva",
      name: "Lou Pilha Leva",
      description: "Socca, pissaladière et beignets à emporter au cœur du Vieux-Nice.",
      cuisine: "Street food niçoise",
      emoji: "🥧",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 10,
      area: "Vieux-Nice",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-chez-palmyre",
      name: "Chez Palmyre",
      description: "Minuscule salle, menu niçois du jour à petit prix. Réserve.",
      cuisine: "Cuisine niçoise",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 20,
      area: "Vieux-Nice",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-la-merenda",
      name: "La Merenda",
      description: "Tabourets, ardoise et vraie cuisine niçoise : pâtes au pistou, daube.",
      cuisine: "Cuisine niçoise",
      emoji: "🍝",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 40,
      area: "Vieux-Nice",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-le-plongeoir",
      name: "Le Plongeoir",
      description: "Restaurant posé sur un rocher au-dessus de la mer, face au soleil couchant.",
      cuisine: "Cuisine méditerranéenne",
      emoji: "🌊",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 65,
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      real: true,
    },
  ],
  geo: {
    center: p(43.6985, 7.2715),
    zoom: 14,
    neighborhoods: {
      "Vieux-Nice": p(43.6965, 7.2765),
      "Port Lympia": p(43.6995, 7.2855),
      "Carré d'Or": p(43.6965, 7.2625),
      Libération: p(43.7145, 7.2625),
    },
    places: {
      "vieux-nice": p(43.6955, 7.275),
      "colline-chateau": p(43.695, 7.281),
      promenade: p(43.695, 7.265),
      "street-food-nice": p(43.6975, 7.2765),
      matisse: p(43.7194, 7.2757),
      chagall: p(43.7093, 7.2694),
      "plage-nice": p(43.6945, 7.262),
      "coco-beach": p(43.692, 7.295),
      "kayak-villefranche": p(43.703, 7.311),
      "cap-ferrat": p(43.684, 7.332),
      "rauba-capeu": p(43.6935, 7.2825),
      "bars-vieux-nice": p(43.6965, 7.2765),
      "port-apero": p(43.6985, 7.2855),
      "eze-monaco": p(43.728, 7.362),
      "r-chez-pipo": p(43.7023, 7.2848),
      "r-lou-pilha-leva": p(43.6977, 7.276),
      "r-chez-palmyre": p(43.6975, 7.2785),
      "r-la-merenda": p(43.696, 7.274),
      "r-le-plongeoir": p(43.6918, 7.2926),
    },
  },
  source: "demo",
};
