import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const palerme: DestinationProfile = {
  id: "palerme",
  name: "Palerme",
  country: "Italie",
  countryCode: "IT",
  iata: "PMO",
  tagline: "Marchés bruyants, mosaïques dorées et street food sicilienne.",
  description:
    "La Sicile brute et généreuse : marchés de Ballarò, églises arabo-normandes couvertes d'or, arancine à chaque coin de rue, plage de Mondello et villages côtiers en excursion.",
  fallbackGradient: "from-amber-300 via-rose-500 to-teal-700",
  type: "mixte",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 25, standard: 55, confort: 110 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h 30",
        durationHours: 2.5,
        roundTripPerPerson: 160,
        details: "Vol direct, navette ou train jusqu'au centre en 45 min",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Le centre historique se découvre à pied" },
    { mode: "bus", description: "Bus pour Mondello et Monreale" },
    { mode: "taxi", description: "Taxis et VTC pour rentrer tard" },
  ],
  idealDays: { min: 3, max: 6 },
  bestMonths: [4, 5, 6, 9, 10],
  styles: { gastronomie: 3, culture: 3, plage: 2, ville: 2, fete: 2, nature: 2 },
  ambiances: { authentique: 3, economique: 3, sociale: 2, festive: 2 },
  strengths: { gastronomie: 3, culture: 3, prix: 3, plages: 2 },
  neighborhoods: [
    {
      name: "Kalsa",
      vibe: "ancien quartier arabe, bars et palais",
      tiers: ["eco", "standard"],
      tags: ["culture", "fete"],
    },
    {
      name: "Centro storico",
      vibe: "autour des Quattro Canti",
      tiers: ["standard", "confort"],
      tags: ["culture"],
    },
    {
      name: "Mondello",
      vibe: "station balnéaire à 20 min",
      tiers: ["standard", "confort"],
      tags: ["plage", "detente"],
    },
  ],
  activities: [
    {
      id: "ballaro",
      name: "Marché de Ballarò",
      description: "Cris des marchands, espadons entiers et fruits siciliens.",
      category: "food",
      emoji: "🍋",
      cost: 10,
      hours: 1.5,
      moments: ["morning"],
      tags: ["gastronomie", "culture"],
      highlight: "Le marché de Ballarò",
    },
    {
      id: "palatine",
      name: "Chapelle palatine",
      description: "Mosaïques dorées et plafond arabe, un bijou arabo-normand.",
      category: "monument",
      emoji: "✨",
      cost: 19,
      hours: 1.5,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Les mosaïques de la chapelle palatine",
    },
    {
      id: "cathedrale-palerme",
      name: "Cathédrale et ses toits",
      description: "Mélange de styles fascinant, et vue depuis les toits.",
      category: "monument",
      emoji: "⛪",
      cost: 10,
      hours: 1.5,
      area: "Centro storico",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "quattro-canti",
      name: "Quattro Canti et fontaine Pretoria",
      description: "Le carrefour baroque du centre et la « fontaine de la honte ».",
      category: "quartier",
      emoji: "⛲",
      cost: 0,
      hours: 1,
      area: "Centro storico",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "teatro-massimo",
      name: "Teatro Massimo",
      description: "Le plus grand opéra d'Italie, décor du Parrain III.",
      category: "monument",
      emoji: "🎭",
      cost: 12,
      hours: 1,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "capucins",
      name: "Catacombes des Capucins",
      description: "Des milliers de momies habillées, étrange et saisissant.",
      category: "musee",
      emoji: "💀",
      cost: 5,
      hours: 1,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "street-food-palerme",
      name: "Tournée street food",
      description: "Arancine, panelle, sfincione et pane ca' meusa.",
      category: "food",
      emoji: "🍙",
      cost: 12,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["gastronomie"],
      repeatable: true,
    },
    {
      id: "mondello",
      name: "Plage de Mondello",
      description: "Sable blanc et eau turquoise entre deux montagnes.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 4,
      area: "Mondello",
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      highlight: "Baignade à Mondello",
      repeatable: true,
    },
    {
      id: "pellegrino",
      name: "Coucher de soleil au Monte Pellegrino",
      description: "La montagne qui domine la baie, vue sur toute la ville.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 2,
      moments: ["evening"],
      tags: ["romantique", "nature"],
    },
    {
      id: "vucciria",
      name: "Soirée à la Vucciria",
      description: "Le vieux marché devient bar à ciel ouvert le soir.",
      category: "nightlife",
      emoji: "🍷",
      cost: 15,
      hours: 3,
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit à la Vucciria",
      repeatable: true,
    },
    {
      id: "monreale",
      name: "Cathédrale de Monreale",
      description: "6 400 m² de mosaïques d'or, sur une colline au-dessus de Palerme.",
      category: "monument",
      emoji: "🕍",
      cost: 5,
      hours: 3,
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "cefalu",
      name: "Excursion à Cefalù",
      description: "Village de pêcheurs, plage et cathédrale normande, à 1 h de train.",
      category: "excursion",
      emoji: "🏘️",
      cost: 15,
      hours: 8,
      moments: ["morning"],
      tags: ["plage", "culture", "romantique"],
      fullDay: true,
    },
    {
      id: "zingaro",
      name: "Réserve naturelle du Zingaro",
      description: "Sentier côtier et criques sauvages, les plus belles eaux de Sicile.",
      category: "excursion",
      emoji: "🥾",
      cost: 5,
      hours: 9,
      moments: ["morning"],
      tags: ["nature", "plage", "aventure"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-ke-palle",
      name: "Ke Palle",
      description: "Arancine de toutes les saveurs, à emporter sur la via Maqueda.",
      cuisine: "Arancine",
      emoji: "🍙",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 5,
      area: "Centro storico",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-antica-focacceria",
      name: "Antica Focacceria San Francesco",
      description: "Institution de 1834 : pane ca' meusa, panelle et caponata.",
      cuisine: "Cuisine sicilienne",
      emoji: "🥪",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "Kalsa",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-maestro-brodo",
      name: "Trattoria Il Maestro del Brodo",
      description: "Trattoria familiale près de la Vucciria, bouillon et poissons du jour.",
      cuisine: "Cuisine sicilienne",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-osteria-vespri",
      name: "Osteria dei Vespri",
      description: "Cuisine sicilienne raffinée dans un palais du centre historique.",
      cuisine: "Cuisine sicilienne d'auteur",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 50,
      area: "Centro storico",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(38.1157, 13.3615),
    zoom: 13,
    neighborhoods: {
      Kalsa: p(38.117, 13.368),
      "Centro storico": p(38.1157, 13.3614),
      Mondello: p(38.2, 13.33),
    },
    places: {
      ballaro: p(38.112, 13.36),
      palatine: p(38.1109, 13.3534),
      "cathedrale-palerme": p(38.1144, 13.3561),
      "quattro-canti": p(38.1157, 13.3614),
      "teatro-massimo": p(38.1204, 13.3572),
      capucins: p(38.1119, 13.3399),
      "street-food-palerme": p(38.1165, 13.3615),
      mondello: p(38.2, 13.33),
      pellegrino: p(38.16, 13.35),
      vucciria: p(38.1185, 13.3635),
      monreale: p(38.0816, 13.2923),
      cefalu: p(38.039, 14.022),
      zingaro: p(38.11, 12.77),
      "r-ke-palle": p(38.1175, 13.361),
      "r-antica-focacceria": p(38.1177, 13.3651),
      "r-maestro-brodo": p(38.1185, 13.3615),
      "r-osteria-vespri": p(38.116, 13.357),
    },
  },
  source: "demo",
};
