import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const porto: DestinationProfile = {
  id: "porto",
  name: "Porto",
  country: "Portugal",
  countryCode: "PT",
  iata: "OPO",
  tagline: "Azulejos, caves de porto et couchers de soleil sur le Douro.",
  description:
    "Une ville à flanc de colline, authentique et abordable : ruelles colorées de la Ribeira, francesinha, caves de porto et plages atlantiques en tram.",
  fallbackGradient: "from-sky-400 via-blue-600 to-indigo-900",
  type: "mixte",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 22, standard: 50, confort: 100 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h 05",
        durationHours: 2.1,
        roundTripPerPerson: 140,
        details: "Vol direct, métro jusqu'au centre en 30 min",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Le centre se fait à pied (prévois de bonnes chaussures : ça monte)" },
    { mode: "metro", description: "Métro léger depuis l'aéroport et vers la plage de Matosinhos" },
    { mode: "tram", description: "Le tram historique n° 1 longe le Douro jusqu'à l'océan" },
    { mode: "taxi", description: "Taxis et VTC bon marché pour rentrer le soir" },
  ],
  idealDays: { min: 3, max: 5 },
  bestMonths: [4, 5, 6, 7, 8, 9, 10],
  styles: { ville: 3, gastronomie: 3, culture: 2, romantique: 3, plage: 1, fete: 2, detente: 2, nature: 1 },
  ambiances: { authentique: 3, romantique: 3, economique: 3, sociale: 2, festive: 2, calme: 2 },
  strengths: { prix: 3, gastronomie: 3, securite: 3, culture: 2, plages: 1, "vie-nocturne": 2, rapidite: 3 },
  neighborhoods: [
    {
      name: "Ribeira",
      vibe: "le cœur historique au bord du Douro",
      tiers: ["standard", "confort"],
      tags: ["romantique", "culture"],
    },
    {
      name: "Baixa",
      vibe: "central, commerçant et animé le soir",
      tiers: ["eco", "standard"],
      tags: ["ville", "fete"],
    },
    {
      name: "Cedofeita",
      vibe: "galeries, cafés et friperies",
      tiers: ["eco", "standard"],
      tags: ["shopping", "ville"],
    },
    {
      name: "Foz do Douro",
      vibe: "bord de mer calme et chic",
      tiers: ["confort"],
      tags: ["detente", "plage"],
    },
  ],
  activities: [
    {
      id: "ribeira",
      name: "Balade dans la Ribeira et sur le pont Dom-Luís I",
      description: "Façades colorées, quais du Douro et traversée du pont métallique à deux étages.",
      category: "quartier",
      emoji: "🌉",
      cost: 0,
      hours: 2.5,
      area: "Ribeira",
      moments: ["morning", "afternoon"],
      tags: ["ville", "romantique", "culture"],
      highlight: "Traversée du pont Dom-Luís I",
    },
    {
      id: "sao-bento",
      name: "Gare de São Bento et ses azulejos",
      description: "Le hall de gare couvert de 20 000 carreaux bleus racontant l'histoire du Portugal.",
      category: "monument",
      emoji: "🚉",
      cost: 0,
      hours: 0.5,
      area: "Baixa",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "lello",
      name: "Librairie Lello",
      description: "L'une des plus belles librairies du monde, escalier rouge et vitraux. Billet à réserver.",
      category: "monument",
      emoji: "📚",
      cost: 10,
      hours: 1,
      area: "Baixa",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "La librairie Lello",
    },
    {
      id: "clerigos",
      name: "Tour des Clercs",
      description: "240 marches pour la plus belle vue sur les toits de Porto.",
      category: "panorama",
      emoji: "🗼",
      cost: 10,
      hours: 1,
      area: "Baixa",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "bolhao",
      name: "Marché du Bolhão",
      description: "Le marché historique rénové : fruits, poissons, charcuteries et petits comptoirs.",
      category: "food",
      emoji: "🧺",
      cost: 10,
      hours: 1,
      area: "Baixa",
      moments: ["morning"],
      tags: ["gastronomie"],
    },
    {
      id: "caves",
      name: "Visite et dégustation dans une cave de porto",
      description: "Traversée vers Vila Nova de Gaia pour découvrir le vin de porto dans les chais.",
      category: "food",
      emoji: "🍷",
      cost: 20,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["gastronomie", "romantique"],
      highlight: "Dégustation de porto à Gaia",
    },
    {
      id: "croisiere-douro",
      name: "Croisière des six ponts",
      description: "Une heure en rabelo (bateau traditionnel) sous les ponts du Douro.",
      category: "panorama",
      emoji: "⛵",
      cost: 18,
      hours: 1,
      area: "Ribeira",
      moments: ["afternoon"],
      tags: ["romantique", "detente"],
    },
    {
      id: "serralves",
      name: "Fondation Serralves",
      description: "Musée d'art contemporain dans un grand parc, avec une villa Art déco rose.",
      category: "musee",
      emoji: "🖼️",
      cost: 25,
      hours: 3,
      moments: ["morning", "afternoon"],
      tags: ["culture", "nature", "detente"],
    },
    {
      id: "palacio-cristal",
      name: "Jardins du Palácio de Cristal",
      description: "Paons en liberté et belvédères sur le Douro, parfait pour souffler.",
      category: "detente",
      emoji: "🦚",
      cost: 0,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["detente", "nature", "romantique"],
    },
    {
      id: "foz",
      name: "Coucher de soleil à Foz do Douro",
      description: "Là où le fleuve rencontre l'océan : phare, jetée et vagues.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      area: "Foz do Douro",
      moments: ["evening"],
      tags: ["romantique", "detente"],
      highlight: "Coucher de soleil sur l'Atlantique",
      repeatable: true,
    },
    {
      id: "matosinhos",
      name: "Plage de Matosinhos",
      description: "Grande plage de sable accessible en métro, spots de surf et grillades de poissons.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 3.5,
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      repeatable: true,
    },
    {
      id: "surf-porto",
      name: "Cours de surf à Matosinhos",
      description: "Cours collectif pour débutants, planche et combinaison fournies.",
      category: "aventure",
      emoji: "🏄",
      cost: 35,
      hours: 2.5,
      moments: ["morning"],
      tags: ["aventure", "plage"],
    },
    {
      id: "galerias",
      name: "Soirée rue Galerias de Paris",
      description: "La rue des bars : on sort d'un bar pour entrer dans le suivant.",
      category: "nightlife",
      emoji: "🍹",
      cost: 20,
      hours: 3,
      area: "Baixa",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit dans les bars de la Baixa",
      repeatable: true,
    },
    {
      id: "douro-valley",
      name: "Excursion dans la vallée du Douro",
      description: "Vignobles en terrasses, dégustation et bateau au départ de Pinhão.",
      category: "excursion",
      emoji: "🍇",
      cost: 90,
      hours: 9,
      moments: ["morning"],
      tags: ["nature", "gastronomie", "romantique"],
      highlight: "Les vignobles du Douro",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-conga",
      name: "Conga",
      description: "La maison de la bifana épicée, servie à la chaîne depuis 1976.",
      cuisine: "Street food portugaise",
      emoji: "🥪",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      area: "Baixa",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-casa-guedes",
      name: "Casa Guedes",
      description: "Sandwich au porc rôti et fromage de brebis, sur la place dos Poveiros.",
      cuisine: "Street food portugaise",
      emoji: "🥖",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      area: "Baixa",
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-cafe-santiago",
      name: "Café Santiago",
      description: "L'une des meilleures francesinhas de la ville (sandwich gratiné à la sauce épicée).",
      cuisine: "Cuisine portugaise",
      emoji: "🍞",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "Baixa",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-majestic",
      name: "Majestic Café",
      description: "Café Art nouveau de 1921, miroirs et boiseries, pour une pause chic.",
      cuisine: "Grand café",
      emoji: "☕",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      area: "Baixa",
      meals: ["lunch"],
      tags: ["romantique"],
      real: true,
    },
    {
      id: "r-cantinho-avillez",
      name: "Cantinho do Avillez",
      description: "Le bistrot portuense du chef José Avillez, plats portugais revisités.",
      cuisine: "Cuisine portugaise moderne",
      emoji: "🍽️",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 35,
      area: "Ribeira",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
    {
      id: "r-dop",
      name: "DOP",
      description: "La table du chef Rui Paula dans un palais de la Ribeira, menus dégustation.",
      cuisine: "Cuisine d'auteur portugaise",
      emoji: "🍷",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 70,
      area: "Ribeira",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(41.1456, -8.6108),
    zoom: 14,
    neighborhoods: {
      Ribeira: p(41.1406, -8.6128),
      Baixa: p(41.1475, -8.6098),
      Cedofeita: p(41.1523, -8.6197),
      "Foz do Douro": p(41.1518, -8.6745),
    },
    places: {
      ribeira: p(41.1405, -8.6131),
      "sao-bento": p(41.1456, -8.6106),
      lello: p(41.1469, -8.6149),
      clerigos: p(41.1457, -8.6146),
      bolhao: p(41.1497, -8.6071),
      caves: p(41.137, -8.613),
      "croisiere-douro": p(41.1402, -8.6118),
      serralves: p(41.1597, -8.6598),
      "palacio-cristal": p(41.1484, -8.6254),
      foz: p(41.1506, -8.6763),
      matosinhos: p(41.1769, -8.6906),
      "surf-porto": p(41.178, -8.69),
      galerias: p(41.1473, -8.6143),
      "douro-valley": p(41.1917, -7.5439),
      "r-conga": p(41.149, -8.61),
      "r-casa-guedes": p(41.1459, -8.6049),
      "r-cafe-santiago": p(41.1467, -8.6058),
      "r-majestic": p(41.1471, -8.6064),
      "r-cantinho-avillez": p(41.1428, -8.614),
      "r-dop": p(41.1432, -8.6149),
    },
  },
  source: "demo",
};
