import { destinationImages } from "@/config/images";
import type { DestinationProfile } from "../../types";

export const prague: DestinationProfile = {
  id: "prague",
  name: "Prague",
  country: "Tchéquie",
  countryCode: "CZ",
  tagline: "Ville de conte de fées, bière légendaire et prix doux.",
  description:
    "Ponts médiévaux, clochers gothiques et caves animées : une capitale magique, festive et étonnamment abordable.",
  image: { src: destinationImages.prague, alt: "Toits et clochers de Prague" },
  fallbackGradient: "from-amber-300 via-rose-500 to-indigo-800",
  type: "ville",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 22, standard: 45, confort: 95 },
    foodPerDay: { eco: 20, standard: 32, confort: 60 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "1 h 45",
        durationHours: 1.75,
        roundTripPerPerson: 150,
        details: "Vol direct, bus express vers le centre",
      },
      {
        mode: "bus",
        durationLabel: "14 h",
        durationHours: 14,
        roundTripPerPerson: 90,
        details: "Autocar longue distance, trajet de nuit possible",
      },
    ],
  },
  localMobility: [
    { mode: "tram", description: "Le tram est le moyen le plus pratique" },
    { mode: "metro", description: "3 lignes simples à utiliser" },
    { mode: "marche", description: "La vieille ville est compacte" },
  ],
  idealDays: { min: 2, max: 5 },
  bestMonths: [4, 5, 6, 7, 8, 9, 12],
  styles: { culture: 3, ville: 3, fete: 3, romantique: 3, gastronomie: 1, festivals: 2, shopping: 1 },
  ambiances: { festive: 3, romantique: 3, economique: 3, sociale: 2, authentique: 2 },
  strengths: { prix: 3, culture: 3, "vie-nocturne": 3, securite: 3, rapidite: 3 },
  neighborhoods: [
    {
      name: "Vieille Ville",
      vibe: "au cœur du conte de fées",
      tiers: ["standard", "confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Malá Strana",
      vibe: "ruelles baroques sous le château",
      tiers: ["standard", "confort"],
      tags: ["romantique"],
    },
    { name: "Žižkov", vibe: "populaire, bars à chaque coin de rue", tiers: ["eco"], tags: ["fete"] },
  ],
  activities: [
    {
      id: "chateau",
      name: "Château de Prague & cathédrale Saint-Guy",
      description: "Le plus grand château ancien du monde.",
      category: "monument",
      emoji: "🏰",
      cost: 18,
      hours: 3,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Le château de Prague",
    },
    {
      id: "charles",
      name: "Pont Charles au petit matin",
      description: "Statues baroques et brume sur la Vltava.",
      category: "monument",
      emoji: "🌉",
      cost: 0,
      hours: 1,
      moments: ["morning"],
      tags: ["culture", "romantique"],
      highlight: "Le pont Charles au lever du jour",
    },
    {
      id: "vieille-ville",
      name: "Place de la Vieille-Ville & horloge astronomique",
      description: "Le cœur médiéval et son horloge animée.",
      category: "quartier",
      emoji: "🕰️",
      cost: 0,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "josefov",
      name: "Quartier juif de Josefov",
      description: "Synagogues et vieux cimetière chargé d'histoire.",
      category: "musee",
      emoji: "🕍",
      cost: 18,
      hours: 2.5,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "mala-strana",
      name: "Balade à Malá Strana",
      description: "Palais, jardins et le mur John Lennon.",
      category: "quartier",
      emoji: "🌸",
      cost: 0,
      hours: 2,
      area: "Malá Strana",
      moments: ["afternoon"],
      tags: ["romantique", "ville"],
    },
    {
      id: "letna",
      name: "Coucher de soleil depuis le parc Letná",
      description: "Bière au biergarten, vue sur les ponts.",
      category: "panorama",
      emoji: "🌅",
      cost: 4,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "detente", "fete"],
      highlight: "Coucher de soleil sur les ponts",
      repeatable: true,
    },
    {
      id: "kayak-vltava",
      name: "Pédalo ou kayak sur la Vltava",
      description: "La ville vue depuis la rivière.",
      category: "aventure",
      emoji: "🛶",
      cost: 12,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["aventure", "detente"],
    },
    {
      id: "beer-tour",
      name: "Dégustation de bières tchèques",
      description: "Brasseries artisanales et pils non filtrée.",
      category: "food",
      emoji: "🍺",
      cost: 20,
      hours: 2,
      moments: ["afternoon", "evening"],
      tags: ["gastronomie", "fete"],
    },
    {
      id: "spa-biere",
      name: "Bain à la bière",
      description: "L'expérience spa la plus insolite d'Europe.",
      category: "detente",
      emoji: "🛁",
      cost: 60,
      hours: 1.5,
      moments: ["afternoon"],
      tags: ["detente"],
    },
    {
      id: "concert",
      name: "Concert classique dans une église baroque",
      description: "Vivaldi et Mozart sous les voûtes dorées.",
      category: "evenement",
      emoji: "🎻",
      cost: 25,
      hours: 1.5,
      moments: ["evening"],
      tags: ["culture", "romantique", "festivals"],
    },
    {
      id: "pub-crawl",
      name: "Soirée dans les bars de Žižkov",
      description: "Le quartier qui compte le plus de bars au mètre carré.",
      category: "nightlife",
      emoji: "🍻",
      cost: 15,
      hours: 3,
      area: "Žižkov",
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "club-5",
      name: "Club sur cinq étages",
      description: "Cinq étages, cinq ambiances musicales.",
      category: "nightlife",
      emoji: "🎉",
      cost: 15,
      hours: 4,
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit dans un club géant",
    },
    {
      id: "kutna",
      name: "Excursion à Kutná Hora",
      description: "L'ossuaire aux 40 000 squelettes et une cathédrale gothique.",
      category: "excursion",
      emoji: "💀",
      cost: 25,
      hours: 6,
      moments: ["morning"],
      tags: ["culture", "aventure"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "hospoda",
      name: "Hospoda traditionnelle",
      description: "Goulash, knedlíky et pils à la pression.",
      priceLevel: 1,
      cost: 12,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "fete"],
    },
    {
      id: "trdelnik",
      name: "Bistro express",
      description: "Soupes et sandwichs chauds pour recharger.",
      priceLevel: 1,
      cost: 8,
      meals: ["lunch"],
      tags: [],
    },
    {
      id: "bistro-cz",
      name: "Bistrot tchèque moderne",
      description: "Cuisine locale revisitée, cadre design.",
      priceLevel: 2,
      cost: 25,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
    },
    {
      id: "cave",
      name: "Taverne médiévale voûtée",
      description: "Dîner aux chandelles dans une cave du XIVe siècle.",
      priceLevel: 2,
      cost: 30,
      meals: ["dinner"],
      tags: ["romantique"],
    },
    {
      id: "gastro-cz",
      name: "Table gastronomique avec vue sur le château",
      description: "Menu dégustation au bord de la Vltava.",
      priceLevel: 3,
      cost: 75,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
    },
  ],
  source: "demo",
};
