import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const reykjavik: DestinationProfile = {
  id: "reykjavik",
  name: "Reykjavik",
  country: "Islande",
  countryCode: "IS",
  iata: "REK",
  tagline: "Geysers, glaciers, bains chauds et aurores boréales.",
  description:
    "La porte d'entrée d'une île de feu et de glace : cascades, plages de sable noir, lagons géothermiques, baleines et, l'hiver, aurores boréales. Chère, mais inoubliable.",
  fallbackGradient: "from-teal-300 via-emerald-500 to-indigo-900",
  type: "mixte",
  costLevel: 4,
  costs: {
    accommodationPerNight: { eco: 50, standard: 110, confort: 210 },
    localTransportPerDay: 15,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "3 h 30",
        durationHours: 3.5,
        roundTripPerPerson: 350,
        details: "Vol direct vers Keflavík, bus Flybus jusqu'à Reykjavik en 45 min",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Le centre-ville se fait entièrement à pied" },
    { mode: "bus", description: "Excursions organisées en minibus au départ du centre" },
    { mode: "taxi", description: "Location de voiture idéale pour la côte sud (roule prudemment)" },
  ],
  idealDays: { min: 4, max: 8 },
  bestMonths: [2, 3, 6, 7, 8, 9],
  styles: { nature: 3, aventure: 3, detente: 3, romantique: 2, culture: 1, fete: 1 },
  ambiances: { aventureuse: 3, calme: 3, romantique: 2, luxueuse: 2 },
  strengths: { nature: 3, securite: 3, activites: 3, confort: 2 },
  neighborhoods: [
    {
      name: "Centre-ville",
      vibe: "Laugavegur, bars et boutiques",
      tiers: ["standard", "confort"],
      tags: ["ville", "fete"],
    },
    {
      name: "Vieux port",
      vibe: "baleines, restos de poisson et vue sur la baie",
      tiers: ["standard", "confort"],
      tags: ["gastronomie", "romantique"],
    },
    {
      name: "Hlíðar",
      vibe: "résidentiel, calme et moins cher",
      tiers: ["eco", "standard"],
      tags: ["detente"],
    },
  ],
  activities: [
    {
      id: "hallgrimskirkja",
      name: "Église Hallgrímskirkja",
      description: "Église en orgues de basalte, montée au clocher pour les toits colorés.",
      category: "monument",
      emoji: "⛪",
      cost: 10,
      hours: 1,
      area: "Centre-ville",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
      highlight: "Reykjavik depuis Hallgrímskirkja",
    },
    {
      id: "harpa",
      name: "Harpa et le front de mer",
      description: "Salle de concert aux mille vitraux, puis la sculpture du Voyageur du soleil.",
      category: "monument",
      emoji: "🎼",
      cost: 0,
      hours: 1,
      area: "Vieux port",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "perlan",
      name: "Perlan, musée des glaciers",
      description: "Une vraie grotte de glace et un planétarium sur les aurores boréales.",
      category: "musee",
      emoji: "🧊",
      cost: 35,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture", "nature"],
    },
    {
      id: "piscine",
      name: "Piscine géothermale",
      description: "Le rituel local : bains chauds en plein air, même sous la neige.",
      category: "detente",
      emoji: "♨️",
      cost: 10,
      hours: 1.5,
      moments: ["morning"],
      tags: ["detente"],
      repeatable: true,
    },
    {
      id: "baleines",
      name: "Observation des baleines",
      description: "Bateau depuis le vieux port à la rencontre des baleines et des dauphins.",
      category: "nature",
      emoji: "🐋",
      cost: 90,
      hours: 3,
      area: "Vieux port",
      moments: ["morning"],
      tags: ["nature", "aventure"],
    },
    {
      id: "blue-lagoon",
      name: "Blue Lagoon",
      description: "Le lagon laiteux au milieu des champs de lave. Réservation obligatoire.",
      category: "detente",
      emoji: "💙",
      cost: 80,
      hours: 3,
      moments: ["afternoon"],
      tags: ["detente", "romantique"],
      highlight: "Baignade au Blue Lagoon",
    },
    {
      id: "sky-lagoon",
      name: "Sky Lagoon",
      description: "Lagon à débordement face à l'océan et rituel sauna en sept étapes.",
      category: "detente",
      emoji: "🌊",
      cost: 70,
      hours: 2.5,
      moments: ["afternoon"],
      tags: ["detente", "romantique"],
    },
    {
      id: "aurores",
      name: "Chasse aux aurores boréales",
      description: "Sortie de nuit loin des lumières (de septembre à mars, selon la météo).",
      category: "nature",
      emoji: "🌌",
      cost: 70,
      hours: 4,
      moments: ["evening"],
      tags: ["nature", "romantique"],
      highlight: "Les aurores boréales",
    },
    {
      id: "laugavegur",
      name: "Bars de Laugavegur",
      description: "Happy hours, bars à bière et concerts, surtout le week-end.",
      category: "nightlife",
      emoji: "🍻",
      cost: 30,
      hours: 3,
      area: "Centre-ville",
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "glacier",
      name: "Randonnée sur le glacier Sólheimajökull",
      description: "Crampons aux pieds et piolet en main, avec un guide.",
      category: "aventure",
      emoji: "🧗",
      cost: 100,
      hours: 9,
      moments: ["morning"],
      tags: ["aventure", "nature"],
      fullDay: true,
    },
    {
      id: "cercle-or",
      name: "Le Cercle d'or",
      description: "Faille tectonique de Þingvellir, geyser Strokkur et chute de Gullfoss.",
      category: "excursion",
      emoji: "💦",
      cost: 90,
      hours: 9,
      moments: ["morning"],
      tags: ["nature"],
      highlight: "Le geyser Strokkur",
      fullDay: true,
    },
    {
      id: "cote-sud",
      name: "Côte sud et plage de sable noir",
      description: "Seljalandsfoss (on passe derrière la cascade), Skógafoss et plage de Reynisfjara.",
      category: "excursion",
      emoji: "🌋",
      cost: 100,
      hours: 11,
      moments: ["morning"],
      tags: ["nature", "aventure"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-baejarins",
      name: "Bæjarins Beztu Pylsur",
      description: "Le stand de hot-dogs d'agneau le plus célèbre d'Islande, depuis 1937.",
      cuisine: "Hot-dogs",
      emoji: "🌭",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 5,
      area: "Vieux port",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-hlemmur",
      name: "Hlemmur Mathöll",
      description: "Ancienne gare routière devenue halle gourmande, une dizaine de comptoirs.",
      cuisine: "Food hall",
      emoji: "🍜",
      kind: "street-food",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      area: "Centre-ville",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-cafe-loki",
      name: "Café Loki",
      description: "Face à l'église : plats islandais, pain de seigle et glace au pain.",
      cuisine: "Cuisine islandaise",
      emoji: "🥣",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Centre-ville",
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-messinn",
      name: "Messinn",
      description: "Poisson du jour servi dans sa poêle en fonte, au cœur du centre.",
      cuisine: "Poissons",
      emoji: "🐟",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 40,
      area: "Centre-ville",
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-grillmarkadurinn",
      name: "Grillmarkaðurinn",
      description: "Produits de fermes islandaises grillés au feu, ambiance de grange chic.",
      cuisine: "Cuisine islandaise moderne",
      emoji: "🔥",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 80,
      area: "Centre-ville",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(64.1466, -21.9426),
    zoom: 12,
    neighborhoods: {
      "Centre-ville": p(64.1455, -21.93),
      "Vieux port": p(64.1515, -21.9425),
      Hlíðar: p(64.133, -21.915),
    },
    places: {
      hallgrimskirkja: p(64.1417, -21.9266),
      harpa: p(64.1504, -21.9326),
      perlan: p(64.129, -21.919),
      piscine: p(64.1436, -21.9261),
      baleines: p(64.153, -21.942),
      "blue-lagoon": p(63.8804, -22.4495),
      "sky-lagoon": p(64.115, -21.946),
      aurores: p(64.2, -21.7),
      laugavegur: p(64.145, -21.928),
      glacier: p(63.532, -19.369),
      "cercle-or": p(64.3271, -20.1199),
      "cote-sud": p(63.616, -19.9886),
      "r-baejarins": p(64.1485, -21.9408),
      "r-hlemmur": p(64.1433, -21.9153),
      "r-cafe-loki": p(64.1419, -21.9252),
      "r-messinn": p(64.1478, -21.9396),
      "r-grillmarkadurinn": p(64.1477, -21.9386),
    },
  },
  source: "demo",
};
