import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const rio: DestinationProfile = {
  id: "rio",
  name: "Rio de Janeiro",
  country: "Brésil",
  countryCode: "BR",
  iata: "RIO",
  tagline: "Plages mythiques, samba et vue sur le Christ.",
  description:
    "La ville la plus spectaculaire du monde : Pain de Sucre et Christ Rédempteur, plages d'Ipanema et Copacabana, randonnées dans la forêt tropicale et samba à Lapa jusqu'à l'aube.",
  fallbackGradient: "from-yellow-300 via-green-500 to-sky-600",
  type: "balneaire",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 22, standard: 55, confort: 120 },
    localTransportPerDay: 6,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "11 h 30",
        durationHours: 11.5,
        roundTripPerPerson: 750,
        details: "Vol direct, VTC ou bus jusqu'à la zone sud en 40 min",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Métro propre et sûr entre le centre, Copacabana et Ipanema" },
    { mode: "taxi", description: "VTC (Uber, 99) conseillé le soir plutôt que la marche" },
    { mode: "velo", description: "Pistes cyclables le long des plages" },
  ],
  idealDays: { min: 6, max: 12 },
  bestMonths: [5, 6, 7, 8, 9, 10],
  styles: { plage: 3, fete: 3, nature: 3, aventure: 2, festivals: 3, culture: 2, romantique: 2 },
  ambiances: { festive: 3, sociale: 3, aventureuse: 3, romantique: 2 },
  strengths: { plages: 3, "vie-nocturne": 3, nature: 3, activites: 3, prix: 2 },
  neighborhoods: [
    {
      name: "Ipanema",
      vibe: "la plage chic et le coucher de soleil",
      tiers: ["standard", "confort"],
      tags: ["plage", "romantique"],
    },
    {
      name: "Copacabana",
      vibe: "la grande plage populaire et animée",
      tiers: ["eco", "standard"],
      tags: ["plage", "fete"],
    },
    {
      name: "Santa Teresa",
      vibe: "colline bohème, ateliers et vue",
      tiers: ["eco", "standard"],
      tags: ["culture", "romantique"],
    },
    { name: "Lapa", vibe: "le quartier de la samba et de la fête", tiers: ["eco"], tags: ["fete"] },
  ],
  activities: [
    {
      id: "christ",
      name: "Christ Rédempteur",
      description: "Train à crémaillère à travers la forêt jusqu'à la statue et la vue sur toute la baie.",
      category: "monument",
      emoji: "🙏",
      cost: 20,
      hours: 3,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Le Christ Rédempteur",
    },
    {
      id: "selaron",
      name: "Escalier Selarón et Santa Teresa",
      description: "215 marches de carreaux colorés venus du monde entier, puis la colline bohème.",
      category: "quartier",
      emoji: "🎨",
      cost: 0,
      hours: 2,
      area: "Santa Teresa",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "dois-irmaos",
      name: "Randonnée des Dois Irmãos",
      description: "Montée par la favela de Vidigal avec un guide, vue folle sur Ipanema.",
      category: "nature",
      emoji: "🥾",
      cost: 15,
      hours: 3,
      moments: ["morning"],
      tags: ["nature", "aventure"],
    },
    {
      id: "jardin-botanique",
      name: "Jardin botanique",
      description: "Allée de palmiers impériaux et singes dans les arbres.",
      category: "detente",
      emoji: "🌴",
      cost: 12,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["nature", "detente"],
    },
    {
      id: "museu-amanha",
      name: "Musée de demain",
      description: "Architecture futuriste sur le port et expositions sur l'avenir de la planète.",
      category: "musee",
      emoji: "🔭",
      cost: 6,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "ipanema",
      name: "Plage d'Ipanema",
      description: "Volley, caïpirinha et vendeurs ambulants : la plage la plus célèbre du monde.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 4,
      area: "Ipanema",
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      highlight: "Journée à Ipanema",
      repeatable: true,
    },
    {
      id: "copacabana",
      name: "Copacabana",
      description: "4 km de sable et la promenade aux vagues noires et blanches.",
      category: "plage",
      emoji: "🌊",
      cost: 0,
      hours: 3,
      area: "Copacabana",
      moments: ["afternoon"],
      tags: ["plage"],
      repeatable: true,
    },
    {
      id: "pain-sucre",
      name: "Pain de Sucre au coucher du soleil",
      description: "Deux téléphériques pour voir la baie et la ville s'illuminer.",
      category: "panorama",
      emoji: "🌅",
      cost: 30,
      hours: 2.5,
      moments: ["evening"],
      tags: ["romantique"],
      highlight: "Coucher de soleil sur le Pain de Sucre",
    },
    {
      id: "arpoador",
      name: "Coucher de soleil à l'Arpoador",
      description: "Le rocher où tout Rio applaudit le soleil couchant.",
      category: "panorama",
      emoji: "👏",
      cost: 0,
      hours: 1.5,
      area: "Ipanema",
      moments: ["evening"],
      tags: ["romantique", "detente"],
      repeatable: true,
    },
    {
      id: "maracana",
      name: "Match au Maracanã",
      description: "Le stade mythique un soir de match, ambiance brésilienne garantie.",
      category: "evenement",
      emoji: "⚽",
      cost: 30,
      hours: 3,
      moments: ["evening"],
      tags: ["festivals", "fete"],
    },
    {
      id: "lapa-samba",
      name: "Samba à Lapa",
      description: "Sous les arches, la rue et les salles de samba vibrent jusqu'au matin.",
      category: "nightlife",
      emoji: "💃",
      cost: 20,
      hours: 4,
      area: "Lapa",
      moments: ["evening"],
      tags: ["fete", "festivals"],
      highlight: "Nuit de samba à Lapa",
      repeatable: true,
    },
    {
      id: "ilha-grande",
      name: "Excursion à Ilha Grande",
      description: "Île sans voitures, plages sauvages comme Lopes Mendes.",
      category: "excursion",
      emoji: "🏝️",
      cost: 60,
      hours: 12,
      moments: ["morning"],
      tags: ["plage", "nature"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-bibi-sucos",
      name: "Bibi Sucos",
      description: "Jus de fruits tropicaux et bols d'açaí en bord de plage.",
      cuisine: "Jus & açaí",
      emoji: "🥤",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-bar-urca",
      name: "Bar Urca",
      description: "Petiscos et bière assis sur le muret face à la baie, au pied du Pain de Sucre.",
      cuisine: "Petiscos",
      emoji: "🍺",
      kind: "bar",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      meals: ["lunch", "dinner"],
      tags: ["fete", "romantique"],
      real: true,
    },
    {
      id: "r-colombo",
      name: "Confeitaria Colombo",
      description: "Salon de thé Belle Époque de 1894, miroirs géants et pâtisseries.",
      cuisine: "Salon de thé",
      emoji: "☕",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      meals: ["lunch"],
      tags: ["romantique"],
      real: true,
    },
    {
      id: "r-bar-do-mineiro",
      name: "Bar do Mineiro",
      description: "Feijoada et pastéis dans le bar bohème de Santa Teresa.",
      cuisine: "Cuisine brésilienne",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 20,
      area: "Santa Teresa",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-palace",
      name: "Churrascaria Palace",
      description: "Rodízio de viandes grillées servies à volonté, à Copacabana.",
      cuisine: "Churrasco",
      emoji: "🥩",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 50,
      area: "Copacabana",
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
  ],
  geo: {
    center: p(-22.9519, -43.2105),
    zoom: 12,
    neighborhoods: {
      Ipanema: p(-22.9838, -43.2045),
      Copacabana: p(-22.9711, -43.1822),
      "Santa Teresa": p(-22.9185, -43.188),
      Lapa: p(-22.9133, -43.18),
    },
    places: {
      christ: p(-22.9519, -43.2105),
      selaron: p(-22.9153, -43.179),
      "dois-irmaos": p(-22.987, -43.241),
      "jardin-botanique": p(-22.967, -43.224),
      "museu-amanha": p(-22.894, -43.1797),
      ipanema: p(-22.9868, -43.2049),
      copacabana: p(-22.9711, -43.1822),
      "pain-sucre": p(-22.9486, -43.1566),
      arpoador: p(-22.989, -43.192),
      maracana: p(-22.9121, -43.2302),
      "lapa-samba": p(-22.9133, -43.18),
      "ilha-grande": p(-23.14, -44.17),
      "r-bibi-sucos": p(-22.984, -43.224),
      "r-bar-urca": p(-22.945, -43.164),
      "r-colombo": p(-22.9054, -43.1788),
      "r-bar-do-mineiro": p(-22.9185, -43.185),
      "r-palace": p(-22.968, -43.183),
    },
  },
  source: "demo",
};
