import { destinationImages } from "@/config/images";
import type { DestinationProfile } from "../../types";

export const rome: DestinationProfile = {
  id: "rome",
  name: "Rome",
  country: "Italie",
  countryCode: "IT",
  tagline: "2 000 ans d'histoire et la meilleure pasta de ta vie.",
  description:
    "Un musée à ciel ouvert où l'on passe du Colisée à une trattoria en dix minutes, sous une lumière dorée.",
  image: { src: destinationImages.rome, alt: "Le Colisée de Rome au coucher du soleil" },
  fallbackGradient: "from-yellow-400 via-orange-500 to-red-700",
  type: "ville",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 30, standard: 65, confort: 140 },
    localTransportPerDay: 7,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h 05",
        durationHours: 2.1,
        roundTripPerPerson: 140,
        details: "Vol direct, train express jusqu'au centre",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Le centre historique se visite à pied" },
    { mode: "metro", description: "Pratique pour le Vatican et le Colisée" },
    { mode: "bus", description: "Réseau dense pour les autres quartiers" },
    { mode: "taxi", description: "Utile le soir pour rentrer" },
  ],
  idealDays: { min: 3, max: 6 },
  bestMonths: [3, 4, 5, 6, 9, 10, 11],
  styles: { culture: 3, gastronomie: 3, romantique: 3, ville: 3, shopping: 2, fete: 1, detente: 1 },
  ambiances: { romantique: 3, authentique: 3, luxueuse: 2, calme: 1, sociale: 1 },
  strengths: { culture: 3, gastronomie: 3, securite: 2, rapidite: 2, confort: 2, activites: 2 },
  neighborhoods: [
    {
      name: "Trastevere",
      vibe: "ruelles pittoresques et terrasses animées",
      tiers: ["eco", "standard"],
      tags: ["romantique", "fete", "gastronomie"],
    },
    {
      name: "Monti",
      vibe: "branché, à deux pas du Colisée",
      tiers: ["standard"],
      tags: ["ville", "culture"],
    },
    {
      name: "Centro Storico",
      vibe: "au pied du Panthéon",
      tiers: ["standard", "confort"],
      tags: ["culture", "romantique"],
    },
  ],
  activities: [
    {
      id: "colisee",
      name: "Colisée & Forum romain",
      description: "Le cœur de la Rome antique, à explorer tôt le matin.",
      category: "monument",
      emoji: "🏛️",
      cost: 18,
      hours: 3.5,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Le Colisée",
    },
    {
      id: "vatican",
      name: "Musées du Vatican & chapelle Sixtine",
      description: "Michel-Ange au plafond, une claque garantie.",
      category: "musee",
      emoji: "🎨",
      cost: 20,
      hours: 3.5,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "La chapelle Sixtine",
    },
    {
      id: "pantheon",
      name: "Panthéon, fontaine de Trevi & place Navone",
      description: "Les places baroques les plus célèbres, à pied.",
      category: "quartier",
      emoji: "⛲",
      cost: 5,
      hours: 2.5,
      area: "Centro Storico",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville", "romantique"],
    },
    {
      id: "borghese",
      name: "Galerie Borghèse",
      description: "Le Bernin et le Caravage dans une villa-musée.",
      category: "musee",
      emoji: "🗿",
      cost: 17,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "trastevere",
      name: "Flânerie à Trastevere",
      description: "Lierre sur les façades et ruelles pavées.",
      category: "quartier",
      emoji: "🌿",
      cost: 0,
      hours: 2,
      area: "Trastevere",
      moments: ["afternoon"],
      tags: ["romantique", "ville"],
    },
    {
      id: "gelato",
      name: "Tournée des meilleurs gelati",
      description: "Pistache, stracciatella… on compare sérieusement.",
      category: "food",
      emoji: "🍨",
      cost: 8,
      hours: 1,
      moments: ["afternoon"],
      tags: ["gastronomie"],
    },
    {
      id: "cooking",
      name: "Cours de pâtes fraîches",
      description: "Apprends les cacio e pepe comme une nonna.",
      category: "food",
      emoji: "🍝",
      cost: 60,
      hours: 3,
      moments: ["morning", "afternoon"],
      tags: ["gastronomie"],
      highlight: "Cours de pâtes fraîches",
    },
    {
      id: "pincio",
      name: "Coucher de soleil au Pincio",
      description: "Vue sur les coupoles depuis la terrasse de la villa Borghèse.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "detente"],
      highlight: "Coucher de soleil sur les coupoles",
    },
    {
      id: "aventin",
      name: "Jardin des Orangers sur l'Aventin",
      description: "Un jardin calme et le fameux trou de serrure.",
      category: "detente",
      emoji: "🍊",
      cost: 0,
      hours: 1.5,
      moments: ["afternoon", "evening"],
      tags: ["detente", "romantique"],
      repeatable: true,
    },
    {
      id: "via-condotti",
      name: "Shopping via del Corso & via Condotti",
      description: "Des enseignes accessibles aux grandes maisons italiennes.",
      category: "shopping",
      emoji: "🛍️",
      cost: 10,
      hours: 2.5,
      moments: ["afternoon"],
      tags: ["shopping"],
    },
    {
      id: "appia",
      name: "Via Appia à vélo",
      description: "Pédaler sur une voie romaine entre pins et aqueducs.",
      category: "aventure",
      emoji: "🚲",
      cost: 25,
      hours: 3,
      moments: ["morning"],
      tags: ["aventure", "nature", "culture"],
    },
    {
      id: "aperitivo",
      name: "Aperitivo à Trastevere",
      description: "Spritz et bruschette sur une piazza animée.",
      category: "nightlife",
      emoji: "🍹",
      cost: 15,
      hours: 2.5,
      area: "Trastevere",
      moments: ["evening"],
      tags: ["fete", "gastronomie"],
      repeatable: true,
    },
    {
      id: "pigneto",
      name: "Bars du Pigneto",
      description: "Le quartier alternatif où sortent les Romains.",
      category: "nightlife",
      emoji: "🎶",
      cost: 20,
      hours: 3,
      moments: ["evening"],
      tags: ["fete"],
    },
    {
      id: "tivoli",
      name: "Excursion à Tivoli (villa d'Este)",
      description: "Jardins Renaissance et centaines de fontaines.",
      category: "excursion",
      emoji: "⛲",
      cost: 25,
      hours: 6,
      moments: ["morning"],
      tags: ["culture", "nature", "romantique"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "trattoria",
      name: "Trattoria OVO",
      description: "Carbonara, amatriciana et nappe à carreaux.",
      cuisine: "Cuisine romaine",
      emoji: "🍝",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 20,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
    },
    {
      id: "pizza-taglio",
      name: "OVO Pizza al Taglio",
      description: "La pizza à la coupe, au poids, à emporter.",
      cuisine: "Pizza à la coupe",
      emoji: "🍕",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      meals: ["lunch"],
      tags: [],
    },
    {
      id: "supplì",
      name: "Friggitoria OVO",
      description: "Croquettes de riz fondantes, le street food romain.",
      cuisine: "Street food romaine",
      emoji: "🍙",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 7,
      meals: ["lunch"],
      tags: ["gastronomie"],
    },
    {
      id: "osteria",
      name: "Osteria OVO",
      description: "Cuisine romaine généreuse en terrasse.",
      cuisine: "Cuisine romaine",
      emoji: "🍷",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 32,
      area: "Trastevere",
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
    },
    {
      id: "gastro-rome",
      name: "Table OVO Roma",
      description: "Cuisine italienne d'auteur sur les toits de Rome.",
      cuisine: "Gastronomie italienne",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 95,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
    },
  ],
  source: "demo",
};
