import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const santorin: DestinationProfile = {
  id: "santorin",
  name: "Santorin",
  country: "Grèce",
  countryCode: "GR",
  iata: "JTR",
  tagline: "Maisons blanches, dômes bleus et couchers de soleil sur la caldeira.",
  description:
    "L'île la plus photogénique de Grèce : villages suspendus au-dessus d'un volcan englouti, plages de sable noir et rouge, vins de l'île et catamaran au coucher du soleil.",
  fallbackGradient: "from-sky-200 via-blue-500 to-indigo-700",
  type: "balneaire",
  costLevel: 4,
  costs: {
    accommodationPerNight: { eco: 45, standard: 100, confort: 220 },
    localTransportPerDay: 10,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "3 h 30",
        durationHours: 3.5,
        roundTripPerPerson: 300,
        details: "Vol direct en saison (sinon via Athènes), bus ou transfert jusqu'à Fira",
      },
    ],
  },
  localMobility: [
    { mode: "bus", description: "Bus KTEL au départ de Fira vers les villages et plages" },
    { mode: "velo", description: "Quad ou scooter pour explorer l'île (avec permis)" },
    { mode: "marche", description: "Sentier de la caldeira entre Fira et Oia" },
  ],
  idealDays: { min: 3, max: 6 },
  bestMonths: [5, 6, 7, 8, 9, 10],
  styles: { romantique: 3, plage: 3, detente: 3, gastronomie: 2, nature: 2, culture: 2, fete: 1 },
  ambiances: { romantique: 3, luxueuse: 3, calme: 2, sociale: 1 },
  strengths: { plages: 3, securite: 3, confort: 3, nature: 2, gastronomie: 2 },
  neighborhoods: [
    {
      name: "Fira",
      vibe: "la capitale animée, bars et vue sur la caldeira",
      tiers: ["standard", "confort"],
      tags: ["fete", "ville"],
    },
    {
      name: "Oia",
      vibe: "le village carte postale, très romantique",
      tiers: ["confort"],
      tags: ["romantique"],
    },
    {
      name: "Perissa",
      vibe: "plage de sable noir, plus abordable",
      tiers: ["eco", "standard"],
      tags: ["plage", "detente"],
    },
  ],
  activities: [
    {
      id: "fira-oia",
      name: "Randonnée Fira–Oia sur la caldeira",
      description: "10 km sur la crête, entre villages blancs et falaises volcaniques.",
      category: "nature",
      emoji: "🥾",
      cost: 0,
      hours: 4,
      moments: ["morning"],
      tags: ["nature", "romantique"],
      highlight: "Le sentier de la caldeira",
    },
    {
      id: "akrotiri",
      name: "Site antique d'Akrotiri",
      description: "La « Pompéi grecque », ville minoenne figée sous les cendres.",
      category: "musee",
      emoji: "🏺",
      cost: 20,
      hours: 1.5,
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "pyrgos",
      name: "Village de Pyrgos",
      description: "Ruelles tranquilles et vue à 360° depuis le sommet du village.",
      category: "quartier",
      emoji: "🏘️",
      cost: 0,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
    },
    {
      id: "ancienne-thira",
      name: "Ancienne Théra",
      description: "Ruines antiques au sommet d'un promontoire entre deux plages.",
      category: "monument",
      emoji: "🏛️",
      cost: 10,
      hours: 2,
      moments: ["morning"],
      tags: ["culture", "aventure"],
    },
    {
      id: "volcan-santorin",
      name: "Randonnée sur le volcan de Nea Kameni",
      description: "Bateau jusqu'au cratère encore fumant, baignade dans les sources chaudes.",
      category: "aventure",
      emoji: "🌋",
      cost: 30,
      hours: 3,
      moments: ["morning"],
      tags: ["aventure", "nature"],
    },
    {
      id: "kayak-santorin",
      name: "Kayak au pied des falaises",
      description: "Grottes marines et snorkeling dans l'eau cristalline.",
      category: "aventure",
      emoji: "🛶",
      cost: 70,
      hours: 3,
      moments: ["morning"],
      tags: ["aventure", "plage"],
    },
    {
      id: "red-beach",
      name: "Plage rouge",
      description: "Falaises rouge sang au-dessus d'une petite plage.",
      category: "plage",
      emoji: "🟥",
      cost: 0,
      hours: 2.5,
      moments: ["afternoon"],
      tags: ["plage", "nature"],
    },
    {
      id: "perissa-plage",
      name: "Plage de sable noir de Perissa",
      description: "Longue plage volcanique, transats et tavernes les pieds dans le sable.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 3.5,
      area: "Perissa",
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      repeatable: true,
    },
    {
      id: "vin-santorin",
      name: "Dégustation dans un domaine viticole",
      description: "Vignes en corbeille et assyrtiko face à la mer.",
      category: "food",
      emoji: "🍷",
      cost: 30,
      hours: 2,
      moments: ["afternoon"],
      tags: ["gastronomie", "romantique"],
    },
    {
      id: "catamaran",
      name: "Catamaran au coucher du soleil",
      description: "Tour de la caldeira, baignade et dîner à bord.",
      category: "excursion",
      emoji: "⛵",
      cost: 120,
      hours: 5,
      moments: ["afternoon"],
      tags: ["romantique", "plage"],
      highlight: "Catamaran au coucher du soleil",
    },
    {
      id: "oia-sunset",
      name: "Coucher de soleil à Oia",
      description: "Le spectacle le plus célèbre de Grèce, depuis les ruines du château.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 2,
      area: "Oia",
      moments: ["evening"],
      tags: ["romantique"],
      highlight: "Le coucher de soleil d'Oia",
      repeatable: true,
    },
    {
      id: "fira-bars",
      name: "Soirée dans les bars de Fira",
      description: "Cocktails sur des terrasses suspendues au-dessus de la caldeira.",
      category: "nightlife",
      emoji: "🍸",
      cost: 25,
      hours: 3,
      area: "Fira",
      moments: ["evening"],
      tags: ["fete", "romantique"],
      repeatable: true,
    },
  ],
  restaurants: [
    {
      id: "r-luckys",
      name: "Lucky's Souvlakis",
      description: "Pitas gyros généreuses et pas chères, en plein Fira.",
      cuisine: "Souvlaki",
      emoji: "🥙",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      area: "Fira",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-pitogyros",
      name: "Pitogyros Oia",
      description: "Gyros et frites maison à emporter pour attendre le coucher du soleil.",
      cuisine: "Gyros",
      emoji: "🥙",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      area: "Oia",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-metaxi-mas",
      name: "Metaxi Mas",
      description: "Taverne adorée des locaux, dans le village d'Exo Gonia.",
      cuisine: "Cuisine grecque",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-ammoudi",
      name: "Ammoudi Fish Tavern",
      description: "Poisson grillé au bord de l'eau, en bas des 300 marches d'Oia.",
      cuisine: "Poissons",
      emoji: "🐟",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 45,
      meals: ["lunch", "dinner"],
      tags: ["romantique", "gastronomie"],
      real: true,
    },
    {
      id: "r-selene",
      name: "Selene",
      description: "Table gastronomique à Pyrgos, produits de l'île sublimés.",
      cuisine: "Cuisine des Cyclades",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 90,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(36.4, 25.43),
    zoom: 11,
    neighborhoods: {
      Fira: p(36.4167, 25.4317),
      Oia: p(36.4618, 25.3753),
      Perissa: p(36.356, 25.476),
    },
    places: {
      "fira-oia": p(36.435, 25.425),
      akrotiri: p(36.3514, 25.4033),
      pyrgos: p(36.383, 25.45),
      "ancienne-thira": p(36.362, 25.477),
      "volcan-santorin": p(36.404, 25.396),
      "kayak-santorin": p(36.348, 25.395),
      "red-beach": p(36.348, 25.395),
      "perissa-plage": p(36.356, 25.476),
      "vin-santorin": p(36.39, 25.45),
      catamaran: p(36.415, 25.425),
      "oia-sunset": p(36.4618, 25.3753),
      "fira-bars": p(36.417, 25.432),
      "r-luckys": p(36.4165, 25.4315),
      "r-pitogyros": p(36.4615, 25.3765),
      "r-metaxi-mas": p(36.393, 25.476),
      "r-ammoudi": p(36.462, 25.37),
      "r-selene": p(36.3832, 25.4502),
    },
  },
  source: "demo",
};
