import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const seoul: DestinationProfile = {
  id: "seoul",
  name: "Séoul",
  country: "Corée du Sud",
  countryCode: "KR",
  iata: "SEL",
  tagline: "Palais, K-pop, barbecue et nuits sans fin.",
  description:
    "La capitale de la K-culture : palais en hanbok, street food de marché, cafés à thème, spas coréens ouverts la nuit et montagnes à portée de métro.",
  fallbackGradient: "from-sky-300 via-violet-500 to-pink-600",
  type: "ville",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 30, standard: 65, confort: 130 },
    localTransportPerDay: 6,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "13 h 30",
        durationHours: 13.5,
        roundTripPerPerson: 800,
        details: "Vol direct ou avec escale, train AREX jusqu'au centre en 45 min",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Métro immense, propre et bon marché (carte T-money)" },
    { mode: "bus", description: "Bus urbains très fréquents" },
    { mode: "taxi", description: "Taxis abordables pour rentrer tard" },
  ],
  idealDays: { min: 5, max: 12 },
  bestMonths: [4, 5, 9, 10, 11],
  styles: { ville: 3, culture: 3, gastronomie: 3, shopping: 3, fete: 3, nature: 2, festivals: 2 },
  ambiances: { festive: 3, sociale: 3, authentique: 2, aventureuse: 2 },
  strengths: { securite: 3, gastronomie: 3, "vie-nocturne": 3, culture: 3, activites: 3 },
  neighborhoods: [
    {
      name: "Myeongdong",
      vibe: "central, shopping et street food",
      tiers: ["standard", "confort"],
      tags: ["shopping", "gastronomie"],
    },
    { name: "Hongdae", vibe: "étudiant, musique live et clubs", tiers: ["eco", "standard"], tags: ["fete"] },
    {
      name: "Jongno",
      vibe: "palais, hanoks et maisons de thé",
      tiers: ["eco", "standard"],
      tags: ["culture"],
    },
    { name: "Gangnam", vibe: "moderne et chic", tiers: ["confort"], tags: ["shopping"] },
  ],
  activities: [
    {
      id: "gyeongbokgung",
      name: "Palais Gyeongbokgung",
      description: "Le grand palais royal et la relève de la garde. Entrée gratuite en hanbok !",
      category: "monument",
      emoji: "🏯",
      cost: 3,
      hours: 2,
      area: "Jongno",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Le palais Gyeongbokgung en hanbok",
    },
    {
      id: "bukchon",
      name: "Village Bukchon Hanok",
      description: "Ruelles de maisons traditionnelles en bois (parle doucement, des gens y vivent).",
      category: "quartier",
      emoji: "🏘️",
      cost: 0,
      hours: 1.5,
      area: "Jongno",
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
    },
    {
      id: "insadong",
      name: "Insadong et salons de thé",
      description: "Artisanat, calligraphie et thé traditionnel.",
      category: "shopping",
      emoji: "🍵",
      cost: 0,
      hours: 2,
      area: "Jongno",
      moments: ["afternoon"],
      tags: ["shopping", "culture"],
    },
    {
      id: "gwangjang",
      name: "Marché de Gwangjang",
      description: "Galettes de haricot mungo, kimbap et tteokbokki au comptoir.",
      category: "food",
      emoji: "🥞",
      cost: 10,
      hours: 1.5,
      moments: ["morning", "afternoon"],
      tags: ["gastronomie"],
      highlight: "Street food au marché de Gwangjang",
    },
    {
      id: "bukhansan",
      name: "Randonnée au mont Bukhansan",
      description: "Des sommets de granit accessibles en métro, vue sur toute la ville.",
      category: "nature",
      emoji: "⛰️",
      cost: 0,
      hours: 5,
      moments: ["morning"],
      tags: ["nature", "aventure"],
    },
    {
      id: "hangang",
      name: "Vélo et pique-nique au bord du Han",
      description: "Le rituel du soir : poulet frit, bière et vue sur le fleuve.",
      category: "detente",
      emoji: "🚲",
      cost: 5,
      hours: 2,
      moments: ["afternoon"],
      tags: ["detente"],
      repeatable: true,
    },
    {
      id: "jjimjilbang",
      name: "Soirée au jjimjilbang",
      description: "Spa coréen ouvert 24 h/24 : bains, saunas et œufs cuits au four.",
      category: "detente",
      emoji: "♨️",
      cost: 12,
      hours: 2.5,
      moments: ["afternoon", "evening"],
      tags: ["detente"],
    },
    {
      id: "namsan",
      name: "N Seoul Tower au coucher du soleil",
      description: "Téléphérique puis vue à 360° sur la ville qui s'allume.",
      category: "panorama",
      emoji: "🗼",
      cost: 15,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "ville"],
      highlight: "Séoul depuis la N Seoul Tower",
      repeatable: true,
    },
    {
      id: "myeongdong-food",
      name: "Street food de Myeongdong",
      description: "Des dizaines d'étals le soir : brochettes, œufs en pain et glaces géantes.",
      category: "food",
      emoji: "🍢",
      cost: 10,
      hours: 1.5,
      area: "Myeongdong",
      moments: ["evening"],
      tags: ["gastronomie"],
    },
    {
      id: "ddp",
      name: "Dongdaemun Design Plaza et shopping de nuit",
      description: "Architecture futuriste de Zaha Hadid et centres commerciaux ouverts jusqu'à l'aube.",
      category: "shopping",
      emoji: "🛸",
      cost: 0,
      hours: 2,
      moments: ["evening"],
      tags: ["shopping", "ville"],
    },
    {
      id: "hongdae",
      name: "Soirée à Hongdae",
      description: "Artistes de rue, bars et clubs étudiants, ambiance jusqu'au matin.",
      category: "nightlife",
      emoji: "🎶",
      cost: 20,
      hours: 4,
      area: "Hongdae",
      moments: ["evening"],
      tags: ["fete", "festivals"],
      highlight: "Nuit à Hongdae",
      repeatable: true,
    },
    {
      id: "dmz",
      name: "Excursion à la DMZ",
      description:
        "La frontière la plus militarisée du monde, tunnels et observatoire. Passeport obligatoire.",
      category: "excursion",
      emoji: "🪖",
      cost: 60,
      hours: 8,
      moments: ["morning"],
      tags: ["culture"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-sunhee",
      name: "Sunhee-ne Bindaetteok",
      description: "Galettes croustillantes de haricot mungo cuites devant toi au marché de Gwangjang.",
      cuisine: "Street food coréenne",
      emoji: "🥞",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-myeongdong-kyoja",
      name: "Myeongdong Kyoja",
      description: "Kalguksu (nouilles au couteau) et raviolis depuis 1966.",
      cuisine: "Nouilles coréennes",
      emoji: "🍜",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 10,
      area: "Myeongdong",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-hadongkwan",
      name: "Hadongkwan",
      description: "Bouillon de bœuf gomtang servi depuis 1939, le matin et le midi.",
      cuisine: "Soupe coréenne",
      emoji: "🥣",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Myeongdong",
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-tosokchon",
      name: "Tosokchon Samgyetang",
      description: "Poulet entier farci au riz gluant et au ginseng, dans une maison traditionnelle.",
      cuisine: "Cuisine coréenne",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 15,
      area: "Jongno",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
  ],
  geo: {
    center: p(37.5665, 126.978),
    zoom: 12,
    neighborhoods: {
      Myeongdong: p(37.5636, 126.986),
      Hongdae: p(37.5563, 126.922),
      Jongno: p(37.5735, 126.9855),
      Gangnam: p(37.4979, 127.0276),
    },
    places: {
      gyeongbokgung: p(37.5796, 126.977),
      bukchon: p(37.5826, 126.983),
      insadong: p(37.574, 126.985),
      gwangjang: p(37.57, 127.0),
      bukhansan: p(37.659, 126.978),
      hangang: p(37.528, 126.934),
      jjimjilbang: p(37.529, 126.965),
      namsan: p(37.5512, 126.9882),
      "myeongdong-food": p(37.5636, 126.986),
      ddp: p(37.567, 127.0095),
      hongdae: p(37.5563, 126.922),
      dmz: p(37.956, 126.677),
      "r-sunhee": p(37.5701, 126.9996),
      "r-myeongdong-kyoja": p(37.5625, 126.9855),
      "r-hadongkwan": p(37.5638, 126.984),
      "r-tosokchon": p(37.578, 126.971),
    },
  },
  source: "demo",
};
