import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const seville: DestinationProfile = {
  id: "seville",
  name: "Séville",
  country: "Espagne",
  countryCode: "ES",
  iata: "SVQ",
  tagline: "Orangers, flamenco et tapas jusqu'à minuit.",
  description:
    "La plus andalouse des villes : palais mauresques, patios fleuris, soirées en terrasse et flamenco dans le quartier de Triana.",
  fallbackGradient: "from-orange-300 via-amber-500 to-red-700",
  type: "ville",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 25, standard: 55, confort: 115 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h 10",
        durationHours: 2.2,
        roundTripPerPerson: 150,
        details: "Vol direct, bus express jusqu'au centre en 35 min",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "Le centre historique se découvre à pied" },
    { mode: "velo", description: "Pistes cyclables partout et vélos en libre-service (Sevici)" },
    { mode: "tram", description: "Un tram et une ligne de métro pour les trajets plus longs" },
    { mode: "taxi", description: "Taxis abordables pour rentrer tard" },
  ],
  idealDays: { min: 3, max: 5 },
  bestMonths: [3, 4, 5, 10, 11],
  styles: { ville: 3, culture: 3, romantique: 3, gastronomie: 3, fete: 2, festivals: 2, detente: 1 },
  ambiances: { authentique: 3, romantique: 3, festive: 2, sociale: 3, economique: 2 },
  strengths: { culture: 3, gastronomie: 3, prix: 2, securite: 3, "vie-nocturne": 2, rapidite: 2 },
  neighborhoods: [
    {
      name: "Santa Cruz",
      vibe: "ruelles blanches et patios près de la cathédrale",
      tiers: ["standard", "confort"],
      tags: ["romantique", "culture"],
    },
    {
      name: "Triana",
      vibe: "l'âme populaire, céramique et flamenco",
      tiers: ["eco", "standard"],
      tags: ["culture", "gastronomie"],
    },
    {
      name: "Alameda de Hércules",
      vibe: "jeune, alternatif, plein de bars",
      tiers: ["eco", "standard"],
      tags: ["fete", "ville"],
    },
    {
      name: "Arenal",
      vibe: "central, entre cathédrale et fleuve",
      tiers: ["standard", "confort"],
      tags: ["ville"],
    },
  ],
  activities: [
    {
      id: "alcazar",
      name: "Real Alcázar",
      description: "Palais mauresque, jardins et fontaines : le décor de Game of Thrones. Billet à réserver.",
      category: "monument",
      emoji: "🏰",
      cost: 15,
      hours: 2.5,
      area: "Santa Cruz",
      moments: ["morning"],
      tags: ["culture", "romantique"],
      highlight: "Les jardins du Real Alcázar",
    },
    {
      id: "cathedrale-seville",
      name: "Cathédrale et Giralda",
      description: "La plus grande cathédrale gothique du monde et la montée à rampes de la Giralda.",
      category: "monument",
      emoji: "⛪",
      cost: 13,
      hours: 2,
      area: "Santa Cruz",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "plaza-espana",
      name: "Plaza de España et parc María Luisa",
      description: "Place monumentale en demi-cercle, canaux et bancs d'azulejos.",
      category: "monument",
      emoji: "🏛️",
      cost: 0,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique", "detente"],
      highlight: "La Plaza de España",
    },
    {
      id: "santa-cruz",
      name: "Balade dans le quartier de Santa Cruz",
      description: "L'ancien quartier juif : ruelles étroites, orangers et places cachées.",
      category: "quartier",
      emoji: "🍊",
      cost: 0,
      hours: 2,
      area: "Santa Cruz",
      moments: ["morning", "afternoon"],
      tags: ["ville", "romantique"],
    },
    {
      id: "setas",
      name: "Coucher de soleil sur Las Setas",
      description: "La passerelle du Metropol Parasol, immense structure en bois au-dessus des toits.",
      category: "panorama",
      emoji: "🌅",
      cost: 15,
      hours: 1,
      moments: ["evening"],
      tags: ["ville", "romantique"],
      highlight: "Coucher de soleil sur Las Setas",
      repeatable: true,
    },
    {
      id: "triana",
      name: "Triana et son marché",
      description: "Céramiques, marché couvert au bord du fleuve et vue sur la ville.",
      category: "quartier",
      emoji: "🏺",
      cost: 0,
      hours: 2,
      area: "Triana",
      moments: ["morning", "afternoon"],
      tags: ["culture", "gastronomie"],
    },
    {
      id: "torre-oro",
      name: "Tour de l'Or",
      description: "Tour de guet du XIIIᵉ siècle au bord du Guadalquivir, petit musée naval.",
      category: "musee",
      emoji: "🗼",
      cost: 3,
      hours: 1,
      area: "Arenal",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "banos-arabes",
      name: "Bains arabes",
      description: "Hammam aux chandelles dans une maison mudéjare, massage en option.",
      category: "detente",
      emoji: "🛁",
      cost: 40,
      hours: 1.5,
      area: "Santa Cruz",
      moments: ["afternoon"],
      tags: ["detente", "romantique"],
    },
    {
      id: "kayak-seville",
      name: "Kayak sur le Guadalquivir",
      description: "Pagayer au pied de la Tour de l'Or et des ponts de la ville.",
      category: "aventure",
      emoji: "🛶",
      cost: 25,
      hours: 2,
      moments: ["morning"],
      tags: ["aventure", "nature"],
    },
    {
      id: "flamenco-seville",
      name: "Spectacle de flamenco",
      description: "Guitare, chant et danse dans une petite salle : l'émotion à un mètre de toi.",
      category: "evenement",
      emoji: "💃",
      cost: 25,
      hours: 1.5,
      moments: ["evening"],
      tags: ["culture", "festivals", "romantique"],
      highlight: "Une soirée flamenco",
    },
    {
      id: "tapas-seville",
      name: "Tournée des bars à tapas",
      description: "De comptoir en comptoir : jamón, salmorejo, espinacas con garbanzos.",
      category: "food",
      emoji: "🍤",
      cost: 25,
      hours: 2.5,
      moments: ["evening"],
      tags: ["gastronomie", "fete"],
      repeatable: true,
    },
    {
      id: "alameda",
      name: "Soirée sur l'Alameda de Hércules",
      description: "La place la plus vivante le soir : terrasses, bars et musique.",
      category: "nightlife",
      emoji: "🍹",
      cost: 20,
      hours: 3,
      area: "Alameda de Hércules",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit sur l'Alameda",
      repeatable: true,
    },
    {
      id: "cordoue",
      name: "Excursion à Cordoue",
      description: "La Mezquita, forêt de colonnes et d'arcs rouges et blancs, à 45 min de train.",
      category: "excursion",
      emoji: "🕌",
      cost: 50,
      hours: 8,
      moments: ["morning"],
      tags: ["culture"],
      highlight: "La Mezquita de Cordoue",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-el-comercio",
      name: "Bar El Comercio",
      description: "Chocolat chaud et churros dans un bar de 1904 resté dans son jus.",
      cuisine: "Churros & café",
      emoji: "☕",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      area: "Arenal",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-puerta-carne",
      name: "Freiduría Puerta de la Carne",
      description: "Cornets de poissons frits à emporter, à manger dans les jardins voisins.",
      cuisine: "Poissons frits",
      emoji: "🐟",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Santa Cruz",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-casa-morales",
      name: "Casa Morales",
      description: "Bodega de 1850 avec ses grandes jarres, tapas écrites à la craie.",
      cuisine: "Tapas",
      emoji: "🍷",
      kind: "bar",
      isLocal: true,
      priceLevel: 1,
      cost: 18,
      area: "Arenal",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-rinconcillo",
      name: "El Rinconcillo",
      description: "Le plus vieux bar de Séville (1670) : l'addition s'écrit à la craie sur le comptoir.",
      cuisine: "Tapas",
      emoji: "🍤",
      kind: "bar",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "fete"],
      real: true,
    },
    {
      id: "r-eslava",
      name: "Eslava",
      description: "Tapas créatives primées dans le quartier de San Lorenzo. Arrive tôt.",
      cuisine: "Tapas d'auteur",
      emoji: "🍳",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
    {
      id: "r-abantal",
      name: "Abantal",
      description: "Table étoilée qui revisite la cuisine andalouse en menu dégustation.",
      cuisine: "Cuisine andalouse d'auteur",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 90,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(37.3886, -5.9923),
    zoom: 14,
    neighborhoods: {
      "Santa Cruz": p(37.3853, -5.9886),
      Triana: p(37.3858, -6.0023),
      "Alameda de Hércules": p(37.3995, -5.9938),
      Arenal: p(37.3855, -5.9965),
    },
    places: {
      alcazar: p(37.3831, -5.9903),
      "cathedrale-seville": p(37.3858, -5.9931),
      "plaza-espana": p(37.3772, -5.9869),
      "santa-cruz": p(37.3854, -5.9884),
      setas: p(37.3933, -5.9917),
      triana: p(37.3858, -6.0023),
      "torre-oro": p(37.3824, -5.9964),
      "banos-arabes": p(37.3867, -5.9892),
      "kayak-seville": p(37.38, -5.996),
      "flamenco-seville": p(37.3918, -5.9905),
      "tapas-seville": p(37.3905, -5.9945),
      alameda: p(37.3995, -5.9938),
      cordoue: p(37.8789, -4.7794),
      "r-el-comercio": p(37.3918, -5.9937),
      "r-puerta-carne": p(37.3869, -5.9849),
      "r-casa-morales": p(37.3868, -5.9951),
      "r-rinconcillo": p(37.3934, -5.9885),
      "r-eslava": p(37.3985, -5.9974),
      "r-abantal": p(37.3885, -5.9775),
    },
  },
  source: "demo",
};
