import type { DestinationProfile } from "../../types";

export const split: DestinationProfile = {
  id: "split",
  name: "Split",
  country: "Croatie",
  countryCode: "HR",
  tagline: "Un palais romain, des îles turquoise et des nuits d'été.",
  description:
    "Porte d'entrée des îles dalmates : vieille ville dans un palais antique, criques cristallines et fêtes en bord de mer.",
  fallbackGradient: "from-cyan-300 via-teal-500 to-blue-800",
  type: "balneaire",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 30, standard: 60, confort: 120 },
    foodPerDay: { eco: 25, standard: 40, confort: 70 },
    localTransportPerDay: 6,
  },
  access: {
    mode: "avion",
    from: "Paris",
    durationLabel: "2 h 15",
    durationHours: 2.25,
    roundTripPerPerson: 190,
  },
  localTransport: "Vieille ville à pied, bateaux et ferries pour les îles",
  idealDays: { min: 4, max: 9 },
  bestMonths: [5, 6, 7, 8, 9],
  styles: { plage: 3, fete: 3, nature: 3, aventure: 3, detente: 2, culture: 2, romantique: 2, festivals: 2 },
  ambiances: { festive: 3, aventureuse: 3, sociale: 3, calme: 1, romantique: 2 },
  strengths: { plages: 3, nature: 3, "vie-nocturne": 2, activites: 3, securite: 3 },
  neighborhoods: [
    {
      name: "Palais de Dioclétien",
      vibe: "dormir dans une ville antique",
      tiers: ["standard", "confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Bačvice",
      vibe: "à deux pas de la plage et des bars",
      tiers: ["eco", "standard"],
      tags: ["plage", "fete"],
    },
    {
      name: "Varoš",
      vibe: "calme, au pied de la colline Marjan",
      tiers: ["eco", "standard"],
      tags: ["detente", "nature"],
    },
  ],
  activities: [
    {
      id: "diocletien",
      name: "Palais de Dioclétien",
      description: "Une vieille ville entière bâtie dans un palais romain.",
      category: "monument",
      emoji: "🏛️",
      cost: 10,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
      highlight: "Le palais de Dioclétien",
    },
    {
      id: "marjan",
      name: "Randonnée sur la colline Marjan",
      description: "Pinèdes, chapelles et vue sur les îles.",
      category: "nature",
      emoji: "🌲",
      cost: 0,
      hours: 2.5,
      moments: ["morning"],
      tags: ["nature", "aventure"],
      repeatable: true,
    },
    {
      id: "bacvice",
      name: "Plage de Bačvice & picigin",
      description: "Le sport local : jongler avec une balle les pieds dans l'eau.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 3,
      moments: ["afternoon"],
      tags: ["plage", "fete", "detente"],
      repeatable: true,
    },
    {
      id: "kayak-split",
      name: "Kayak de mer vers les grottes",
      description: "Pagayer le long des falaises.",
      category: "aventure",
      emoji: "🛶",
      cost: 40,
      hours: 3,
      moments: ["morning"],
      tags: ["aventure", "nature", "plage"],
      highlight: "Kayak dans les grottes marines",
    },
    {
      id: "riva",
      name: "Coucher de soleil sur la Riva",
      description: "La promenade du front de mer, glace à la main.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      moments: ["evening"],
      tags: ["romantique", "detente"],
      repeatable: true,
    },
    {
      id: "boat-party",
      name: "Boat party en mer",
      description: "DJ, baignade et soleil sur un bateau.",
      category: "nightlife",
      emoji: "🛥️",
      cost: 55,
      hours: 4,
      moments: ["afternoon"],
      tags: ["fete", "plage"],
      highlight: "Boat party",
    },
    {
      id: "bars-split",
      name: "Bars de la vieille ville",
      description: "Des terrasses cachées entre les murs romains.",
      category: "nightlife",
      emoji: "🍹",
      cost: 20,
      hours: 3,
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "club-split",
      name: "Club en plein air à Bačvice",
      description: "La fête jusqu'au lever du soleil sur la plage.",
      category: "nightlife",
      emoji: "🎉",
      cost: 20,
      hours: 4,
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit sur la plage",
    },
    {
      id: "hvar",
      name: "Journée à Hvar",
      description: "Ferry vers l'île la plus festive et ensoleillée.",
      category: "excursion",
      emoji: "⛴️",
      cost: 35,
      hours: 9,
      moments: ["morning"],
      tags: ["plage", "fete", "romantique"],
      highlight: "Une journée à Hvar",
      fullDay: true,
    },
    {
      id: "krka",
      name: "Cascades du parc national de Krka",
      description: "Baignade (selon saison) au pied des chutes.",
      category: "excursion",
      emoji: "💦",
      cost: 45,
      hours: 8,
      moments: ["morning"],
      tags: ["nature", "aventure"],
      highlight: "Les cascades de Krka",
      fullDay: true,
    },
    {
      id: "blue-lagoon",
      name: "Tour en bateau au Blue Lagoon",
      description: "Snorkeling dans une eau irréelle.",
      category: "excursion",
      emoji: "🐠",
      cost: 60,
      hours: 8,
      moments: ["morning"],
      tags: ["plage", "aventure", "detente"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "burek",
      name: "Pekara (boulangerie)",
      description: "Burek au fromage, le snack des Dalmates.",
      priceLevel: 1,
      cost: 5,
      meals: ["lunch"],
      tags: [],
    },
    {
      id: "konoba",
      name: "Konoba familiale",
      description: "Poisson grillé, blettes et vin de l'île.",
      priceLevel: 2,
      cost: 28,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
    },
    {
      id: "beach-bar",
      name: "Bar de plage",
      description: "Salades, grillades et cocktails les pieds dans l'eau.",
      priceLevel: 1,
      cost: 15,
      meals: ["lunch", "dinner"],
      tags: ["plage", "fete"],
    },
    {
      id: "gastro-hr",
      name: "Restaurant de fruits de mer en terrasse",
      description: "Plateaux de l'Adriatique face au port.",
      priceLevel: 3,
      cost: 60,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
    },
  ],
  source: "demo",
};
