import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const tallinn: DestinationProfile = {
  id: "tallinn",
  name: "Tallinn",
  country: "Estonie",
  countryCode: "EE",
  iata: "TLL",
  tagline: "Une ville médiévale de conte de fées au bord de la Baltique.",
  description:
    "Remparts, tours pointues et ruelles pavées parfaitement conservés, avec un côté ultra-moderne : friches créatives, saunas, forêts et Helsinki à deux heures de ferry.",
  fallbackGradient: "from-sky-300 via-blue-600 to-slate-800",
  type: "ville",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 25, standard: 60, confort: 120 },
    localTransportPerDay: 4,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h 50",
        durationHours: 2.85,
        roundTripPerPerson: 200,
        details: "Vol direct ou avec escale, tram jusqu'au centre en 15 min",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "La vieille ville est piétonne et compacte" },
    { mode: "tram", description: "Trams et bus, gratuits pour les habitants mais pas chers pour toi" },
    { mode: "ferry", description: "Ferries vers Helsinki en 2 h" },
  ],
  idealDays: { min: 2, max: 5 },
  bestMonths: [5, 6, 7, 8, 9, 12],
  styles: { culture: 3, romantique: 3, ville: 2, nature: 2, detente: 2, fete: 2, gastronomie: 1 },
  ambiances: { romantique: 3, calme: 2, authentique: 2, sociale: 2 },
  strengths: { culture: 3, securite: 3, prix: 2, nature: 2, rapidite: 2 },
  neighborhoods: [
    {
      name: "Vieille ville",
      vibe: "médiévale, dans les remparts",
      tiers: ["standard", "confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Kalamaja",
      vibe: "maisons en bois, cafés et friches créatives",
      tiers: ["eco", "standard"],
      tags: ["fete", "shopping"],
    },
    { name: "Kadriorg", vibe: "parc, palais et calme", tiers: ["standard", "confort"], tags: ["detente"] },
  ],
  activities: [
    {
      id: "vieille-ville-tallinn",
      name: "Vieille ville et place de l'hôtel de ville",
      description: "Une des villes médiévales les mieux conservées d'Europe.",
      category: "quartier",
      emoji: "🏰",
      cost: 0,
      hours: 2,
      area: "Vieille ville",
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
      highlight: "La vieille ville de Tallinn",
    },
    {
      id: "toompea",
      name: "Colline de Toompea et ses belvédères",
      description: "Les toits rouges et les flèches de la ville basse, vus d'en haut.",
      category: "panorama",
      emoji: "🌇",
      cost: 0,
      hours: 1.5,
      area: "Vieille ville",
      moments: ["morning", "afternoon"],
      tags: ["romantique", "ville"],
    },
    {
      id: "nevski",
      name: "Cathédrale Alexandre-Nevski",
      description: "Coupoles en bulbe et icônes dorées au sommet de Toompea.",
      category: "monument",
      emoji: "⛪",
      cost: 0,
      hours: 1,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "kgb",
      name: "Musée de la KGB",
      description: "Le poste d'écoute secret au 23ᵉ étage de l'hôtel Viru.",
      category: "musee",
      emoji: "🕵️",
      cost: 15,
      hours: 1,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "lennusadam",
      name: "Musée maritime Lennusadam",
      description: "Hangars à hydravions, sous-marin à visiter et brise-glace.",
      category: "musee",
      emoji: "⚓",
      cost: 20,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture", "aventure"],
    },
    {
      id: "telliskivi",
      name: "Telliskivi Creative City",
      description: "Anciennes usines : boutiques de créateurs, street art et food trucks.",
      category: "shopping",
      emoji: "🎨",
      cost: 0,
      hours: 2,
      area: "Kalamaja",
      moments: ["afternoon"],
      tags: ["shopping", "ville"],
    },
    {
      id: "kadriorg",
      name: "Palais et parc de Kadriorg",
      description: "Palais baroque de Pierre le Grand et jardins.",
      category: "detente",
      emoji: "🌳",
      cost: 10,
      hours: 2,
      area: "Kadriorg",
      moments: ["afternoon"],
      tags: ["detente", "culture"],
    },
    {
      id: "sauna-tallinn",
      name: "Sauna estonien",
      description: "Le rituel local : sauna chaud, puis plongeon froid.",
      category: "detente",
      emoji: "🧖",
      cost: 20,
      hours: 2,
      moments: ["afternoon"],
      tags: ["detente"],
    },
    {
      id: "linnahall",
      name: "Coucher de soleil sur le toit de la Linnahall",
      description: "L'étrange amphithéâtre soviétique face à la mer.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1,
      moments: ["evening"],
      tags: ["romantique"],
      repeatable: true,
    },
    {
      id: "bars-tallinn",
      name: "Bars de la vieille ville et de Telliskivi",
      description: "Caves médiévales, bars à bière artisanale et rooftops.",
      category: "nightlife",
      emoji: "🍻",
      cost: 15,
      hours: 3,
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit à Tallinn",
      repeatable: true,
    },
    {
      id: "helsinki",
      name: "Excursion à Helsinki",
      description: "Deux heures de ferry pour une journée dans la capitale finlandaise.",
      category: "excursion",
      emoji: "⛴️",
      cost: 50,
      hours: 10,
      moments: ["morning"],
      tags: ["culture", "ville"],
      fullDay: true,
    },
    {
      id: "lahemaa",
      name: "Parc national de Lahemaa",
      description: "Tourbières sur pilotis, forêts de pins et manoirs baltes.",
      category: "excursion",
      emoji: "🌲",
      cost: 30,
      hours: 8,
      moments: ["morning"],
      tags: ["nature", "aventure"],
      highlight: "Les tourbières de Lahemaa",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-iii-draakon",
      name: "III Draakon",
      description: "Taverne médiévale à la bougie : soupe d'élan et pâtés, sans couverts.",
      cuisine: "Taverne médiévale",
      emoji: "🕯️",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 5,
      area: "Vieille ville",
      meals: ["lunch", "dinner"],
      tags: ["fete"],
      real: true,
    },
    {
      id: "r-f-hoone",
      name: "F-Hoone",
      description: "Cantine branchée dans une ancienne usine de Telliskivi.",
      cuisine: "Bistrot",
      emoji: "🏭",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 18,
      area: "Kalamaja",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-rataskaevu-16",
      name: "Rataskaevu 16",
      description: "Cuisine estonienne réconfortante, réputée pour son élan braisé.",
      cuisine: "Cuisine estonienne",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      area: "Vieille ville",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
    {
      id: "r-olde-hansa",
      name: "Olde Hansa",
      description: "Festin médiéval en costume, bière au miel et plats d'époque.",
      cuisine: "Cuisine médiévale",
      emoji: "🍖",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 40,
      area: "Vieille ville",
      meals: ["dinner"],
      tags: ["fete"],
      real: true,
    },
  ],
  geo: {
    center: p(59.437, 24.7536),
    zoom: 14,
    neighborhoods: {
      "Vieille ville": p(59.437, 24.745),
      Kalamaja: p(59.445, 24.733),
      Kadriorg: p(59.438, 24.791),
    },
    places: {
      "vieille-ville-tallinn": p(59.437, 24.745),
      toompea: p(59.437, 24.737),
      nevski: p(59.436, 24.739),
      kgb: p(59.436, 24.755),
      lennusadam: p(59.4515, 24.739),
      telliskivi: p(59.44, 24.73),
      kadriorg: p(59.438, 24.791),
      "sauna-tallinn": p(59.445, 24.73),
      linnahall: p(59.446, 24.752),
      "bars-tallinn": p(59.438, 24.744),
      helsinki: p(60.1699, 24.9384),
      lahemaa: p(59.58, 25.8),
      "r-iii-draakon": p(59.4371, 24.7452),
      "r-f-hoone": p(59.44, 24.729),
      "r-rataskaevu-16": p(59.4372, 24.7425),
      "r-olde-hansa": p(59.4368, 24.7458),
    },
  },
  source: "demo",
};
