import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const tbilissi: DestinationProfile = {
  id: "tbilissi",
  name: "Tbilissi",
  country: "Géorgie",
  countryCode: "GE",
  iata: "TBS",
  tagline: "Balcons en bois, bains de soufre, vin en amphore et techno.",
  description:
    "La pépite qui monte : une vieille ville aux balcons ciselés, des bains chauds sulfureux, la cuisine la plus généreuse du Caucase, du vin né il y a 8 000 ans et une scène électro légendaire. Et des prix doux.",
  fallbackGradient: "from-rose-300 via-red-600 to-violet-900",
  type: "ville",
  costLevel: 1,
  costs: {
    accommodationPerNight: { eco: 15, standard: 40, confort: 90 },
    localTransportPerDay: 3,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "4 h 45",
        durationHours: 4.75,
        roundTripPerPerson: 280,
        details: "Vol direct ou avec escale (souvent via Kutaisi, moins cher), taxi jusqu'au centre",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Métro soviétique très profond et bon marché" },
    { mode: "taxi", description: "VTC (Bolt, Yandex) pour quelques lari" },
    { mode: "marche", description: "La vieille ville est à parcourir à pied (ça grimpe)" },
  ],
  idealDays: { min: 4, max: 8 },
  bestMonths: [5, 6, 9, 10],
  styles: { culture: 3, gastronomie: 3, fete: 3, nature: 2, aventure: 2, ville: 2, romantique: 2 },
  ambiances: { authentique: 3, economique: 3, festive: 3, aventureuse: 3, sociale: 3 },
  strengths: { prix: 3, gastronomie: 3, "vie-nocturne": 3, culture: 2, nature: 2 },
  neighborhoods: [
    {
      name: "Vieille ville",
      vibe: "balcons en bois, églises et bains",
      tiers: ["eco", "standard", "confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Sololaki",
      vibe: "maisons Art nouveau et cafés",
      tiers: ["eco", "standard"],
      tags: ["culture", "gastronomie"],
    },
    { name: "Chugureti", vibe: "Fabrika, bars et street art", tiers: ["eco"], tags: ["fete"] },
  ],
  activities: [
    {
      id: "vieille-ville-tbilissi",
      name: "Balade dans la vieille ville",
      description: "Ruelles pavées, balcons colorés et églises orthodoxes.",
      category: "quartier",
      emoji: "🏘️",
      cost: 0,
      hours: 2,
      area: "Vieille ville",
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
      highlight: "Les balcons de la vieille ville",
    },
    {
      id: "sameba",
      name: "Cathédrale de la Sainte-Trinité",
      description: "L'immense cathédrale aux dômes dorés qui domine la ville.",
      category: "monument",
      emoji: "⛪",
      cost: 0,
      hours: 1,
      moments: ["morning"],
      tags: ["culture"],
    },
    {
      id: "dry-bridge",
      name: "Marché aux puces du Dry Bridge",
      description: "Objets soviétiques, bijoux anciens et tableaux.",
      category: "shopping",
      emoji: "🛍️",
      cost: 0,
      hours: 1.5,
      moments: ["morning"],
      tags: ["shopping"],
    },
    {
      id: "musee-national-ge",
      name: "Musée national de Géorgie",
      description: "Trésors d'or de la Colchide, le pays de la Toison d'or.",
      category: "musee",
      emoji: "🏺",
      cost: 10,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "narikala",
      name: "Forteresse de Narikala en téléphérique",
      description: "Téléphérique au-dessus du fleuve jusqu'aux remparts, vue imprenable.",
      category: "panorama",
      emoji: "🚡",
      cost: 3,
      hours: 1.5,
      area: "Vieille ville",
      moments: ["afternoon", "evening"],
      tags: ["ville", "romantique"],
      highlight: "Tbilissi depuis Narikala",
    },
    {
      id: "bains-soufre",
      name: "Bains de soufre d'Abanotubani",
      description: "Bains privés sous des coupoles de brique, gommage traditionnel.",
      category: "detente",
      emoji: "♨️",
      cost: 20,
      hours: 1.5,
      area: "Vieille ville",
      moments: ["afternoon"],
      tags: ["detente", "romantique"],
      highlight: "Les bains de soufre",
    },
    {
      id: "mtatsminda",
      name: "Coucher de soleil au parc Mtatsminda",
      description: "Funiculaire jusqu'au sommet, grande roue et ville illuminée.",
      category: "panorama",
      emoji: "🌅",
      cost: 3,
      hours: 2,
      moments: ["evening"],
      tags: ["romantique"],
      repeatable: true,
    },
    {
      id: "vin-qvevri",
      name: "Dégustation de vins en qvevri",
      description: "Vins ambrés vinifiés en amphores enterrées, la tradition géorgienne.",
      category: "food",
      emoji: "🍷",
      cost: 15,
      hours: 2,
      area: "Sololaki",
      moments: ["evening"],
      tags: ["gastronomie"],
      highlight: "Dégustation de vin géorgien",
    },
    {
      id: "fabrika",
      name: "Soirée à Fabrika",
      description: "Ancienne usine devenue auberge, bars et cour pleine de monde.",
      category: "nightlife",
      emoji: "🍻",
      cost: 10,
      hours: 3,
      area: "Chugureti",
      moments: ["evening"],
      tags: ["fete"],
      repeatable: true,
    },
    {
      id: "bassiani",
      name: "Nuit techno au Bassiani",
      description: "Club légendaire installé sous une piscine de stade soviétique.",
      category: "nightlife",
      emoji: "🎧",
      cost: 15,
      hours: 5,
      moments: ["evening"],
      tags: ["fete", "festivals"],
      highlight: "Nuit techno à Tbilissi",
    },
    {
      id: "mtskheta",
      name: "Mtskheta et le monastère de Jvari",
      description: "L'ancienne capitale sacrée au confluent de deux rivières.",
      category: "excursion",
      emoji: "⛰️",
      cost: 15,
      hours: 5,
      moments: ["morning"],
      tags: ["culture", "nature"],
    },
    {
      id: "kazbegi",
      name: "Excursion à Kazbegi",
      description: "La route militaire du Caucase jusqu'à l'église de Gergeti sous le mont Kazbek.",
      category: "excursion",
      emoji: "🏔️",
      cost: 40,
      hours: 11,
      moments: ["morning"],
      tags: ["nature", "aventure"],
      highlight: "L'église de Gergeti face au Kazbek",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-machakhela",
      name: "Machakhela",
      description: "Khachapuri (pain au fromage fondu) et khinkali (raviolis) à petit prix.",
      cuisine: "Cuisine géorgienne",
      emoji: "🧀",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-shavi-lomi",
      name: "Shavi Lomi",
      description: "Cuisine géorgienne créative dans une maison au jardin caché.",
      cuisine: "Cuisine géorgienne moderne",
      emoji: "🦁",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      area: "Chugureti",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
    {
      id: "r-barbarestan",
      name: "Barbarestan",
      description: "Recettes d'un livre de cuisine du XIXᵉ siècle, dans une cave chaleureuse.",
      cuisine: "Cuisine géorgienne",
      emoji: "📖",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      area: "Chugureti",
      meals: ["dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-cafe-littera",
      name: "Café Littera",
      description: "Jardin de la maison des écrivains, cuisine géorgienne réinventée.",
      cuisine: "Cuisine géorgienne d'auteur",
      emoji: "🌿",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 35,
      area: "Sololaki",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(41.6938, 44.8015),
    zoom: 13,
    neighborhoods: {
      "Vieille ville": p(41.691, 44.807),
      Sololaki: p(41.6905, 44.7985),
      Chugureti: p(41.7094, 44.8023),
    },
    places: {
      "vieille-ville-tbilissi": p(41.691, 44.807),
      sameba: p(41.6972, 44.8163),
      "dry-bridge": p(41.698, 44.806),
      "musee-national-ge": p(41.696, 44.8),
      narikala: p(41.6875, 44.8086),
      "bains-soufre": p(41.688, 44.811),
      mtatsminda: p(41.6947, 44.7866),
      "vin-qvevri": p(41.692, 44.803),
      fabrika: p(41.7094, 44.8023),
      bassiani: p(41.723, 44.79),
      mtskheta: p(41.842, 44.721),
      kazbegi: p(42.6627, 44.62),
      "r-machakhela": p(41.6935, 44.803),
      "r-shavi-lomi": p(41.709, 44.804),
      "r-barbarestan": p(41.711, 44.803),
      "r-cafe-littera": p(41.704, 44.79),
    },
  },
  source: "demo",
};
