import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const tokyo: DestinationProfile = {
  id: "tokyo",
  name: "Tokyo",
  country: "Japon",
  countryCode: "JP",
  iata: "TYO",
  tagline: "Néons, temples et ramen à 3 h du matin.",
  description:
    "Une mégapole qui mélange tout : sanctuaires paisibles, quartiers électriques, izakayas minuscules, manga, onsen et vue sur le mont Fuji. Dépaysement garanti, et étonnamment sûr.",
  fallbackGradient: "from-pink-400 via-rose-600 to-indigo-900",
  type: "ville",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 35, standard: 75, confort: 150 },
    localTransportPerDay: 8,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "14 h",
        durationHours: 14,
        roundTripPerPerson: 900,
        details: "Vol direct ou avec une escale, train ou bus jusqu'au centre en 1 h",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "Métro et trains d'une ponctualité parfaite (carte Suica)" },
    { mode: "marche", description: "Chaque quartier se découvre à pied" },
    { mode: "velo", description: "Vélos en location pour les quartiers résidentiels" },
  ],
  idealDays: { min: 7, max: 14 },
  bestMonths: [3, 4, 5, 10, 11],
  styles: { ville: 3, culture: 3, gastronomie: 3, shopping: 3, fete: 2, detente: 2, nature: 1, festivals: 2 },
  ambiances: { sociale: 2, authentique: 2, festive: 2, calme: 2, aventureuse: 2 },
  strengths: { securite: 3, culture: 3, gastronomie: 3, activites: 3, "vie-nocturne": 2 },
  neighborhoods: [
    {
      name: "Shinjuku",
      vibe: "pratique, néons et vie nocturne",
      tiers: ["eco", "standard", "confort"],
      tags: ["fete", "ville"],
    },
    {
      name: "Shibuya",
      vibe: "jeune, mode et le célèbre carrefour",
      tiers: ["standard", "confort"],
      tags: ["shopping", "fete"],
    },
    {
      name: "Asakusa",
      vibe: "le Tokyo traditionnel, moins cher",
      tiers: ["eco", "standard"],
      tags: ["culture"],
    },
    { name: "Ginza", vibe: "chic et central", tiers: ["confort"], tags: ["shopping", "gastronomie"] },
  ],
  activities: [
    {
      id: "senso-ji",
      name: "Temple Sensō-ji et rue Nakamise",
      description: "Le plus vieux temple de Tokyo, grande lanterne rouge et échoppes de snacks.",
      category: "monument",
      emoji: "⛩️",
      cost: 0,
      hours: 1.5,
      area: "Asakusa",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "Le temple Sensō-ji",
    },
    {
      id: "meiji",
      name: "Sanctuaire Meiji et Harajuku",
      description: "Forêt sacrée en pleine ville, puis la rue Takeshita et ses looks improbables.",
      category: "monument",
      emoji: "🌳",
      cost: 0,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture", "shopping"],
    },
    {
      id: "ueno",
      name: "Parc d'Ueno et musée national",
      description: "Le plus grand musée d'art japonais et, au printemps, les cerisiers.",
      category: "musee",
      emoji: "🌸",
      cost: 10,
      hours: 2.5,
      moments: ["morning"],
      tags: ["culture", "nature"],
    },
    {
      id: "tsukiji",
      name: "Marché extérieur de Tsukiji",
      description: "Sushi, omelette tamagoyaki et brochettes de fruits de mer dès le matin.",
      category: "food",
      emoji: "🍣",
      cost: 20,
      hours: 1.5,
      moments: ["morning"],
      tags: ["gastronomie"],
    },
    {
      id: "teamlab",
      name: "teamLab Planets",
      description: "Musée immersif où l'on marche pieds nus dans l'eau et la lumière.",
      category: "musee",
      emoji: "✨",
      cost: 25,
      hours: 2,
      moments: ["afternoon"],
      tags: ["culture"],
    },
    {
      id: "akihabara",
      name: "Akihabara, manga et jeux vidéo",
      description: "Salles d'arcade, figurines et maid cafés sur plusieurs étages.",
      category: "shopping",
      emoji: "🎮",
      cost: 0,
      hours: 2.5,
      moments: ["afternoon"],
      tags: ["shopping", "ville"],
    },
    {
      id: "shimokitazawa",
      name: "Friperies de Shimokitazawa",
      description: "Le quartier vintage et indé, cafés et petites salles de concert.",
      category: "shopping",
      emoji: "👕",
      cost: 0,
      hours: 2,
      moments: ["afternoon"],
      tags: ["shopping"],
    },
    {
      id: "onsen-tokyo",
      name: "Bain chaud au sentō ou à l'onsen",
      description: "Le rituel japonais du bain, pour récupérer après une journée de marche.",
      category: "detente",
      emoji: "♨️",
      cost: 15,
      hours: 2,
      moments: ["afternoon"],
      tags: ["detente"],
    },
    {
      id: "shibuya-sky",
      name: "Shibuya Crossing et Shibuya Sky",
      description: "Le carrefour le plus fréquenté du monde, vu d'en haut au coucher du soleil.",
      category: "panorama",
      emoji: "🌆",
      cost: 20,
      hours: 1.5,
      area: "Shibuya",
      moments: ["evening"],
      tags: ["ville"],
      highlight: "Tokyo illuminé depuis Shibuya Sky",
    },
    {
      id: "karaoke",
      name: "Karaoké en cabine privée",
      description: "La soirée la plus japonaise qui soit, entre amis.",
      category: "evenement",
      emoji: "🎤",
      cost: 15,
      hours: 2,
      area: "Shibuya",
      moments: ["evening"],
      tags: ["fete"],
    },
    {
      id: "golden-gai",
      name: "Golden Gai et Omoide Yokocho",
      description: "Des ruelles de bars de six places et de brochettes fumantes.",
      category: "nightlife",
      emoji: "🏮",
      cost: 25,
      hours: 3,
      area: "Shinjuku",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit dans les ruelles de Shinjuku",
      repeatable: true,
    },
    {
      id: "hakone",
      name: "Excursion à Hakone et vue sur le Fuji",
      description: "Téléphérique au-dessus des volcans, bateau sur le lac et onsen en plein air.",
      category: "excursion",
      emoji: "🗻",
      cost: 50,
      hours: 10,
      moments: ["morning"],
      tags: ["nature", "detente"],
      highlight: "Le mont Fuji depuis Hakone",
      fullDay: true,
    },
    {
      id: "nikko",
      name: "Excursion à Nikkō",
      description: "Temples dorés au milieu des cèdres et cascades.",
      category: "excursion",
      emoji: "🏯",
      cost: 40,
      hours: 10,
      moments: ["morning"],
      tags: ["culture", "nature"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-uobei",
      name: "Uobei Shibuya",
      description: "Sushis commandés sur tablette et livrés par un petit train, à prix mini.",
      cuisine: "Sushi",
      emoji: "🍣",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Shibuya",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-fuunji",
      name: "Fuunji",
      description: "Tsukemen (nouilles à tremper) au bouillon épais, file d'attente devant.",
      cuisine: "Ramen",
      emoji: "🍜",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 10,
      area: "Shinjuku",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-ichiran",
      name: "Ichiran Shibuya",
      description: "Ramen tonkotsu dégustés seul dans sa cabine, ouvert 24 h/24.",
      cuisine: "Ramen",
      emoji: "🍜",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Shibuya",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-maisen",
      name: "Tonkatsu Maisen Aoyama",
      description: "Côtelette de porc panée dans un ancien bain public.",
      cuisine: "Tonkatsu",
      emoji: "🥩",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-gonpachi",
      name: "Gonpachi Nishi-Azabu",
      description: "Izakaya en bois qui a inspiré Kill Bill : yakitori et soba.",
      cuisine: "Izakaya",
      emoji: "🏮",
      kind: "bar",
      isLocal: true,
      priceLevel: 2,
      cost: 35,
      meals: ["dinner"],
      tags: ["fete"],
      real: true,
    },
    {
      id: "r-kyubey",
      name: "Kyubey Ginza",
      description: "Comptoir de sushi réputé où le chef prépare chaque pièce devant toi.",
      cuisine: "Sushi omakase",
      emoji: "🍱",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 100,
      area: "Ginza",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(35.6812, 139.7671),
    zoom: 11,
    neighborhoods: {
      Shinjuku: p(35.6938, 139.7034),
      Shibuya: p(35.6595, 139.7005),
      Asakusa: p(35.7148, 139.7967),
      Ginza: p(35.6717, 139.765),
    },
    places: {
      "senso-ji": p(35.7148, 139.7967),
      meiji: p(35.6764, 139.6993),
      ueno: p(35.7188, 139.7765),
      tsukiji: p(35.6654, 139.7707),
      teamlab: p(35.649, 139.7898),
      akihabara: p(35.6984, 139.7731),
      shimokitazawa: p(35.6613, 139.668),
      "onsen-tokyo": p(35.628, 139.775),
      "shibuya-sky": p(35.6585, 139.7022),
      karaoke: p(35.66, 139.699),
      "golden-gai": p(35.694, 139.7045),
      hakone: p(35.2324, 139.1069),
      nikko: p(36.758, 139.599),
      "r-uobei": p(35.66, 139.6985),
      "r-fuunji": p(35.6873, 139.6975),
      "r-ichiran": p(35.6612, 139.701),
      "r-maisen": p(35.668, 139.711),
      "r-gonpachi": p(35.6575, 139.724),
      "r-kyubey": p(35.668, 139.761),
    },
  },
  source: "demo",
};
