import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const valence: DestinationProfile = {
  id: "valence",
  name: "Valence",
  country: "Espagne",
  countryCode: "ES",
  iata: "VLC",
  tagline: "Plage en ville, paella d'origine et architecture futuriste.",
  description:
    "Le parfait combo ville-plage : vieille ville animée, Cité des Arts et des Sciences, 9 km de jardins à vélo et la vraie paella au bord de l'Albufera.",
  fallbackGradient: "from-cyan-300 via-sky-500 to-orange-500",
  type: "mixte",
  costLevel: 2,
  costs: {
    accommodationPerNight: { eco: 25, standard: 55, confort: 110 },
    localTransportPerDay: 5,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "1 h 55",
        durationHours: 1.9,
        roundTripPerPerson: 120,
        details: "Vol direct, métro jusqu'au centre en 25 min",
      },
    ],
  },
  localMobility: [
    { mode: "velo", description: "Ville plate et jardins du Turia : le vélo est roi (Valenbisi)" },
    { mode: "metro", description: "Métro et tram vers la plage et l'aéroport" },
    { mode: "marche", description: "La vieille ville et Ruzafa se font à pied" },
    { mode: "bus", description: "Bus vers l'Albufera et les plages du sud" },
  ],
  idealDays: { min: 3, max: 6 },
  bestMonths: [3, 4, 5, 6, 9, 10],
  styles: { plage: 3, ville: 3, gastronomie: 3, fete: 2, detente: 3, culture: 2, festivals: 3, aventure: 1 },
  ambiances: { sociale: 3, festive: 2, calme: 2, authentique: 2, economique: 3 },
  strengths: { plages: 3, gastronomie: 3, prix: 3, securite: 3, rapidite: 3, "vie-nocturne": 2 },
  neighborhoods: [
    {
      name: "El Carmen",
      vibe: "vieille ville, street art et bars à tapas",
      tiers: ["eco", "standard"],
      tags: ["culture", "fete"],
    },
    {
      name: "Ruzafa",
      vibe: "le quartier branché : cafés, brunchs et bars",
      tiers: ["standard"],
      tags: ["fete", "shopping"],
    },
    {
      name: "El Cabanyal",
      vibe: "ancien quartier de pêcheurs, à deux pas de la plage",
      tiers: ["eco", "standard"],
      tags: ["plage", "detente"],
    },
    {
      name: "Ciutat Vella",
      vibe: "central, près de la cathédrale",
      tiers: ["confort"],
      tags: ["culture", "romantique"],
    },
  ],
  activities: [
    {
      id: "cac",
      name: "Cité des Arts et des Sciences",
      description: "Les bâtiments blancs futuristes de Calatrava, entre bassins et jardins.",
      category: "monument",
      emoji: "🛸",
      cost: 0,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
      highlight: "La Cité des Arts et des Sciences",
    },
    {
      id: "oceanografic",
      name: "Oceanogràfic",
      description: "Le plus grand aquarium d'Europe : requins, bélugas et tunnels sous-marins.",
      category: "musee",
      emoji: "🐬",
      cost: 33,
      hours: 3,
      moments: ["morning", "afternoon"],
      tags: ["nature", "culture"],
    },
    {
      id: "turia",
      name: "Vélo dans les jardins du Turia",
      description: "9 km de parc dans l'ancien lit du fleuve, de la vieille ville à la Cité des Arts.",
      category: "nature",
      emoji: "🚲",
      cost: 6,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["nature", "detente", "aventure"],
      repeatable: true,
    },
    {
      id: "mercado-central",
      name: "Marché central",
      description: "Halle moderniste de 1928, l'un des plus grands marchés frais d'Europe.",
      category: "food",
      emoji: "🧺",
      cost: 10,
      hours: 1,
      area: "Ciutat Vella",
      moments: ["morning"],
      tags: ["gastronomie"],
    },
    {
      id: "lonja",
      name: "La Lonja de la Seda",
      description: "Bourse de la soie gothique classée à l'Unesco, colonnes torsadées.",
      category: "monument",
      emoji: "🏛️",
      cost: 2,
      hours: 1,
      area: "Ciutat Vella",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "micalet",
      name: "Cathédrale et tour du Micalet",
      description: "207 marches pour une vue à 360° sur la ville et la mer.",
      category: "panorama",
      emoji: "🗼",
      cost: 9,
      hours: 1.5,
      area: "Ciutat Vella",
      moments: ["morning", "afternoon"],
      tags: ["culture", "ville"],
    },
    {
      id: "carmen",
      name: "Street art dans le quartier d'El Carmen",
      description: "Façades peintes, placettes et remparts médiévaux.",
      category: "quartier",
      emoji: "🎨",
      cost: 0,
      hours: 2,
      area: "El Carmen",
      moments: ["morning", "afternoon"],
      tags: ["ville", "culture"],
    },
    {
      id: "malvarrosa",
      name: "Plage de la Malvarrosa",
      description: "Sable fin, promenade et chiringuitos à 20 minutes du centre.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 3.5,
      area: "El Cabanyal",
      moments: ["afternoon"],
      tags: ["plage", "detente"],
      highlight: "Après-midi à la Malvarrosa",
      repeatable: true,
    },
    {
      id: "paddle-valence",
      name: "Paddle à la plage de la Patacona",
      description: "Location de paddle ou cours sur une mer souvent calme.",
      category: "aventure",
      emoji: "🏄",
      cost: 25,
      hours: 2,
      moments: ["morning"],
      tags: ["aventure", "plage"],
    },
    {
      id: "albufera",
      name: "Coucher de soleil en barque sur l'Albufera",
      description: "Lagune et rizières où est née la paella, balade en barque au crépuscule.",
      category: "nature",
      emoji: "🌅",
      cost: 10,
      hours: 3,
      moments: ["afternoon"],
      tags: ["nature", "romantique", "detente"],
      highlight: "Coucher de soleil sur l'Albufera",
    },
    {
      id: "ruzafa-soiree",
      name: "Soirée à Ruzafa",
      description: "Le quartier le plus vivant le soir : bars à cocktails et terrasses.",
      category: "nightlife",
      emoji: "🍹",
      cost: 20,
      hours: 3,
      area: "Ruzafa",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit à Ruzafa",
      repeatable: true,
    },
    {
      id: "marina-valence",
      name: "Clubs et terrasses de la Marina",
      description: "Clubs en bord de mer autour du port, ambiance festive l'été.",
      category: "nightlife",
      emoji: "🎉",
      cost: 25,
      hours: 3.5,
      moments: ["evening"],
      tags: ["fete", "plage"],
    },
    {
      id: "carmen-bars",
      name: "Tapas et bars d'El Carmen",
      description: "Petites places animées pour grignoter et boire un agua de Valencia.",
      category: "food",
      emoji: "🍤",
      cost: 20,
      hours: 2,
      area: "El Carmen",
      moments: ["evening"],
      tags: ["gastronomie", "fete"],
    },
  ],
  restaurants: [
    {
      id: "r-santa-catalina",
      name: "Horchatería Santa Catalina",
      description: "Horchata (lait de souchet) et fartons dans une salle d'azulejos de 1836.",
      cuisine: "Horchata & pâtisseries",
      emoji: "🥛",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      area: "Ciutat Vella",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-la-pascuala",
      name: "Bodega La Pascuala",
      description: "Bocadillos géants et bière pression dans une bodega de quartier depuis 1920.",
      cuisine: "Bocadillos",
      emoji: "🥖",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 9,
      area: "El Cabanyal",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-central-bar",
      name: "Central Bar",
      description: "Le comptoir du chef Ricard Camarena dans le Marché central : tapas et bocadillos.",
      cuisine: "Tapas de marché",
      emoji: "🍤",
      kind: "bar",
      isLocal: true,
      priceLevel: 1,
      cost: 16,
      area: "Ciutat Vella",
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-casa-montana",
      name: "Casa Montaña",
      description: "Taverne de 1836 aux tonneaux de vin, anchois et tapas de la mer.",
      cuisine: "Tapas",
      emoji: "🍷",
      kind: "bar",
      isLocal: true,
      priceLevel: 2,
      cost: 28,
      area: "El Cabanyal",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
    {
      id: "r-la-pepica",
      name: "La Pepica",
      description: "Paella valencienne au feu de bois face à la plage, adorée d'Hemingway.",
      cuisine: "Paella",
      emoji: "🥘",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 35,
      area: "El Cabanyal",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "plage"],
      real: true,
    },
  ],
  geo: {
    center: p(39.4699, -0.3763),
    zoom: 13,
    neighborhoods: {
      "El Carmen": p(39.4786, -0.3794),
      Ruzafa: p(39.4623, -0.3746),
      "El Cabanyal": p(39.4668, -0.329),
      "Ciutat Vella": p(39.4753, -0.3767),
    },
    places: {
      cac: p(39.4546, -0.351),
      oceanografic: p(39.453, -0.348),
      turia: p(39.474, -0.37),
      "mercado-central": p(39.4735, -0.379),
      lonja: p(39.4743, -0.3783),
      micalet: p(39.4755, -0.3753),
      carmen: p(39.4786, -0.3794),
      malvarrosa: p(39.478, -0.324),
      "paddle-valence": p(39.49, -0.324),
      albufera: p(39.333, -0.352),
      "ruzafa-soiree": p(39.463, -0.375),
      "marina-valence": p(39.462, -0.325),
      "carmen-bars": p(39.4775, -0.3785),
      "r-santa-catalina": p(39.475, -0.377),
      "r-la-pascuala": p(39.4686, -0.33),
      "r-central-bar": p(39.4736, -0.3793),
      "r-casa-montana": p(39.4668, -0.329),
      "r-la-pepica": p(39.4648, -0.324),
    },
  },
  source: "demo",
};
