import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const venise: DestinationProfile = {
  id: "venise",
  name: "Venise",
  country: "Italie",
  countryCode: "IT",
  iata: "VCE",
  tagline: "Canaux, palais et spritz au soleil couchant.",
  description:
    "Une ville sans voitures posée sur l'eau : on s'y perd volontiers entre ponts et ruelles, de la place Saint-Marc aux bacari de Cannaregio et aux maisons colorées de Burano.",
  fallbackGradient: "from-teal-300 via-cyan-600 to-indigo-800",
  type: "ville",
  costLevel: 4,
  costs: {
    accommodationPerNight: { eco: 45, standard: 95, confort: 190 },
    localTransportPerDay: 12,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "1 h 40",
        durationHours: 1.7,
        roundTripPerPerson: 150,
        details: "Vol direct, puis bus ou bateau Alilaguna jusqu'à la lagune",
      },
    ],
  },
  localMobility: [
    { mode: "marche", description: "À pied avant tout : pas de voitures ni de vélos" },
    { mode: "ferry", description: "Vaporetto (bateau-bus) : le pass 24 h ou 48 h est rentable" },
  ],
  idealDays: { min: 2, max: 4 },
  bestMonths: [4, 5, 6, 9, 10],
  styles: { romantique: 3, culture: 3, ville: 2, gastronomie: 2, shopping: 1, detente: 2, fete: 1 },
  ambiances: { romantique: 3, luxueuse: 3, calme: 2, authentique: 2 },
  strengths: { culture: 3, securite: 3, gastronomie: 2, rapidite: 2 },
  neighborhoods: [
    {
      name: "San Marco",
      vibe: "au centre de tout, très touristique",
      tiers: ["standard", "confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Cannaregio",
      vibe: "le Venise des Vénitiens, bacari et canaux calmes",
      tiers: ["eco", "standard"],
      tags: ["gastronomie", "fete"],
    },
    {
      name: "Dorsoduro",
      vibe: "étudiant et artistique, les Zattere au soleil",
      tiers: ["eco", "standard"],
      tags: ["culture", "fete"],
    },
    {
      name: "Castello",
      vibe: "calme, loin de la foule",
      tiers: ["standard", "confort"],
      tags: ["detente", "romantique"],
    },
  ],
  activities: [
    {
      id: "san-marco",
      name: "Place et basilique Saint-Marc",
      description: "Mosaïques d'or byzantines et la plus belle place du monde, tôt le matin.",
      category: "monument",
      emoji: "⛪",
      cost: 3,
      hours: 2,
      area: "San Marco",
      moments: ["morning"],
      tags: ["culture"],
      highlight: "La basilique Saint-Marc",
    },
    {
      id: "palais-doges",
      name: "Palais des Doges et pont des Soupirs",
      description: "Salles dorées, prisons et passage secret de l'ancienne république.",
      category: "musee",
      emoji: "🏛️",
      cost: 30,
      hours: 2.5,
      area: "San Marco",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "rialto",
      name: "Pont du Rialto et marché aux poissons",
      description: "Le pont le plus célèbre et l'animation du marché le matin.",
      category: "quartier",
      emoji: "🌉",
      cost: 0,
      hours: 1.5,
      moments: ["morning"],
      tags: ["ville"],
    },
    {
      id: "vaporetto",
      name: "Le Grand Canal en vaporetto",
      description: "La ligne 1 longe tous les palais : la croisière la moins chère du monde.",
      category: "panorama",
      emoji: "🚤",
      cost: 10,
      hours: 1,
      moments: ["morning", "afternoon"],
      tags: ["ville", "romantique"],
    },
    {
      id: "gondole",
      name: "Balade en gondole",
      description: "Le cliché assumé, plus doux à plusieurs (le prix est par gondole).",
      category: "panorama",
      emoji: "🛶",
      cost: 30,
      hours: 1,
      moments: ["afternoon", "evening"],
      tags: ["romantique"],
      highlight: "Balade en gondole",
    },
    {
      id: "guggenheim",
      name: "Collection Peggy Guggenheim",
      description: "Picasso, Pollock et Magritte dans un palais au bord du Grand Canal.",
      category: "musee",
      emoji: "🎨",
      cost: 16,
      hours: 2,
      area: "Dorsoduro",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "ghetto",
      name: "Le Ghetto juif de Cannaregio",
      description: "Le premier ghetto de l'histoire, synagogues et hautes maisons.",
      category: "quartier",
      emoji: "🕍",
      cost: 0,
      hours: 1.5,
      area: "Cannaregio",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "acqua-alta",
      name: "Libreria Acqua Alta",
      description: "Librairie où les livres dorment dans des gondoles et des baignoires.",
      category: "shopping",
      emoji: "📚",
      cost: 0,
      hours: 1,
      area: "Castello",
      moments: ["morning", "afternoon"],
      tags: ["shopping", "culture"],
    },
    {
      id: "kayak-venise",
      name: "Kayak dans les petits canaux",
      description: "Voir Venise au ras de l'eau, avec un guide, loin des gondoles.",
      category: "aventure",
      emoji: "🛶",
      cost: 80,
      hours: 3,
      moments: ["morning"],
      tags: ["aventure"],
    },
    {
      id: "lido",
      name: "Plage du Lido",
      description: "Le long banc de sable face à l'Adriatique, à 15 min de vaporetto.",
      category: "plage",
      emoji: "🏖️",
      cost: 0,
      hours: 4,
      moments: ["afternoon"],
      tags: ["plage", "detente"],
    },
    {
      id: "zattere",
      name: "Coucher de soleil aux Zattere",
      description: "Le quai ensoleillé de Dorsoduro, un spritz à la main.",
      category: "panorama",
      emoji: "🌅",
      cost: 0,
      hours: 1.5,
      area: "Dorsoduro",
      moments: ["evening"],
      tags: ["romantique", "detente"],
      highlight: "Coucher de soleil sur la lagune",
      repeatable: true,
    },
    {
      id: "bacari",
      name: "Tournée des bacari",
      description: "Cicchetti (petites bouchées) et ombra de vin de bar en bar.",
      category: "food",
      emoji: "🍷",
      cost: 25,
      hours: 2.5,
      area: "Cannaregio",
      moments: ["evening"],
      tags: ["gastronomie", "fete"],
      highlight: "Tournée des bacari",
      repeatable: true,
    },
    {
      id: "santa-margherita",
      name: "Soirée campo Santa Margherita",
      description: "La place étudiante où Venise sort le soir.",
      category: "nightlife",
      emoji: "🍹",
      cost: 15,
      hours: 3,
      area: "Dorsoduro",
      moments: ["evening"],
      tags: ["fete"],
    },
    {
      id: "burano",
      name: "Murano et Burano",
      description: "Souffleurs de verre à Murano, maisons arc-en-ciel à Burano.",
      category: "excursion",
      emoji: "🎨",
      cost: 20,
      hours: 6,
      moments: ["morning"],
      tags: ["culture", "romantique"],
      highlight: "Les maisons colorées de Burano",
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-dal-moro",
      name: "Dal Moro's",
      description: "Pâtes fraîches à emporter dans une boîte, à manger au bord d'un canal.",
      cuisine: "Pâtes à emporter",
      emoji: "🍝",
      kind: "street-food",
      isLocal: false,
      priceLevel: 1,
      cost: 10,
      area: "Castello",
      meals: ["lunch"],
      tags: [],
      real: true,
    },
    {
      id: "r-all-arco",
      name: "All'Arco",
      description: "Minuscule bacaro près du Rialto, cicchetti faits minute.",
      cuisine: "Cicchetti",
      emoji: "🥖",
      kind: "bar",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-do-mori",
      name: "Cantina Do Mori",
      description: "Le plus vieux bacaro de Venise (1462), casseroles en cuivre au plafond.",
      cuisine: "Cicchetti & vins",
      emoji: "🍷",
      kind: "bar",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "fete"],
      real: true,
    },
    {
      id: "r-bancogiro",
      name: "Osteria Bancogiro",
      description: "Terrasse sur le Grand Canal, près du marché du Rialto.",
      cuisine: "Cuisine vénitienne",
      emoji: "🐟",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 40,
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      real: true,
    },
    {
      id: "r-gatto-nero",
      name: "Trattoria Al Gatto Nero",
      description: "Le risotto au gô, petit poisson de la lagune, à Burano face aux maisons colorées.",
      cuisine: "Poissons de la lagune",
      emoji: "🐈‍⬛",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 50,
      meals: ["lunch"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
    {
      id: "r-carampane",
      name: "Antiche Carampane",
      description: "Cachée dans les ruelles de San Polo, cuisine de poisson de référence.",
      cuisine: "Cuisine vénitienne",
      emoji: "🦐",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 65,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(45.4371, 12.3326),
    zoom: 14,
    neighborhoods: {
      "San Marco": p(45.4343, 12.3375),
      Cannaregio: p(45.4432, 12.3285),
      Dorsoduro: p(45.4315, 12.3255),
      Castello: p(45.4355, 12.3475),
    },
    places: {
      "san-marco": p(45.4341, 12.3388),
      "palais-doges": p(45.4337, 12.3404),
      rialto: p(45.438, 12.3359),
      vaporetto: p(45.438, 12.33),
      gondole: p(45.436, 12.335),
      guggenheim: p(45.4309, 12.3316),
      ghetto: p(45.4453, 12.3265),
      "acqua-alta": p(45.4378, 12.3425),
      "kayak-venise": p(45.441, 12.346),
      lido: p(45.405, 12.37),
      zattere: p(45.429, 12.326),
      bacari: p(45.443, 12.331),
      "santa-margherita": p(45.4344, 12.3243),
      burano: p(45.4853, 12.417),
      "r-dal-moro": p(45.437, 12.3395),
      "r-all-arco": p(45.4385, 12.3337),
      "r-do-mori": p(45.439, 12.3345),
      "r-bancogiro": p(45.4389, 12.335),
      "r-gatto-nero": p(45.485, 12.4165),
      "r-carampane": p(45.4383, 12.3308),
    },
  },
  source: "demo",
};
