import type { DestinationProfile } from "../../types";

const p = (lat: number, lng: number) => ({ lat, lng });

export const vienne: DestinationProfile = {
  id: "vienne",
  name: "Vienne",
  country: "Autriche",
  countryCode: "AT",
  iata: "VIE",
  tagline: "Palais impériaux, cafés viennois et bars au bord du canal.",
  description:
    "Élégante sans être guindée : Schönbrunn et Klimt le jour, Sachertorte au café, grande roue du Prater, opéra en place debout et soirées au bord du canal du Danube.",
  fallbackGradient: "from-amber-200 via-yellow-500 to-red-700",
  type: "ville",
  costLevel: 3,
  costs: {
    accommodationPerNight: { eco: 35, standard: 75, confort: 150 },
    localTransportPerDay: 8,
  },
  access: {
    from: "Paris",
    routes: [
      {
        mode: "avion",
        durationLabel: "2 h",
        durationHours: 2,
        roundTripPerPerson: 150,
        details: "Vol direct, train CAT ou S-Bahn jusqu'au centre en 20 min",
      },
    ],
  },
  localMobility: [
    { mode: "metro", description: "U-Bahn rapide, pass 24 h / 48 h / 72 h avantageux" },
    { mode: "tram", description: "Le tram du Ring fait le tour des grands monuments" },
    { mode: "velo", description: "Pistes cyclables le long du Danube" },
    { mode: "marche", description: "Le centre historique est piéton" },
  ],
  idealDays: { min: 3, max: 5 },
  bestMonths: [4, 5, 6, 9, 10, 12],
  styles: {
    culture: 3,
    romantique: 3,
    gastronomie: 2,
    ville: 2,
    fete: 2,
    detente: 2,
    festivals: 2,
    nature: 1,
  },
  ambiances: { romantique: 3, calme: 2, luxueuse: 2, authentique: 2, sociale: 2 },
  strengths: { culture: 3, securite: 3, confort: 3, gastronomie: 2, "vie-nocturne": 2 },
  neighborhoods: [
    {
      name: "Innere Stadt",
      vibe: "le centre impérial, tout à pied",
      tiers: ["standard", "confort"],
      tags: ["culture", "romantique"],
    },
    {
      name: "Neubau",
      vibe: "créatif, concept stores et cafés",
      tiers: ["eco", "standard"],
      tags: ["shopping", "fete"],
    },
    {
      name: "Wieden",
      vibe: "autour du Naschmarkt, vivant et central",
      tiers: ["eco", "standard"],
      tags: ["gastronomie"],
    },
    {
      name: "Leopoldstadt",
      vibe: "entre le Prater et le canal",
      tiers: ["eco", "standard"],
      tags: ["fete", "detente"],
    },
  ],
  activities: [
    {
      id: "schonbrunn",
      name: "Château de Schönbrunn",
      description: "La résidence d'été des Habsbourg et ses immenses jardins jusqu'à la Gloriette.",
      category: "monument",
      emoji: "🏰",
      cost: 30,
      hours: 3,
      moments: ["morning"],
      tags: ["culture", "romantique"],
      highlight: "Les jardins de Schönbrunn",
    },
    {
      id: "belvedere",
      name: "Belvédère et Le Baiser de Klimt",
      description: "Palais baroque abritant le tableau doré le plus célèbre d'Autriche.",
      category: "musee",
      emoji: "🎨",
      cost: 17,
      hours: 2,
      moments: ["morning", "afternoon"],
      tags: ["culture", "romantique"],
      highlight: "Le Baiser de Klimt",
    },
    {
      id: "stephansdom",
      name: "Cathédrale Saint-Étienne",
      description: "Toit de tuiles colorées et montée dans la tour sud.",
      category: "monument",
      emoji: "⛪",
      cost: 6,
      hours: 1.5,
      area: "Innere Stadt",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "hofburg",
      name: "Hofburg et musée Sissi",
      description: "Les appartements impériaux et la vie de l'impératrice Élisabeth.",
      category: "musee",
      emoji: "👑",
      cost: 20,
      hours: 2,
      area: "Innere Stadt",
      moments: ["morning", "afternoon"],
      tags: ["culture"],
    },
    {
      id: "mq",
      name: "MuseumsQuartier",
      description: "Musées d'art moderne et cour où l'on se pose sur les « Enzis » colorés.",
      category: "musee",
      emoji: "🖼️",
      cost: 15,
      hours: 2,
      area: "Neubau",
      moments: ["afternoon"],
      tags: ["culture", "detente"],
    },
    {
      id: "naschmarkt",
      name: "Naschmarkt",
      description: "Un kilomètre de marché : épices, falafels, fromages et petits restos.",
      category: "food",
      emoji: "🧺",
      cost: 15,
      hours: 1.5,
      area: "Wieden",
      moments: ["morning"],
      tags: ["gastronomie"],
    },
    {
      id: "cafe-viennois",
      name: "Pause dans un café viennois",
      description: "Sachertorte ou strudel dans un grand café classé à l'Unesco.",
      category: "food",
      emoji: "🍰",
      cost: 12,
      hours: 1,
      area: "Innere Stadt",
      moments: ["afternoon"],
      tags: ["gastronomie", "romantique"],
      repeatable: true,
    },
    {
      id: "kahlenberg",
      name: "Randonnée au Kahlenberg",
      description: "Vignes et forêt de Vienne, vue sur toute la ville et le Danube.",
      category: "nature",
      emoji: "🥾",
      cost: 0,
      hours: 3,
      moments: ["morning"],
      tags: ["nature", "detente"],
    },
    {
      id: "donauinsel",
      name: "Baignade sur la Donauinsel",
      description: "Île de 21 km sur le Danube : plages, vélo et barbecues l'été.",
      category: "plage",
      emoji: "🏊",
      cost: 0,
      hours: 3,
      moments: ["afternoon"],
      tags: ["plage", "detente"],
    },
    {
      id: "prater",
      name: "Grande roue du Prater",
      description: "La roue de 1897 au coucher du soleil, puis les manèges du parc.",
      category: "evenement",
      emoji: "🎡",
      cost: 14,
      hours: 1.5,
      area: "Leopoldstadt",
      moments: ["evening"],
      tags: ["romantique", "festivals"],
      highlight: "La grande roue au crépuscule",
    },
    {
      id: "opera",
      name: "Soirée à l'Opéra, en place debout",
      description: "Des places debout à quelques euros, en vente le jour même.",
      category: "evenement",
      emoji: "🎭",
      cost: 15,
      hours: 3,
      area: "Innere Stadt",
      moments: ["evening"],
      tags: ["culture", "romantique"],
    },
    {
      id: "canal-danube",
      name: "Bars du canal du Danube",
      description: "Transats, street art et bars flottants le long de l'eau.",
      category: "nightlife",
      emoji: "🍹",
      cost: 20,
      hours: 3,
      area: "Leopoldstadt",
      moments: ["evening"],
      tags: ["fete"],
      highlight: "Nuit au bord du canal",
      repeatable: true,
    },
    {
      id: "heuriger",
      name: "Soirée dans un Heuriger",
      description: "Guinguette à vin au milieu des vignes de Grinzing, vin blanc maison.",
      category: "food",
      emoji: "🍷",
      cost: 25,
      hours: 3,
      moments: ["evening"],
      tags: ["gastronomie", "fete"],
    },
    {
      id: "wachau",
      name: "Excursion dans la vallée de la Wachau",
      description: "Abbaye de Melk, vignobles et croisière sur le Danube.",
      category: "excursion",
      emoji: "🍇",
      cost: 60,
      hours: 9,
      moments: ["morning"],
      tags: ["nature", "culture", "romantique"],
      fullDay: true,
    },
  ],
  restaurants: [
    {
      id: "r-bitzinger",
      name: "Bitzinger Würstelstand",
      description: "Le stand à saucisses derrière l'Opéra, käsekrainer et moutarde.",
      cuisine: "Saucisses viennoises",
      emoji: "🌭",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      area: "Innere Stadt",
      meals: ["lunch", "dinner"],
      tags: [],
      real: true,
    },
    {
      id: "r-cafe-sperl",
      name: "Café Sperl",
      description: "Café de 1880 resté intact : billards, journaux et strudel.",
      cuisine: "Café viennois",
      emoji: "☕",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      meals: ["lunch"],
      tags: ["romantique"],
      real: true,
    },
    {
      id: "r-schwarzes-kameel",
      name: "Zum Schwarzen Kameel",
      description: "Épicerie fine de 1618, petits sandwichs raffinés au comptoir.",
      cuisine: "Sandwichs & traiteur",
      emoji: "🥪",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      area: "Innere Stadt",
      meals: ["lunch"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-figlmuller",
      name: "Figlmüller",
      description: "L'escalope viennoise qui dépasse de l'assiette, depuis 1905.",
      cuisine: "Cuisine viennoise",
      emoji: "🥩",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      area: "Innere Stadt",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      real: true,
    },
    {
      id: "r-plachutta",
      name: "Plachutta",
      description: "Le Tafelspitz (bœuf bouilli) servi dans sa marmite, rite viennois.",
      cuisine: "Cuisine viennoise",
      emoji: "🍲",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 50,
      area: "Innere Stadt",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      real: true,
    },
  ],
  geo: {
    center: p(48.2082, 16.3738),
    zoom: 13,
    neighborhoods: {
      "Innere Stadt": p(48.2085, 16.3721),
      Neubau: p(48.2015, 16.349),
      Wieden: p(48.1965, 16.3685),
      Leopoldstadt: p(48.2155, 16.385),
    },
    places: {
      schonbrunn: p(48.1845, 16.3122),
      belvedere: p(48.1915, 16.3809),
      stephansdom: p(48.2085, 16.3731),
      hofburg: p(48.2075, 16.3655),
      mq: p(48.2033, 16.3589),
      naschmarkt: p(48.1985, 16.3625),
      "cafe-viennois": p(48.204, 16.369),
      kahlenberg: p(48.276, 16.333),
      donauinsel: p(48.23, 16.41),
      prater: p(48.2166, 16.3964),
      opera: p(48.203, 16.369),
      "canal-danube": p(48.214, 16.378),
      heuriger: p(48.255, 16.35),
      wachau: p(48.228, 15.332),
      "r-bitzinger": p(48.2045, 16.369),
      "r-cafe-sperl": p(48.199, 16.359),
      "r-schwarzes-kameel": p(48.2098, 16.369),
      "r-figlmuller": p(48.2089, 16.3752),
      "r-plachutta": p(48.2078, 16.379),
    },
  },
  source: "demo",
};
