import type { GeoPoint } from "@/types/travel-plan";
import type { RestaurantTemplate } from "../types";

/**
 * Restaurants RÉELS du catalogue : adresses connues et bien établies, choisies
 * pour couvrir tous les budgets. Prix moyens indicatifs par personne.
 * Un établissement peut fermer ou changer : l'interface propose toujours de
 * vérifier sur Google Maps. Positions approximatives (quelques dizaines de mètres).
 */
type RealRestaurant = Omit<RestaurantTemplate, "real"> & { at: GeoPoint };

const p = (lat: number, lng: number) => ({ lat, lng });

const REAL: Record<string, RealRestaurant[]> = {
  lisbonne: [
    {
      id: "r-o-trevo",
      name: "O Trevo",
      description: "Le comptoir à bifanas (sandwich au porc mariné) de la place Camões, sans chichis.",
      cuisine: "Street food portugaise",
      emoji: "🥪",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 7,
      area: "Baixa-Chiado",
      meals: ["lunch"],
      tags: [],
      at: p(38.7107, -9.1437),
    },
    {
      id: "r-ze-da-mouraria",
      name: "Zé da Mouraria",
      description: "Cantine populaire aux portions généreuses, à partager. Midi uniquement, souvent complet.",
      cuisine: "Cuisine portugaise",
      emoji: "🐟",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "Alfama",
      meals: ["lunch"],
      tags: ["gastronomie"],
      at: p(38.7156, -9.1349),
    },
    {
      id: "r-time-out-market",
      name: "Time Out Market Lisboa",
      description: "L'ancien marché de la Ribeira : une trentaine de stands de chefs et de spécialités.",
      cuisine: "Food hall",
      emoji: "🍤",
      kind: "street-food",
      isLocal: true,
      priceLevel: 2,
      cost: 18,
      area: "Cais do Sodré",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "fete"],
      at: p(38.7069, -9.1459),
    },
    {
      id: "r-taberna-flores",
      name: "Taberna da Rua das Flores",
      description: "Petite taverne de petiscos (tapas portugaises) inventifs, ardoise du jour.",
      cuisine: "Petiscos",
      emoji: "🍷",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Baixa-Chiado",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(38.7094, -9.1432),
    },
    {
      id: "r-cervejaria-ramiro",
      name: "Cervejaria Ramiro",
      description: "L'institution des fruits de mer : crevettes à l'ail, palourdes et prego pour finir.",
      cuisine: "Fruits de mer",
      emoji: "🦐",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 40,
      meals: ["dinner"],
      tags: ["gastronomie", "fete"],
      at: p(38.7206, -9.1356),
    },
    {
      id: "r-cevicheria",
      name: "A Cevicheria",
      description: "Ceviches péruviens sous une pieuvre géante suspendue, ambiance animée.",
      cuisine: "Cuisine péruvienne",
      emoji: "🐙",
      kind: "bistrot",
      isLocal: false,
      priceLevel: 2,
      cost: 32,
      area: "Príncipe Real",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(38.716, -9.1488),
    },
    {
      id: "r-bairro-avillez",
      name: "Bairro do Avillez",
      description: "Le « quartier » gourmand du chef José Avillez : taverne, marché et salle chic.",
      cuisine: "Cuisine d'auteur portugaise",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 50,
      area: "Baixa-Chiado",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(38.7118, -9.1422),
    },
  ],
  barcelone: [
    {
      id: "r-cova-fumada",
      name: "La Cova Fumada",
      description: "Bar de pêcheurs sans enseigne, berceau de la « bomba » (croquette épicée).",
      cuisine: "Tapas",
      emoji: "🍢",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 18,
      area: "Barceloneta",
      meals: ["lunch"],
      tags: ["gastronomie"],
      at: p(41.379, 2.1896),
    },
    {
      id: "r-el-quim",
      name: "El Quim de la Boqueria",
      description: "Comptoir mythique au cœur du marché : œufs au plat aux chipirons, produits du jour.",
      cuisine: "Cuisine de marché",
      emoji: "🍳",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Gothique & Born",
      meals: ["lunch"],
      tags: ["gastronomie"],
      at: p(41.3818, 2.1719),
    },
    {
      id: "r-xampanyet",
      name: "El Xampanyet",
      description: "Bar à cava carrelé de bleu depuis 1929, anchois et tapas debout au comptoir.",
      cuisine: "Tapas & cava",
      emoji: "🥂",
      kind: "bar",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      area: "Gothique & Born",
      meals: ["lunch", "dinner"],
      tags: ["fete", "gastronomie"],
      at: p(41.3847, 2.1817),
    },
    {
      id: "r-cerveceria-catalana",
      name: "Cervecería Catalana",
      description: "Grand bar à tapas de l'Eixample, choix immense et service rapide.",
      cuisine: "Tapas",
      emoji: "🍤",
      kind: "bar",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      area: "Eixample",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "fete"],
      at: p(41.3926, 2.1604),
    },
    {
      id: "r-can-culleretes",
      name: "Can Culleretes",
      description: "Le plus vieux restaurant de la ville (1786) : cuisine catalane de grand-mère.",
      cuisine: "Cuisine catalane",
      emoji: "🥘",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 28,
      area: "Gothique & Born",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(41.3813, 2.1746),
    },
    {
      id: "r-can-sole",
      name: "Can Solé",
      description: "Paellas et riz de la mer à la Barceloneta depuis 1903.",
      cuisine: "Paella & poissons",
      emoji: "🥘",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 40,
      area: "Barceloneta",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(41.3797, 2.1889),
    },
    {
      id: "r-7-portes",
      name: "7 Portes",
      description: "Brasserie historique (1836) près du port, célèbre pour ses paellas.",
      cuisine: "Cuisine catalane",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 50,
      area: "Gothique & Born",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(41.3822, 2.1831),
    },
  ],
  rome: [
    {
      id: "r-supplizio",
      name: "Supplizio",
      description: "Le temple du supplì, la boulette de riz frite romaine, à manger sur le pouce.",
      cuisine: "Street food romaine",
      emoji: "🍙",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      area: "Centro Storico",
      meals: ["lunch"],
      tags: [],
      at: p(41.8985, 12.4688),
    },
    {
      id: "r-forno-roscioli",
      name: "Antico Forno Roscioli",
      description: "Boulangerie historique : pizza bianca et parts de pizza à emporter.",
      cuisine: "Boulangerie & pizza al taglio",
      emoji: "🍕",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      area: "Centro Storico",
      meals: ["lunch"],
      tags: ["gastronomie"],
      at: p(41.8933, 12.4735),
    },
    {
      id: "r-pizzarium",
      name: "Pizzarium Bonci",
      description: "La pizza al taglio la plus célèbre de Rome, près du Vatican.",
      cuisine: "Pizza al taglio",
      emoji: "🍕",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      meals: ["lunch"],
      tags: ["gastronomie"],
      at: p(41.907, 12.4468),
    },
    {
      id: "r-ai-marmi",
      name: "Ai Marmi (Panattoni)",
      description: "Pizzeria du Trastevere aux tables de marbre, pizza fine et bruyante à souhait.",
      cuisine: "Pizzeria romaine",
      emoji: "🍕",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 18,
      area: "Trastevere",
      meals: ["dinner"],
      tags: ["fete"],
      at: p(41.8878, 12.4719),
    },
    {
      id: "r-da-enzo",
      name: "Da Enzo al 29",
      description: "Minuscule trattoria du Trastevere : carbonara, cacio e pepe et artichauts.",
      cuisine: "Trattoria romaine",
      emoji: "🍝",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      area: "Trastevere",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(41.8877, 12.4776),
    },
    {
      id: "r-armando",
      name: "Armando al Pantheon",
      description: "Trattoria familiale depuis 1961, à deux pas du Panthéon. Réservation conseillée.",
      cuisine: "Cuisine romaine",
      emoji: "🍝",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 40,
      area: "Centro Storico",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(41.8987, 12.4757),
    },
    {
      id: "r-roscioli",
      name: "Roscioli Salumeria con Cucina",
      description: "Épicerie fine et restaurant : charcuteries, burrata et une carbonara de référence.",
      cuisine: "Cuisine romaine",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 55,
      area: "Centro Storico",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(41.894, 12.473),
    },
  ],
  amsterdam: [
    {
      id: "r-vleminckx",
      name: "Vleminckx de Sausmeester",
      description: "Le comptoir à frites le plus célèbre de la ville, une vingtaine de sauces.",
      cuisine: "Frites",
      emoji: "🍟",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      meals: ["lunch"],
      tags: [],
      at: p(52.3677, 4.8903),
    },
    {
      id: "r-winkel-43",
      name: "Winkel 43",
      description: "Café du Jordaan réputé pour sa tarte aux pommes, parfait pour une pause.",
      cuisine: "Café & tarte aux pommes",
      emoji: "🥧",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Jordaan",
      meals: ["lunch"],
      tags: [],
      at: p(52.3784, 4.8854),
    },
    {
      id: "r-foodhallen",
      name: "Foodhallen",
      description: "Halle couverte d'Oud-West : une vingtaine de stands et des bars, animé le soir.",
      cuisine: "Food hall",
      emoji: "🍔",
      kind: "street-food",
      isLocal: false,
      priceLevel: 2,
      cost: 20,
      meals: ["lunch", "dinner"],
      tags: ["fete", "gastronomie"],
      at: p(52.3669, 4.868),
    },
    {
      id: "r-moeders",
      name: "Moeders",
      description: "Cuisine néerlandaise familiale, murs couverts de photos de mamans.",
      cuisine: "Cuisine néerlandaise",
      emoji: "🥘",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      area: "Jordaan",
      meals: ["dinner"],
      tags: ["gastronomie"],
      at: p(52.3736, 4.8744),
    },
    {
      id: "r-haesje-claes",
      name: "Haesje Claes",
      description: "Maison traditionnelle près du Spui : stamppot, croquettes et ambiance boisée.",
      cuisine: "Cuisine néerlandaise",
      emoji: "🧆",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 35,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(52.37, 4.8912),
    },
    {
      id: "r-blauw",
      name: "Blauw",
      description: "La référence du rijsttafel indonésien : une vingtaine de petits plats à partager.",
      cuisine: "Cuisine indonésienne",
      emoji: "🍛",
      kind: "gastronomique",
      isLocal: false,
      priceLevel: 3,
      cost: 45,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(52.3556, 4.8553),
    },
  ],
  marrakech: [
    {
      id: "r-mechoui-alley",
      name: "Chez Lamine Hadj Mustapha",
      description: "Méchoui et tanjia cuits au four souterrain, dans la ruelle des méchouis.",
      cuisine: "Méchoui & tanjia",
      emoji: "🍖",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 10,
      area: "Médina",
      meals: ["lunch"],
      tags: ["gastronomie"],
      at: p(31.6262, -7.988),
    },
    {
      id: "r-chez-chegrouni",
      name: "Chez Chegrouni",
      description: "Terrasse simple face à la place Jemaa el-Fna : tajines et couscous à petit prix.",
      cuisine: "Cuisine marocaine",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 9,
      area: "Médina",
      meals: ["lunch", "dinner"],
      tags: [],
      at: p(31.6263, -7.9887),
    },
    {
      id: "r-cafe-epices",
      name: "Café des Épices",
      description: "Terrasse sur la place Rahba Kedima, thé à la menthe et salades marocaines.",
      cuisine: "Café marocain",
      emoji: "🫖",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Médina",
      meals: ["lunch"],
      tags: ["detente"],
      at: p(31.6305, -7.9861),
    },
    {
      id: "r-nomad",
      name: "Nomad",
      description: "Rooftop de la médina, cuisine marocaine revisitée avec vue sur les toits.",
      cuisine: "Marocain moderne",
      emoji: "🌇",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Médina",
      meals: ["lunch", "dinner"],
      tags: ["romantique", "gastronomie"],
      at: p(31.6304, -7.986),
    },
    {
      id: "r-al-fassia",
      name: "Al Fassia",
      description: "Restaurant tenu par des femmes depuis 1987, réputé pour son épaule d'agneau.",
      cuisine: "Cuisine marocaine",
      emoji: "🥘",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 35,
      area: "Guéliz",
      meals: ["dinner"],
      tags: ["gastronomie"],
      at: p(31.6372, -8.0104),
    },
    {
      id: "r-dar-yacout",
      name: "Dar Yacout",
      description: "Dîner-spectacle dans un palais de la médina, menu marocain en plusieurs services.",
      cuisine: "Cuisine marocaine",
      emoji: "🕌",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 70,
      area: "Médina",
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      at: p(31.6356, -7.9947),
    },
  ],
  londres: [
    {
      id: "r-beigel-bake",
      name: "Beigel Bake",
      description: "Bagels au bœuf salé ouverts 24 h/24 sur Brick Lane, pour quelques livres.",
      cuisine: "Bagels",
      emoji: "🥯",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 6,
      area: "Shoreditch",
      meals: ["lunch", "dinner"],
      tags: [],
      at: p(51.5245, -0.0717),
    },
    {
      id: "r-poppies",
      name: "Poppies Fish & Chips",
      description: "Fish & chips à l'ancienne, décor années 1950, près de Spitalfields.",
      cuisine: "Fish & chips",
      emoji: "🐟",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 20,
      area: "Shoreditch",
      meals: ["lunch", "dinner"],
      tags: [],
      at: p(51.5207, -0.0716),
    },
    {
      id: "r-padella",
      name: "Padella",
      description: "Pâtes fraîches à prix doux au pied de Borough Market. File d'attente, mais rapide.",
      cuisine: "Pâtes fraîches",
      emoji: "🍝",
      kind: "bistrot",
      isLocal: false,
      priceLevel: 1,
      cost: 20,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      at: p(51.5054, -0.0909),
    },
    {
      id: "r-dishoom",
      name: "Dishoom Covent Garden",
      description: "Café à la mode de Bombay : naan au bacon le matin, biryani et chai le soir.",
      cuisine: "Cuisine indienne",
      emoji: "🍛",
      kind: "bistrot",
      isLocal: false,
      priceLevel: 2,
      cost: 32,
      area: "Covent Garden",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      at: p(51.5124, -0.1269),
    },
    {
      id: "r-churchill-arms",
      name: "The Churchill Arms",
      description: "Pub couvert de fleurs à Kensington, avec une cuisine thaïe au fond.",
      cuisine: "Pub & cuisine thaïe",
      emoji: "🍺",
      kind: "bar",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      meals: ["dinner"],
      tags: ["fete"],
      at: p(51.5068, -0.1947),
    },
    {
      id: "r-duck-waffle",
      name: "Duck & Waffle",
      description: "Au 40ᵉ étage d'une tour de la City, ouvert tard, vue spectaculaire.",
      cuisine: "Cuisine britannique moderne",
      emoji: "🌃",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 65,
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      at: p(51.5162, -0.0809),
    },
  ],
  prague: [
    {
      id: "r-nase-maso",
      name: "Naše maso",
      description: "Boucherie-comptoir : burgers, pain de viande et saucisses à manger debout.",
      cuisine: "Boucherie & burgers",
      emoji: "🍔",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Vieille Ville",
      meals: ["lunch"],
      tags: ["gastronomie"],
      at: p(50.09, 14.4252),
    },
    {
      id: "r-lokal-dlouha",
      name: "Lokál Dlouhááá",
      description: "Brasserie tchèque interminable : Pilsner à la pression et goulasch.",
      cuisine: "Cuisine tchèque",
      emoji: "🍺",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "Vieille Ville",
      meals: ["lunch", "dinner"],
      tags: ["fete", "gastronomie"],
      at: p(50.0899, 14.4247),
    },
    {
      id: "r-cafe-louvre",
      name: "Café Louvre",
      description: "Grand café historique de 1902, billard et plats tchèques.",
      cuisine: "Café & cuisine tchèque",
      emoji: "☕",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 1,
      cost: 18,
      meals: ["lunch"],
      tags: ["romantique"],
      at: p(50.082, 14.4185),
    },
    {
      id: "r-u-fleku",
      name: "U Fleků",
      description: "Brasserie ouverte depuis 1499, bière brune maison et accordéon.",
      cuisine: "Brasserie tchèque",
      emoji: "🍻",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      meals: ["dinner"],
      tags: ["fete"],
      at: p(50.0787, 14.4174),
    },
    {
      id: "r-modre-kachnicky",
      name: "U Modré kachničky",
      description: "Salles voûtées de Malá Strana, spécialité de canard rôti.",
      cuisine: "Cuisine tchèque",
      emoji: "🦆",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 45,
      area: "Malá Strana",
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      at: p(50.0858, 14.4057),
    },
  ],
  budapest: [
    {
      id: "r-karavan",
      name: "Karaván",
      description: "Cour de food trucks collée au Szimpla : lángos, burgers et goulasch.",
      cuisine: "Street food",
      emoji: "🌯",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 9,
      area: "Quartier juif (VIIe)",
      meals: ["lunch", "dinner"],
      tags: ["fete"],
      at: p(47.4971, 19.0632),
    },
    {
      id: "r-frici-papa",
      name: "Frici Papa",
      description: "Cuisine hongroise simple et copieuse à tout petit prix.",
      cuisine: "Cuisine hongroise",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 10,
      area: "Quartier juif (VIIe)",
      meals: ["lunch", "dinner"],
      tags: [],
      at: p(47.4999, 19.064),
    },
    {
      id: "r-menza",
      name: "Menza",
      description: "Déco rétro des années 1970 sur la place Liszt Ferenc, classiques hongrois.",
      cuisine: "Cuisine hongroise",
      emoji: "🥘",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 20,
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      at: p(47.5052, 19.0631),
    },
    {
      id: "r-mazel-tov",
      name: "Mazel Tov",
      description: "Cour-jardin lumineuse du quartier juif, cuisine du Moyen-Orient à partager.",
      cuisine: "Cuisine du Moyen-Orient",
      emoji: "🥙",
      kind: "bistrot",
      isLocal: false,
      priceLevel: 2,
      cost: 22,
      area: "Quartier juif (VIIe)",
      meals: ["dinner"],
      tags: ["romantique", "fete"],
      at: p(47.4999, 19.0659),
    },
    {
      id: "r-new-york-cafe",
      name: "New York Café",
      description: "Le café « le plus beau du monde » : dorures, fresques et pâtisseries.",
      cuisine: "Grand café",
      emoji: "☕",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      meals: ["lunch"],
      tags: ["romantique"],
      at: p(47.4985, 19.0707),
    },
    {
      id: "r-gundel",
      name: "Gundel",
      description: "Restaurant de légende près du Városliget, crêpes Gundel en dessert.",
      cuisine: "Cuisine hongroise raffinée",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 65,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(47.5176, 19.0797),
    },
  ],
  athenes: [
    {
      id: "r-kostas",
      name: "Kostas",
      description: "Minuscule échoppe de souvlaki pita depuis 1950, sauce tomate maison.",
      cuisine: "Souvlaki",
      emoji: "🥙",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 5,
      area: "Plaka",
      meals: ["lunch"],
      tags: [],
      at: p(37.9771, 23.7274),
    },
    {
      id: "r-thanasis",
      name: "O Thanasis",
      description: "Kebabs grillés et pitas face à la place Monastiraki.",
      cuisine: "Grillades grecques",
      emoji: "🍢",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 12,
      area: "Plaka",
      meals: ["lunch", "dinner"],
      tags: [],
      at: p(37.9765, 23.7254),
    },
    {
      id: "r-diporto",
      name: "Diporto",
      description: "Taverne en sous-sol près du marché central, sans carte : on mange ce qu'il y a.",
      cuisine: "Taverne grecque",
      emoji: "🍲",
      kind: "local",
      isLocal: true,
      priceLevel: 1,
      cost: 15,
      area: "Psiri",
      meals: ["lunch"],
      tags: ["gastronomie"],
      at: p(37.9803, 23.7266),
    },
    {
      id: "r-karamanlidika",
      name: "Karamanlidika tou Fani",
      description: "Épicerie-meze : charcuteries, fromages et mezze d'Anatolie à partager.",
      cuisine: "Meze",
      emoji: "🧀",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Psiri",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      at: p(37.9803, 23.7249),
    },
    {
      id: "r-a-for-athens",
      name: "A for Athens",
      description: "Rooftop face à l'Acropole illuminée, cocktails au coucher du soleil.",
      cuisine: "Bar à cocktails",
      emoji: "🍸",
      kind: "bar",
      isLocal: false,
      priceLevel: 2,
      cost: 25,
      area: "Psiri",
      meals: ["dinner"],
      tags: ["romantique", "fete"],
      at: p(37.9761, 23.7255),
    },
    {
      id: "r-strofi",
      name: "Strofi",
      description: "Taverne classique avec terrasse sur l'Acropole, au pied de la colline.",
      cuisine: "Cuisine grecque",
      emoji: "🏛️",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 35,
      area: "Koukaki",
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      at: p(37.9687, 23.725),
    },
    {
      id: "r-varoulko",
      name: "Varoulko Seaside",
      description: "Table étoilée de poissons sur le petit port de Mikrolimano, au Pirée.",
      cuisine: "Poissons & fruits de mer",
      emoji: "🐟",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 80,
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(37.938, 23.659),
    },
  ],
  split: [
    {
      id: "r-kantun-paulina",
      name: "Kantun Paulina",
      description: "Petit comptoir de ćevapi (brochettes grillées) en pain, près de la Riva.",
      cuisine: "Grillades des Balkans",
      emoji: "🌭",
      kind: "street-food",
      isLocal: true,
      priceLevel: 1,
      cost: 8,
      area: "Varoš",
      meals: ["lunch", "dinner"],
      tags: [],
      at: p(43.5093, 16.4378),
    },
    {
      id: "r-villa-spiza",
      name: "Villa Spiza",
      description: "Quelques tabourets dans le palais, cuisine du marché qui change chaque jour.",
      cuisine: "Cuisine dalmate",
      emoji: "🐟",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 25,
      area: "Palais de Dioclétien",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie"],
      at: p(43.5087, 16.4393),
    },
    {
      id: "r-fetivi",
      name: "Konoba Fetivi",
      description: "Konoba familiale de Varoš : poisson du jour grillé et vin maison.",
      cuisine: "Cuisine dalmate",
      emoji: "🦑",
      kind: "local",
      isLocal: true,
      priceLevel: 2,
      cost: 30,
      area: "Varoš",
      meals: ["dinner"],
      tags: ["gastronomie", "romantique"],
      at: p(43.507, 16.4323),
    },
    {
      id: "r-bokeria",
      name: "Bokeria Kitchen & Wine",
      description: "Bistrot animé du vieux Split, bons vins croates et assiettes de saison.",
      cuisine: "Cuisine méditerranéenne",
      emoji: "🍷",
      kind: "bistrot",
      isLocal: true,
      priceLevel: 2,
      cost: 35,
      area: "Palais de Dioclétien",
      meals: ["lunch", "dinner"],
      tags: ["gastronomie", "fete"],
      at: p(43.5088, 16.4368),
    },
    {
      id: "r-zoi",
      name: "Zoi",
      description: "Terrasse accrochée aux murs du palais, cuisine dalmate raffinée.",
      cuisine: "Cuisine dalmate raffinée",
      emoji: "🍽️",
      kind: "gastronomique",
      isLocal: true,
      priceLevel: 3,
      cost: 60,
      area: "Palais de Dioclétien",
      meals: ["dinner"],
      tags: ["romantique", "gastronomie"],
      at: p(43.5078, 16.4392),
    },
  ],
};

/** Restaurants réels d'une destination (liste vide si aucun). */
export function realRestaurants(destinationId: string): RestaurantTemplate[] {
  return (REAL[destinationId] ?? []).map(({ at: _at, ...restaurant }) => ({ ...restaurant, real: true }));
}

/** Positions des restaurants réels, à fusionner dans `geo.places`. */
export function realRestaurantPoints(destinationId: string): Record<string, GeoPoint> {
  return Object.fromEntries((REAL[destinationId] ?? []).map((r) => [r.id, r.at]));
}
